### DISCUSSION TITLE
Portainer container stuck starting

### DISCUSSION THREAD

**Discussion by EBS-DarkD** [firefly-iii/firefly-iii#10187] [Firefly III]
After my earlier problems, i've managed to progress a little bit but am stuck again!

My setup is a portainer stack and I'm running several other stacks with various services and apps

The stack is as follows
```
services:
  #Firefly III
  firefly3:
    container_name: firefly3_core
    image: fireflyiii/core:latest
    hostname: firefly3
    networks:
      t2_proxy:
        ipv4_address: 192.168.92.80
    ports:
      - "8101:8080"
    volumes:
      - /random-stuff/data:/var/www/html/storage/upload/
    env_file: stack.env
    labels:
      - "traefik.enable=true"
	## other traefik config to setup in reverse proxy
	  
  #FF3 Importer
  ff3-importer:
    container_name: firefly3_importer
    image: fireflyiii/data-importer:latest
    networks:
      t2_proxy:
        ipv4_address: 192.168.92.91
    ports:
      - "8102:8080"
    depends_on:
      - firefly3
    env_file: stack.env`

```

Within the stack.env file I've set
TRUSTED_PROXIES=**
APP_URL=http://fly.you-goat-lovers.com
FIREFLY_III_URL=http://192.168.92.80:8080 # also tried port 8101
VANITY_URL=http://fly.you-goat-lovers.com

The database is in another stack and i've included the details in the stack.env
When I start the stack and monitor the logs, there are a few php errors and then it connects to the database, sets up the tables and I end up at the screen below

```

              ______ _           __ _            _____ _____ _____  
             |  ____(_)         / _| |          |_   _|_   _|_   _| 
             | |__   _ _ __ ___| |_| |_   _       | |   | |   | |   
             |  __| | | '__/ _ \  _| | | | |      | |   | |   | |   
             | |    | | | |  __/ | | | |_| |     _| |_ _| |_ _| |_  
             |_|    |_|_|  \___|_| |_|\__, |    |_____|_____|_____| 
                                       __/ |                        
                                      |___/                         
+------------------------------------------------------------------------------+
|                                                                                                                    
| Thank you for installing Firefly III, v6.2.12!                                                 
| There are no extra installation instructions.                                               
| Firefly III should be ready for use.                                                              
|                                                                                                                    
| Did you know you can support the development of Firefly III?                 
| You can donate in many ways, like GitHub Sponsors or Patreon.              
| For more information, please visit https://bit.ly/donate-to-Firefly-III        
|                                                                                                  
+------------------------------------------------------------------------------+
[22-Apr-2025 21:44:53] NOTICE: fpm is running, pid 193
[22-Apr-2025 21:44:53] NOTICE: ready to handle connections
```

Checking portainer the firefly3_core container is still showing as starting even after 15 mins
firefly3_importer shows starting and flips to unhealthy after about 5 minutes
The instance isn't visible in my reverse proxy
I'm unable to access the firefly instance via url or ip address

I will look at this again sober tomorrow evening but it would be great if anyone give me 
any pointers as to what I need to look at?

Thanks
