### DISCUSSION TITLE
There seems to be a failure in checking the NGINX + PHP-FPM.

### DISCUSSION THREAD

**Discussion by ed0c** [firefly-iii/firefly-iii#10196] [Firefly III]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [x] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem
- [x] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

when I start the docker version of firefly, I repeatedly get an error about a problem accessing localhost.
It concerns the app and the importer.
I have replaced all occurrences mentioning localhost in all files, so i don't understand this error.

### Debug information

There seems to be a failure in checking the NGINX + PHP-FPM.

curl: (7) Failed to connect to localhost port 8080 after 0 ms: Couldn't connect to server

HTTP Status Code: 000

### Steps to reproduce

docker compose up -d

### Additional info

System : Linux truenas 6.12.15-production+truenas 
Docker Compose version v2.32.3
Docker Version 27.5.0
Firefly III version : 6.2.12

**Comment by JC5** [comment]
Hey, thanks for starting this discussion.

`localhost` in this particular instance is referring to the container itself. But I have no idea how truenas works, I hope somebody else does.

Cheers,
James

**Comment by Dinth** [comment]
I am not using TrueNAS and have just migrated my setup to a docker compose last night. While i can see that Firefly III container is working all right, the data-importers are constantly throwing out the same error:

```
fireflyiii_michal_dataimporter   | 2025-05-02T20:43:34.018773173Z User:              'www-data'
fireflyiii_michal_dataimporter   | 2025-05-02T20:43:34.021195409Z Group:             www-data
fireflyiii_michal_dataimporter   | 2025-05-02T20:43:34.021979736Z Working dir:       /var/www/html
fireflyiii_michal_dataimporter   | 2025-05-02T20:43:34.022005333Z Base build number: 279
fireflyiii_michal_dataimporter   | 2025-05-02T20:43:34.022009957Z Base build date:   19-04-2025 04:01:14 UTC
fireflyiii_michal_dataimporter   | 2025-05-02T20:43:34.024549627Z Build number:      1026
fireflyiii_michal_dataimporter   | 2025-05-02T20:43:34.028824807Z Build date:        24-04-2025 18:27:22 CEST
fireflyiii_michal_dataimporter   | 2025-05-02T20:43:34.029143413Z Now parsing _FILE variables.
fireflyiii_michal_dataimporter   | 2025-05-02T20:43:34.032046244Z done!
fireflyiii_michal_dataimporter   | 2025-05-02T20:43:39.721651544Z Firefly III data importer v1.6.2
fireflyiii_michal_dataimporter   | 2025-05-02T20:43:39.721727522Z PHP: cli 8.4.6 Linux
fireflyiii_michal_dataimporter   | 2025-05-02T20:43:43.329415107Z [02-May-2025 20:43:43] NOTICE: fpm is running, pid 148
fireflyiii_michal_dataimporter   | 2025-05-02T20:43:43.331154987Z [02-May-2025 20:43:43] NOTICE: ready to handle connections
fireflyiii_michal_dataimporter   | 2025-05-02T20:43:44.328422176Z curl: (7) Failed to connect to localhost port 8080 after 0 ms: Couldn't connect to server
fireflyiii_michal_dataimporter   | 2025-05-02T20:43:44.329487327Z ❌ There seems to be a failure in checking the NGINX + PHP-FPM.
fireflyiii_michal_dataimporter   | 2025-05-02T20:43:44.339149948Z curl: (7) Failed to connect to localhost port 8080 after 0 ms: Couldn't connect to server
fireflyiii_michal_dataimporter   | 2025-05-02T20:43:44.340243552Z HTTP Status Code: 000
fireflyiii_michal_dataimporter   | 2025-05-02T20:43:45.357437866Z ✅ NGINX + PHP-FPM is running correctly.
```

im not sure if i have anything wrong?
Here is my docker-compose:

```
services:
  fireflyiii:
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    cap_drop:
      - ALL
    command:
      - /init
    container_name: fireflyiii
    entrypoint: ['docker-php-serversideup-entrypoint']
    environment:
      DB_CONNECTION: "pgsql"
      DB_PORT: "5432"
      DB_HOST: "10.10.1.13"
      DB_DATABASE: "fireflyiii"
      DB_USERNAME: "fireflyiii"
      DB_PASSWORD: "${FIREFLYIII_DB_PASS}"
      APP_KEY: "${FIREFLYIII_APP_KEY}"
      DEFAULT_LANGUAGE: "en_GB"
      TZ: "${TZ}"
      ENABLE_EXTERNAL_RATES: "true"
      APP_URL: "https://finance.${DOMAIN_NAME}"
      TRUSTED_PROXIES: "*"
      FIREFLY_III_LAYOUT: "v2"
      SESSION_DRIVER: "file"
    hostname: firefly
    image: fireflyiii/core:latest
    ipc: private
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - fireflyiii
    ports:
      - 4747:8080/tcp
    restart: unless-stopped
    user: www-data
    volumes:
      - /opt/docker/fireflyiii/fireflyiii_upload:/var/www/html/storage/upload
    working_dir: /var/www/html

  fireflyiii_paulina_dataimporter:
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    cap_drop:
      - ALL
    command: ['/init']
    container_name: fireflyiii_paulina_dataimporter
    entrypoint: ['docker-php-serversideup-entrypoint']
    environment:
      FIREFLY_III_ACCESS_TOKEN: "${FIREFLYIII_PAULINA_ACCESS_TOKEN}"
      FIREFLY_III_URL: "http://fireflyiii:4747"
      NORDIGEN_ID: "${FIREFLYIII_PAULINA_NORD_ID}"
      NORDIGEN_KEY: "${FIREFLYIII_PAULINA_NORD_KEY}"
      CAN_POST_AUTOIMPORT: "true"
      IMPORT_DIR_ALLOWLIST: "/import"
      AUTO_IMPORT_SECRET: "${FIREFLYIII_PAULINA_AUTOIMPORT_KEY}"
    hostname: fireflyiii_paulina_dataimporter
    image: fireflyiii/data-importer:latest
    ipc: private
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - fireflyiii
    ports:
      - 4749:8080/tcp
    restart: unless-stopped
    user: www-data
    volumes:
      - /opt/docker/fireflyiii/fireflyiii_dataimporter_paulina_upload:/var/www/html/storage/upload
      - /Data/IT/filebrowser-data/users/paulina/Paulina-Documents/firefly_configurations:/import:ro
    working_dir: /var/www/html
  fireflyiii_michal_dataimporter:
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    cap_drop:
      - ALL
    command: ['/init']
    container_name: fireflyiii_michal_dataimporter
    entrypoint: ['docker-php-serversideup-entrypoint']
    environment:
      FIREFLY_III_ACCESS_TOKEN: "${FIREFLYIII_MICHAL_ACCESS_TOKEN}"
      FIREFLY_III_URL: "http://fireflyiii:4747"
      NORDIGEN_ID: "${FIREFLYIII_MICHAL_NORD_ID}"
      NORDIGEN_KEY: "${FIREFLYIII_MICHAL_NORD_KEY}"
      CAN_POST_AUTOIMPORT: "true"
      IMPORT_DIR_ALLOWLIST: "/import"
      AUTO_IMPORT_SECRET: "${FIREFLYIII_MICHAL_AUTOIMPORT_KEY}"
    hostname: fireflyiii_michal_dataimporter
    image: fireflyiii/data-importer:latest
    ipc: private
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - fireflyiii
    ports:
      - 4748:8080/tcp
    restart: unless-stopped
    user: www-data
    volumes:
      - /Data/IT/filebrowser-data/users/michal/Michal-Documents/firefly_configurations:/import:ro
      - /opt/docker/fireflyiii/fireflyiii_dataimporter_michal_upload:/var/www/html/storage/upload
    working_dir: /var/www/html
networks:
  fireflyiii:
    name: fireflyiii
    driver: bridge
    external: false
```
