### DISCUSSION TITLE
" SQLSTATE[HY000] [2002] Connection refused" when trying to start Firefly

### DISCUSSION THREAD

**Discussion by Dizzy49** [firefly-iii/firefly-iii#10292] [Firefly III] [answered]
First off, I am on TrueNAS and I'm installing Firefly III using the Custom App via YAML option, so no .env file.  I tried to put everything into one YAML.

```
services:
  app:
    image: fireflyiii/core:latest
    hostname: app
    container_name: firefly_iii_core
    restart: unless-stopped
    volumes:
      - /mnt/ssd_pool/appdata/finance/firefly/upload:/var/www/html/storage/upload
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - USE_RUNNING_BALANCE=false
      - FIREFLY_III_LAYOUT=v1
      - APP_NAME=FireflyIII
      - BROADCAST_DRIVER=log
      - QUEUE_DRIVER=sync
      - CACHE_PREFIX=firefly
      - PUSHER_KEY=
      - IPINFO_TOKEN=
      - PUSHER_SECRET=
      - PUSHER_ID=
      - DEMO_USERNAME=
      - DEMO_PASSWORD=
      - DKR_BUILD_LOCALE=false
      - DKR_CHECK_SQLITE=true
      - QUERY_PARSER_IMPLEMENTATION=legacy
      - DB_CONNECTION=mysql
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_DATABASE=firefly
      - DB_USERNAME=NoName
      - DB_PASSWORD=changeme
      - APP_KEY=thisisthesecret32characterappkey
      - APP_URL=https://firefly.mydomain.com
    ports:
      - 5520:8080
    depends_on:
      - db
  
  db:
    image: mariadb:lts
    hostname: db
    container_name: firefly_iii_db
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=firefly
      - MYSQL_USER=NoName
      - MYSQL_PASSWORD=changeme
    volumes:
      - /mnt/ssd_pool/appdata/finance/firefly/db:/var/lib/mysql
  
  cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable and replace REPLACEME below
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    image: alpine
    restart: always
    container_name: firefly_iii_cron
#    env_file: .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - STATIC_CRON_TOKEN=thisisthesecret32characterappkey
    command: sh -c "
      apk add tzdata
      && ln -s /usr/share/zoneinfo/${TZ} /etc/localtime
      | echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/REPLACEME;echo\" 
      | crontab - 
      && crond -f -L /dev/stdout"

volumes:
   firefly_iii_upload:
   firefly_iii_db:
```

It looks like the DB spins up fine, but I am getting the following error:

> Could not poll the database: SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: select `id`, `name`, `data` from `configuration` where `name` = is_demo_site and `configuration`.`deleted_at` is null limit 1)
> 
> This error occurred in file /var/www/html/app/Support/FireflyConfig.php on line 91 with code 0.

Here is what I see in the logs:
```2025-05-12 00:34:51.914565+00:00[i] Wait for the database. You may see an error about an 'aborted connection', this is normal.
2025-05-12 00:34:51.948111+00:00wait-for-it.sh: waiting 60 seconds for 127.0.0.1:3306
2025-05-12 00:35:51.938652+00:00wait-for-it.sh: timeout occurred after waiting 60 seconds for 127.0.0.1:3306
2025-05-12 00:35:51.946518+00:00[✓] DB is up.
2025-05-12 00:35:51.946786+00:00[i] Wait another 10 seconds in case the DB needs to boot.
2025-05-12 00:36:01.949273+00:00[✓] Done waiting for the DB to boot.
2025-05-12 00:36:01.949370+00:00[i] Will run database commands.
2025-05-12 00:36:02.363520+00:00DSN is mysql:host=127.0.0.1;port=3306;charset=utf8mb4
2025-05-12 00:36:02.363650+00:00[x]  Error when connecting to DB: SQLSTATE[HY000] [2002] Connection refused
2025-05-12 00:36:02.374046+00:00[i] Will run upgrade commands.
2025-05-12 00:36:02.814264+00:00[2025-05-11 18:36:02] production.ERROR: Exception is: {"class":"Illuminate\\Database\\QueryException","errorMessage":"SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: select exists (select 1 from information_schema.tables where table_schema = 'firefly' and table_name = 'migrations' and table_type in ('BASE TABLE', 'SYSTEM VERSIONED')) as `exists`)","time":"Sun, 11 May 2025 18:36:02 -0600","file":"\/var\/www\/html\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Connection.php","line":825,"code":2002,"version":"6.2.12","url":"https:\/\/firefly.dizzy49.com","userAgent":"Symfony","json":true,"method":"GET","post":""}  
2025-05-12 00:36:02.835502+00:00[2025-05-11 18:36:02] production.ERROR: SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: select exists (select 1 from information_schema.tables where table_schema = 'firefly' and table_name = 'migrations' and table_type in ('BASE TABLE', 'SYSTEM VERSIONED')) as `exists`) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 2002): SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: select exists (select 1 from information_schema.tables where table_schema = 'firefly' and table_name = 'migrations' and table_type in ('BASE TABLE', 'SYSTEM VERSIONED')) as `exists`) at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:825)```

I am pretty new to this, I don't know if I have a setting wrong, or incorrect, or what.  Any help would be appreciated.
