### DISCUSSION TITLE
Mariadb won't let firefly connect

### DISCUSSION THREAD

**Discussion by agryson** [firefly-iii/firefly-iii#10475] [Firefly III] [answered]
Hello,
I recently restarted my machine but hadn't made any config change to firefly, it was working great before but now is giving me an error in teh db container:

`Aborted connection 3 to db: 'unconnected' user: 'unauthenticated' host: '172.30.0.3' (This connection closed normally without authentication)`

I run firefly in its own network, could that be the cause? It was working fine before, even with restarts, ti's just the latest that seems to have caused the issue...
Any tips or further info needed to help?

My compose with some lines obfuscated:

```
services:
  app:
    image: fireflyiii/core:latest
    hostname: app
    container_name: firefly
    networks:
      - reverse_proxy
      - firefly_iii
    restart: unless-stopped
    env_file: stack.env
    volumes:
      - /nas/config/firefly/uploads:/var/www/html/storage/upload
    depends_on:
      - db

  db:
    image: mariadb
    hostname: fireflyiiidb
    networks:
      - firefly_iii
    restart: unless-stopped
    env_file: stack.env
    volumes:
      - /nas/config/firefly/db:/var/lib/mysql

networks:
  reverse_proxy:
    external: true
  firefly_iii:
    driver: bridge
```

I've looked at a [few similar discussions](https://github.com/orgs/firefly-iii/discussions/4337) but have not found any "try these 3 things" kinds of solution - they talk about changing passwords leading to this but I haven't changed any config since it was last working so nto sure it applies...
