### DISCUSSION TITLE
Problems installing Firefly

### DISCUSSION THREAD

**Discussion by thefx88** [firefly-iii/firefly-iii#10532] [Firefly III]
Hi, I'm having problems installing Firefly using docker on Raspberry 4. Everything seems running fine from the logs but when I try to access https://my-url/firefly I get 404 page not found. Probably it's just a reverse proxy issue but I cannot figure it out, can someone help me? Below you can see the piece of docker-compose.yml for the Firefly app and the configuration for the apache2 reverse proxy

```
  app:
     image: fireflyiii/core:version-6.1.25
     hostname: app
     platform: linux/arm/v8
     container_name: firefly_iii_core
     restart: unless-stopped
     volumes:
       - firefly_iii_upload:/var/www/html/storage/upload
     env_file: .env
     networks:
       - firefly_iii
     ports:
       - 12280:8080
     depends_on:
       - db
  db:
     image: postgres:latest
     platform: linux/arm/v7
     hostname: db
     container_name: firefly_iii_db
     restart: unless-stopped
     env_file: .db.env
     ports:
        - 15432:5432
     networks:
        - firefly_iii
     volumes:
        - firefly_iii_db:/var/lib/postgresql/data-firefly
  cron:
     image: alpine
     restart: unless-stopped
     container_name: firefly_iii_cron
     env_file: .env
     command: >-
       /bin/sh -c "echo '0 3 * * * wget -q0- http://app:12280/api/v1/cron/$STATIC_CRON_TOKEN' | crontab - && crond -f -L /dev/stdout"
volumes:
    firefly_iii_upload:
    firefly_iii_db:
networks:
    firefly_iii:
       driver: bridge
```

```
<VirtualHost *:443>
  SSLProxyEngine Off
        SSLProxyCheckPeerCN Off
        ProxyPreserveHost On
        ProxyRequests Off

        ProxyPass /firefly http://127.0.0.1:12280/firefly keepalive=On retry=5
        ProxyPassReverse /firefly http://127.0.0.1:12280/firefly
</VirtualHost>
```
