### DISCUSSION TITLE
Internal links point to HTTP even though I'm using HTTPS

### DISCUSSION THREAD

**Discussion by nununo** [firefly-iii/firefly-iii#4991] [Firefly III]
**Bug description**
I am running Firefly III version 5.5.13, and my problem is:

I'm running the Docker version and am using Traefik as a reverse proxy to implement TLS. Unfortunately, even though my url is `https://firefly.private.com`, all internal links are still built using `HTTP`.

My browser is reporting this warning:
> Mixed Content: The page at 'https://firefly.private.com/register' was loaded over a secure connection, but contains a form that targets an insecure endpoint 'http://firefly.private.com/register'. This endpoint should be made available over a secure connection.

And this error:
> Refused to send form data to 'http://firefly.private.com/register' because it violates the following Content Security Policy directive: "form-action 'self'".

I will disable TLS so that I am able to use it until I find a workaround or fix for this problem.

**Steps to reproduce**
Put `firefly` behind Traefik with TLS.

**Extra info**
Host: Docker running on Debian buster.
Client: Brave browser V1.28.105 running on macOS 11.5.1.

I cannot access the `/debug` page because when I access it with `https://firefly.private.com/debug` it gets redirected to `http://firefly.private.com/register`.

Thank you!
Nuno

**Comment by JC5** [comment]
This is most likely a configuration issue. I know how to set this in nginx, not in Traefik.

**Reply by nununo** [reply]
I understand what you mean. In Traefik these are called middlewares. They are the last thing I set up on purpose to avoid being misled. I don't know about nginx but in Traefik these will not solve the problem because they are just redirects. They won't rewrite the hard coded absolute urls in the HTML.

I have now implemented the automatic schema redirect like this:

```toml
[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http]
      [entryPoints.web.http.redirections]
        [entryPoints.web.http.redirections.entrypoint]
          to = "websecure"
          scheme = "https"

  [entryPoints.websecure]
    address = ":443"
``` 
While now all `http` links are automatically redirected to `https` with a 301 command, the problem remains: I still have a `https` page which is complaining of insecure content.

These are all the errors and warnings I'm getting in the browser:
> Mixed Content: The page at 'https://firefly.private.com/login' was loaded over HTTPS, but requested an insecure element 'http://firefly.private.com/v2/images/firefly-iii-logo-new.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html

> login:4 Refused to set the document's base URI to 'http://firefly.private.com/' because it violates the following Content Security Policy directive: "base-uri 'self'".

> login:32 Mixed Content: The page at 'https://firefly.private.com/login' was loaded over a secure connection, but contains a form that targets an insecure endpoint 'http://firefly.private.com/login'. This endpoint should be made available over a secure connection.

> login:1 Mixed Content: The page at 'https://firefly.private.com/login' was loaded over a secure connection, but contains a form that targets an insecure endpoint 'http://firefly.private.com/login'. This endpoint should be made available over a secure connection.

> login:1 Refused to send form data to 'http://firefly.private.com/login' because it violates the following Content Security Policy directive: "form-action 'self'".

Any suggestions?

Can I ask why is fireflyiii writing its internal links as absolute urls? If they were relative all this would be automatically solved.

Thanks!
Nuno

**Reply by JC5** [reply]
> Can I ask why is fireflyiii writing its internal links as absolute urls? If they were relative all this would be automatically solved.

It would also create a score of other problems, but that's another discussion. What you need is something like this:

```
		proxy_set_header X-Forwarded-Host $host;
		proxy_set_header X-Forwarded-Server $host;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```

This will make Firefly III (or rather, the Apache server in the standard Docker image) respond with https URLs.

**Reply by nununo** [reply]
Ah I think I understand now what you're suggesting. I didn't know about this.

I'm already trying to implement it in Traefik but I'm still struggling with the docs. I will investigate further.

Thanks for pointing in the right direction!

Regards,
Nuno

**Reply by lukeberry99** [reply]
@nununo please update here if you fix this issue. I'm experiencing it as well and also investigating. I'll update here if I get it working.

**Reply by lukeberry99** [reply]
@JC5 would it be possible to add configuration to set the FQDN? An environment variable perhaps?

**Reply by lukeberry99** [reply]
@nununo setting the following in my entrypoint worked for me

```yaml
        forwardedHeaders:
            insecure: true
```

https://doc.traefik.io/traefik/routing/entrypoints/#forwarded-headers

**Reply by nununo** [reply]
Hello @lukeberry99,

I have already done some failed experiments both adding middleware headers:

```yaml
- traefik.enable=true
- traefik.http.services.firefly.loadbalancer.server.port=8080
- traefik.http.middlewares.firefly-headers.headers.sslproxyheaders.X-Forwarded-Proto=https
- traefik.http.middlewares.firefly-headers.headers.sslredirect=true
- traefik.http.routers.firefly.rule=Host(`{{ docker_firefly_fqdn }}`)
- traefik.http.routers.firefly.entrypoints=websecure
- traefik.http.routers.firefly.tls=true
- traefik.http.routers.firefly.middlewares=firefly-headers
- traefik.docker.network=traefik
```

And to the endpoints:

```toml
[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http]
      [entryPoints.web.http.redirections]
        [entryPoints.web.http.redirections.entrypoint]
          to = "websecure"
          scheme = "https"

  [entryPoints.websecure]
    address = ":443"
    [entryPoints.websecure.forwardedHeaders]
      trustedIPs= "0.0.0.0/0"
      insecure = true
```

But I'm glad that worked for you. I'll try it.

I guess I added too much in too many places :)

So what you're saying is that you just added this and it worked for you?

```toml
  [entryPoints.websecure]
    address = ":443"
    [entryPoints.websecure.forwardedHeaders]
      insecure = true
```

I'll give it a try later today.

Thanks!!
Nuno

**Reply by sl33pydog1207** [reply]
@lukeberry99 I'm also interested in your configuration as well.  I've been running into the same issue as @nununo and am unable to figure it out.  What do your labels look like?

edit:  NVM I didn't need the forward header entry point modification.  All I needed was the TRUSTED_PROXIES=** in my environments.  Sorry I should have read the wiki better.

**Reply by nununo** [reply]
Hello @sl33pydog1207,

I found that firefly iii is missing some features I really need. So, while I like it a lot, I'll try a couple of other solutions before I decide on which one I'll adopt. If I do come back to firefly iii I'll investigate this further.

Sorry that I cannot be of any help to you right now.

Regards,
Nuno

**Reply by cybermcm** [reply]
Stumbled over the same issue. Just for everyone with a traefik reverse proxy: No special config needed, just add `TRUSTED_PROXIES=**` as  environment in your docker(compose) config and all is working (thx to @sl33pydog1207).
Remember to add the same option to the csv-importer, I forgot to add it there...

**Comment by glecetre** [comment]
Hi, I'm having the same issue with a Docker install on a Synology NAS and using a reverse proxy.

I've configured the proxy set the `X-Forwarded-Proto` port to `https` and in `.env`, I've set `TRUSTED_PROXIES=**`.
I'm having the same problem as OP: the base URL defined in the HTML meta is `http` but the website is served in `https` so the browser refuses to navigate (I can't log in).

**Reply by JC5** [reply]
These are the headers I use in nginx, hope they help:

```
		proxy_set_header X-Forwarded-Host $host;
		proxy_set_header X-Forwarded-Server $host;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header Host $host;
		client_max_body_size 64M;
		proxy_read_timeout 300s;
```

**Reply by glecetre** [reply]
Unfortunately, this doesn't work. When I set these headers, I can't even reach the application anymore and have a 502 Bad Gateway HTTP error. Maybe this is all specifically releated to Synology NAS. I am using their reverse proxy, configuring it through the UI instead of writing any configuration file.

Edit:
I've managed to make it work.
I've set the headers as you told me and I also changed to `APP_URL` environment variable to the actual URL exposed to the Internet (with `https://`). I didn't do it before because the documentation says it has nearly no impact and it's no use trying to change it if you have a problem.
If anyone has the same issue, there you go. 

Thank you!

**Reply by JC5** [reply]
I will add this thread as an exception though, who knows!

**Reply by Bpazy** [reply]
> Unfortunately, this doesn't work. When I set these headers, I can't even reach the application anymore and have a 502 Bad Gateway HTTP error. Maybe this is all specifically releated to Synology NAS. I am using their reverse proxy, configuring it through the UI instead of writing any configuration file.
> 
> Edit: I've managed to make it work. I've set the headers as you told me and I also changed to `APP_URL` environment variable to the actual URL exposed to the Internet (with `https://`). I didn't do it before because the documentation says it has nearly no impact and it's no use trying to change it if you have a problem. If anyone has the same issue, there you go.
> 
> Thank you!

Hi, I had the same problem yesterday. Such as `add nginx headers`, `clean chrome cache`, `restart nginx`, `restart firefly-iii`, I tried these but it doesn't work.

But it became normal today. All URL start with `https://` now. So maybe some expired cache is the heart of the matter.

Here's the preview:
![image](https://user-images.githubusercontent.com/9838749/160972528-b0161052-c167-4fcf-8246-1355e6be0c23.png)

Here's my nginx conf:
```
server {
    listen 443 ssl;
    server_name firefly.example.com;

    ssl_certificate     /etc/nginx/ssl/fullchain.cer;
    ssl_certificate_key /etc/nginx/ssl/example.com.key;
    ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers         HIGH:!aNULL:!MD5;


    location / {
        proxy_pass http://127.0.0.1:12380;

        proxy_http_version      1.1;
        proxy_cache_bypass      $http_upgrade;
        proxy_set_header Upgrade                $http_upgrade;
        proxy_set_header Connection             "upgrade";
        proxy_set_header Host                   $host;
        proxy_set_header X-Real-IP              $remote_addr;
        proxy_set_header X-Forwarded-For        $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto      $scheme;
        proxy_set_header X-Forwarded-Host       $host;
        proxy_set_header X-Forwarded-Port       $server_port;
    }
}
```

My `docker-compose.yml`:
```yaml
version: '3.3'
  
services:
  app:
    image: fireflyiii/core:latest
    restart: unless-stopped
    volumes:
      - ./firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - 127.0.0.1:12380:8080
    depends_on:
      - db
  db:
    image: mariadb
    hostname: fireflyiiidb
    restart: unless-stopped
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly
    volumes:
      - ./firefly_iii_db:/var/lib/mysql
```

My changed `.env`:
```
TZ=Asia/Shanghai
TRUSTED_PROXIES=**
APP_URL=https://firefly.example.com
```
