### DISCUSSION TITLE
Updating Firefly from old Version - Using old database

### DISCUSSION THREAD

**Discussion by kste1** [firefly-iii/firefly-iii#5013] [Firefly III]
Hi there,

I was using Firefly for roughly two years and was pretty happy with it. I was hosting it myself using docker. 
When I started working with Firefly it was still in a 4.x version. I do not know the exact version, but I would say it was 4.8.2.
I just had a look in the repository and saw, that there have been a lot of new realeases since, so I decided to update my container. 
I always had backups of my db and volumes so I though it would be very easy. 

I can create the application using the new provided docker-compose.yml and .env files, but I cannot manage to restore my old data. I now saw, that the old version was using a postgres database, where it now uses mysql. I tried to get it running setting it to postgres but I did not manage. I guess I will have to convert/migrate my data somehow, is that correct? Unfortunately, I am completely lost here. Is there an "easy" way you could help me out with to get my data running in the new version?

Back at the time I did just use the provided .env and docker-compose.yml files to create the application. This is my .yml file which creates the firefly application:

```
--- 
networks: 
  firefly_iii_net: 
    driver: bridge
services: 
  firefly_iii_app: 
    image: jc5x/firefly-iii:latest
    depends_on:
      - firefly_iii_db
    networks: 
      - firefly_iii_net
    ports: 
      - "80:80"
    env_file: env.env
    volumes: 
      - 
        source: firefly_iii_export
        target: /var/www/firefly-iii/storage/export
        type: volume
      - 
        source: firefly_iii_upload
        target: /var/www/firefly-iii/storage/upload
        type: volume
  firefly_iii_db: 
    image: "postgres:10"
    environment:
      - POSTGRES_PASSWORD=secret_firefly_password
      - POSTGRES_USER=firefly
    networks: 
      - firefly_iii_net
    volumes: 
      - firefly_iii_db:/var/lib/postgresql/data
version: "3.2"
volumes: 
  firefly_iii_db: ~
  firefly_iii_export: ~
  firefly_iii_upload: ~
```

Thanks a lot for your help!

**Comment by JC5** [comment]
Try starting it using postgres:10. And if you have some logs, please share. 

It should upgrade with no trouble, even from that version.

**Comment by kste1** [comment]
Hi @JC5, thanks so much for your quick help! 
You were right, in the end I was able to upgrade it with postgres to the newest version. So your tip was correct. I had to tweak the settings a little bit, but I now have my data in the newest version. Thanks for that!

For everyone that might run into the same issue and might wonder what I did: 

I took the `docker-compose.yml` and the `.env` file from the documentation page. In the YAML I let everything as it is, but just set the db image to postgres:10 (the version was actually important here, did not work with latest). Further, I copied over the environment variables from my old .env file (wich is posted in the question) as well as the path of the volume. 

In the .env file I set the database to `pgsql` and the db port to `5432`. That did the trick for me. So in the end I have this `docker-compose.yml`:

```
version: '3.3'

services:
  app:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: env.env
    ports:
      - 80:8080
    depends_on:
      - db
  db:
    image: postgres:10    
    hostname: fireflyiiidb
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret_firefly_password
      - POSTGRES_USER=firefly
    volumes:
      - firefly_iii_db:/var/lib/postgresql/data
volumes:
   firefly_iii_upload:
   firefly_iii_db:
```

and made these changes to the `.env`:

```
DB_CONNECTION=pgsql
DB_HOST=db
DB_PORT=5432
DB_DATABASE=firefly
DB_USERNAME=firefly
DB_PASSWORD=secret_firefly_password
```
