### DISCUSSION TITLE
Unable to run csv-importer in a docker container

### DISCUSSION THREAD

**Discussion by Haarolean** [firefly-iii/firefly-iii#5062] [Firefly III] [answered]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

If both csv-importer and firefly are being run in containers it's impossible to set importer up. 
CSV-I needs an app url, if I specify localhost it tries to reach the app via localhost and fails (since it's being run in a separate container).
If I specify app's docker hostname like `http://firefly:8080` CSV-I redirects me to this URL in my browser, which is unreachable obviously. 

### Expected behaviour

It works.

### Actual behaviour

It does not.

### Steps to reproduce

I used the following compose file:
```
version: '3.3'

services:
  app:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - 3333:8080
    depends_on:
      - db
    hostname: app
    networks:
      - firefly
  db:
    image: mariadb
    hostname: fireflyiiidb
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly
    volumes:
      - firefly_iii_db:/var/lib/mysql
    networks:
      - firefly

  importer:
    image: fireflyiii/csv-importer:latest
    restart: always
    ports:
      - 3334:8080
    depends_on:
      - app
    networks:
      - firefly
    hostname: csv


volumes:
   firefly_iii_upload:
   firefly_iii_db:


networks:
  firefly:
    driver: bridge
```

### Debug information

Debug information generated at 2021-09-08 02:01:45 Europe/Amsterdam for Firefly III version **5.5.13**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.13 |
| Firefly III API | 1.5.2 |
| PHP | 8.0.8 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | d0961555-fdd4-46c1-83a6-386dd7ad51bb |
| Using docker? | true |
| Telemetry | false |
| Layout | v1 |
| System TZ | Europe/Amsterdam |
| Browser TZ | Europe/Moscow |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-09-01 00:00:00 |
| Session end | 2021-09-30 23:59:59 |
| Session first | 2021-09-07 18:32:13 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36 |
