### DISCUSSION TITLE
Firefly 3 trying to use HTTP with Reverse Proxy (new request)

### DISCUSSION THREAD

**Discussion by alter** [firefly-iii/firefly-iii#5175] [Firefly III]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I run docker image with nginx as reverse proxoy and get:
`refused to send form data to 'http://domain/register' because it violates the following Content Security Policy directive: "form-action 'self'".`
I've already added to .env:
```
APP_URL=https://domain
TRUSTED_PROXIES=**
USE_PROXIES=127.0.0.1
```

my nginx.conf contains:
```
    location / {
      proxy_buffering off;
      proxy_set_header Host $http_host;
      proxy_set_header        X-Real-IP $remote_addr;
      proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header        X-Forwarded-Proto $scheme;
      proxy_http_version 1.1;
      proxy_pass http://127.0.0.1:8080;
      proxy_read_timeout  300;
    }
```

nginx version: nginx/1.20.1
docker image fireflyiii/core:latest for 15.10.2021, repo digest: fireflyiii/core@sha256:8cd228acaa956441ac0d45a0926cfa78f31e562ba78bc22dc036a92e88a0ae3c

### Expected behaviour

properly working https

### Debug information

it just return 302 with redirect to Location: http://domain/login

### Steps to reproduce

docker-compose.yaml
```
version: '3.8'
services:
  firefly:
    image: fireflyiii/core:latest
    expose:
      - "8080"
    ports:
      - "8080:8080"
    env_file:
     - .env
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    networks:
      - firefly
    depends_on:
      - mysql
    restart: always
  mysql:
    image: mysql/mysql-server:latest
    volumes:
      - firefly_mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'firefly'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'dev'
      MYSQL_PASSWORD: 'dev'
    networks:
      - firefly
    expose:
      - '3306'
    restart: always

volumes:
  firefly_iii_upload:
  firefly_mysql:

networks:
  firefly:
    name: firefly
```

.env
```
APP_KEY=quophu9Ka3ohGhiej1QuaeBe4ii1deil
APP_URL=https://domain
DB_HOST=mysql
DB_PORT=3306
DB_CONNECTION=mysql
DB_DATABASE=firefly
DB_USERNAME=user
DB_PASSWORD=pass
TZ=Europe/Moscow
TRUSTED_PROXIES=**
USE_PROXIES=127.0.0.1
```

nginx.conf:
```
server {
    listen 443 ssl;

    server_name domain;

    root /var/www/html;
    index index.html index.htm;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
    ssl_certificate /etc/letsencrypt/live/domain/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/domain/privkey.pem; # managed by Certbot
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
      proxy_buffering off;
      proxy_set_header Host $http_host;
      proxy_set_header        X-Real-IP $remote_addr;
      proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header        X-Forwarded-Proto $scheme;
      proxy_http_version 1.1;
      proxy_pass http://127.0.0.1:8080;
      proxy_read_timeout  300;
    }

}
server {
    listen 80 default_server;
    server_name _;
    access_log /var/log/nginx/access_redirect.log;
    error_log /var/log/nginx/error_redirect.log;
    index index.html index.htm;
    return       301 https://$host$request_uri;
}
```
