### DISCUSSION TITLE
500 Error Could not poll the database: SQLSTATE[HY000] [2006] MySQL server has gone away

### DISCUSSION THREAD

**Discussion by charles-997** [firefly-iii/firefly-iii#5395] [Firefly III]
I am attempting my initial install of FireflyIII.

Using Docker on a Linux server.

Here is my docker-compose file:
```yaml
version: '3.3'

services:
  app:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - /mnt/remotes/TRUENAS.<redacted>.HOME_firefly/upload:/var/www/html/storage/upload
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - SITE_OWNER=<redacted>
      - APP_KEY=<redacted>
      - DEFAULT_LANGUAGE=en_US
      - DEFAULT_LOCALE=equal
      - TZ=America/New_York
      - TRUSTED_PROXIES=**
      - LOG_CHANNEL=stack
      - PAPERTRAIL_HOST=
      - PAPERTRAIL_PORT=
      - APP_LOG_LEVEL=notice
      - AUDIT_LOG_LEVEL=info
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=firefly
      - DB_USERNAME=firefly
      - DB_PASSWORD=<redacted>
      - MYSQL_USE_SSL=false
      - MYSQL_SSL_VERIFY_SERVER_CERT=true
      - MYSQL_SSL_CAPATH=/etc/ssl/certs/
      - MYSQL_SSL_CA=
      - MYSQL_SSL_CERT=
      - MYSQL_SSL_KEY=
      - MYSQL_SSL_CIPHER=
      - PGSQL_SSL_MODE=prefer
      - PGSQL_SSL_ROOT_CERT=null
      - PGSQL_SSL_CERT=null
      - PGSQL_SSL_KEY=null
      - PGSQL_SSL_CRL_FILE=null
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - REDIS_SCHEME=tcp
      - REDIS_PATH=
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379
      - REDIS_PASSWORD=null
      - REDIS_DB="0"
      - REDIS_CACHE_DB="1"
      - COOKIE_PATH="/"
      - COOKIE_DOMAIN=
      - COOKIE_SECURE=false
      - COOKIE_SAMESITE=lax
      - MAIL_MAILER=log
      - MAIL_HOST=null
      - MAIL_PORT=2525
      - MAIL_FROM=changeme@example.com
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - MAILGUN_DOMAIN=
      - MAILGUN_SECRET=
      - MAILGUN_ENDPOINT=api.mailgun.net
      - MANDRILL_SECRET=
      - SPARKPOST_SECRET=
      - SEND_REGISTRATION_MAIL=true
      - SEND_ERROR_MESSAGE=true
      - SEND_LOGIN_NEW_IP_WARNING=true
      - SEND_REPORT_JOURNALS=true
      - ENABLE_EXTERNAL_MAP=false
      - MAP_DEFAULT_LAT=51.983333
      - MAP_DEFAULT_LONG=5.916667
      - MAP_DEFAULT_ZOOM=6
      - AUTHENTICATION_GUARD=web
      - LDAP_DIALECT=OpenLDAP
      - LDAP_HOST=ldap.yourserver.com
      - LDAP_PORT=389
      - LDAP_TIMEOUT=5
      - LDAP_SSL=false
      - LDAP_TLS=false
      - LDAP_BASE_DN="o=something,dc=site,dc=com"
      - LDAP_USERNAME="uid=X,ou=,o=,dc=something,dc=com"
      - LDAP_PASSWORD=super_secret
      - LDAP_AUTH_FIELD=uid
      - LDAP_EXTRA_FILTER=
      - AUTHENTICATION_GUARD_HEADER=REMOTE_USER
      - AUTHENTICATION_GUARD_EMAIL=
      - CUSTOM_LOGOUT_URL=
      - DISABLE_FRAME_HEADER=false
      - DISABLE_CSP_HEADER=false
      - TRACKER_SITE_ID=
      - TRACKER_URL=
      - ALLOW_WEBHOOKS=false
      - STATIC_CRON_TOKEN=
      - DKR_CHECK_SQLITE=true
      - DKR_RUN_MIGRATION=true
      - DKR_RUN_UPGRADE=true
      - DKR_RUN_VERIFY=true
      - DKR_RUN_REPORT=true
      - DKR_RUN_PASSPORT_INSTALL=true
      - APP_NAME=FireflyIII
      - ADLDAP_CONNECTION=default
      - BROADCAST_DRIVER=log
      - QUEUE_DRIVER=sync
      - CACHE_PREFIX=firefly
      - PUSHER_KEY=
      - IPINFO_TOKEN=
      - PUSHER_SECRET=
      - PUSHER_ID=
      - DEMO_USERNAME=
      - DEMO_PASSWORD=
      - IS_HEROKU=false
      - FIREFLY_III_LAYOUT=v1
      - APP_URL=<redacted>
    ports:
      - 8001:8080
    depends_on:
      - db
  db:
    image: mariadb    
    hostname: fireflyiiidb
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=<redacted>
      - MYSQL_DATABASE=firefly
    volumes:
      - /mnt/remotes/TRUENAS.<redacted>.HOME_firefly/db:/var/lib/mysql

```

When I bring the docker stack up, the 2 containers start and the webUI is accessible but only shows an error page.
![image](https://user-images.githubusercontent.com/52077853/145879196-24e1701b-0d3a-42c5-8e01-c150233787ab.png)

The error shown reads:
> Could not poll the database: SQLSTATE[HY000] [2006] MySQL server has gone away (SQL: select `id`, `name`, `data` from `configuration` where `name` = is_demo_site and `configuration`.`deleted_at` is null limit 1)

Is anyone able to point me in the right direction here? Not sure what is going on.  I have a basic (or maybe intermediate?) familiarity with docker & containerization but little to no familiarity with Firefly.
Thanks
