### DISCUSSION TITLE
Docker + Data Importer: Error accessing "127.0.0.1:8080/api/v1/about"

### DISCUSSION THREAD

**Discussion by jike212** [firefly-iii/firefly-iii#5442] [Firefly III]
I'm using Docker Compose with Firefly however I'm unable to get the data importer to see the Firefly installation.

The error I get when accessing the data importer on port 81 is:

`production.ERROR: Could not connect to Firefly III: Error accessing "127.0.0.1:8080/api/v1/about". Status code is 404.`

I'm not sure why it continues to try and access `127.0.0.1:8080` even when I set the environment variable for `FIREFLY_III_URL` to something else.

My Docker Compose file:

```
version: '3.3'

services:
  app:
    image: fireflyiii/core:latest
    hostname: app
    networks:
      - firefly
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - 80:8080
    depends_on:
      - db
  db:
    image: mariadb
    hostname: fireflyiiidb
    networks:
      - firefly
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly
    volumes:
      - firefly_iii_db:/var/lib/mysql

  data_importer:
    image: fireflyiii/data-importer:latest
    hostname: data
    networks:
      - firefly
    restart: always
    ports:
      - 81:8080
    depends_on:
      - app
    environment:
      - VANITY_URL=https://my.domain.com
      - FIREFLY_III_URL=http://app
volumes:
   firefly_iii_upload:
   firefly_iii_db:

networks:
  firefly:
    driver: bridge
```
