### DISCUSSION TITLE
Question on API id types that appear as both int and string in the schema.

### DISCUSSION THREAD

**Discussion by jafin** [firefly-iii/firefly-iii#5605] [Firefly III] [answered]
I generate a strongly typed client from the OpenAPI Schema.
And what I notice is that in various API calls, the /get  will specify the id as an `integer`.
But a put/post will require the id as a `string`.

For example:

```yaml
api/v1/rule_groups/{id}/rules:
...
- get 
  id: integer

RuleStore:
...
 rule_group_id:
    type: string
    format: string
    example: "81"

```

When using a typed client, this requires casting the string <-> int (and vice versa) and feels unnecessary.   
Is there any reason they cannot both can be typed as integers?
