### DISCUSSION TITLE
Can't get MariaDB .db.env to work

### DISCUSSION THREAD

**Discussion by 2600box** [firefly-iii/firefly-iii#5686] [Firefly III]
I am getting this error trying to get myself db working for the first time:

`firefly_iii-db-1    | 2022-02-01 17:00:15 57 [Warning] Access denied for user 'firefly'@'192.168.32.3' (using password: YES)`

I am pulling my hair out. All the DB passwords match up. 

Am I missing some critical configuration below?

```
docker_user@docker ~/firefly_iii$ cat .db.env

MYSQL_RANDOM_ROOT_PASSWORD=yes
MYSQL_USER=firefly
MYSQL_PASSWORD=LongRandomString
MYSQL_DATABASE=firefly
```

```
docker_user@docker ~/firefly_iii$ cat docker-compose.yml
version: '3.3'

services:
  app:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - 7000:8080
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    env_file: .db.env
    volumes:
      - firefly_iii_db:/var/lib/mysql
  fidi:
    image: fireflyiii/data-importer:latest
    env_file: .fidi.env
    ports:
      - 8081:8080
    depends_on:
      - app
volumes:
  firefly_iii_upload:
  firefly_iii_db:
```

```
docker_user@docker ~/firefly_iii$ cat .env

APP_ENV=local
APP_DEBUG=false
SITE_OWNER=mail@example.com
APP_KEY=DifferentLongRandomKey
DEFAULT_LANGUAGE=en_GB
DEFAULT_LOCALE=equal
TZ=Europe/Paris
TRUSTED_PROXIES=
LOG_CHANNEL=stack
PAPERTRAIL_HOST=
PAPERTRAIL_PORT=
APP_LOG_LEVEL=notice
AUDIT_LOG_LEVEL=info
DB_CONNECTION=mysql
DB_HOST=db
DB_PORT=3306
DB_DATABASE=firefly
DB_USERNAME=firefly
DB_PASSWORD= LongRandomString
DB_SOCKET=
MYSQL_USE_SSL=false
MYSQL_SSL_VERIFY_SERVER_CERT=true
MYSQL_SSL_CAPATH=/etc/ssl/certs/
MYSQL_SSL_CA=
MYSQL_SSL_CERT=
MYSQL_SSL_KEY=
MYSQL_SSL_CIPHER=
PGSQL_SSL_MODE=prefer
PGSQL_SSL_ROOT_CERT=null
PGSQL_SSL_CERT=null
PGSQL_SSL_KEY=null
PGSQL_SSL_CRL_FILE=null
PGSQL_SCHEMA=public
CACHE_DRIVER=file
SESSION_DRIVER=file
REDIS_SCHEME=tcp
REDIS_PATH=
REDIS_HOST=127.0.0.1
REDIS_PORT=6379
REDIS_PASSWORD=null
REDIS_DB="0"
REDIS_CACHE_DB="1"
COOKIE_PATH="/"
COOKIE_DOMAIN=
COOKIE_SECURE=false
COOKIE_SAMESITE=lax
MAIL_MAILER=log
MAIL_HOST=null
MAIL_PORT=2525
MAIL_FROM=changeme@example.com
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAILGUN_DOMAIN=
MAILGUN_SECRET=
MAILGUN_ENDPOINT=api.mailgun.net
MANDRILL_SECRET=
SPARKPOST_SECRET=
SEND_REGISTRATION_MAIL=true
SEND_ERROR_MESSAGE=true
SEND_LOGIN_NEW_IP_WARNING=true
SEND_REPORT_JOURNALS=true
ENABLE_EXTERNAL_MAP=false
MAP_DEFAULT_LAT=51.983333
MAP_DEFAULT_LONG=5.916667
MAP_DEFAULT_ZOOM=6
AUTHENTICATION_GUARD=web
LDAP_DIALECT=OpenLDAP
LDAP_HOST=ldap.yourserver.com
LDAP_PORT=389
LDAP_TIMEOUT=5
LDAP_SSL=false
LDAP_TLS=false
LDAP_BASE_DN="o=something,dc=site,dc=com"
LDAP_USERNAME="uid=X,ou=,o=,dc=something,dc=com"
LDAP_PASSWORD=super_secret
LDAP_AUTH_FIELD=uid
LDAP_EXTRA_FILTER=
AUTHENTICATION_GUARD_HEADER=REMOTE_USER
AUTHENTICATION_GUARD_EMAIL=
CUSTOM_LOGOUT_URL=
DISABLE_FRAME_HEADER=false
DISABLE_CSP_HEADER=false
TRACKER_SITE_ID=
TRACKER_URL=
ALLOW_WEBHOOKS=false
STATIC_CRON_TOKEN=
DKR_CHECK_SQLITE=true
DKR_RUN_MIGRATION=true
DKR_RUN_UPGRADE=true
DKR_RUN_VERIFY=true
DKR_RUN_REPORT=true
DKR_RUN_PASSPORT_INSTALL=true
APP_NAME=FireflyIII
ADLDAP_CONNECTION=default
BROADCAST_DRIVER=log
QUEUE_DRIVER=sync
CACHE_PREFIX=firefly
PUSHER_KEY=
IPINFO_TOKEN=
PUSHER_SECRET=
PUSHER_ID=
DEMO_USERNAME=
DEMO_PASSWORD=
IS_HEROKU=false
FIREFLY_III_LAYOUT=v1
APP_URL=http://localhost
```

```
docker_user@docker ~/firefly_iii$ cat .fidi.env
FIREFLY_III_URL=
VANITY_URL=
FIREFLY_III_ACCESS_TOKEN=
FIREFLY_III_CLIENT_ID=
NORDIGEN_ID=
NORDIGEN_KEY=
NORDIGEN_SANDBOX=false
SPECTRE_APP_ID=
SPECTRE_SECRET=
USE_CACHE=false
IGNORE_DUPLICATE_ERRORS=false
AUTO_IMPORT_SECRET=
CAN_POST_AUTOIMPORT=false
CAN_POST_FILES=false
IMPORT_DIR_WHITELIST=
VERIFY_TLS_SECURITY=true
JSON_CONFIGURATION_DIR=
CONNECTION_TIMEOUT=31.41
APP_ENV=local
APP_DEBUG=false
LOG_CHANNEL=stack
LOG_LEVEL=debug
TRUSTED_PROXIES=
TZ=Europe/Amsterdam
ASSET_URL=
ENABLE_MAIL_REPORT=false
EXPECT_SECURE_URL=false
MAIL_MAILER=
MAIL_DESTINATION=noreply@example.com
MAIL_FROM_ADDRESS=noreply@example.com
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=username
MAIL_PASSWORD=password
MAIL_ENCRYPTION=null
MAILGUN_DOMAIN=
MAILGUN_SECRET=
MAILGUN_ENDPOINT=
POSTMARK_TOKEN=
BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120
IS_EXTERNAL=false
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379
REDIS_DB="0"
REDIS_CACHE_DB="1"
TRACKER_SITE_ID=
TRACKER_URL=
APP_NAME=DataImporter
APP_URL=http://localhost
```
