### DISCUSSION TITLE
Firefly iii data import connection error

### DISCUSSION THREAD

**Discussion by shizunge** [firefly-iii/firefly-iii#5772] [Firefly III] [answered]
I am currently migrating from the old csv importer to the new data import.

I need help to resolve the problem about `connection error`

The import tool version is v0.8.0.
The error I got is 
![image](https://user-images.githubusercontent.com/1281491/153788943-bdd3e7f6-b64e-429f-8f9e-e0d18f3ab455.png)
Start over or Reauthenticate does not help.
I have also tried to use a new token, it did not help.

There is no error message in the UI or in the docker log. So I have no clue where I should debug my setup.

I started the services using a docker compose file. (non swarm mode)

```
  firefly-csv:
    image: fireflyiii/data-importer:latest
    container_name: firefly-csv
    restart: always
    hostname: firefly-csv
    networks:
      - traefik
    env_file:
      - ./env-global.env
    environment:
      - FIREFLY_III_ACCESS_TOKEN=${FIREFLY_III_ACCESS_TOKEN}
      - FIREFLY_III_URL=http://firefly-iii:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${VOLUME_PATH}/firefly-iii/csv-importer/storage/configurations:/var/www/html/storage/configurations
      - ${VOLUME_PATH}/firefly-iii/csv-importer/storage/upload/:/var/www/html/storage/upload
```

Docker log looks like:
```
today at 18:05:23Now in entrypoint.sh for Firefly III Data Importer
today at 18:05:23Script:        1.5 (2021-12-05)
today at 18:05:23User:          'root'
today at 18:05:23Group:         'root'
today at 18:05:23Working dir:   '/var/www/html'
today at 18:05:23Build number:  93
today at 18:05:23Build date:    06-02-2022 09:21:56 CET
today at 18:05:35Firefly III data importer v0.8.0
today at 18:05:35PHP: cli 8.0.13 Linux
today at 18:05:36Will now run Apache web server:
today at 18:05:36AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.31.240.13. Set the 'ServerName' directive globally to suppress this message
today at 18:05:36AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.31.240.13. Set the 'ServerName' directive globally to suppress this message
today at 18:05:36[Sun Feb 13 18:05:36.386576 2022] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) configured -- resuming normal operations
today at 18:05:36[Sun Feb 13 18:05:36.386909 2022] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
today at 18:05:37[2022-02-13 18:05:37] production.DEBUG: Now in App\Http\Controllers\IndexController::index  
today at 18:05:37[2022-02-13 18:05:37] production.DEBUG: App\Services\Shared\Authentication\SecretManager::hasValidSecrets  
today at 18:05:37172.31.240.47 - - [13/Feb/2022:18:05:36 -0800] "GET / HTTP/1.1" 200 3158 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0"
today at 18:05:40[2022-02-13 18:05:40] production.DEBUG: Now in App\Http\Controllers\IndexController::index  
today at 18:05:40[2022-02-13 18:05:40] production.DEBUG: App\Services\Shared\Authentication\SecretManager::hasValidSecrets  
today at 18:05:40172.31.240.47 - - [13/Feb/2022:18:05:40 -0800] "GET / HTTP/1.1" 200 3158 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0"
today at 18:05:41[2022-02-13 18:05:41] production.DEBUG: Now in App\Http\Controllers\IndexController::index  
today at 18:05:41[2022-02-13 18:05:41] production.DEBUG: App\Services\Shared\Authentication\SecretManager::hasValidSecrets  
today at 18:05:41172.31.240.47 - - [13/Feb/2022:18:05:41 -0800] "GET / HTTP/1.1" 200 3158 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0"
today at 18:11:52[2022-02-13 18:11:52] production.DEBUG: Now in App\Http\Controllers\IndexController::index  
today at 18:11:52[2022-02-13 18:11:52] production.DEBUG: App\Services\Shared\Authentication\SecretManager::hasValidSecrets  
```

Firefly-iii info:
Debug information generated at 2022-02-13 18:13:42 America/Los_Angeles for Firefly III version **5.6.14**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.14 |
| Firefly III API | 1.5.5 |
| Build | 96, 05-02-2022 10:01:49 CET |
| PHP | 8.0.13 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 57a1d0d8-18b6-4a3a-87e2-654f62b99727 |
| Using docker? | true |
| Layout |  |
| System TZ | America/Los_Angeles |
| Browser TZ | America/Los_Angeles |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | 172.31.240.0/20 |

| User info | Value |
| --- | --- |
| Session start | 2022-01-01 00:00:00 |
| Session end | 2022-12-31 23:59:59 |
| Session first | 2018-12-18 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0 |
