### DISCUSSION TITLE
Setup CronJob for data-importer from Nordigen Vol. 2

### DISCUSSION THREAD

**Discussion by AndreiGavriliu** [firefly-iii/firefly-iii#5963] [Firefly III]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

HI, I've finally managed to try again to move to kuberntes. Everything runs smoothly, however, I still cannot create a cronjob which automagically imports from nordigen via data-importer into firefly-iii.. (#5484 was my last attempt)

here's my "import" script:

```
#!/bin/bash
ACCESS_TOKEN=[redacted]
SECRET_ID=[redacted]
SECRET_KEY=[redacted]

curl -v --location --request POST 'http://[redacted]/autoupload?secret=[redacted]' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer ${access_token}' \
--form 'json=@"./import_config_2022-04-03.json"'
```

Here's where I'm confused. The cURL command from [here](https://docs.firefly-iii.org/data-importer/usage/post/#uploading-files-and-importing-them) requires `secret_id` and `secret_key` (actually nordigen requires them), or it fails with `Client error: POST https://ob.nordigen.com/api/v2/token/new/ resulted in a '400 Bad Request' response:\n{\"secret_id\":[\"This field may not be blank.\"],\"status_code\":400}\n`. I added these two into my previously generated `import_config_2022-04-03.json` file. Now the error changed to `{"message":"The given data was invalid.","errors":{"json":["The json field is required."]}}`

The `import_config_2022-04-03.json` file is available under `/configurations/import_config_2022-04-03.json` in the data-importer pod. I can also select it manually from the UI

Were/what am I doing wrong? All I am trying to achieve is run some kind of cronjob that triggers the data-importer to request "yesterdays" transactions and import them in my firefly-iii instance. All this without manual intervention.

Cheers,
Andrei

### Expected behaviour

Successful import from nordigen via UNIX CronJob running a cURL POST

### Debug information

Debug information generated at 2022-04-03 21:29:05 Europe/Amsterdam for Firefly III Data Importer version **0.9.2**.

| Scope | Version |
| --- | --- |
| FIDI | 0.9.2 |
| Build | 108, 02-04-2022 14:05:32 CEST |
| PHP | 8.0.17 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Using docker? | true |
| System TZ |  |
| Browser TZ | Europe/Berlin |
| App environment | production |
| App debug mode | true |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| BCscale | 12 |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:98.0) Gecko/20100101 Firefox/98.0 |

**Comment by JC5** [comment]
> The cURL command from [here](https://docs.firefly-iii.org/data-importer/usage/post/#uploading-files-and-importing-them) requires secret_id and secret_key (actually nordigen requires them),

I don't know what you mean by this. These fields are not present in the cURL command you show. How are they "required"?

> The import_config_2022-04-03.json file is available under /configurations/import_config_2022-04-03.json in the data-importer pod. I can also select it manually from the UI

If the file is present on the server you may be better of using this command:

`curl --location --request POST 'https://fidi/autoimport?directory=/configurations&secret=YOURSECRETHERE'`

**Comment by AndreiGavriliu** [comment]
I ran this, it failed with the following error:

```
# curl --location --request POST 'http://[redacted-fidi-url]/autoimport?directory=/configurations&secret=P3ntdr1g0n7wiuCHle' --header 'Accept: application/json' --header 'Content-Type: application/json' --header 'Authorization: Bearer ${access_token}'
2022-04-04 07:22:55: Going to convert from file /configurations/import-nordigen.json using configuration /configurations/import-nordigen.json and flow "nordigen".
{
    "message": "Client error: `POST https://ob.nordigen.com/api/v2/token/new/` resulted in a `400 Bad Request` response:\n{\"secret_id\":[\"This field may not be blank.\"],\"status_code\":400}\n",
    "exception": "GuzzleHttp\\Exception\\ClientException",
    "file": "/var/www/html/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php",
    "line": 113,
    "trace": [...
```

apparently it is trying to import `import-nordigen.json` as the "data" file file using the `import-nordigen.json` configuration file...

my deployment is:
```
            - name: FIREFLY_III_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: firefly-iii
                  key: access_token
            - name: FIREFLY_III_URL
              value: "[redacted]"
            - name: TRUSTED_PROXIES
              value: "**"
            - name: AUTO_IMPORT_SECRET
              value: "[redacted]"
            - name: CAN_POST_FILES
              value: "true"
            - name: CAN_POST_AUTOIMPORT
              value: "true"
            - name: JSON_CONFIGURATION_DIR
              value: "/configurations"
            - name: IMPORT_DIR_WHITELIST
              value: "/configurations"
          ports:
            - containerPort: 8080
              name: data-importer
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /configurations/import-nordigen.json
              subPath: import-nordigen.json
              name: import-nordigen
      volumes:
        - name: import-nordigen
          configMap:
            name: import-nordigen
```

the `/configuration` from the FIDI pod:
```
root@data-importer-5cbbb7868b-4l4cv:/var/www/html# ls -al /configurations/
total 12
drwxr-xr-x 2 root root 4096 Apr  4 05:17 .
drwxr-xr-x 1 root root 4096 Apr  4 05:17 ..
-rw-r--r-- 1 root root 1063 Apr  4 05:17 import-nordigen.json
```
I even added the secrets at the end of my import-nordigen.json file 
```
...
  "nordigen_country": "DE",
  "nordigen_bank": "[redacted]",
  "nordigen_requisitions": {
    "[redacted]": "[redacted]"
  },
  "conversion": false,
  "secret_id": "[redacted]",
  "secret_key": "[redacted]"
}
```
... I'm confused. Where should I store the `secret_id` and `secret_key`
