### DISCUSSION TITLE
ERROR: Could not poll the database

### DISCUSSION THREAD

**Discussion by campana-giuseppe** [firefly-iii/firefly-iii#6200] [Firefly III] [answered]
Hello,
I have installed (or at least tried =D ) Firefly on Docker. 
When I go to the page I load the Firefly error page with the following error shown : **_Could not poll the database: SQLSTATE[HY000] [2002] No such file or directory (SQL: select `id`, `name`, `data` from `configuration` where `name` = is_demo_site and `configuration`.`deleted_at` is null limit 1)_**

This is the compose that i used:

```
version: '3.3'

services:
  app:
    container_name: firefly3_app
    image: fireflyiii/core:latest
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - APP_KEY=S0m3R@nd0mStr1ngOf32Ch@rsEx@ctly
    volumes:
      - /xxxxx/export:/var/www/html/storage/export
      - /xxxxx/upload:/var/www/html/storage/upload
    ports:
      - 7097:8080
    depends_on:
      - db
  db:
    container_name: firefly3_db
    image: mariadb    
    hostname: fireflyiiidb
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USERNAME=xxxx
      - MYSQL_PASSWORD=xxxx
      - MYSQL_DATABASE=firefly
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/server/docker-applications/firefly/database:/var/lib/mysql
volumes:
   upload:
   export:
   database:
```

one thing i have noticed is that the .env file is perhaps not picked up, at the first deployment i was getting a 404 with an error in the logs that the key was not specified and after entering it in the compose i resolved the error and switched to this one.

I tried adding different combinations of variables (especially those concerning the db) from the .env file but nothing.
