### DISCUSSION TITLE
No entrypoint when starting docker compose

### DISCUSSION THREAD

**Discussion by LuKaS0473** [firefly-iii/firefly-iii#6274] [Firefly III]
I want to run Firefly-iii with docker compose and nginx as proxy. Nginx works and the database too. But the firerfly-iii service is not starting. By default it should show "Now in entrypoint.sh for Firefly III", but all it does is: 
"
firefly-iii-app-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
firefly-iii-app-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
firefly-iii-app-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
firefly-iii-app-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
firefly-iii-app-1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
firefly-iii-app-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
firefly-iii-app-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
firefly-iii-app-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
"

Here my docker compose file: 
"
version: '3.3'

services:
  app:
    build: ./frontend
    image: fireflyiii/core:latest
    environment:
      - VIRTUAL_HOST=myurl.com
      - LETSENCRYPT_HOST=myurl.com
      - LETSENCRYPT_EMAIL=myemail.com
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - default
  db:
    image: mariadb
    hostname: fireflyiiidb
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly
    volumes:
      - firefly_iii_db:/var/lib/mysql
    networks:
      - default
volumes:
   firefly_iii_upload:
   firefly_iii_db:

networks:
  default:
    external: true
    name: proxy"
"

**Comment by JC5** [comment]
Why did you add the "build:" line?

**Reply by LuKaS0473** [reply]
To add the nginx.conf to the docker container

**Reply by madindehead** [reply]
> To add the nginx.conf to the docker container

That's not how you add the nginx.conf.

**Comment by JC5** [comment]
And why are there env variables AND a .env file?

**Reply by LuKaS0473** [reply]
the .env file is for firefly and the env variables is for nginx

**Comment by LuKaS0473** [comment]
I added the env variables in the .env file and I deleted the build entry and same result. DB is running fine, but firefly won't start.
New docker-compose.yml:

```
version: '3.3'

services:
  app:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - default
  db:
    image: mariadb
    hostname: fireflyiiidb
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly
    volumes:
      - firefly_iii_db:/var/lib/mysql
    networks:
      - default
volumes:
   firefly_iii_upload:
   firefly_iii_db:

networks:
  default:
    external: true
    name: proxy
```
