### DISCUSSION TITLE
Firefly 502 error running through Portainer and Nginx Proxy Manager

### DISCUSSION THREAD

**Discussion by fernyzablah** [firefly-iii/firefly-iii#6276] [Firefly III]
Hi! I am new to self-hosting and reverse-proxying, I can't figure out what I am doing wrong or what the correct set up is. I am using Portainer to deploy a firefly-iii stack (basically using all the defaults) and then trying to set up with Nginx Proxy Manager, but I get a 502 error.

This is the docker compose (in portainer)

```
version: '3.3'

services:
  app:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    ports:
      - 5191:8080
    depends_on:
      - db
  db:
    image: mariadb    
    hostname: fireflyiiidb
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=firefly
    volumes:
      - firefly_iii_db:/var/lib/mysql
volumes:
   firefly_iii_upload:
   firefly_iii_db:
networks:
  default:
    name: proxyman_default
    external: true
```

and all the environment variables
```
APP_ENV=local
APP_DEBUG=false
SITE_OWNER=flop****@gmail.com
APP_KEY=Lyv3ZPKHTWjj0PoquLuCWDsuWfnhx1DI
DEFAULT_LANGUAGE=en_US
DEFAULT_LOCALE=equal
TZ=Europe/Amsterdam
TRUSTED_PROXIES=**
LOG_CHANNEL=stack
APP_LOG_LEVEL=notice
AUDIT_LOG_LEVEL=info
DB_CONNECTION=mysql
DB_HOST=db
DB_PORT=3306
DB_DATABASE=firefly
DB_USERNAME=firefly
DB_PASSWORD=
MYSQL_USE_SSL=false
MYSQL_SSL_VERIFY_SERVER_CERT=true
MYSQL_SSL_CAPATH=/etc/ssl/certs/
PGSQL_SSL_MODE=prefer
PGSQL_SSL_ROOT_CERT=null
PGSQL_SSL_CERT=null
PGSQL_SSL_KEY=null
PGSQL_SSL_CRL_FILE=null
PGSQL_SCHEMA=public
CACHE_DRIVER=file
SESSION_DRIVER=file
REDIS_SCHEME=tcp
REDIS_HOST=127.0.0.1
REDIS_PORT=6379
REDIS_PASSWORD=null
REDIS_DB="0"
REDIS_CACHE_DB="1"
COOKIE_PATH="/"
COOKIE_SECURE=false
COOKIE_SAMESITE=lax
MAIL_MAILER=log
MAIL_HOST=null
MAIL_PORT=2525
MAIL_FROM=changeme@example.com
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAILGUN_ENDPOINT=api.mailgun.net
SEND_REGISTRATION_MAIL=true
SEND_ERROR_MESSAGE=true
SEND_LOGIN_NEW_IP_WARNING=true
SEND_REPORT_JOURNALS=true
ENABLE_EXTERNAL_MAP=false
MAP_DEFAULT_LAT=51.983333
MAP_DEFAULT_LONG=5.916667
MAP_DEFAULT_ZOOM=6
AUTHENTICATION_GUARD=web
AUTHENTICATION_GUARD_HEADER=REMOTE_USER
DISABLE_FRAME_HEADER=false
DISABLE_CSP_HEADER=false
ALLOW_WEBHOOKS=false
DKR_BUILD_LOCALE=false
DKR_CHECK_SQLITE=true
DKR_RUN_MIGRATION=true
DKR_RUN_UPGRADE=true
DKR_RUN_VERIFY=true
DKR_RUN_REPORT=true
DKR_RUN_PASSPORT_INSTALL=true
APP_NAME=FireflyIII
BROADCAST_DRIVER=log
QUEUE_DRIVER=sync
CACHE_PREFIX=firefly
IS_HEROKU=false
FIREFLY_III_LAYOUT=v1
APP_URL=https://fire.{iputmydomainhere}.com
```

I just copied the .env from the documentation and loaded it into Portainer, I only changed the ones that are necessary.

I added the containers to my proxy network (proxyman_default), which is where I've been able to reverse proxy my other containers. For example, miniflux and syncthing:

![image](https://user-images.githubusercontent.com/87058028/182049837-283f1013-33e7-4160-b6e1-df1c089aaef2.png)
![image](https://user-images.githubusercontent.com/87058028/182049855-f1513960-0379-4ad1-b51c-d5dbd302c01a.png)

but to be honest, I got those working through brute trial and error, changing the ports around on nginx proxy manager. I tried using the servers actual IP address instead of "firefly" and relying on the Docker network, but that also leads to the same 502 result. I'd appreciate some guidence as to how to avoid a 502 error when entering fire.mydomain.com or just in general how to set up the reverse proxy for Firefly. I tried without SSL and it also gives a 502.
