### DISCUSSION TITLE
backup and restore of database 'forgets' the user

### DISCUSSION THREAD

**Discussion by schepens83** [firefly-iii/firefly-iii#6399] [Firefly III] [answered]
Hello

I'm running firefly on my ubuntu desktop through docker with a docker-compose file. Now I've got a year of data and especially rules set up I want to make a backup. I tried backing up my database volume and it seems to work, except it doesnt seem to migrate the user itself. When i run with the old volume and with a tmp volume with the backup restored, basically all the startup output is the same wrt to the database which tells me the database was actually transferred correctly. When it comes to the running report commands it doesn't see the user though. 

Logs can be found here: [logs.zip](https://github.com/firefly-iii/firefly-iii/files/9507664/logs.zip)

My config:
```yaml
version: '3.3'

services:

  fireflyiii_mysql:
    container_name: fireflyiiimysql
    image: jc5x/firefly-iii:version-5.4.6
    volumes:
      - firefly_iii_mysql_upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - 8090:8080
    depends_on:
      - fireflyiiimysqldb

  fireflyiiimysqldb:
    image: intland/mysql:5.7.21
    environment:
      # - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly
    volumes:
      - firefly_mysql_db:/var/lib/mysql
    ports:
      - 83:3306

  fireflyimport_mysql:
    image: fireflyiii/csv-importer:latest
    environment:
      - FIREFLY_III_ACCESS_TOKEN=xxxx
      - FIREFLY_III_URL=http://fireflyiii_mysql:8080
    ports:
      - 8091:8080

volumes:
   firefly_iii_mysql_upload:


   firefly_mysql_db:

```

If anything else is needed let me know. Hope anyone can help me!
