### DISCUSSION TITLE
Unable to connect to MySQL database via SSL. (DB: SQLSTATE[HY000] [1105] unknown error: Code: UNAVAILABLE)

### DISCUSSION THREAD

**Discussion by frodera** [firefly-iii/firefly-iii#6422] [Firefly III]
Configuration (set via `values.yaml` in [firefly-iii helm chart](https://github.com/firefly-iii/kubernetes/tree/main/charts/firefly-iii), I'm running this in my homelab Kubernetes cluster):

```yaml
    values:
      - image:
          tag: alpha # tried stable and several other versions, same error
      - persistence:
          enabled: false
      - config:
          existingSecret: "firefly-iii-secret-variables"
          env:
            # APP_LOG_LEVEL: debug
            DB_CONNECTION: mysql
            DB_DATABASE: firefly-3
            DB_HOST: aws-ap-southeast-2.connect.psdb.cloud
            DB_PORT: 3306
            DB_USERNAME: myusername
            MYSQL_SSL_CA: /etc/ssl/certs/ca-certificates.crt
            MYSQL_SSL_CAPATH: /etc/ssl/certs/
            MYSQL_SSL_VERIFY_SERVER_CERT: true
            MYSQL_USE_SSL: true
```

Note: Commenting out either `MYSQL_SSL_CA` or `MYSQL_SSL_CAPATH` produces the same error.

For context, I'm trying to to connect to a [Planetscale](https://planetscale.com) MySQL serverless instance, which [mandates SSL/TLS validation.](https://planetscale.com/docs/concepts/secure-connections).

I've tried connecting via `mysql` CLI from my laptop to the very same MySQL instance and it works fine:

```shell
mysql -h aws-ap-southeast-2.connect.psdb.cloud -u myusername --ssl-mode=VERIFY_IDENTITY --ssl-ca=/etc/ssl/cert.pem -p
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 2554422908
Server version: 8.0.23-PlanetScale
[...]
mysql>
```

Error:

```
| Discovered Package: rcrowe/twigbridge                                                                                                                   │
│ Package manifest generated successfully.                                                                                                                │
│ Current working dir is '/var/www/html'                                                                                                                  │
│ Wait for the database.                                                                                                                                  │
│ wait-for-it.sh: waiting 60 seconds for aws-ap-southeast-2.connect.psdb.cloud:3306                                                                       │
│ wait-for-it.sh: aws-ap-southeast-2.connect.psdb.cloud:3306 is available after 1 seconds                                                                 │
│ DB is up. Time to execute artisan commands.                                                                                                             │
│ Wait another 5 seconds in case the DB needs to boot.                                                                                                    │
│ Done waiting for the DB to boot.                                                                                                                        │
│ Current working dir is '/var/www/html'                                                                                                                  │
│ Run various artisan commands...                                                                                                                         │
│ Running migration commands...                                                                                                                           │
│ Error when connecting to DB: SQLSTATE[HY000] [1105] unknown error: Code: UNAVAILABLE                                                                    │
│ server does not allow insecure connections, client must use SSL/TLS
```
