### DISCUSSION TITLE
Database connection refused, InnoDB error 2 in MariaDB when starting Firefly III via Docker Compose

### DISCUSSION THREAD

**Discussion by sandervh14** [firefly-iii/firefly-iii#6439] [Firefly III] [answered]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

It turns out that using the latest image of MariaDB in `docker-compose.yml` did not work for me, and may also not work for other users starting Firefly III via Docker.

The Firefly III logs mentioned `Connection refused` a lot, the MariaDB logs mentioned on start-up the error `InnoDB: preallocating 147456 bytes for file ./firefly/tag_transaction_journal.ibd failed with error 2`.

The solution for me was to clearly specify the image for MariaDB as `image: mariadb:10.3.9` in the `docker-compose.yml` file. if the error starts happening for a lot of users, changing the MariaDB image version could be a good idea for the code base, otherwise, if just a few people sporadically also encounter this problem, I wrote up this issue for them. 

More details below in Additional info.

### Expected behaviour

No MariaDB database errors while using Firefly III with Docker (Compose).

### Debug information

Debug information generated at 2022-09-18 14:27:28 Europe/Amsterdam for Firefly III version **5.7.12**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.12 |
| Firefly III API | 1.5.6 |
| Build | 255, 11-09-2022 07:30:27 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.1.9` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Amsterdam |
| Browser TZ | Europe/Brussels |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-09-01 00:00:00 |
| Session end | 2022-09-30 23:59:59 |
| Session first | 2022-09-18 13:59:04 |
| User ID | 1 |
| User language | nl_NL |
| User locale | nl_NL |
| Attempt at "nl_NL.utf8" | 'nl_NL.utf8' |
| Attempt at "nl_NL.UTF-8" | 'nl_NL.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 |

### Steps to reproduce

1. Start Firefly III through Docker Compose (`docker-compose -f docker-compose.yml up -d`) as per the instructions on https://docs.firefly-iii.org/firefly-iii/installation/docker/#using-docker-compose.

I changed the docker-compose.yml file though to use bind mounts, instead of regular Docker volumes, for both the Firefly and the MariaDB containers, but this should not be the root cause of the problem I report here.

```
version: '3.3'

services:
  app:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      # Bind mount instead of a Docker volume, to be able to easily backup the files generated by Firefly-III.
      # - firefly_iii_upload:/var/www/html/storage/upload
      - ./firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - 80:8080
    depends_on:
      - db
  db:
    image: mariadb
    hostname: fireflyiiidb
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly
    volumes:
      # Bind mount instead of a Docker volume, to be able to easily backup the files generated by Firefly-III.
      # - firefly_iii_db:/var/lib/mysql
      - ./firefly_iii_db:/var/lib/mysql
# volumes:
   # Bind mounts instead of Docker volumes, to be able to easily backup the files generated by Firefly-III.
   # firefly_iii_upload:
   # firefly_iii_db:
```

I made no changes to the .env file.

2. I opened Firefly III at http://localhost/, filled some account credentials in the registration form and submitted the form.
3. A "Whoops" page appears. The container logs indicate that database connections are refused - see Additional info below.

### Additional info

When starting Firefly III for the first time through Docker Compose (`docker-compose -f docker-compose.yml up -d`), I could start Firefly and fill in the account registration form, but when submitting that form, I got a "Whoops" error page. 

Looking at the logs of Firefly III, a database error occurred, because a table did not yet properly exist.

Looking at the logs of Firefly's initial set-up, it looks like it was not able to run the database migrations successfully. The first fail is at:

```
2016_06_16_000002_create_main_tables .......................... 2,321ms FAIL
[2022-09-18 12:29:42] local.ERROR: Exception is: {"class":"Illuminate\\Database\\QueryException","errorMessage":"SQLSTATE[HY000] [2002] Connection refused (SQL: alter table `tag_transaction_journal` add unique `tag_transaction_journal_tag_id_transaction_journal_id_unique`(`tag_id`, `transaction_journal_id`))","time":"Sun, 18 Sep 2022 12:29:42 +0200","file":"\/var\/www\/html\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Connection.php","line":759,"code":2002,"version":"5.7.12","url":"http:\/\/localhost","userAgent":"Symfony","json":true,"method":"GET"}  
```

Looking at the logs of the MariaDB container, the first error on start-up was `[ERROR] InnoDB: preallocating 147456 bytes for file ./firefly/tag_transaction_journal.ibd failed with error 2 2022-09-18 10:29:42 0x7f97b01bf640 InnoDB: Assertion failure in file ./storage/innobase/fil/fil0fil.cc line 604`.

I found the following StackOverflow question that corresponded with this problem: https://stackoverflow.com/questions/70784437/innodb-preallocating-147456-bytes-for-file-xxx-ibd-failed-with-error-2.
The root cause of this problem has not been found in the answer to this question, but the answer and a comment below suggested that reverting MariaDB to version 10.3.9 helps avoiding the problem.

So I changed the MariaDB image in my `docker-compose.yml` to `image: mariadb:10.3.9` as follows:

```
version: '3.3'

services:
  app:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      # Bind mount instead of a Docker volume, to be able to easily backup the files generated by Firefly-III.
      # - firefly_iii_upload:/var/www/html/storage/upload
      - ./firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - 80:8080
    depends_on:
      - db
  db:
    # image: mariadb ==> changed version because of https://stackoverflow.com/questions/70784437/innodb-preallocating-147456-bytes-for-file-xxx-ibd-failed-with-error-2.
    image: mariadb:10.3.9   
    hostname: fireflyiiidb
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly
    volumes:
      # Bind mount instead of a Docker volume, to be able to easily backup the files generated by Firefly-III.
      # - firefly_iii_db:/var/lib/mysql
      - ./firefly_iii_db:/var/lib/mysql
# volumes:
   # Bind mounts instead of Docker volumes, to be able to easily backup the files generated by Firefly-III.
   # firefly_iii_upload:
   # firefly_iii_db:
```

Note that changing the Docker volumes to bind mounts was just my own choice, not related to this problem.

I'm writing this down, so other users bumping into the same issue will easily find a fix. Thank you for the great software!!
