### DISCUSSION TITLE
data import connection error 401

### DISCUSSION THREAD

**Discussion by TWART016** [firefly-iii/firefly-iii#6541] [Firefly III]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I am running the data importer for some time. Now I get the error in the CLI and UI.
`Error accessing "http://192.168.178.36:10000/api/v1/about?". Status code is 401. Body is: {"message":"Unauthenticated","exception":"AuthenticationException"}`

```
  import:
    image: fireflyiii/data-importer:latest
    container_name: fireflyiii_import_data
    restart: unless-stopped
    volumes:
      - /volume1/Skripte/fireflyIII/import:/import
      - /volume1/docker/fireflyIII/import/temp:/data
    ports:
      - 10001:8080
    environment:
      - FIREFLY_III_ACCESS_TOKEN=MY_Client_Token
      - FIREFLY_III_URL=http://192.168.178.36:10000
      - JSON_CONFIGURATION_DIR=/import/configurations 
      - IMPORT_DIR_WHITELIST=/import/configurations
      - IMPORT_DIR_WHITELIST=/data,/import/configurations
    depends_on:
      - app
      - db
```
   
Importer v0.9.16 

### Expected behaviour

correct authentication

### Debug information

Debug information generated at 2022-10-15 00:53:17 Europe/Amsterdam for Firefly III version **5.7.12**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.12 |
| Firefly III API | 1.5.6 |
| Build | 255, 11-09-2022 07:30:27 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.1.9` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Amsterdam |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-10-01 00:00:00 |
| Session end | 2022-12-31 23:59:59 |
| Session first | 2019-01-02 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 |

**Comment by JC5** [comment]
There's not much that can go wrong here I'm afraid. Regenerating the token should do the trick.

**Reply by TWART016** [reply]
After creating the a new Personal Token the import script is working fine. In the browser it maybe was a caching problem.
Strange is that I still had the error in container logs.

**Comment by poudenes** [comment]
Hi All,

I want reopen this issue. Since couple of weeks I get same issue. Every time I create a new token in FFIII and add them into the importer. Restart de importer docker and then it's working again. But what can I do to investigate why this happen?

Does it happen when FFIII is getting updated ?

**Reply by JC5** [reply]
No, the token survives an upgrade. At least, it does for me. 

I'm not sure exactly WHEN the token invalidates for you, do you have that clear?

**Comment by poudenes** [comment]
This morning I recreated a new token. From now on I will monitor everything. When there is an auto update of FFIII docker and will this affect the working of the importer. I will come back with some info later.

**Comment by poudenes** [comment]
This morning there was no email that import was done automatically. Did it manual and again this error:

```
Will launch auto import on /import directory.
Could not connect to Firefly III at http://172.30.33.119:8080: Error accessing "http://172.30.33.119:8080/api/v1/about?". Status code is 401. Body is: {"message":"Unauthenticated","exception":"AuthenticationException"}
Could not connect to your local Firefly III instance at http://172.30.33.119:8080.
```

FireFlyIII or FireFlyIII Importer are both not updated (docker).

Coupe of weeks ago I enabled 2FA. This was only change I did on the config lately. I will disable this and renew token and see if this will help.

**Reply by JC5** [reply]
Mmmmm. Have the containers been restarted recently?

**Reply by poudenes** [reply]
Fitefly III runs now for 28 days. So that's not the problem also.

**Reply by JC5** [reply]
Before you try it manually, press [Reauthenticate]

**Comment by poudenes** [comment]
Since I deactivate the 2FA 3 weeks ago everything works great again. No errors that token is invalid. No new tokens created to let it work. So for me it looks like the 2FA was the problem maker

**Comment by IniterWorker** [comment]
I encountered a similar error recently, and after some investigation, I found success by utilizing Kustomize for managing my Kubernetes configurations. Through this approach of blanking `access_token`, I was able to resolve the issue and successfully select a client_id for OAuth. While I'm uncertain if this aligns with the best practices, I can confirm that it's both functional and secure.

Here's a snippet of the YAML configuration that worked for me:

```yaml
apiVersion: v1
data:
  access_token: ""
```
