### DISCUSSION TITLE
Docker image does not publish port

### DISCUSSION THREAD

**Discussion by r00tr4v3n** [firefly-iii/firefly-iii#6603] [Firefly III]
Hallo,
I'm trying to set up Firefly with Docker and MariaDB:
```
  fireflyiii:
    image: fireflyiii/core:latest
    container_name: firefly
    volumes:
      - ./volumes/firefly/upload:/var/www/html/storage/upload
    env_file: env/firefly.env
    ports:
      - 8082:8080
    depends_on:
      - firefly-db 
    networks:
      - firefly

  firefly-db:
    image: mariadb:10.3.9   #as seen at https://github.com/firefly-iii/firefly-iii/discussions/6439
    container_name: firefly-db
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_DATABASE=firefly
      - MYSQL_PASSWORD=secret_firefly_password
    volumes:
      - ./volumes/firefly/db:/var/lib/mysql
    networks:
      - firefly
```

```
APP_URL=https://ff.domain.com
TRUSTED_PROXIES=** 
```

Both containers start successfully but no port is published. What am I missing?

**Comment by JC5** [comment]
What do you mean, no port is published? It's in the [Dockerfile](https://dev.azure.com/Firefly-III/_git/BaseImage?path=/apache-8.1/Dockerfile&version=GBmain&line=304&lineEnd=305&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents) of the base image.

**Reply by r00tr4v3n** [reply]
Portainer does not detect the port. It seems there is no access to the started container. It's like forgetting the line '- 8082:8080'.
Thus I cannot connect to it. There is no error other than the domain name:
```
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.22.0.3. Set the 'ServerName' directive globally to suppress this message

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.22.0.3. Set the 'ServerName' directive globally to suppress this message

[Sat Nov 05 17:28:55.917988 2022] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) configured -- resuming normal operations

[Sat Nov 05 17:28:55.918072 2022] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'

127.0.0.1 - - [05/Nov/2022:17:29:26 +0100] "GET /robots.txt HTTP/1.1" 200 237 "-" "curl/7.64.0"

127.0.0.1 - - [05/Nov/2022:17:30:26 +0100] "GET /robots.txt HTTP/1.1" 200 237 "-" "curl/7.64.0"
```

![image](https://user-images.githubusercontent.com/6073574/200134757-f16a0e9a-9148-4865-a62e-be51c0e37b7f.png)

**Reply by JC5** [reply]
It seems to work, the health check returns 200. The domain name isn't really that important. I'm not sure what to do next, it seems to be something in Portainer.

**Reply by r00tr4v3n** [reply]
Other containers work fine. The port is not used twice. Recreated it multiple times in hope the db image is at fault but there is no error and the server is not responsive.

**Reply by JC5** [reply]
Sorry I'm not sure what to tell you. Here's my own docker-compose file:

```
version: '3.3'

services:
  app:
    image: fireflyiii/core:develop
    env_file: .env
    volumes:
      - /home/james/volumes/firefly-iii-attachments:/var/www/html/storage/upload
    ports:
      - '10000:8080'
    depends_on:
      - db
      - redis
  db:
    env_file: .env
    image: lscr.io/linuxserver/mariadb:latest
    ports:
      - '10001:3306'
    volumes:
      - /home/james/volumes/firefly-iii-db:/config
  redis:
    image: redis
```
