### DISCUSSION TITLE
DB not initialized in kubernetes with external postgres

### DISCUSSION THREAD

**Discussion by mtb-xt** [firefly-iii/firefly-iii#6608] [Firefly III] [answered]
Hey everyone,

I need help installing firefly iii on kubernetes - I have an already installed postgres instance there, I've made a deployment of firefly iii with helm (and I disabled built in chart for db). The pod now starts, but complains that some tables are missing. Which step am I missing? :eyes: ?

here's my values file:
```
    values:
      firefly-db:
        enabled: false
      firefly-iii:
        config:
          env:
            APP_KEY: <REDACTED32CHARS>
            DB_CONNECTION: pgsql
            DB_DATABASE: firefly
            DB_HOST: infra-cluster-rw.infra.svc.cluster.local
            DB_PORT: "5432"
            DEFAULT_LANGUAGE: en_US
            DEFAULT_LOCALE: equal
            TRUSTED_PROXIES: '**'
            TZ: Pacific/Auckland
          envValueFrom:
            DB_PASSWORD:
              secretKeyRef:
                key: password
                name: db-creds
            DB_USERNAME:
              secretKeyRef:
                key: username
                name: db-creds
        cronjob:
          enabled: true
          token: <REDACTED>
        enabled: true
        ingress:
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-production
          className: nginx
          enabled: true
          hosts:
          - firefly.mc.<REDACTED>
          tls:
          - hosts:
            - firefly.mc.<REDACTED>
            secretName: firefly-tls
        persistence:
          accessModes: ReadWriteOnce
          enabled: true
          storage: 5Gi
          storageClassName: hdds
      importer:
        enabled: false
```

this is the error i'm getting:

```
Updated version.
[2022-11-06 22:13:58] local.INFO: Could not create or generate installation ID. Do not continue.  
+------------------------------------------------------------------------------+
|                                                                              |
| Thank you for installing Firefly III, v5.6.14!                               |
|                                                                              |
|                                                                              |
+------------------------------------------------------------------------------+
Go!
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.244.0.16. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.244.0.16. Set the 'ServerName' directive globally to suppress this message
[Sun Nov 06 22:13:58.489075 2022] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) configured -- resuming normal operations
[Sun Nov 06 22:13:58.489133 2022] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[2022-11-06 22:14:05] local.INFO: Could not create or generate installation ID. Do not continue.  
[2022-11-06 22:14:05] local.ERROR: Exception is: {"class":"FireflyIII\\Exceptions\\FireflyException","errorMessage":"Could not poll the database: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation \"configuration\" does not exist\nLINE 1: select \"id\", \"name\", \"data\" from \"configuration\" where \"name...\n                                         ^ (SQL: select \"id\", \"name\", \"data\" from \"configuration\" where \"name\" = is_demo_site and \"configuration\".\"deleted_at\" is null limit 1)","time":"Sun, 06 Nov 2022 22:14:05 +1300","file":"\/var\/www\/html\/app\/Support\/FireflyConfig.php","line":73,"code":0,"version":"5.6.14","url":"http:\/\/10.244.0.16:8080\/health","userAgent":"kube-probe\/1.25","json":true}  
[2022-11-06 22:14:05] local.ERROR: Could not poll the database: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "configuration" does not exist
LINE 1: select "id", "name", "data" from "configuration" where "name...
                                         ^ (SQL: select "id", "name", "data" from "configuration" where "name" = is_demo_site and "configuration"."deleted_at" is null limit 1) {"exception":"[object] (FireflyIII\\Exceptions\\FireflyException(code: 0): Could not poll the database: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation \"configuration\" does not exist
LINE 1: select \"id\", \"name\", \"data\" from \"configuration\" where \"name...
                                         ^ (SQL: select \"id\", \"name\", \"data\" from \"configuration\" where \"name\" = is_demo_site and \"configuration\".\"deleted_at\" is null limit 1) at /var/www/html/app/Support/FireflyConfig.php:73)
[stacktrace]
#0 /var/www/html/app/Http/Controllers/Controller.php(54): FireflyIII\\Support\\FireflyConfig->get()
```
