### DISCUSSION TITLE
How can I run docker compose for rasperry pi 3 (arm/v7)

### DISCUSSION THREAD

**Discussion by j-antunes** [firefly-iii/firefly-iii#6634] [Firefly III] [answered]
This is the DockerFile that I am trying to use:

```
`version: '3.3'

services:
  app:
    image: fireflyiii/core:latest
    hostname: firefly
    restart: unless-stopped
    volumes:
      - /mnt/ext_db/apps/firefly/firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - 8788:8080
    depends_on:
      - db
  db:
    image: linuxserver/mariadb
    hostname: fireflyiiidb
    restart: unless-stopped
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly
    volumes:
      - /mnt/ext_db/apps/firefly/firefly_iii_db:/var/lib/mysql
volumes:
   firefly_iii_upload:
```
   firefly_iii_db:`

However it's not working, and I get this error. Any idea why?

`firefly-app-1  |   Could not poll the database: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for firefly_iii_db failed: Name or service not known (SQL: select `id`, `name`, `data` from `configuration` where `name` = 480_transaction_identifier and `configuration`.`deleted_at` is null limit 1)`

**Comment by bartekd123** [comment, marked as answer]
Your app doesn't have any DB details, so maybe thats why it can't connect. Try something like this (I just quickly grabbed what you have, and modified it, could have missed something)

```
`version: '3.3'

services:
  app:
    image: fireflyiii/core:latest
    hostname: firefly
    restart: unless-stopped
    environment:
      - DB_HOST=fireflyiiidb
      - DB_USERNAME=firefly
      - DB_PASSWORD=secret_firefly_password
      - DB_DATABASE=firefly

    volumes:
      - /mnt/ext_db/apps/firefly/firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - 8788:8080
    depends_on:
      - db
  db:
    image: linuxserver/mariadb
    hostname: fireflyiiidb
    restart: unless-stopped
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly
    volumes:
      - /mnt/ext_db/apps/firefly/firefly_iii_db:/var/lib/mysql
volumes:
   firefly_iii_upload:

```
