### DISCUSSION TITLE
services.db.environment contains {"MYSQL_RANDOM_ROOT_PASSWORD": true}, which is an invalid type, it should be a string

### DISCUSSION THREAD

**Discussion by nodecentral** [firefly-iii/firefly-iii#6636] [Firefly III]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hi,

I’m trying to install firefly via ContainerStation on my QNAP, and using the provided Docker compose it return this message. Interestingly it has the word `yes` as the value on the compose file, yet it interprets it as `true`?

````
The Compose YAML is invalid
The Compose file './docker-compose.yml' is invalid because: 
services.db.environment contains {"MYSQL_RANDOM_ROOT_PASSWORD": true}, 
which is an invalid type, it should be a string
````
**screenshot**..
![A7155AC8-26C2-4C49-8C9D-6613932867C4](https://user-images.githubusercontent.com/4349292/201472991-c675da11-4444-4713-9919-fe925382e4fe.jpeg)

### Expected behaviour

I was not expecting an error, I tried to change this to a string value e.g "muffin" to test but the same error was returned , this time quoting the string i’d used..

### Debug information

Nothing at this stage other than in the messages shared earlier.

### Steps to reproduce

I’m literally at the very start of the process using the provided Docker compose file, so curious what the cause can be..

### Additional info

I’m using a single yaml file see below, if you want to give it a try ?

````
version: '3.3'

services:
  app:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - /share/Container/firefly/upload:/var/www/html/storage/upload
    # - firefly_iii_upload:/var/www/html/storage/upload
    # env_file: .env
    environment:
      APP_ENV: local
      APP_DEBUG: false
      SITE_OWNER: mail@example.com
      APP_KEY: SomeRandomStringOf32CharsExactly
      DEFAULT_LANGUAGE: en_US
      DEFAULT_LOCALE: equal
      TZ: Europe/London
      LOG_CHANNEL: stack
      APP_LOG_LEVEL: notice
      AUDIT_LOG_LEVEL: info
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: firefly
      DB_USERNAME: firefly
      DB_PASSWORD: secret_firefly_password
      CACHE_DRIVER: file
      SESSION_DRIVER: file
      COOKIE_PATH: "/"
      COOKIE_DOMAIN: 
      COOKIE_SECURE: false
      COOKIE_SAMESITE: lax
      MAIL_MAILER: log
      MAIL_HOST: null
      MAIL_PORT: 2525
      MAIL_FROM: changeme@example.com
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: null
      AUTHENTICATION_GUARD: web
      ALLOW_WEBHOOKS: false
    ports:
      - 3888:8080
    depends_on:
      - db
  db:
    image: mariadb    
    hostname: fireflyiiidb
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD: yes
      - MYSQL_USER: firefly
      - MYSQL_PASSWORD: secret_firefly_password
      - MYSQL_DATABASE: firefly
    volumes:
      - firefly_iii_db:/var/lib/mysql
volumes:
   firefly_iii_upload:
   firefly_iii_db:
````

**Comment by JC5** [comment]
Any non-empty value should work, like "yes".

But keep in mind that you also have `-` in your list. See the difference between Firefly III's environment variables, and MariaDB's?

**Reply by nodecentral** [reply]
Thanks @JC5 - please could you elaborate on your other point on the dB configuration ? Do I not need the same information in both places ? 

````
App environment
      DB_CONNECTION: mysql 
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: firefly
      DB_USERNAME: firefly
      DB_PASSWORD: secret_firefly_password
````
And ..
````
dB environment:
      - MYSQL_RANDOM_ROOT_PASSWORD: yes
      - MYSQL_USER: firefly
      - MYSQL_PASSWORD: secret_firefly_password
      - MYSQL_DATABASE: firefly
````

**Comment by nodecentral** [comment]
Hi @JC5 

I’ve removed the app references to dab, and I’m not sure if you saw my original comment about trying a string, as that didn’t work either, but i tired again to confirm (see screenshot)..

````

version: '3.3'

services:
  app:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - /share/Container/firefly/upload:/var/www/html/storage/upload
    # - firefly_iii_upload:/var/www/html/storage/upload
    # env_file: .env
    environment:
      APP_ENV: local
      APP_DEBUG: false
      SITE_OWNER: mail@example.com
      APP_KEY: SomeRandomStringOf32CharsExactly
      DEFAULT_LANGUAGE: en_US
      DEFAULT_LOCALE: equal
      TZ: Europe/London
      LOG_CHANNEL: stack
      APP_LOG_LEVEL: notice
      AUDIT_LOG_LEVEL: info
#      DB_CONNECTION: mysql
#      DB_HOST: db
#      DB_PORT: 3306
#      DB_DATABASE: firefly
#      DB_USERNAME: firefly
#      DB_PASSWORD: secret_firefly_password
      CACHE_DRIVER: file
      SESSION_DRIVER: file
      COOKIE_PATH: "/"
      COOKIE_DOMAIN: 
      COOKIE_SECURE: false
      COOKIE_SAMESITE: lax
      MAIL_MAILER: log
      MAIL_HOST: null
      MAIL_PORT: 2525
      MAIL_FROM: changeme@example.com
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: null
      AUTHENTICATION_GUARD: web
      ALLOW_WEBHOOKS: false
    ports:
      - 3888:8080
    depends_on:
      - db
  db:
    image: mariadb    
    hostname: fireflyiiidb
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      - MYSQL_USER: firefly
      - MYSQL_PASSWORD: secret_firefly_password
      - MYSQL_DATABASE: firefly
    volumes:
      - firefly_iii_db:/var/lib/mysql
volumes:
   firefly_iii_upload:
   firefly_iii_db:
````
![C6EBD94A-671E-4364-AB5A-197D606E3FF3](https://user-images.githubusercontent.com/4349292/201496477-ad77c274-d1db-4395-8fb6-c2ab5dc7e89b.jpeg)
