### DISCUSSION TITLE
Consume static cron token from docker-compose secrets

### DISCUSSION THREAD

**Discussion by duviful** [firefly-iii/firefly-iii#6689] [Firefly III] [answered]
i would like to improve the cron container by consuming the STATIC_CRON_TOKEN_FILE variable in the command used in the alpine image.

unlucky me, i lack the knowledge to do so

I'm trying this two way to achieve that, but looks like I'm encountering in escaping problems and at this point I'm not even sure it's supported by compose.

```yaml
cron:
    image: alpine
    command: sh -c "echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/$$(cat /run/secrets/cron_token)" | crontab - && crond -f -L /dev/stdout"
    environment:
      STATIC_CRON_TOKEN_FILE: /run/secrets/cron_token
    secrets:
       - cron_token
```

or

```yaml
cron:
    image: alpine
    command: sh -c "echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/${STATIC_CRON_TOKEN_FILE}" | crontab - && crond -f -L /dev/stdout"
    environment:
      STATIC_CRON_TOKEN_FILE: /run/secrets/cron_token
    secrets:
       - cron_token
```

i hope somebody can give me a hint.

PS. I'm using secrets in docker-compose without swarm. this two examples above does not work.
Best!
