### DISCUSSION TITLE
traefik+firefly (app,db,importer) with docker-compose and nordigen

### DISCUSSION THREAD

**Discussion by volkerkarle** [firefly-iii/firefly-iii#6707] [Firefly III] [answered]
Hello,

does somebody have a working example of the firefly importer with docker-compose? I get firefly working, but the importer does not really work (I think it does not properly connect, but it also does not throw an error). Also I do not see why it is not included in the main app? The main app is secured with 2FA, but for the importer it seems I need to come up with my own authentication, it's just accessible as is. I want to have these services accessible from outside, that is why I use traefik. I do not quite see how to get Nordigen running either. I created a user secret at the Nordigen page and I put it in the config file of the firefly importer. But can I configure it headless, so to say, so I do not need to expose it?

Thanks!

**Comment by JC5** [comment, marked as answer]
https://github.com/firefly-iii/docker/blob/main/docker-compose-data.yml doesn't work?

**Comment by marcelbrueckner** [comment]
> does somebody have a working example of the firefly importer with docker-compose?

It's untested with the newest versions of Firefly III and the new Data Importer. I've set it up for testing purposes a long time ago when CSV importer and Nordigen importer etc. have been separate services. I guess it will work likely the same with the new Data Importer.

Below is my current `docker-compose.yml`. I've added some comments regarding the variables.

```yaml
# Firefly III
# https://docs.firefly-iii.org/installation/docker

version: '3.5'

services:
  firefly-iii:
    image: fireflyiii/core:version-5.5.13
    # A static name is easier referenced from Ofelia
    # If used, service cannot be scaled beyond 1 container
    # https://docs.docker.com/compose/compose-file/#container_name
    container_name: ${COMPOSE_PROJECT_NAME}
    labels:
      com.centurylinklabs.watchtower.enable: "false"
      ofelia.enabled: "true"
      ofelia.job-exec.firefly-iii-cron.schedule: "@hourly"
      ofelia.job-exec.firefly-iii-cron.command: "/usr/local/bin/php /var/www/html/artisan firefly:cron"
      # https://github.com/firefly-iii/firefly-iii/issues/3530
      ofelia.job-exec.firefly-iii-cron.user: "www-data"
      # Traefik
      # https://doc.traefik.io/traefik/routing/providers/docker/#general
      traefik.enable: "true"
      traefik.http.routers.firefly-iii.rule: Host(`firefly-iii.example.com`)
      traefik.http.routers.firefly-iii.entrypoints: traefik_default
      traefik.http.services.firefly-iii.loadbalancer.server.port: 8080
    volumes:
      # https://docs.docker.com/storage/bind-mounts/
      - source: /volume1/docker/firefly-iii/data/firefly-iii/upload
        target: /var/www/html/storage/upload
        type: bind
    # All my environment variables come from the below file. All the variables defined within are passed to this service
    # In addition, they are automatically read by Docker Compose and made available to use within the Compose file (see db and importer services below)
    env_file: .env
    networks:
      - firefly_iii_net
      - traefik
    depends_on:
      - firefly-iii-db

  firefly-iii-db:
    # https://github.com/docker-library/mariadb/issues/262
    # Let MariaDB take it's time (10+ minutes) for startup
    # Might be solved with 10.5.5
    image: mariadb:10.5.4
    # There's an issue with this image
    # https://github.com/firefly-iii/firefly-iii/issues/3633
    # image: yobasystems/alpine-mariadb:10.4.13
    container_name: ${COMPOSE_PROJECT_NAME}-db
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - TZ=${TZ}
    volumes:
      - source: /volume1/docker/firefly-iii/data/firefly-iii-db
        target: /var/lib/mysql
        type: bind
    networks:
      - firefly_iii_net

  firefly-iii-csv-importer:
    # https://hub.docker.com/r/fireflyiii/csv-importer
    image: fireflyiii/csv-importer:version-2.5.3
    container_name: ${COMPOSE_PROJECT_NAME}-csv-importer
    labels:
      com.centurylinklabs.watchtower.enable: "false"
      # Traefik
      # https://doc.traefik.io/traefik/routing/providers/docker/#general
      traefik.enable: "true"
      traefik.http.routers.firefly-iii-csv-importer.rule: Host(`csv-importer.firefly-iii.example.com`)
      traefik.http.routers.firefly-iii-csv-importer.entrypoints: traefik_default
      traefik.http.services.firefly-iii-csv-importer.loadbalancer.server.port: 8080
    environment:
      - FIREFLY_III_ACCESS_TOKEN=${FIREFLY_III_ACCESS_TOKEN}
      # As this service is in the same internal Docker network as Firefly III, it can access Firefly III by it's service name.
      # However, this variable requires the service port
      - FIREFLY_III_URL=${FIREFLY_III_URL} # FIREFLY_III_URL=http://firefly-iii:8080
      # TRUSTED_PROXIES is a useful variable when using Docker and/or a reverse proxy.
      # Set it to ** and reverse proxies work just fine.
      - TRUSTED_PROXIES=${TRUSTED_PROXIES} # TRUSTED_PROXIES=**
    volumes:
      # https://docs.firefly-iii.org/csv/help/config/
      - source: /volume1/docker/firefly-iii/config/firefly-iii-csv-importer
        target: /var/www/html/storage/configurations
        type: bind
    networks:
      - firefly_iii_net
      - traefik

networks:
  # The name of the network depends on the directory where the "docker-compose.yml" file is in,
  # e.g. if the directory is named "firefly-iii" the network will be "fireflyiii_net".
  # https://forums.docker.com/t/set-default-network-name-for-compose/36779/2
  firefly_iii_net:
    name: firefly_iii_net
    driver: bridge
  traefik:
    name: traefik
    external: true
```
