### DISCUSSION TITLE
Data Importer wil not work

### DISCUSSION THREAD

**Discussion by RVis78** [firefly-iii/firefly-iii#6784] [Firefly III]
I've installed Firefly III in docker on synology NAS, as described in:
https://mariushosting.com/how-to-install-firefly-iii-on-your-synology-nas/

Works great!

Then I would like to use the data importer and installed it in a saperate docker container (data-importer). 
Data importer is also correct loaded. 

![Knipsel](https://user-images.githubusercontent.com/62797454/210139455-4915a5b1-cedc-424e-bfb6-1afa32d1c3e7.PNG)

I created a user ID refering to the callback URL,
Entered the URL of the installed firefly instance Firefly III URL.

And after a while i get the following message: Waiting time to long.

Can somebody help me.

Maybe with some step by step instructions how to get this work | Firefly and FIDI

**Comment by mso1830** [comment]
I am trying to compose both the firefly and FIDI both at the same time in portainer. I contacted Marious hopefully he'll update the tutorial with adding the FIDI too

**Reply by PiotrEsse** [reply]
Wve wrote to Marius with working DockerCompose file to have also FIDI in same stack with Firefly. Hopefully he'll add it to his tutorial.
 You needto add following section to your Docker Stack:       

```
fidi:
    image: fireflyiii/data-importer:latest
    restart: always
    volumes:
      - /volume1/docker/firefly/import_configuration_files:/configurations:rw
    ports:
      - 6183:8080
    depends_on:
      firefly:
        condition: service_started
```

You also need to add ENV 
![image](https://user-images.githubusercontent.com/42764623/217778315-2c83d471-712f-4895-b720-d8813fd3fd9e.png)
