### DISCUSSION TITLE
Could not create or generate installation ID. Do not continue.

### DISCUSSION THREAD

**Discussion by fedex03** [firefly-iii/firefly-iii#6926] [Firefly III]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [ ] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hi there,

I deploy FireFly III as docker stack (firefly-iii, mariadb, firefly-data-importer) usign a docker compose file and pulling the latest images.

Since I cannot reach the web pay, I take a look into firefly container logs and I get this error: "Could not create or generate installation ID. Do not continue.  "

I checked the database container and it is running.

My system is x64.

Thank you foor the help!

BR,
Federico

``
[_FireFly_logs(1).txt](https://github.com/firefly-iii/firefly-iii/files/10490611/_FireFly_logs.1.txt)

### Expected behaviour

Access trough web page

### Debug information

.

**Comment by JC5** [comment]
Mmm, it looks like you're missing the APP_KEY variable when launching the container. Could that be the issue?

**Comment by fedex03** [comment]
Hi @JC5,

I tought the same thing.
I checked and the APP_KEY is inside the .env file.

Should I add it also to the Docker Compose file?

Thank you.

**Reply by JC5** [reply]
What is your Docker compose file like?

**Reply by fedex03** [reply]
```
version: '3.3'

services:
  fire-fly:
    container_name: FireFly
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - "/srv/docker/volumes/fire-fly/upload:/var/www/html/storage/upload"
    env_file: .env
    networks:
        - fire_fly_net
    ports:
      - 8080:8080
    depends_on:
      - fire-fly-db

  fire-fly-db:
    image: mariadb   
    container_name: FireFlyDb
    restart: always
    hostname: fireflydb
    ports:
      - 3306:3306
    networks:
        - fire_fly_net
    environment:
      - MYSQL_USER=firefly
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=firefly
    volumes:
      - "/srv/docker/volumes/fire-fly/db:/var/lib/mysql"
      
  fire-fly-di:
    image: fireflyiii/data-importer:latest
    container_name: FireFlyDataImporter
    restart: always
    env_file: .fidi.env
    ports:
      - 8081:8080
    networks:
      - fire_fly_net
    depends_on:
      - fire-fly
      
networks:
    fire_fly_net:  
        name: fire_fly_net
```
