### DISCUSSION TITLE
Exception during the Oauth authorization

### DISCUSSION THREAD

**Discussion by Gsyltc** [firefly-iii/firefly-iii#6929] [Firefly III]
Hi, 

Before to declare an issue I want to be sure there no problem with my configuration.
I want to use n8n for some automation. I'm behind Authelia

n8n Oauth Configuration 
```
Call back : https://n8n.mydomain.com/rest/oauth2-credential/callback
Grant Type : Autorization Code
Authorization URL : https://firefly.mydomain.com/oauth/authorize
Access Token URL : https://firefly.mydomain.com/oauth/token
Client ID : The ID I configure in Firefly. Exemple : 28
Client Secret : The secret from Firefly
Scope : 
Authentification : Header
```

Authelia Configuration:
```
    - domain:
        - "firefly.mydomain.com"
      resources:
        - "^/api([/?].*)?$"
        - "^/manifest.webmanifest([/?].*)?$"
        - "^/oauth([/?].*)?$"           
      networks:
        - 'myinternalnetwork'
      policy: bypass
```

Firefly Configuration
```
    - AUTHENTICATION_GUARD=remote_user_guard
    - AUTHENTICATION_GUARD_HEADER=Remote-User
    - AUTHENTICATION_GUARD_EMAIL=Remote-Email
```
and Oauth Client configured.
Docker version latest

I have this execption during authorize

![Firefly](https://user-images.githubusercontent.com/20156293/214476025-b66960da-0864-49bd-a970-aec0d8243fb9.png)

I try with the personnal access token via a curl command and all is good.

Should I check something on my side to make sure my configuration is correct before reporting a bug?

Thanks
