### DISCUSSION TITLE
What is the default data directory path?

### DISCUSSION THREAD

**Discussion by mrtargaryen** [firefly-iii/firefly-iii#7032] [Firefly III]
Where is the data stored within the container? I'm wanting to change the directory path but I need to first need to know where the data is currently being stored. There doesn't seem to be an easy way to find this in Docker. I'm only new to using docker and I'm still learning.

**Comment by JC5** [comment]
What are you trying to accomplish?

**Reply by mrtargaryen** [reply]
> What are you trying to accomplish?

I understand that in order to keep your data from being erased after deleting a container and reinstalling it, you have to change the data directory to one outside the docker container.  Is that true for Fireflyiii?

**Reply by JC5** [reply]
Are you running Firefly III with a separate database?

**Reply by mrtargaryen** [reply]
> Are you running Firefly III with a separate database?

Firefly iii is using mariadb that's installed in docker

**Reply by JC5** [reply]
Are you using a Docker compose file or separate Docker run commands?

**Reply by mrtargaryen** [reply]
> Are you using a Docker compose file or separate Docker run commands?

Docker compose file

**Reply by JC5** [reply]
Is there a line in the file that refers to volumes?

**Reply by mrtargaryen** [reply]
> Is there a line in the file that refers to volumes?

```
version: '3.3'

services:
  app:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - 80:8080
    depends_on:
      - db
  db:
    image: mariadb
    hostname: fireflyiiidb
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=                                                                                                                                                                                                                                                                                                                                                             
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly
    volumes:
      - firefly_iii_db:/var/lib/mysql
volumes:
   firefly_iii_upload:
   firefly_iii_db:
```
