### DISCUSSION TITLE
"Name or service not known" SSL configuration problem?

### DISCUSSION THREAD

**Discussion by arjenfvellinga** [firefly-iii/firefly-iii#7110] [Firefly III] [answered]
My importer (Firefly III Data Import Tool, v1.0.2) stopped working:
```
Error accessing "http://192.168.0.115:8013/api/v1/about?". Status code is 401. Body is: {"message":"Unauthenticated","exception":"AuthenticationException"}
```
Since the last import the dockers probably updated, so my goto solution would be to create a new token.

When I create a token I get the following error:

```
[2023-03-03 14:46:32] local.ERROR: Exception is: {"class":"Symfony\\Component\\Mailer\\Exception\\TransportException","errorMessage":"Connection could not be established with host \"ssl:\/\/:465\": stream_socket_client(): php_network_getaddresses: getaddrinfo for  failed: Name or service not known","time":"Fri, 03 Mar 2023 14:46:32 +0100","file":"\/var\/www\/html\/vendor\/symfony\/mailer\/Transport\/Smtp\/Stream\/SocketStream.php","line":154,"code":0,"version":"6.0.0","url":"https:\/\/firefly.foobar.nl\/oauth\/personal-access-tokens","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko\/20100101 Firefox\/110.0","json":true,"method":"POST"}  
[2023-03-03 14:46:32] local.ERROR: Connection could not be established with host "ssl://:465": stream_socket_client(): php_network_getaddresses: getaddrinfo for  failed: Name or service not known {"userId":1,"exception":"[object] (Symfony\\Component\\Mailer\\Exception\\TransportException(code: 0): Connection could not be established with host \"ssl://:465\": stream_socket_client(): php_network_getaddresses: getaddrinfo for  failed: Name or service not known at /var/www/html/vendor/symfony/mailer/Transport/Smtp/Stream/SocketStream.php:154)
```
I must note that since the last time I enabled https and made the instance via a reverse proxy accessible from outside my local network. But everything else works via the external url, only not the token creation. Same result when accessing Firefly via the local ip.

config:
```
  fireflyiii:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - ${USERDIR}/docker/fireflyiii/upload:/var/www/html/storage/upload
    # env_file: .env
    environment:
      - APP_KEY=*******
      - APP_URL=https://firefly.foobar.nl
      - TRUSTED_PROXIES=*
      - DB_CONNECTION=mysql
      - DB_HOST=192.168.0.115
      - DB_PORT=3306
      - DB_DATABASE=fireflyiii
      - DB_USERNAME=fireflyiii
      - DB_PASSWORD=*******
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8013:8080
    depends_on:
      - mariadb
```
| Scope | Version |
| --- | --- |
| Firefly III | 6.0.0 |
| Firefly III API | 2.0.0 |
| Build | 407, 02-03-2023 21:24:37 CET |
| DB version | 19 (exp. 19) |
| PHP | `8.2.3` |
| Host | `Linux` |

I assume a configuration error, but I'm not sure what the cause is.
```
