### DISCUSSION TITLE
Data Importer Issues followed Docs but getting a DB user Bock

### DISCUSSION THREAD

**Discussion by thorrrr** [firefly-iii/firefly-iii#7244] [Firefly III]
HI
I have followed the [docs](https://docs.firefly-iii.org/data-importer/installation/docker/) and double checked them.
But it has bricked the app please can you help me fix the connection to get back in.
DB Log [HERE](https://logs.notifiarr.com/?7cfc792828919493#BVXVA5p79TSHtnvUdtEEQCWSPSTUCm5xfE8jJXZWtHaH)

If anything else is needed please ask
I am not sure about the error never asked to enter a user called firefly and the ip is not my servers ip ?

![image](https://user-images.githubusercontent.com/8170673/225872274-09ece311-9199-4081-9a9b-acd4600d25b6.png)

![image](https://user-images.githubusercontent.com/8170673/225872446-b64aef08-e6c9-4fb3-aaa1-997bc949faab.png)

**Comment by JC5** [comment]
Is the password the same in the .db.env (MYSQL_PASSWORD) as it is in the .env (DB_PASSWORD)?

**Comment by thorrrr** [comment]
HI 
Yes it is the only issue is i cannot follow the ports numbers you have as my whole CCTV uses them 

Seeing another error in terminal "services.db Additional property importer is not allowed"

**Comment by thorrrr** [comment]
Maybe to help here are my files 
![compose](https://user-images.githubusercontent.com/8170673/225887130-9ba7a2c1-d74e-4339-a9e9-4e85eab30c51.png)
![importer](https://user-images.githubusercontent.com/8170673/225887136-be7f9020-1663-4f27-bf01-196ac522c9bf.png)
![db](https://user-images.githubusercontent.com/8170673/225887139-aabcbb5d-73ac-458a-a3e7-68668c8da364.png)
![env](https://user-images.githubusercontent.com/8170673/225887142-f231a85c-385b-4c9a-8986-51b1d8486c13.png)

**Comment by thorrrr** [comment]
HI James
OK i think there is a weird issue if i change the passwords back to the default secret_firefly_password then everything boots up.
If i enter anything else i get an error  the same as above i have tried
'test' and it  fails 
'secret_firefly_passwor' and it fails with the d missing
secret_firefly_password works ???

**Reply by JC5** [reply]
Ah yes. The first time you start the database it sets the password and it can't be changed if you start it again later. 

What you can do is delete the database volume (this will delete all your data so far) and then start again. With your final password.

**Reply by thorrrr** [reply]
> Ah yes. The first time you start the database it sets the password and it can't be changed if you start it again later.
> 
> What you can do is delete the database volume (this will delete all your data so far) and then start again. With your final password.

I think that would be very useful if was included in the docs :)

**Reply by JC5** [reply]
Will do!

**Reply by thorrrr** [reply]
> Ah yes. The first time you start the database it sets the password and it can't be changed if you start it again later.
> 
> What you can do is delete the database volume (this will delete all your data so far) and then start again. With your final password.

Is there a way for me to export the data i have already added, delete the db volume add new db with secure password then re import my data ?

**Reply by JC5** [reply]
I'm sure there is, but honestly I wouldn't know.

**Comment by thorrrr** [comment]
Hi James 
Still having cron issues it errors when it runs 
crond: USER root pid  17 cmd wget -qO- http://app:8080/api/v1/cron/0289e83c37501650ca0a5e8d6e22cb8b
wget: bad address 'app:8080'

A helpful channel member said i need to change app to fireflyiii in the crom path, which i did but its not in the docs.
Anyway app or fireflyiii throws same error!!
I have checked compose file and is same as official one albeit my own settings!

**Reply by lennardk** [reply]
Hi @thorrrr,

Just to make sure, can you post your  docker-compose file as it currently is again? Preferably as text, not as a screenshot. With any secrets removed, of course!

**Comment by thorrrr** [comment]
```
version: '3.3'

services:
  app:
    image: fireflyiii/core:latest
    hostname: app
    networks:
      - firefly
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - '8012:8080'
    depends_on:
      - db
  db:
    image: mariadb
    hostname: fireflyiiidb
    networks:
      - firefly
    restart: always
    env_file: .db.env
    volumes:
      - firefly_iii_db:/var/lib/mysql

  cron:
    image: alpine
    command: sh -c "echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/REDACTED\" | crontab - && crond -f -L /dev/stdout"

  importer:
    image: fireflyiii/data-importer:latest
    hostname: importer
    networks:
      - firefly
    restart: always
    ports:
      - '8013:8080'
    depends_on:
      - app
    env_file: .importer.env

volumes:
   firefly_iii_upload:
   firefly_iii_db:

networks:
  firefly:
    driver: bridge
root@omv:/srv/dev-disk-by-uuid-1REDACTEDb7f/appdata/firefly#
```

**Reply by lennardk** [reply]
I've tried your docker-compose. There was one error in it: `"echo "0 3`... should be `"echo \"0 3`... with an extra backslash.
That wasn't the problem itself though, to actually fix the `wget: bad address 'app:8080'` error, I simply added the firefly network to the cron service as well. This worked in my setup.
The full difference between your file and my working version:
```diff
--- a/docker-compose.yaml
+++ b/docker-compose.yaml
@@ -24,7 +24,9 @@ services:
 
   cron:
     image: alpine
-    command: sh -c "echo "* * * * * wget -qO- http://app:8080/api/v1/cron/REDACTED\" | crontab - && crond -f -L /dev/stdout"
+    command: sh -c "echo \"* * * * * wget -qO- http://app:8080/api/v1/cron/REDACTED\" | crontab - && crond -f -L /dev/stdout"
+    networks:
+     - firefly
 
   importer:
```

**Comment by thorrrr** [comment]
HI
You have me confused slightly mine does have `"echo \"0 3` see the screen shot above
Also i do have the network in as well or are you saying also add it to cron as well as importer?

**Reply by JC5** [reply]
Yes, that is what he's saying.

**Reply by thorrrr** [reply]
Let me try that fingers crossed

**Comment by thorrrr** [comment]
version: '3.3'

services:
  app:
    image: fireflyiii/core:latest
    hostname: app
    networks:
      - firefly
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - '8012:8080'
    depends_on:
      - db
  db:
    image: mariadb
    hostname: fireflyiiidb
    networks:
      - firefly
    restart: always
    env_file: .db.env
    volumes:
      - firefly_iii_db:/var/lib/mysql

  cron:
    image: alpine
    command: sh -c "echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/Redacted\" | crontab - && crond -f -L /dev/stdout"
    network:
      - firefly
	
  importer:
    image: fireflyiii/data-importer:latest
    hostname: importer
    networks:
      - firefly
    restart: always
    ports:
      - '8013:8080'
    depends_on:
      - app
    env_file: .importer.env

volumes:
   firefly_iii_upload:
   firefly_iii_db:

networks:
  firefly:
    driver: bridge

**Reply by lennardk** [reply]
Are you sure you are actually updating your container? Your file still has multiple issues and I don't think it can run at all like this.

- The cron command still doesn't have the `"` quoted correctly
- It's `networks`, not `network` with the bit you now added to `cron`

```yaml
version: '3.3'

services:
  app:
    image: fireflyiii/core:latest
    hostname: app
    networks:
     - firefly
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - '8012:8080'
    depends_on:
      - db
  db:
    image: mariadb
    hostname: fireflyiiidb
    networks:
     - firefly
    restart: always
    env_file: .db.env
    volumes:
      - firefly_iii_db:/var/lib/mysql

  cron:
    image: alpine
    command: sh -c "echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/REDACTED\" | crontab - && crond -f -L /dev/stdout"
    networks:
     - firefly

  importer:
    image: fireflyiii/data-importer:latest
    hostname: importer
    networks:
      - firefly
    restart: always
    ports:
      - '8013:8080'
    depends_on:
      - app
    env_file: .importer.env

volumes:
  firefly_iii_upload:
  firefly_iii_db:

networks:
  firefly:
    driver: bridge
```
