### DISCUSSION TITLE
Can't access importer start screen, apache server error?

### DISCUSSION THREAD

**Discussion by BackedUpBooty** [firefly-iii/firefly-iii#7258] [Firefly III]
I've been trawling through the discussions and issues here, I haven't found anything that seems to point to my issue (#5948 came closest). I've obviously missed something basic but I can't figure out what it is. 

Using docker. 

FireflyIII works like a dream. About a week after installing it I tried to get the importer up and running. It seemed to install fine, container = healthy, but I can't access the importer screen on IP:port, response is `ERR_EMPTY_RESPONSE`. Note that everything is inside my docker network/LAN, nothing leaves my network. Firewall is not the issue. 

My compose (not including cron, db or redis):
```
services:
  firefly:
    image: fireflyiii/core:latest
    container_name: Firefly
    hostname: firefly
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    healthcheck:
      test: curl -f http://localhost:8080/ || exit 1
    volumes:
      - ./upload:/var/www/html/storage/upload:rw
      - $LOCALTIME
    ports:
      - 6182:8080
    restart: unless-stopped
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_healthy

  firefly-dataimporter:
    image: fireflyiii/data-importer:latest
    container_name: firefly-dataimporter
    hostname: importer
    ports:
      - 8181:8000
    restart: unless-stopped
    env_file:
      - .fidi.env
    depends_on:
      firefly:
        condition: service_started
```

The FIDI .env (.fidi.env):
```
FIREFLY_III_URL=http://firefly:8080

#VANITY_URL=

#
# Set your Firefly III Personal Access Token (OAuth)
# You can create a Personal Access Token on the /profile page:
# go to the OAuth tab, then Personal Access Token and "Create token".
#
# - Do not use the "command line token". That's the WRONG one.
# - Do not use "APP_KEY" value from your Firefly III installation. That's the WRONG one.
#
# Setting this value is not mandatory. Instructions will follow if you omit this field.
#
# This variable can be set from a file if you append it with _FILE
#
#FIREFLY_III_ACCESS_TOKEN=

FIREFLY_III_CLIENT_ID={redacted}

#
# Nordigen information.
# The key and ID can be set from a file if you append it with _FILE
#
NORDIGEN_ID={redacted}
NORDIGEN_KEY={redacted}
NORDIGEN_SANDBOX=true

USE_CACHE=false

IGNORE_DUPLICATE_ERRORS=false

VERIFY_TLS_SECURITY=true

#
# Time out when connecting with Firefly III.
# π*10 seconds is usually fine.
#
CONNECTION_TIMEOUT=31.41

# The following variables can be useful when debugging the application
APP_ENV=local
APP_DEBUG=true
LOG_CHANNEL=stack

LOG_LEVEL=info

# TRUSTED_PROXIES is a useful variable when using Docker and/or a reverse proxy.
# Set it to ** and reverse proxies work just fine.
TRUSTED_PROXIES=**

#
# Time zone
#
TZ=Asia/Tokyo

#
# Email settings.
# The data importer can send you a message with all errors, warnings and messages
# after a successful import. This is disabled by default
#
ENABLE_MAIL_REPORT=false

#
# Force Firefly III URL to be secure?
#
#
EXPECT_SECURE_URL=false


#
# You probably won't need to change these settings.
#
BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120
IS_EXTERNAL=false

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

# always use quotes
REDIS_DB="0"
REDIS_CACHE_DB="1"

APP_NAME=DataImporter

APP_URL=http://localhost
```

Importer logs:
```
Now in entrypoint.sh for Firefly III Data Importer
Script:        1.6 (2022-02-17)
User:          'root'
Group:         'root'
Working dir:   '/var/www/html'
Build number:  201
Build date:    12-03-2023 18:16:05 CET
Now parsing _FILE variables.
done!
Firefly III data importer v1.2.1
PHP: cli 8.2.3 Linux
Will now run Apache web server:
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.28.0.6. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.28.0.6. Set the 'ServerName' directive globally to suppress this message
[Mon Mar 20 15:21:42.832669 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.54 (Debian) configured -- resuming normal operations
[Mon Mar 20 15:21:42.832725 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
127.0.0.1 - - [20/Mar/2023:15:22:38 +0900] "GET /robots.txt HTTP/1.1" 200 236 "-" "Firefly III Health Checker/1.0"
```
The last line continues to repeat, and I've not been able to figure out where the AH00558 error is coming from. I've seen it reported in other issues on firefly but not the importer, and even then it doesn't seem to have been an issue. 

I've set the fidi env log level to debug but it doesn't show any further info, and bashing into the container shows no logs in the /storage folder, so there's no other threads for me to follow. 

I can curl to the main firefly app from inside the importer container using `http://firefly:8080` so communication is possible. Not really sure what else it may be on my end that I'm screwing up. Any help or suggestions would be great.
