### DISCUSSION TITLE
Docker Raspberry-pi 4 not working

### DISCUSSION THREAD

**Discussion by Groovylein** [firefly-iii/firefly-iii#7284] [Firefly III]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I am trying to run frirefly-iii as docker on my raspberry-pi 4 by following the instructions [here](https://docs.firefly-iii.org/firefly-iii/installation/docker/) , but this does not work as expected.

My `docker-compose.yml`
```
version: '3.3'

services:
  app:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - 89:8080
    depends_on:
      - db
  db:
    image: yobasystems/alpine-mariadb
    hostname: fireflyiiidb
    restart: always
    env_file: .db.env
    volumes:
      - firefly_iii_db:/var/lib/mysql
volumes:
   firefly_iii_upload:
   firefly_iii_db:
```

I changed
- `yobasystems/alpine-mariadb` due to incompatibility of `mariadb`
- `DB_PASSWORD` in `.env`
- `MYSQL_PASSWORD` in `.db.env`

### Debug information

```firefly-iii-docker_app_1 exited with code 1
app_1  | exec /usr/local/bin/entrypoint.sh: exec format error
app_1  | exec /usr/local/bin/entrypoint.sh: exec format error
app_1  | exec /usr/local/bin/entrypoint.sh: exec format error
app_1  | exec /usr/local/bin/entrypoint.sh: exec format error
app_1  | exec /usr/local/bin/entrypoint.sh: exec format error
firefly-iii-docker_app_1 exited with code 1
app_1  | exec /usr/local/bin/entrypoint.sh: exec format error
app_1  | exec /usr/local/bin/entrypoint.sh: exec format error
app_1  | exec /usr/local/bin/entrypoint.sh: exec format error
app_1  | exec /usr/local/bin/entrypoint.sh: exec format error
app_1  | exec /usr/local/bin/entrypoint.sh: exec format error
app_1  | exec /usr/local/bin/entrypoint.sh: exec format error```

### Expected behaviour

_No response_

### Steps to reproduce

_No response_

### Additional info

_No response_
