### DISCUSSION TITLE
Firefly III is unable to format monetary amounts because your server is missing the required packages - Docker

### DISCUSSION THREAD

**Discussion by mczapala** [firefly-iii/firefly-iii#7548] [Firefly III]
Hello,
I am running the latest firefly version using docker container, and I cannot seem to configure locales properly. I cannot even open the preferences page because firefly crashes trying to find nonexisting locale directory (sk-SK instead of sk_SK).
```
Unfortunately, this error was not recoverable :(. Firefly III broke. The error is:
file_get_contents(/var/www/html/resources/lang/sk-SK/locales.json): Failed to open stream: No such file or directory 
This error occured in file /var/www/html/app/Http/Controllers/PreferencesController.php on line 124 with code 0. 
```
My configuration is listed below. Does anyone have any ideas on how to fix it?

Debug information generated at 2023-05-25 00:00:00 Europe/Bratislava for Firefly III version **6.0.10**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.10 |
| Firefly III API | 2.0.1 |
| Build | 479, 13-05-2023 06:42:29 CEST |
| Base Build | 3, 29-04-2023 14:45:54 CEST |
| DB version | 19 (exp. 19) |
| PHP | `8.2.5` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Bratislava |
| Browser TZ | Europe/Prague |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | sk_SK |
| Default locale | sk_SK |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | remote_user_guard  |
| Headers | HTTP_REMOTE_USER, HTTP_REMOTE_EMAIL  |
| Stateful domains |  |
| Session start | 2023-05-01 00:00:00 |
| Session end | 2023-05-31 23:59:59 |
| Session first | 2023-01-01 00:00:00 |
| User ID | 1 |
| User language | sk-SK |
| User locale | sk-SK |
| Attempt at "sk-SK.utf8" | false |
| Attempt at "sk-SK.UTF-8" | false |

Relevant log entries
```
[2023-05-25 19:54:09] local.ERROR: Could not set locale. The following array doesnt work:  ["sk-SK.utf8","sk-SK.UTF-8"] 
172.168.88.7 - - [25/May/2023:19:54:09 +0200] "GET /v1/js/lib/moment/sk-SK.js?v=6.0.10 HTTP/1.1" 404 3792
172.168.88.7 - - [25/May/2023:19:54:09 +0200] "GET /v1/jscript/variables?ext=.js&v=6.0.10 HTTP/1.1" 200 3979
[2023-05-25 19:54:15] local.ERROR: Could not set locale. The following array doesnt work:  ["sk-SK.utf8","sk-SK.UTF-8"] 
[2023-05-25 19:54:15] local.ERROR: Exception is: {"class":"ErrorException","errorMessage":"file_get_contents(\/var\/www\/html\/resources\/lang\/sk-SK\/locales.json): Failed to open stream: No such file or directory","time":"Thu, 25 May 2023 19:54:15 +0200","file":"\/var\/www\/html\/app\/Http\/Controllers\/PreferencesController.php","line":124,"code":0,"version":"6.0.10",... ,"json":true,"method":"GET"}  
```
locale -a
```
C
C.UTF-8
POSIX
bg_BG.utf8
ca_ES.utf8
cs_CZ.utf8
da_DK.utf8
de_DE.utf8
el_GR.utf8
en_GB.utf8
en_US.utf8
es_ES.utf8
fi_FI.utf8
fr_FR.utf8
hu_HU.utf8
id_ID.utf8
it_IT.utf8
ja_JP.utf8
nb_NO.utf8
nl_NL.utf8
pl_PL.utf8
pt_BR.utf8
pt_PT.utf8
ro_RO.utf8
ru_RU.utf8
sk_SK.utf8
sl_SI.utf8
sv_SE.utf8
tr_TR.utf8
uk_UA.utf8
vi_VN.utf8
zh_CN.utf8
zh_TW.utf8
```

part of docker compose
```
firefly:
    image: fireflyiii/core:version-6.0.10
    container_name: firefly
    restart: unless-stopped
    volumes:
      - ./firefly:/var/www/html/storage/upload
      - ./ssl:/etc/certs:ro
    environment:
      SITE_OWNER: redacted
      APP_KEY: redacted
      DEFAULT_LANGUAGE: "sk_SK"
      DEFAULT_LOCALE: "sk_SK"
      TZ: Europe/Bratislava
      DB_CONNECTION: "pgsql"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_DATABASE: redacted
      DB_USERNAME: redacted
      DB_PASSWORD: redacted
      PGSQL_SSL_MODE: "prefer"
      PGSQL_SSL_ROOT_CERT: "/etc/certs/public/fullchain.pem"
      PGSQL_SSL_KEY: "/etc/certs/private/privkey.pem"
      MAIL_MAILER: "smtp"
      MAIL_HOST: "mailserver"
      MAIL_PORT: 587
      MAIL_FROM: redacted
      MAIL_USERNAME: redacted
      MAIL_PASSWORD: redacted
      MAIL_ENCRYPTION: "tls"
      SEND_ERROR_MESSAGE: "true"
      AUTHENTICATION_GUARD: "remote_user_guard"
      AUTHENTICATION_GUARD_HEADER: "HTTP_REMOTE_USER"
      AUTHENTICATION_GUARD_EMAIL: "HTTP_REMOTE_EMAIL"
      APP_URL: redacted
    depends_on:
      - db
      - mailserver
    networks:
      - customnet
```
