### DISCUSSION TITLE
Failure to deploy docker Firefly III

### DISCUSSION THREAD

**Discussion by mailliwal** [firefly-iii/firefly-iii#7682] [Firefly III] [answered]
```yaml
version: '3.3'

services:
  firefly:
    container_name: firefly
    image: fireflyiii/core:latest
    restart: always
    environment:
      - DB_PASSWORD=P@ssw0rd
      - APP_KEY=XXXXXXXXXXXXX
      - DB_HOST=172.22.22.76
      - DB_PORT=3306
      - DB_CONNECTION=mariadb
      - DB_DATABASE=firefly
      - DB_USERNAME=firefly
      - APP_URL=http://127.0.0.1
      #- TRUSTED_PROXIES={My Reverse proxy}
      #- MAIL_MAILER=smtp
      #- MAIL_HOST=you mail host
      #- MAIL_PORT=587
      #- MAIL_FROM={My Mailadress}
      #- MAIL_USERNAME={MY Usernamne}
      #- MAIL_PASSWORD={My Password}
      #- MAIL_ENCRYPTION=tls
      - COMPOSER_ALLOW_SUPERUSER=1
      - TZ=Asia\Taipei
      #- APP_LOG_LEVEL: debug
    volumes:
      - /volume1/docker/firefly/upload:/var/www/html/storage/upload
      - /volume1/docker/firefly/export:/var/www/html/storage/export
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9088:8080
    depends_on:
      - database
    networks:
       firefly_net:
          ipv4_address: 172.22.22.75

  database:
    container_name: mariadb
    image: mariadb    
    restart: always
    hostname: mariadb
    #user: '1026'
    environment:
      PUID: 1000
      PGID: 1000
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: firefly
      MYSQL_USER: firefly
      MYSQL_PASSWORD: P@ssw0rd
      TZ: Asia\Taipei
    volumes:
      - /volume1/docker/firefly/db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3306:3306
    networks:
       firefly_net:
          ipv4_address: 172.22.22.76

networks:
  firefly_net:
    external: true
    name: test_2_network
```

======================================

```
#0 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\\Template->displayWithErrorHandling()
#1 /var/www/html/vendor/twig/twig/src/Template.php(379): Twig\\Template->display()
#2 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\\Template->render()
#3 /var/www/html/vendor/rcrowe/twigbridge/src/Engine/Twig.php(92): Twig\\TemplateWrapper->render()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(195): TwigBridge\\Engine\\Twig->get()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(178): Illuminate\\View\\View->getContents()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(147): Illuminate\\View\\View->renderContents()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(57): Illuminate\\Http\\Response->__construct()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(87): Illuminate\\Routing\\ResponseFactory->make()
#11 /var/www/html/app/Exceptions/Handler.php(168): Illuminate\\Routing\\ResponseFactory->view()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(217): FireflyIII\\Exceptions\\Handler->render()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(194): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(254): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()
#15 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#16 {main}
Next ErrorException: An exception has been thrown during the rendering of a template (\"Route [index] not defined.\"). in /var/www/html/resources/views/errors/FireflyException.twig:9

Stack trace:
#0 /var/www/html/vendor/rcrowe/twigbridge/src/Engine/Twig.php(94): TwigBridge\\Engine\\Twig->handleTwigError()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(195): TwigBridge\\Engine\\Twig->get()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(178): Illuminate\\View\\View->getContents()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(147): Illuminate\\View\\View->renderContents()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(57): Illuminate\\Http\\Response->__construct()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(87): Illuminate\\Routing\\ResponseFactory->make()
#8 /var/www/html/app/Exceptions/Handler.php(168): Illuminate\\Routing\\ResponseFactory->view()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(217): FireflyIII\\Exceptions\\Handler->render()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(194): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(254): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()
#12 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#13 {main}
  thrown at /var/www/html/resources/views/errors/FireflyException.twig:9)

[stacktrace]

}
"} 
127.0.0.1 - - [24/Jun/2023:09:45:05 +0000] "GET /health HTTP/1.1" 500 169 "-" "Firefly III Health Checker/2.0"
```

=================================

I have deployed with both Firefly III and MariaDB but failure to start and browse Firefly III webpage.

Enclosed docker compose and FireflyIII log.
