### DISCUSSION TITLE
New install data importer does not connect

### DISCUSSION THREAD

**Discussion by rajil** [firefly-iii/firefly-iii#7777] [General]
Hello,

I have setup a firefly instance importer per the docker instructions.

The .importer.env file has the following set.

```
$ grep -v '^\s*$\|^\s*\#' .importer.env |head -4
FIREFLY_III_URL=http://app:8080
VANITY_URL=
FIREFLY_III_ACCESS_TOKEN=
FIREFLY_III_CLIENT_ID=
```
The firefly oAuth has the following setting for the importer
![image](https://github.com/firefly-iii/firefly-iii/assets/379266/40b43f00-70bf-40d4-b217-69fa9d0a1e87)

I try to setup importer like so,

![image](https://github.com/firefly-iii/firefly-iii/assets/379266/c9118ece-5145-4b18-81f9-ab2b91135608)

 But it fails with the following error:
![image](https://github.com/firefly-iii/firefly-iii/assets/379266/2e8dd07f-5896-4069-95fc-a7e9b46ad558)

The docker compose file is:
```
version: '3.3'

#
# The Firefly III Data Importer will ask you for the Firefly III URL and a "Client ID".
# You can generate the Client ID at http://localhost/profile (after registering)
# The Firefly III URL is: http://app:8080
#
# Other URL's will give 500 | Server Error
#

services:
  app:
    image: fireflyiii/core:latest
    hostname: app
    container_name: firefly_iii_core
    networks:
      - firefly_iii
    restart: always
    volumes:
      - /home/ubuntu/dockerdata/volumes/firefly/upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - '8083:8080'

  importer:
    image: fireflyiii/data-importer:latest
    hostname: importer
    restart: always
    container_name: firefly_iii_importer
    networks:
      - firefly_iii
    ports:
      - '8084:8080'
    depends_on:
      - app
    env_file: .importer.env

  cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable and replace REPLACEME below
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    image: alpine
    container_name: firefly_iii_cron
    restart: always
    command: sh -c "echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/REPLACEME\" | crontab - && crond -f -L /dev/stdout"
    networks:
      - firefly_iii
volumes:
   firefly_iii_upload:
   firefly_iii_db:

networks:
  firefly_iii:
    driver: bridge
```

Firefly itself is working fine. Any idea why the importer doesnt work?
