### DISCUSSION TITLE
k8s Installation

### DISCUSSION THREAD

**Discussion by Avendo07** [firefly-iii/firefly-iii#8182] [Firefly III]
I tried to install firefly on a k8s cluster using the helm repo. The PVC "firefly-db-storage-claim" is giving out the following error-

"storageclass.storage.k8s.io "nfs-client" not found".

The first issue that I faced is-
- Also, this is causing the pods to not spin up.

Due to this I am facing some other issues.
- The deployment resource for application never stabilises and keeps restarting the pods due to restarting (this is probably because of the pvc not being bound)
- The helm release shows "deployed" even though it isn't
- Due to incorrect deployment going through, I face an issue that after I try to uninstall this helm chart in this state. It spins up the db-backup-job which in turn fails as the db deployment isn't working. At the end I can't get rid of these resources, and only solution is to delete the namespace itself(don't know if there is another solution).

Note- I am relatively new to helm and was trying to do use this to work out helm and k8s, would appreciate any help that I can get.

**Comment by venkivijay** [comment]
You can use the below command to uninstall the release if `pre-delete` hook jobs are failing.
`helm delete --no-hooks <release-name>`

**Comment by IniterWorker** [comment]
If It can help, you can use :

```bash
microk8s helm uninstall firefly-iii #...
```

The cron task blocks the uninstall process. You must delete the backup-job.

```bash
microk8s kubectl delete job  firefly-iii-firefly-db-backup-job -n default
```

The `nfs` is a storage class. So, if you are not using `nfs`, you can't run it. You can use custom storage class or use an existing claim.

```yaml
firefly-db:
  # if you set this to false it will not be installed
  enabled: true
  image:
    repository: postgres
    tag: 10-alpine
    pullPolicy: IfNotPresent

  storage:
    existingClaim: data-firefly-iii-mysql

  # environment variables
  configs:
    RESTORE_URL: ""
    BACKUP_URL: ""
    PGPASSWORD: "YOURDBPASSWORD"
    DBHOST: firefly-firefly-db
    DBPORT: "5432"
    DBNAME: firefly
    DBUSER: firefly
    TZ: Europe/Berlin

  backupSchedule: "0 3 * * *"

firefly-iii:
  # -- Set to false to not deploy Firefly III
  enabled: true

  persistence:
    existingClaim: data-firefly-iii

importer:
  # -- Set to false to not deploy the importer
  enabled: true
```

Still get an error 500 when I am able to run it green on all services.

We need more documentation on how to use it.
