### DISCUSSION TITLE
Migration to new machine

### DISCUSSION THREAD

**Discussion by SimonVleugels** [firefly-iii/firefly-iii#8241] [Firefly III] [answered]
Hi,

I'm trying to migrate my FF3 install to another machine (RPI3 -> x86). I used the docker-compose install strategy. I followed the backup and restore steps from [the documentation](https://docs.firefly-iii.org/firefly-iii/advanced-installation/backup/). On the new install I created a new user (same email) but the transactions are not showing up. I also copied over the .env. I have no clue what I'm doing wrong. Any guidance here?

Backup:
```
docker run --rm -v "budget_firefly_db:/tmp" -v "$HOME/budget/backup:/backup" ubuntu tar -czvf /backup/firefly_db.tar /tmp
```

Restore:
```
docker run --rm -v "firefly_iii_firefly_db:/recover" -v "/srv/mergerfs/mergerPOOL/backup:/backup" ubuntu tar -xvf /backup/test2.tar -C /recover --strip 1
```

docker-compose.yml:
```
services:
  app:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - firefly_upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - 9300:8080
    depends_on:
      - db
  db:
    image: mariadb
    hostname: fireflyiiidb
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly
    volumes:
      - firefly_db:/var/lib/mysql

volumes:
   firefly_upload:
   firefly_db:
```

I see that 2 volumes are made:
```
VOLUME NAME                  LINKS     SIZE
firefly_iii_firefly_db       1         263.3MB
firefly_iii_firefly_upload   1         14B
```

Thanks
