### DISCUSSION TITLE
How do I automate the Data Importer from the cron container?

### DISCUSSION THREAD

**Discussion by lsalgueiro** [firefly-iii/firefly-iii#8495] [Firefly III]
How do I automate the Data Importer from the cron container?
Alternatively: how do I automate the Data Importer from the docker-compose file?

I've read the documentation, and am able to import via the CLI with both methods. I would much rather set this on the compose manifest instead of writing to crontab on the host system. Is this possible somehow, by extending the command called on spinning up the cron container? This uses the API, as far as I can tell, so perhaps the answer is no?

**Comment by JC5** [comment]
Something like this?

```
  cron_importer:
    image: alpine
    restart: always
    container_name: firefly_iii_cron2
    command: sh -c "echo \"0 3 * * * wget -qO- http://importer:8080/URLHERE\" | crontab - && crond -f -L /dev/stdout"
```

**Comment by lsalgueiro** [comment]
Nevermind, turns out I wasn't thorough enough reading the documentation. I mentioned I was able to import via the CLI via both methods, which was technically true if we don't consider (as the documentation doesn't) API calls via curl from shell commands. :) D'oh!

However, calling `wget -qO- http://importer:8081/autoimport?directory=/import&secret=[SECRET]` returns connection refused. The secret is set in the `(.importer).env` as per [the documentation](https://docs.firefly-iii.org/how-to/data-importer/advanced/post/) (and so are the other keys).

Then it would be a matter of writing this to crontab inside the cron container, right?

**Reply by JC5** [reply]
Yes, especially since the secret can be pre-configured. I'm not sure if you can do something like `&secret=${AUTO_IMPORT_SECRET}` though, I don't know if Docker would parse that.

**Reply by lsalgueiro** [reply]
Perfect!

Exposing the key in the compose manifest isn't amazing, but it's good enough for personal use, so I don't mind leaving it there. But it's returning connection refused, even after re-upping the stack with `--force-recreate` for good measure.

**Reply by JC5** [reply]
Try port 8080, not 8081. Since you're internal the forwarded port isn't the right one.

**Reply by lsalgueiro** [reply]
More silliness, sorry. 8081 is what I've mapped it to, not the internal port, of course.

Now I'm getting `405 Method Not Allowed`.

**Reply by lsalgueiro** [reply]
Do I have to declare the method as POST explicitly in wget?

**Reply by JC5** [reply]
Yes.

**Reply by lsalgueiro** [reply]
I asked to double-check; I intuitively thought I should, but it wasn't working for me at first. I believe what was tripping me was this (quoted from [here](https://unix.stackexchange.com/questions/678572/execute-post-request-from-alpine-container)):

> there is a `busybox` binary in the Alpine image which **contains a stripped-down version of `wget`**.

I've successfully triggered the import with `wget -qO - --post-data '' --header 'Accept: application/json' 'http://importer:8080/autoimport?directory=/import&secret=[SECRET]'`, bringing my final command to

```
command: sh -c "echo -e \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/[SECRET]\" > /tmp/crontab_tmp && echo -e \"40 2 * * * wget -qO - --post-data '' --header 'Accept":" application/json' 'http://importer:8080/autoimport?directory=/import&secret=[SECRET]'\" >> /tmp/crontab_tmp && crontab /tmp/crontab_tmp && crond -f -L /dev/stdout && rm /tmp/crontab_tmp"
```

This is not the most elegant, but I was struggling to get both lines into `crontab` in a way that worked within the constraints.

Thanks for the help, I hope it wasn't too much hand-holding. And hopefully this might benefit someone else down the road.

**Reply by JC5** [reply]
Nice work, no problem! I will definitely refer to this from the docs!

**Reply by valzevul** [reply]
@lsalgueiro @JC5 hey folks, I am facing the same problem, but for me
`wget -qO - --post-data '' --header 'Accept":" application/json' 'http://importer:8080/autoimport?directory=/import&secret=[SECRET]'` leads to either 400 Bad Request or 500 Internal Server Error (depending on the quotes used).

I tried running the same container as the one mentioned [in the updated docs](https://docs.firefly-iii.org/how-to/data-importer/import/automated/):
```
  cron_importer:
    image: alpine
    container_name: firefly_iii_import_cron
    restart: always
    command: sh -c "echo -e \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/[SECRET]\" > /tmp/crontab_tmp && echo -e \"40 2 * * * wget -qO - --post-data '' --header 'Accept":" application/json' 'http://importer:8080/autoimport?directory=/import&secret=[SECRET]'\" >> /tmp/crontab_tmp && crontab /tmp/crontab_tmp && crond -f -L /dev/stdout && rm /tmp/crontab_tmp"
    networks:
      - firefly_iii
```
(after replacing secret and setting my network)

First cron works fine, the second always fails due to 500 Internal Server error.  

Any advice on debugging? Setting a crontab on host via docker exec works perfectly fine, but I'd love to have it in the docker-compose file instead.
