### DISCUSSION TITLE
Importer & Cron - How to have GoCardless import with Cron / Blank Charts

### DISCUSSION THREAD

**Discussion by delize** [firefly-iii/firefly-iii#8535] [Firefly III]
First off, thank you for this tool. I have been trying discuss software or solutions like this with my bank - and they are, effectively useless. 

Heck, even asking them about automated downloads / exports / imports from them - were met with "We don't provide anything". Leaving me to have to research the PSD2, and then this tool.

### Automating GoCardless & Importer for transactions

Anyways - I am trying to do automated importing using the cron tool that is included. 

```
[2024-02-10 16:20:00] local.INFO: Recognized user #1 (me) from his access token.  
[2024-02-10 16:20:00] local.INFO: It has been 1s before since the recurring transactions cron-job has fired. It will fire now!  
[2024-02-10 16:20:00] local.INFO: Will now fire recurring cron job task for date "2024-02-10 00:00:00".  
[2024-02-10 16:20:00] local.INFO: Marked the last time this job has run as "2024-02-10 00:00:00" (1707519600)  
[2024-02-10 16:20:00] local.INFO: Done with recurring cron job task.  
[2024-02-10 16:20:01] local.INFO: It has been 1s before since the auto budget cron-job has fired. It will fire now!  
[2024-02-10 16:20:01] local.INFO: Will now fire auto budget cron job task for date "2024-02-10".  
[2024-02-10 16:20:01] local.INFO: Done with auto budget cron job task.  
[2024-02-10 16:20:01] local.INFO: It has been 1s before since the bill warning cron-job has fired. It will fire now!  
[2024-02-10 16:20:01] local.INFO: Will now fire bill warning job task for date "2024-02-10 00:00:00".  
[2024-02-10 16:20:01] local.INFO: Marked the last time this job has run as "2024-02-10 00:00:00" (1707519600)  
[2024-02-10 16:20:01] local.INFO: Done with bill warning cron job task.  
````

However, when I run this, no transactions from the previous day actually get imported from GoCardless from the importer. - and I am not sure if this is something I am doing wrong, or if this is just normal behavior.  I have looked through:
* https://docs.firefly-iii.org/how-to/data-importer/import/gocardless/
* https://docs.firefly-iii.org/how-to/data-importer/advanced/post/

I also tried to search through the Github discussions, but, maybe I was using the wrong terms. 

My end goal here, is to automatically import the transactions, deposits, and transfers from my bank account which is already hooked up to the importer confguration - or I though it was at least.

### CSRF & Chart issues

```
version: '3.3'

#
# The Firefly III Data Importer will ask you for the Firefly III URL and a "Client ID".
# You can generate the Client ID at http://localhost/profile (after registering)
# The Firefly III URL is: http://app:8080
#
# Other URL's will give 500 | Server Error
#

services:
  app:
    image: fireflyiii/core:latest
    hostname: firefly-iii
    container_name: firefly-iii-core
    restart: unless-stopped
    volumes:
        - ${BASE_PATH}/firefly_iii_upload:/var/www/html/storage/upload
    environment:
        TZ: ${TIME_ZONE:-Europe/Stockholm}
        TRUSTED_PROXIES: "192.168.50.0/24"
        DB_CONNECTION: pgsql
        DB_HOST: ${POSTGRES_HOST}
        DB_PORT: ${POSTGRES_PORT}
        DB_DATABASE: ${FIREFLY_POSTGRES_DB}
        DB_USERNAME: ${FIREFLY_POSTGRES_USER}
        DB_PASSWORD: ${FIREFLY_POSTGRES_PASS}
        APP_KEY: ${FIREFLY_APP_KEY}
        SITE_OWNER: ${OWNER}
        MAP_DEFAULT_LAT: ${FIREFLY_MAP_DEFAULT_LAT}
        MAP_DEFAULT_LONG: ${FIREFLY_MAP_DEFAULT_LONG}
        MAP_DEFAULT_ZOOM: 6
        SERVERNAME: firefly.${DOMAIN}
    networks:
        - backend
        - database
        - firefly_iii
    # ports:
    #   - 8020:8080


  importer:
    image: fireflyiii/data-importer:latest
    hostname: importer
    restart: unless-stopped
    container_name: firefly-iii-importer
    networks:
      - firefly_iii
    ports:
      - '8120:8080'
    depends_on:
      - app
    env_file: .importer.env
    volumes:
      - ${BASE_PATH}/firefly_iii_upload:/var/www/html/storage/upload

  cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable and replace REPLACEME below
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    image: alpine
    container_name: firefly-iii-cron
    restart: unless-stopped
    command: sh -c "echo \"00 3 * * * wget -qO- http://firefly-iii:8080/api/v1/cron/${STATIC_CRON_TOKEN}\" | crontab - && crond -f -L /dev/stdout"
    networks:
      - firefly_iii

networks:
  firefly_iii:
    driver: bridge
  database:
    external: true
  backend:
    external: true
```

When I check chrome's devtools, I see:
`Refused to connect to 'http://firefly.my.domain/chart/transactions/categories/withdrawal/2024-02-01/2024-02-29' because it violates the following Content Security Policy directive: "connect-src 'self'".`
