### DISCUSSION TITLE
Firefly III with path prefix for traefik

### DISCUSSION THREAD

**Discussion by raspberry1704** [firefly-iii/firefly-iii#8571] [Firefly III]
Hello,

I have this configuration : 

```
services:
  firefly:
    image: fireflyiii/core:version-6.1.9
    volumes:
      - ./firefly_iii_export:/var/www/firefly-iii/storage/export
      - ./firefly_iii_upload:/var/www/firefly-iii/storage/upload
    env_file: .env
    container_name: firefly
    environment:
      - FIREFLY_III_URL_PREFIX=/finances
    networks:
      - firefly
      - all_traefik
    depends_on:
      - firefly_db
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=all_traefik"
      - "traefik.http.routers.firefly.entrypoints=http"
      - "traefik.http.routers.firefly.rule=Host(`myserver`) && PathPrefix(`/finances`)"
      - "traefik.http.services.firefly.loadbalancer.server.port=8080"
```

And it doesn't work with myserver/finances

Firefly always redirect to 404 page.

Someone got an idea ?

Thanks in advance.
