### DISCUSSION TITLE
[Help] Firefly III Importer - The importer could not connect but no error shown

### DISCUSSION THREAD

**Discussion by MantasXVIII** [firefly-iii/firefly-iii#8591] [Firefly III]
![image](https://github.com/firefly-iii/firefly-iii/assets/129862749/232ac948-c9ee-453b-93aa-e02c23627bda)
No error, so I go to the logs and I find nothing that signals what the issue is (heavily redacted):

 Params for access token { ....}
 2024-02-27 23:50:40] local.DEBUG: Will contact "https://mydomain/oauth/token" for a token.
 2024-02-27 23:50:41] local.DEBUG: Response {"token_type":"Bearer","expires_in":1209600,"access_token": ...... 
 2024-02-27 23:50:41] local.DEBUG: Return redirect  to "http://import.mydomain"
 2024-02-27 23:50:41] local.DEBUG: Now in App\Http\Controllers\IndexController::index
[2024-02-27 23:50:41] local.DEBUG: App\Services\Shared\Authentication\SecretManager::hasValidSecrets
172.20.0.1 - - [27/Feb/2024:23:50:41 +0100] "GET / HTTP/1.0" 200 3394 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"

And nothing else. So no error in the image, no error in the logs, what now?

See my nginx setups below (in .env I used 901 and 902 respectively):

```nginx
server {
    listen 80;
    server_name finance.mydomain.dev;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    server_name finance.mydomain.dev;

    ssl_certificate /etc/letsencrypt/live/finance.mydomain.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/finance.mydomain.dev/privkey.pem;

    location / {
        proxy_pass http://localhost:901;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $host;
                client_max_body_size 64M;
                proxy_read_timeout 300s;
    }
}
```

```nginx
server {
        listen 80;
        server_name import.mydomain.dev;
        return 301 https://$server_name$request_uri;
}

server {
        listen 443 ssl;
        server_name import.mydomain.dev;

        ssl_certificate /etc/letsencrypt/live/import.mydomain.dev/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/import.mydomain.dev/privkey.pem;
        location / {
                proxy_pass http://localhost:902;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $host;
# This line is optional and may help in some cases.
                proxy_set_header X-Forwarded-Port $server_port;
                client_max_body_size 64M;
                proxy_read_timeout 300s;
        }
}

```

And here is docker compose

```yaml

version: '3.3'

#
# The Firefly III Data Importer will ask you for the Firefly III URL and a "Client ID".
# You can generate the Client ID at http://localhost/profile (after registering)
# The Firefly III URL is: http://app:8080
#
# Other URL's will give 500 | Server Error
#

services:
  app:
    image: fireflyiii/core:latest
    hostname: app
    container_name: firefly_iii_core
    networks:
      - firefly_iii
    restart: always
    volumes:
      - ./firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - '901:8080'
    depends_on:
      - db
  db:
    image: mariadb:lts
    hostname: db
    container_name: firefly_iii_db
    networks:
      - firefly_iii
    restart: always
    env_file: .db.env
    volumes:
      - ./firefly_iii_db:/var/lib/mysql

  importer:
    image: fireflyiii/data-importer:latest
    hostname: importer
    restart: always
    container_name: firefly_iii_importer
    networks:
      - firefly_iii
    ports:
      - '902:8080'
    depends_on:
      - app
    env_file: .importer.env

  cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable and replace REPLACEME below
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    image: alpine
    container_name: firefly_iii_cron
    restart: always
    command: sh -c "echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/REPLACEME\" | crontab - && crond -f -L /dev/stdout"
    networks:
      - firefly_iii

networks:
  firefly_iii:
    driver: bridge
~
```
Any tips for how I can further debug this and figure out the issue? I have all the debug variables set as suggested per the documentation.
