### DISCUSSION TITLE
Setting timezone in Cron Docker container.

### DISCUSSION THREAD

**Discussion by f6310** [firefly-iii/firefly-iii#8604] [Firefly III]
I'm having an issue with setting a timezone in the cron container. The cron is successfully firing but at the wrong time. 

The "core" container and app is set yo Australia/Sydney but the cron container is set to UTC time. When running the automated transactions at 0300 UTC, they're being run at 1400 AEDT instead.

How do I make the "cron" container recognise the TZ command?

Here is the compose snippet for the "cron" container. 
```
 firefly-iii-cron:
  image: alpine
  container_name: firefly-iii-cron
  networks:
  - firefly-iii
  restart: always
  environment:
  - PUID=1000
  - PGID=1000
  - TZ=Australia/Sydney
  command: sh -c "echo \"0 3 * * * wget -qO- http://firefly-iii-core:8080/api/v1/cron/eSVSkuDtcyPaCY6F4tRCvkDvJDDbmppi\" | crontab - && crond -f -L /dev/stdout"

networks:
 firefly-iii:
  driver: bridge
```
