### DISCUSSION TITLE
Error message Too many connections (Connection: mysql, SQL: select * from `users` where `id` = 1 limit 1) {"exception":"

### DISCUSSION THREAD

**Discussion by BobWs** [firefly-iii/firefly-iii#8684] [General]
Hi,
I keep getting these error messages in my log, is this something to worry about? If so how do I fix this?

```
[2024-03-18 08:02:05] production.ERROR: SQLSTATE[HY000] [1040] Too many connections (Connection: mysql, SQL: select * from `users` where `id` = 1 limit 1) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 1040): SQLSTATE[HY000] [1040] Too many connections (Connection: mysql, SQL: select * from `users` where `id` = 1 limit 1) at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:829)
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
[2024-03-18 08:06:25] production.ERROR: SQLSTATE[HY000] [1040] Too many connections (Connection: mysql, SQL: select * from `users` where `id` = 1 limit 1) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 1040): SQLSTATE[HY000] [1040] Too many connections (Connection: mysql, SQL: select * from `users` where `id` = 1 limit 1) at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:829)
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
[2024-03-18 08:08:51] production.ERROR: SQLSTATE[HY000] [1040] Too many connections (Connection: mysql, SQL: select * from `users` where `id` = 1 limit 1) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 1040): SQLSTATE[HY000] [1040] Too many connections (Connection: mysql, SQL: select * from `users` where `id` = 1 limit 1) at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:829)
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
[2024-03-18 08:11:21] production.ERROR: SQLSTATE[HY000] [1040] Too many connections (Connection: mysql, SQL: select * from `users` where `id` = 1 limit 1) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 1040): SQLSTATE[HY000] [1040] Too many connections (Connection: mysql, SQL: select * from `users` where `id` = 1 limit 1) at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:829)
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
[2024-03-18 08:14:07] production.ERROR: SQLSTATE[HY000] [1040] Too many connections (Connection: mysql, SQL: select * from `users` where `id` = 1 limit 1) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 1040): SQLSTATE[HY000] [1040] Too many connections (Connection: mysql, SQL: select * from `users` where `id` = 1 limit 1) at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:829)
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
```
TIA

**Comment by JC5** [comment]
I've never seen this before, sorry. Could you share some info on your installation? My crystal ball is in the shop.

**Comment by BobWs** [comment]
I've installed the `latest images` of Firefly and I'm using an exsistant `mariadb:latest` for database. All running in docker on a Synology NAS. All running behind Ngnix-Proxy-Manager (NPM).
docker-compose (using Portainer)
```
version: '3.8'

services:
  firefly:              
    container_name: firefly
    image: fireflyiii/core:latest
    hostname: firefly
    security_opt:
      - no-new-privileges:true
    mem_limit: 256m
    mem_reservation: 256m
    ports:
      - "8050:8080"
    secrets:
      - firefly_file_appkey
      - firefly_file_mail
      - firefly_file_dbpass
      - firefly_file_crontoken    
    volumes: 
      - /volume1/docker/firefly/upload:/var/www/html/storage/upload
      - /etc/localtime:/etc/localtime:ro
      - /etc/TZ:/etc/timezone:ro
    env_file: stack.env
    environment:
      TZ: "Europe/Berlin"
    restart: "unless-stopped"
    networks:
      home:
  firefly-importer:              
    container_name: firefly-importer
    image: fireflyiii/data-importer:latest
    depends_on:
     - firefly  
    hostname: firefly-importer
    security_opt:
      - no-new-privileges:true
    mem_limit: 256m
    mem_reservation: 256m
    ports:
      - "8055:8080"
    env_file: stack.env
    environment:
      TZ: "Europe/Berlin"
    restart: "unless-stopped"
    networks:
      home:
  firefly-cron:              
    container_name: firefly-cron
    image: alpine:latest
    depends_on:
     - firefly  
    hostname: firefly-cron
    security_opt:
      - no-new-privileges:true
    mem_limit: 128m
    mem_reservation: 128m
    secrets:
      - firefly_file_crontoken    
    command: sh -c "echo \"0 3 * * * wget -qO- http://192.168.178.100:8050/api/v1/cron/$(cat /run/secrets/firefly_file_crontoken)\" | crontab - && crond -f -L /dev/stdout"
    env_file: stack.env    
    environment:
      TZ: "Europe/Berlin"
    restart: "unless-stopped"
    networks:
      home:



networks:
  home:
    external: true

secrets:
  firefly_file_appkey:
    file: /volume1/docker-docs/.secret/firefly_file_appkey.txt
  firefly_file_mail:
    file: /volume1/docker-docs/.secret/firefly_file_mail.txt
  firefly_file_dbpass:
    file: /volume1/docker-docs/.secret/firefly_file_dbpass.txt 
  firefly_file_crontoken:
    file: /volume1/docker-docs/.secret/firefly_file_crontoken.txt           
```
stack.env (for Portainer)
```
# Firefly III
APP_ENV=production
APP_DEBUG=false
PUID=1026
PGID=100
SITE_OWNER_FILE=/run/secrets/firefly_file_mail
APP_KEY_FILE=/run/secrets/firefly_file_appkey
DEFAULT_LANGUAGE=en_US
DEFAULT_LOCALE=equal
TZ=Europe/Berlin
TRUSTED_PROXIES=**
LOG_CHANNEL=stack
APP_LOG_LEVEL=notice
AUDIT_LOG_LEVEL=emergency
AUDIT_LOG_CHANNEL=
PAPERTRAIL_HOST=
PAPERTRAIL_PORT=
DB_CONNECTION=mysql
DB_HOST=192.168.178.100
DB_PORT=3306
DB_DATABASE=firefly
DB_USERNAME=firefly
DB_PASSWORD_FILE=/run/secrets/firefly_file_dbpass
DB_SOCKET=
MYSQL_USE_SSL=false
MYSQL_SSL_VERIFY_SERVER_CERT=true
MYSQL_SSL_CAPATH=/etc/ssl/certs/
MYSQL_SSL_CA=
MYSQL_SSL_CERT=
MYSQL_SSL_KEY=
MYSQL_SSL_CIPHER=
PGSQL_SSL_MODE=prefer
PGSQL_SSL_ROOT_CERT=null
PGSQL_SSL_CERT=null
PGSQL_SSL_KEY=null
PGSQL_SSL_CRL_FILE=null
PGSQL_SCHEMA=public
CACHE_DRIVER=file
SESSION_DRIVER=file
REDIS_SCHEME=tcp
REDIS_PATH=
REDIS_HOST=127.0.0.1
REDIS_PORT=6379
REDIS_USERNAME=
REDIS_PASSWORD=
REDIS_DB="0"
REDIS_CACHE_DB="1"
COOKIE_PATH="/"
COOKIE_DOMAIN=
COOKIE_SECURE=false
COOKIE_SAMESITE=lax
MAIL_MAILER=log
MAIL_HOST=null
MAIL_PORT=2525
MAIL_FROM=changeme@example.com
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_SENDMAIL_COMMAND=
MAILGUN_DOMAIN=
MAILGUN_SECRET=
MAILGUN_ENDPOINT=api.eu.mailgun.net
MANDRILL_SECRET=
SPARKPOST_SECRET=
SEND_ERROR_MESSAGE=false
SEND_REPORT_JOURNALS=false
ENABLE_EXTERNAL_MAP=false
ENABLE_EXTERNAL_RATES=false
MAP_DEFAULT_LAT=51.983333
MAP_DEFAULT_LONG=5.916667
MAP_DEFAULT_ZOOM=6
VALID_URL_PROTOCOLS=
AUTHENTICATION_GUARD=web
AUTHENTICATION_GUARD_HEADER=REMOTE_USER
AUTHENTICATION_GUARD_EMAIL=
PASSPORT_PRIVATE_KEY=
PASSPORT_PUBLIC_KEY=
CUSTOM_LOGOUT_URL=
DISABLE_FRAME_HEADER=false
DISABLE_CSP_HEADER=false
TRACKER_SITE_ID=
TRACKER_URL=
ALLOW_WEBHOOKS=true
STATIC_CRON_TOKEN_FILE=/run/secrets/firefly_file_crontoken
DKR_BUILD_LOCALE=false
DKR_CHECK_SQLITE=true
DKR_RUN_MIGRATION=true
DKR_RUN_UPGRADE=true
DKR_RUN_VERIFY=true
DKR_RUN_REPORT=true
DKR_RUN_PASSPORT_INSTALL=true
APP_NAME=FireflyIII
BROADCAST_DRIVER=log
QUEUE_DRIVER=sync
CACHE_PREFIX=firefly
PUSHER_KEY=
IPINFO_TOKEN=
PUSHER_SECRET=
PUSHER_ID=
DEMO_USERNAME=
DEMO_PASSWORD=
FIREFLY_III_LAYOUT=v1
APP_URL=https://fin.domain.tld

# Data Importer
PUID=1026
PGID=100
FIREFLY_III_URL=http://192.168.178.100:8050
VANITY_URL=http://192.168.178.100:8050
FIREFLY_III_ACCESS_TOKEN=
FIREFLY_III_CLIENT_ID=
NORDIGEN_ID=
NORDIGEN_KEY=
NORDIGEN_SANDBOX=false
SPECTRE_APP_ID=
SPECTRE_SECRET=
USE_CACHE=false
IGNORE_DUPLICATE_ERRORS=false
AUTO_IMPORT_SECRET=
CAN_POST_AUTOIMPORT=false
CAN_POST_FILES=false
IMPORT_DIR_ALLOWLIST=
VERIFY_TLS_SECURITY=true
JSON_CONFIGURATION_DIR=
CONNECTION_TIMEOUT=31.41
LOG_RETURN_JSON=false
LOG_LEVEL=debug
ASSET_URL=
ENABLE_MAIL_REPORT=false
EXPECT_SECURE_URL=false
MAIL_DESTINATION=
MAIL_FROM_ADDRESS=
POSTMARK_TOKEN=
QUEUE_CONNECTION=sync
SESSION_LIFETIME=120
IS_EXTERNAL=false
```
Please let me know if you need something else.
TIA
