### DISCUSSION TITLE
docker deploy in portainer in a loop

### DISCUSSION THREAD

**Discussion by hellofinch** [firefly-iii/firefly-iii#8824] [Firefly III] [answered]
I deploy the firefly-iii in my NAS with portainer. And it struck in a loop. I search for issues but the others face this in upgrade.
Here is my dockerfile-compose.yml and stack.env.
```
version: '3.3'

#
# The Firefly III Data Importer will ask you for the Firefly III URL and a "Client ID".
# You can generate the Client ID at http://localhost/profile (after registering)
# The Firefly III URL is: http://app:8080
#
# Other URL's will give 500 | Server Error
#

services:
  app:
    image: fireflyiii/core:latest
    hostname: app
    container_name: firefly_iii_core
    networks:
      - firefly_iii
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: stack.env
    ports:
      - '80:8080'
    depends_on:
      - db
  db:
    image: mariadb:lts
    hostname: db
    container_name: firefly_iii_db
    networks:
      - firefly_iii
    restart: always
    env_file: stack.env
    volumes:
      - firefly_iii_db:/var/lib/mysql

  importer:
    image: fireflyiii/data-importer:latest
    hostname: importer
    restart: always
    container_name: firefly_iii_importer
    networks:
      - firefly_iii
    ports:
      - '81:8080'
    depends_on:
      - app
    env_file: stack.env

  cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable and replace REPLACEME below
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    image: alpine
    container_name: firefly_iii_cron
    restart: always
    command: sh -c "echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/REPLACEME\" | crontab - && crond -f -L /dev/stdout"
    networks:
      - firefly_iii
volumes:
   firefly_iii_upload:
   firefly_iii_db:

networks:
  firefly_iii:
    driver: bridge
```
```
# Firefly III
APP_ENV=production
APP_DEBUG=false
SITE_OWNER=mail@example.com
APP_KEY=XujCOMV9TgnYUqAd4rOjQXpqWCYril6j
DEFAULT_LANGUAGE=en_US
DEFAULT_LOCALE=equal
TZ=Europe/Amsterdam
TRUSTED_PROXIES=
LOG_CHANNEL=stack
APP_LOG_LEVEL=notice
AUDIT_LOG_LEVEL=emergency
AUDIT_LOG_CHANNEL=
PAPERTRAIL_HOST=
PAPERTRAIL_PORT=
DB_CONNECTION=mysql
DB_HOST=db
DB_PORT=3306
DB_DATABASE=firefly
DB_USERNAME=firefly
DB_PASSWORD=123456
DB_SOCKET=
MYSQL_USE_SSL=false
MYSQL_SSL_VERIFY_SERVER_CERT=false
MYSQL_SSL_CAPATH=/etc/ssl/certs/
MYSQL_SSL_CA=
MYSQL_SSL_CERT=
MYSQL_SSL_KEY=
MYSQL_SSL_CIPHER=
PGSQL_SSL_MODE=prefer
PGSQL_SSL_ROOT_CERT=null
PGSQL_SSL_CERT=null
PGSQL_SSL_KEY=null
PGSQL_SSL_CRL_FILE=null
PGSQL_SCHEMA=public
CACHE_DRIVER=file
SESSION_DRIVER=file
REDIS_SCHEME=tcp
REDIS_PATH=
REDIS_HOST=127.0.0.1
REDIS_PORT=6379
REDIS_USERNAME=
REDIS_PASSWORD=
REDIS_DB="0"
REDIS_CACHE_DB="1"
COOKIE_PATH="/"
COOKIE_DOMAIN=
COOKIE_SECURE=false
COOKIE_SAMESITE=lax
MAIL_MAILER=log
MAIL_HOST=null
MAIL_PORT=2525
MAIL_FROM=changeme@example.com
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_SENDMAIL_COMMAND=
MAILGUN_DOMAIN=
MAILGUN_SECRET=
MAILGUN_ENDPOINT=api.mailgun.net
MANDRILL_SECRET=
SPARKPOST_SECRET=
SEND_ERROR_MESSAGE=true
SEND_REPORT_JOURNALS=true
ENABLE_EXTERNAL_MAP=false
ENABLE_EXCHANGE_RATES=false
ENABLE_EXTERNAL_RATES=false
MAP_DEFAULT_LAT=51.983333
MAP_DEFAULT_LONG=5.916667
MAP_DEFAULT_ZOOM=6
VALID_URL_PROTOCOLS=
AUTHENTICATION_GUARD=web
AUTHENTICATION_GUARD_HEADER=REMOTE_USER
AUTHENTICATION_GUARD_EMAIL=
PASSPORT_PRIVATE_KEY=
PASSPORT_PUBLIC_KEY=
CUSTOM_LOGOUT_URL=
DISABLE_FRAME_HEADER=false
DISABLE_CSP_HEADER=false
TRACKER_SITE_ID=
TRACKER_URL=
ALLOW_WEBHOOKS=false
STATIC_CRON_TOKEN=XujCOMV9TgnYUqAd4rOjQXpqWCYril6j
DKR_BUILD_LOCALE=false
DKR_CHECK_SQLITE=true
DKR_RUN_MIGRATION=true
DKR_RUN_UPGRADE=true
DKR_RUN_VERIFY=true
DKR_RUN_REPORT=true
DKR_RUN_PASSPORT_INSTALL=true
APP_NAME=FireflyIII
BROADCAST_DRIVER=log
QUEUE_DRIVER=sync
CACHE_PREFIX=firefly
PUSHER_KEY=
IPINFO_TOKEN=
PUSHER_SECRET=
PUSHER_ID=
DEMO_USERNAME=
DEMO_PASSWORD=
FIREFLY_III_LAYOUT=v1
APP_URL=http://localhost

# Data Importer
FIREFLY_III_URL=http://app:8080
VANITY_URL=http://localhost
FIREFLY_III_ACCESS_TOKEN=
FIREFLY_III_CLIENT_ID=
NORDIGEN_ID=
NORDIGEN_KEY=
NORDIGEN_SANDBOX=false
SPECTRE_APP_ID=
SPECTRE_SECRET=
USE_CACHE=false
IGNORE_DUPLICATE_ERRORS=false
IGNORE_NOT_FOUND_TRANSACTIONS=false
AUTO_IMPORT_SECRET=
CAN_POST_AUTOIMPORT=false
CAN_POST_FILES=false
IMPORT_DIR_ALLOWLIST=
FALLBACK_IN_DIR=false
VERIFY_TLS_SECURITY=true
JSON_CONFIGURATION_DIR=
CONNECTION_TIMEOUT=31.41
LOG_RETURN_JSON=false
LOG_LEVEL=debug
ENABLE_MAIL_REPORT=false
EXPECT_SECURE_URL=false
MAIL_DESTINATION=noreply@example.com
MAIL_FROM_ADDRESS=noreply@example.com
POSTMARK_TOKEN=
QUEUE_CONNECTION=sync
SESSION_LIFETIME=120
IS_EXTERNAL=false
ASSET_URL=

# Database
MYSQL_RANDOM_ROOT_PASSWORD=yes
MYSQL_USER=firefly
MYSQL_PASSWORD=123456
MYSQL_DATABASE=firefly
```
The log continue outputting and I try to catch the part where error shows up.
```
  [i] Will run verification commands.
      Now executing command "firefly-iii:fix-piggies"
  [✓] All piggy bank events are OK.
      Now executing command "firefly-iii:create-link-types"
  [✓] All link types are OK
      Now executing command "firefly-iii:create-access-tokens"
  [✓] Verified access tokens.
      Now executing command "firefly-iii:remove-bills"
  [✓] All bills and journals are OK
      Now executing command "firefly-iii:fix-amount-pos-neg"
  [✓] All auto budget amounts are positive.
  [✓] All available budget amounts are positive.
  [✓] All bill amounts are positive.
  [✓] All budget limit amounts are positive.
  [✓] All currency exchange rates are positive.
  [✓] All piggy bank repetition amounts are positive.
  [✓] All piggy bank amounts are positive.
  [✓] All recurring transaction amounts are positive.
  [✓] All rule trigger amounts are positive.
      Now executing command "firefly-iii:enable-currencies"
      Now executing command "firefly-iii:fix-transfer-budgets"
  [✓] No invalid budget/journal entries.
      Now executing command "firefly-iii:fix-uneven-amount"
  [✓] Database amount integrity is OK
      Now executing command "firefly-iii:delete-zero-amount"
  [✓] No zero-amount transaction journals.
      Now executing command "firefly-iii:delete-orphaned-transactions"
  [✓] No orphaned journals.
  [✓] No orphaned transactions.
  [✓] No orphaned accounts.
      Now executing command "firefly-iii:delete-empty-journals"
  [✓] No uneven transaction journals.
  [✓] No empty transaction journals.
      Now executing command "firefly-iii:delete-empty-groups"
  [i] Verified there are no empty groups.
      Now executing command "firefly-iii:fix-account-types"
  [✓] All account types are OK
      Now executing command "firefly-iii:fix-ibans"
  [✓] All IBANs are valid.
      Now executing command "firefly-iii:fix-account-order"
  [✓] All accounts are ordered correctly
      Now executing command "firefly-iii:rename-meta-fields"
  [✓] All meta fields are correct.
      Now executing command "firefly-iii:fix-ob-currencies"
  [✓] There was nothing to fix in the opening balance transactions.
      Now executing command "firefly-iii:fix-long-descriptions"
  [✓] All transaction group and journal title lengths are within bounds.
      Now executing command "firefly-iii:fix-recurring-transactions"
  [✓] All recurring transactions are OK.
      Now executing command "firefly-iii:upgrade-group-information"
      Now executing command "firefly-iii:fix-transaction-types"
  [✓] All transaction journals are of the correct transaction type
      Now executing command "firefly-iii:fix-frontpage-accounts"
  [✓] Account preferences are OK
      Now executing command "firefly-iii:unify-group-accounts"
  [✓] Updated possible inconsistent transaction groups.
      Now executing command "firefly-iii:trigger-credit-recalculation"
      Now executing command "firefly-iii:migrate-preferences"
  [i] Will run report commands.
      Now executing firefly-iii:create-group-memberships
  [✓] Validated group memberships
      Now executing firefly-iii:report-empty-objects
      Now executing firefly-iii:report-sum
      Now executing firefly-iii:upgrade-group-information
  [i] Will generate OAuth keys commands.
   ERROR  Encryption keys already exist. Use the --force option to overwrite them.  
  [i] Updated version.
```
I followed the guide to deploy the docker again and again. I tried to delete all things about firefly-iii and install but it also failed.
What should I do?

**Comment by JC5** [comment]
I see no errors in your logs? 

```
   ERROR  Encryption keys already exist. Use the --force option to overwrite them.  
```

This is not a fatal error.

**Comment by hellofinch** [comment]
But I try to visit http://localhost:6666 and it is show nothing. And I get this log again and again. BTW, I map 8080 to 6666.
This is my new docker-compose.yml
```
version: '3.3'

#
# The Firefly III Data Importer will ask you for the Firefly III URL and a "Client ID".
# You can generate the Client ID at http://localhost/profile (after registering)
# The Firefly III URL is: http://app:8080
#
# Other URL's will give 500 | Server Error
#

services:
  app:
    image: fireflyiii/core:latest
    hostname: app
    container_name: firefly_iii_core
    networks:
      - firefly_iii
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: stack.env
    ports:
      - '6666:8080'
    depends_on:
      - db
  db:
    image: mariadb:lts
    hostname: db
    container_name: firefly_iii_db
    networks:
      - firefly_iii
    restart: always
    env_file: stack.env
    volumes:
      - firefly_iii_db:/var/lib/mysql

  importer:
    image: fireflyiii/data-importer:latest
    hostname: importer
    restart: always
    container_name: firefly_iii_importer
    networks:
      - firefly_iii
    ports:
      - '6667:8080'
    depends_on:
      - app
    env_file: stack.env

  cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable and replace REPLACEME below
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    image: alpine
    container_name: firefly_iii_cron
    restart: always
    command: sh -c "echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/REPLACEME\" | crontab - && crond -f -L /dev/stdout"
    networks:
      - firefly_iii
volumes:
   firefly_iii_upload:
   firefly_iii_db:

networks:
  firefly_iii:
    driver: bridge
```
I got this message again and again. It shows in log repeated.
```
      Now executing command "firefly-iii:delete-orphaned-transactions"
  [✓] No orphaned journals.
  [✓] No orphaned transactions.
  [✓] No orphaned accounts.
      Now executing command "firefly-iii:delete-empty-journals"
  [✓] No uneven transaction journals.
  [✓] No empty transaction journals.
      Now executing command "firefly-iii:delete-empty-groups"
  [i] Verified there are no empty groups.
      Now executing command "firefly-iii:fix-account-types"
  [✓] All account types are OK
      Now executing command "firefly-iii:fix-ibans"
  [✓] All IBANs are valid.
      Now executing command "firefly-iii:fix-account-order"
  [✓] All accounts are ordered correctly
      Now executing command "firefly-iii:rename-meta-fields"
  [✓] All meta fields are correct.
      Now executing command "firefly-iii:fix-ob-currencies"
  [✓] There was nothing to fix in the opening balance transactions.
      Now executing command "firefly-iii:fix-long-descriptions"
  [✓] All transaction group and journal title lengths are within bounds.
      Now executing command "firefly-iii:fix-recurring-transactions"
  [✓] All recurring transactions are OK.
      Now executing command "firefly-iii:upgrade-group-information"
      Now executing command "firefly-iii:fix-transaction-types"
  [✓] All transaction journals are of the correct transaction type
      Now executing command "firefly-iii:fix-frontpage-accounts"
  [✓] Account preferences are OK
      Now executing command "firefly-iii:unify-group-accounts"
  [✓] Updated possible inconsistent transaction groups.
      Now executing command "firefly-iii:trigger-credit-recalculation"
      Now executing command "firefly-iii:migrate-preferences"
  [i] Will run report commands.
      Now executing firefly-iii:create-group-memberships
  [✓] Validated group memberships
      Now executing firefly-iii:report-empty-objects
      Now executing firefly-iii:report-sum
      Now executing firefly-iii:upgrade-group-information
  [i] Will generate OAuth keys commands.
   ERROR  Encryption keys already exist. Use the --force option to overwrite them.  
  [i] Updated version.
  [✓] No security alerts for version 6.1.15
              ______ _           __ _            _____ _____ _____  
             |  ____(_)         / _| |          |_   _|_   _|_   _| 
             | |__   _ _ __ ___| |_| |_   _       | |   | |   | |   
             |  __| | | '__/ _ \  _| | | | |      | |   | |   | |   
             | |    | | | |  __/ | | | |_| |     _| |_ _| |_ _| |_  
             |_|    |_|_|  \___|_| |_|\__, |    |_____|_____|_____| 
                                       __/ |                        
                                      |___/                         
+------------------------------------------------------------------------------+
|                                                                              |
| Thank you for installing Firefly III, v6.1.15!                               |
| This version of Firefly III requires PHP8.3.                                 |
|                                                                              |
+------------------------------------------------------------------------------+
  [!] You can safely ignore the error about the 'fully qualified domain name'.
[Fri Apr 26 15:06:49.752501 2024] [:crit] [pid 1] (38)Function not implemented: AH00141: Could not initialize random number generator
Now in entrypoint.sh for Firefly III
Script:            1.3.0 (2024-03-20)
User:              root
Group:             root
Working dir:       /var/www/html
Base build number: 83
Base build date:   23-04-2024 07:09:41 CEST
Build number:      1074
Build date:        23-04-2024 17:46:29 CEST
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
Generated optimized autoload files containing 6687 classes
   INFO  Discovering packages.  
  diglactic/laravel-breadcrumbs ......................................... DONE
  jc5/google2fa-laravel ................................................. DONE
  laravel/passport ...................................................... DONE
  laravel/sanctum ....................................................... DONE
  laravel/slack-notification-channel .................................... DONE
  laravel/ui ............................................................ DONE
  nesbot/carbon ......................................................... DONE
  nunomaduro/collision .................................................. DONE
  nunomaduro/termwind ................................................... DONE
  rcrowe/twigbridge ..................................................... DONE
  spatie/laravel-html ................................................... DONE
  spatie/laravel-ignition ............................................... DONE
  [i] Wait for the database. You may see an error about an 'aborted connection', this is normal.
wait-for-it.sh: waiting 60 seconds for db:3306
wait-for-it.sh: db:3306 is available after 0 seconds
  [✓] DB is up.
  [i] Wait another 10 seconds in case the DB needs to boot.
........
```
I think those info show once.
