### DISCUSSION TITLE
SQLite Database error, happened randomly

### DISCUSSION THREAD

**Discussion by shyonae** [firefly-iii/firefly-iii#8829] [Firefly III] [answered]
Hi everyone, I have no idea what happened, but I am getting this error once I try to access Firefly's main page:

![image](https://github.com/firefly-iii/firefly-iii/assets/88051140/8512ae9e-658f-42a3-84de-7c229034e70e)

This is my compose:

```yaml
version: "3.8"

x-default-conf: &default_conf
  restart: unless-stopped
  networks:
    - generalStackNetwork

services:
  firefly_iii_app:
    image: fireflyiii/core:latest
    hostname: firefly_iii_app
    container_name: firefly_iii_app
    environment:
      TZ: ${TZ}
      APP_ENV: "local"
      APP_DEBUG: false
      SITE_OWNER: ${DEFAULT_EMAIL}
      APP_KEY: ${FIREFLY3_APP_KEY}
      DEFAULT_LANGUAGE: "en_US"
      DEFAULT_LOCALE: "equal"
      TRUSTED_PROXIES: "**"
      LOG_CHANNEL: "stack"
      APP_LOG_LEVEL: "notice"
      AUDIT_LOG_LEVEL: "info"
      DB_CONNECTION: "sqlite"
      CACHE_DRIVER: "file"
      SESSION_DRIVER: "file"
      COOKIE_PATH: "/"
      COOKIE_SECURE: false
      COOKIE_SAMESITE: "lax"
      SEND_ERROR_MESSAGE: true
      SEND_REPORT_JOURNALS: false
      ENABLE_EXTERNAL_MAP: false
      ENABLE_EXTERNAL_RATES: false
      MAP_DEFAULT_LAT: "51.983333"
      MAP_DEFAULT_LONG: "5.916667"
      MAP_DEFAULT_ZOOM: "6"
      AUTHENTICATION_GUARD: "web"
      DISABLE_FRAME_HEADER: false
      DISABLE_CSP_HEADER: false
      ALLOW_WEBHOOKS: false
      STATIC_CRON_TOKEN: ${FIREFLY3_APP_KEY}
      DKR_BUILD_LOCALE: false
      DKR_CHECK_SQLITE: true
      DKR_RUN_MIGRATION: false
      DKR_RUN_UPGRADE: false
      DKR_RUN_VERIFY: false
      DKR_RUN_REPORT: true
      DKR_RUN_PASSPORT_INSTALL: true
      APP_NAME: "FireflyIII"
      BROADCAST_DRIVER: "log"
      QUEUE_DRIVER: "sync"
      CACHE_PREFIX: "firefly"
      FIREFLY_III_LAYOUT: "v1"
    <<: *default_conf
    labels:
      - docker-volume-backup.stop-during-backup=true
    ports:
      - 8007:8080
    volumes:
      - ${DOCKERCONFDIR}/firefly_iii/firefly_iii_upload:/var/www/html/storage/upload
      - ${DOCKERCONFDIR}/firefly_iii/database:/var/www/html/storage/database

networks:
  generalStackNetwork:
    driver: bridge
    external: true
```

Any idea on what happened here? I'm running it on Ubuntu 22.04.
