### DISCUSSION TITLE
Error: Password Authentication Failed for user 'firefly'

### DISCUSSION THREAD

**Discussion by Samvid95** [firefly-iii/firefly-iii#8993] [Firefly III]
Hey guys, 

I am trying to install firefly-iii with pico and I am following this yml file to install. 
```
version: '3.3'
services:

  firefly-pico:
    image: cioraneanu/firefly-pico:latest
    container_name: firefly_pico
    restart: always
    depends_on:
      - firefly-pico-postgresql
    ports:
      - 6976:80
    environment:
      - FIREFLY_URL=http://firefly-app:8080
      - DB_CONNECTION=pgsql
      - DB_HOST=firefly-pico-postgresql
      - DB_PORT=5432
      - DB_DATABASE=firefly-pico
      - DB_USERNAME=firefly-pico
      - DB_PASSWORD={DB_PASSWORD}
      - TZ={TZ}
    networks:
      firefly:

  firefly-pico-postgresql:
    image: postgres:latest
    container_name: firefly_pico_db
    restart: always
    environment:
      - POSTGRES_DB=firefly-pico
      - POSTGRES_USER=firefly-pico
      - POSTGRES_PASSWORD={DB_PASSWORD}
    volumes:
      -portainer/Files/AppData/Config/firefly/firefly-pico-db:/var/lib/postgresql/data
    networks:
      firefly:


  firefly-app:
    image: fireflyiii/core:latest
    container_name: firefly_iii
    restart: always
    depends_on:
      - firefly-app-postgresql
    ports:
      - 6041:8080
    environment:
      - FIREFLY_III_LAYOUT=v1
      - APP_URL=https://firefly.domain.com
      - APP_KEY=somerandomstringOf32charsexactly
      - TRUSTED_PROXIES=**
      - DB_CONNECTION=pgsql
      - DB_HOST=firefly-app-postgresql
      - DB_PORT=5432
      - DB_DATABASE=firefly
      - DB_USERNAME=firefly
      - DB_PASSWORD={DB_PASSWORD}
    volumes:
      - /portainer/Files/AppData/Config/firefly/firefly-upload:/var/www/html/storage/upload
    networks:
      firefly:

  firefly-app-postgresql:
    image: postgres:latest
    container_name: firefly_iii_db
    restart: always
    environment:
      - POSTGRES_DB=firefly
      - POSTGRES_USER=firefly
      - POSTGRES_PASSWORD={DB_PASSWORD}
    volumes:
      -portainer/Files/AppData/Config/firefly/firefly-db:/var/lib/postgresql/data
    networks:
      firefly:

  importer:
    image: fireflyiii/data-importer:latest
    restart: always
    container_name: firefly_iii_importer
    ports:
      - 4086:8080
    depends_on:
      - firefly-app
    environment:
      - FIREFLY_III_URL=http://firefly-app:8080
    networks:
      firefly:

networks:
  firefly:
```
  
  Now after deploying this stack I am getting this error on my firefly_iii_db container: 
`2024-06-24 06:50:28.683 UTC [53] FATAL:  password authentication failed for user "firefly"
2024-06-24 06:50:28.683 UTC [53] DETAIL:  Role "firefly" does not exist.`

And due to this error: 
`Could not poll the database: SQLSTATE[08006] [7] FATAL: password authentication failed for user "firefly" (Connection: pgsql, SQL: select "id", "name", "data" from "configuration" where "name" = is_demo_site and "configuration"."deleted_at" is null limit 1)`

What am I missing? 

My environment file contains {DB_PASSWORD} variable.
