### DISCUSSION TITLE
The network firefly3_firefly_iii cannot be used with services. Only networks scoped to the swarm can be used, such as those created with the overlay driver

### DISCUSSION THREAD

**Discussion by KalaRaja** [firefly-iii/firefly-iii#9242] [Firefly III]
I am trying to deploy in my docker swarm on my leader raspberry pi 3b+ node.

I get the following error - 
```
Creating service firefly3_app
failed to create service firefly3_app: Error response from daemon: The network firefly3_firefly_iii cannot be used with services. Only networks scoped to the swarm can be used, such as those created with the overlay driver.
```

docker compose file - 
```
services:
  app:
    image: fireflyiii/core:latest
    hostname: app
    networks:
      - firefly_iii
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: ./.env
    ports:
      - '80:8080'
    depends_on:
      - db
    deploy:
      placement:
        constraints:
          - node.hostname==pi1
          - node.role==manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  db:
    image: mariadb:lts
    hostname: db
    networks:
      - firefly_iii
    env_file: ./.db.env
    volumes:
      - firefly_iii_db:/var/lib/mysql
    deploy:
      placement:
        constraints:
          - node.hostname==pi1
          - node.role==manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  importer:
    image: fireflyiii/data-importer:latest
    hostname: importer
    networks:
      - firefly_iii
    ports:
      - '81:8080'
    depends_on:
      - app
    env_file: ./.importer.env
    deploy:
      placement:
        constraints:
          - node.hostname==pi1
          - node.role==manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  cron:
    image: alpine
    command: sh -c "echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/klI0JEC7TkDisfFuyjbRsIqATxmH5qRWwq\" | crontab - && crond -f -L /dev/stdout"
    networks:
      - firefly_iii
    deploy:
      placement:
        constraints:
          - node.hostname==pi1
          - node.role==manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

volumes:
   firefly_iii_upload:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./upload

   firefly_iii_db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./db


networks:
  firefly_iii:
    driver: bridge

```

I'm running `sudo docker stack deploy --compose-file=docker-compose.yml firefly3`

does anyone know what I am doing wrong ?
