### DISCUSSION TITLE
Need Help with Recurring Transactions Issue

### DISCUSSION THREAD

**Discussion by BobWs** [firefly-iii/firefly-iii#9289] [General]
Hi everyone,

I’m reaching out for assistance with a problem I’m experiencing. My recurring transactions suddenly stopped working, and I keep receiving an error message. Everything was functioning perfectly last month, but this month, none of the recurring transactions are processing.

I haven’t made any changes to the configuration in months, and everything was running smoothly until now. I’ve updated to the latest version, but that hasn’t resolved the issue. Additionally, the logs don’t indicate any errors related to the cron container.

I’m not sure where to start looking for a solution. If anyone has any insights or suggestions, I would greatly appreciate your help!

Thank you!

```
Warning! It looks like it has been more than 36 hours since the cron job to support recurring transactions has fired for the last time. Are you sure it has been set up correctly? Please check out the help-pages using the (?)-icon in the top right corner of the page. 
```

This is my docker-compose file:
```
version: '3.8'

services:
  firefly:              
    container_name: firefly
    image: fireflyiii/core:latest
    hostname: firefly
    security_opt:
      - no-new-privileges:true
    mem_limit: 256m
    mem_reservation: 256m
    ports:
      - "8050:8080"
    secrets:
      - firefly_file_appkey
      - firefly_file_mail
      - firefly_file_dbpass
      - firefly_file_crontoken    
    volumes: 
      - /volume1/docker/firefly/upload:/var/www/html/storage/upload
      - /etc/localtime:/etc/localtime:ro
      - /etc/TZ:/etc/timezone:ro
    env_file: stack.env
    environment:
      TZ: "Europe/Berlin"
    restart: "unless-stopped"
    networks:
      home:
  
  firefly-importer:              
    container_name: firefly-importer
    image: fireflyiii/data-importer:latest
    depends_on:
     - firefly  
    hostname: firefly-importer
    security_opt:
      - no-new-privileges:true
    mem_limit: 256m
    mem_reservation: 256m
    ports:
      - "8055:8080"
    volumes: 
      - /volume1/docker/firefly/upload:/var/www/html/storage/upload
      - /etc/localtime:/etc/localtime:ro
      - /etc/TZ:/etc/timezone:ro
    env_file: stack.env
    environment:
      TZ: "Europe/Berlin"
    restart: "unless-stopped"
    networks:
      home:
  
  firefly-cron:              
    container_name: firefly-cron
    image: alpine:latest
    depends_on:
     - firefly  
    hostname: firefly-cron
    security_opt:
      - no-new-privileges:true
    mem_limit: 128m
    mem_reservation: 128m
    secrets:
      - firefly_file_crontoken    
    command: sh -c "echo \"0 3 * * * wget -qO- http://192.168.178.100:8050/api/v1/cron/$(cat /run/secrets/firefly_file_crontoken)\" | crontab - && crond -f -L /dev/stdout"
    env_file: stack.env    
    environment:
      TZ: "Europe/Berlin"
    restart: "unless-stopped"
    networks:
      home:

networks:
  home:
    external: true

secrets:
  firefly_file_appkey:
    file: /volume1/docker-docs/.secret/firefly_file_appkey.txt
  firefly_file_mail:
    file: /volume1/docker-docs/.secret/firefly_file_mail.txt
  firefly_file_dbpass:
    file: /volume1/docker-docs/.secret/firefly_file_dbpass.txt 
  firefly_file_crontoken:
    file: /volume1/docker-docs/.secret/firefly_file_crontoken.txt           
```
