### DISCUSSION TITLE
Using Tailscale proxy is not sending some assets

### DISCUSSION THREAD

**Discussion by enboig** [firefly-iii/firefly-iii#9354] [Firefly III]
I have configured docker-compose to use Tailscale, but when loading the page some assets (css, images, ...) are not loaded. Browser complains:
![imatge](https://github.com/user-attachments/assets/30f9c2ef-5d58-405b-8834-fc921bab82c6)

docker-compose.yaml:
```yaml
services:
  ts-firefly:
    image: tailscale/tailscale:latest
    container_name: ts-firefly
    hostname: firefly
    env_file: .ts.env
    volumes:
      - ./ts-firefly/state:/var/lib/tailscale
      - ./ts-firefly/config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: no
    networks:
      - firefly_iii

  app:
    image: fireflyiii/core:latest
    # hostname: app
    container_name: firefly_iii_core
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    # networks:
    #   - firefly_iii
    # ports:
    #   - 80:8080
    network_mode: service:ts-firefly # added
    depends_on:
      - db
  db:
    image: mariadb:lts
    hostname: db
    container_name: firefly_iii_db
    restart: always
    env_file: .db.env
    networks:
      - firefly_iii
    volumes:
      - firefly_iii_db:/var/lib/mysql
  cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable and replace REPLACEME below
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    image: alpine
    restart: always
    container_name: firefly_iii_cron
    command: sh -c "echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/REPLACEME;echo\" | crontab - && crond -f -L /dev/stdout"
    networks:
      - firefly_iii

volumes:
  firefly_iii_upload:
  firefly_iii_db:

networks:
  firefly_iii:
    driver: bridge
```

After this, I will have to make `cron` work.
