### DISCUSSION TITLE
First time setup, i cant get it pass the start

### DISCUSSION THREAD

**Discussion by IIIdefconIII** [firefly-iii/firefly-iii#9393] [Firefly III]
HI all,
As of today i was starting tro try this container. I have almost 40 containers running next to each other but it seems i cant get this one up.
Not sure ehwat im missing here, port 80 is in use its says which i think ok let me try something else, but the progrram only works on 80 i guess as the default web port. Can i change the port 80 to something else so i might be able to get it launched?

The files configurerd below in the dockerfolde also not getting updates, probably because its not starting in the beginning.
Perhaps i HAVE to create a seperate network on my NAS to be able to use port 80, but all other docker containers are working, i had it before on a frw containers and ask the devs to implent a port change environment variable and they did so it works now.

```
# Firefly________
  Firefly:
    image: fireflyiii/core:latest
    hostname: app
    container_name: firefly_iii_core
    restart: always
    volumes:
      - $DOCKERDIR/firefly_iii/firefly_iii_upload:/var/www/html/storage/upload
    env_file: $DOCKERDIR/firefly_iii/firefly.env
    ports:
      - 80:8080
    depends_on:
      - db
  db:
    image: mariadb:lts
    hostname: db
    container_name: firefly_iii_db
    restart: always
    env_file: $DOCKERDIR/firefly_iii/firefly_iii_db/firefly.db.env
    volumes:
      - $DOCKERDIR/firefly_iii/firefly_iii_db:/var/lib/mysql

  cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable and replace REPLACEME below
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    image: alpine
    restart: always
    container_name: firefly_iii_cron
    command: sh -c "echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/REPLACEME;echo\" | crontab - && crond -f -L /dev/stdout"
    ```
