### DISCUSSION TITLE
Cannot Login, Returns To The Register Everytime Clicking Login After Migration

### DISCUSSION THREAD

**Discussion by lem0nbleach** [firefly-iii/firefly-iii#9679] [Firefly III] [answered]
Hi all,

I have just migrated my firefly docker host from localhost to a dedicated docker host with Traefik. The issue here is that I am stuck in the register page and cannot get into login (Returns me to firefly.fishstall.net/register).

Expected behavior: Click on login and I will be sent to firefly.fishstall.net/login

**First I will list my process of migration:** 

1. On local machine
```
docker run --rm -v "firefly_firefly_iii_db:/tmp" \
    -v "$HOME/backups/firefly:/backup" \
    ubuntu tar -czvf /backup/firefly_db.tar /tmp
```
2. Transfer the .tar file to the docker host using rsync
3. On docker host 
```
docker run --rm -v "firefly_firefly_iii_db:/recover" \
    -v "$HOME/backups/firefly:/backup" \
    ubuntu tar -xvf /backup/firefly_db.tar -C /recover --strip 1
```
4. Transfer all config files (ie. docker-compose.yml, .env, .db.env) to docker host and `sudo docker compose up -d`

**Next here are the logs when I click on "I want to login":**
```
firefly_iii_core  | 172.19.0.2 - - [20/Jan/2025:10:19:05 -0500] "GET /login HTTP/1.1" 302 2169 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:134.0) Gecko/20100101 Firefox/134.0"
firefly_iii_core  | 172.19.0.2 - - [20/Jan/2025:10:19:05 -0500] "GET /register HTTP/1.1" 200 4479 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:134.0) Gecko/20100101 Firefox/134.0"
firefly_iii_core  | 172.19.0.2 - - [20/Jan/2025:10:19:06 -0500] "GET /build/assets/dashboard-COcAMlDN.js HTTP/1.1" 200 7127 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:134.0) Gecko/20100101 Firefox/134.0"
firefly_iii_core  | 172.19.0.2 - - [20/Jan/2025:10:19:06 -0500] "GET /build/assets/show-internals-button-D8bynbIo.js HTTP/1.1" 200 2251 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:134.0) Gecko/20100101 Firefox/134.0"
firefly_iii_core  | [2025-01-20 10:19:06] local.DEBUG: Now in Handler::render()  
firefly_iii_core  | [2025-01-20 10:19:06] local.DEBUG: Return JSON unauthenticated error.  
firefly_iii_core  | 172.19.0.2 - - [20/Jan/2025:10:19:06 -0500] "GET /api/v1/preferences/lastActivity HTTP/1.1" 401 940 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:134.0) Gecko/20100101 Firefox/134.0"
firefly_iii_core  | [2025-01-20 10:19:06] local.DEBUG: Now in Handler::render()  
firefly_iii_core  | [2025-01-20 10:19:06] local.DEBUG: Return JSON unauthenticated error.  
firefly_iii_core  | 172.19.0.2 - - [20/Jan/2025:10:19:06 -0500] "POST /api/v1/preferences HTTP/1.1" 401 940 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:134.0) Gecko/20100101 Firefox/134.0"
firefly_iii_core  | [2025-01-20 10:19:06] local.DEBUG: Now in Handler::render()  
firefly_iii_core  | [2025-01-20 10:19:06] local.DEBUG: Return JSON unauthenticated error.  
firefly_iii_core  | 172.19.0.2 - - [20/Jan/2025:10:19:06 -0500] "GET /api/v1/preferences/locale HTTP/1.1" 401 940 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:134.0) Gecko/20100101 Firefox/134.0"
firefly_iii_core  | [2025-01-20 10:19:06] local.DEBUG: Now in Handler::render()  
firefly_iii_core  | [2025-01-20 10:19:06] local.DEBUG: Return JSON unauthenticated error.  
firefly_iii_core  | 172.19.0.2 - - [20/Jan/2025:10:19:06 -0500] "GET /api/v1/preferences/viewRange HTTP/1.1" 401 940 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:134.0) Gecko/20100101 Firefox/134.0"
firefly_iii_core  | [2025-01-20 10:19:06] local.DEBUG: Now in Handler::render()  
firefly_iii_core  | [2025-01-20 10:19:06] local.DEBUG: Now in Handler::render()  
firefly_iii_core  | [2025-01-20 10:19:06] local.DEBUG: Return JSON unauthenticated error.  
firefly_iii_core  | [2025-01-20 10:19:06] local.DEBUG: Return JSON unauthenticated error.  
firefly_iii_core  | 172.19.0.2 - - [20/Jan/2025:10:19:06 -0500] "GET /api/v1/preferences/darkMode HTTP/1.1" 401 940 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:134.0) Gecko/20100101 Firefox/134.0"
firefly_iii_core  | 172.19.0.2 - - [20/Jan/2025:10:19:06 -0500] "GET /api/v1/preferences/language HTTP/1.1" 401 940 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:134.0) Gecko/20100101 Firefox/134.0"
firefly_iii_core  | [2025-01-20 10:19:06] local.DEBUG: Now in Handler::render()  
firefly_iii_core  | [2025-01-20 10:19:06] local.DEBUG: Return JSON unauthenticated error.  
firefly_iii_core  | 172.19.0.2 - - [20/Jan/2025:10:19:06 -0500] "POST /api/v1/preferences HTTP/1.1" 401 940 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:134.0) Gecko/20100101 Firefox/134.0"
firefly_iii_core  | [2025-01-20 10:19:06] local.DEBUG: Now in Handler::render()  
firefly_iii_core  | [2025-01-20 10:19:06] local.DEBUG: Return JSON unauthenticated error.  
firefly_iii_core  | [2025-01-20 10:19:06] local.DEBUG: Now in Handler::render()  
firefly_iii_core  | [2025-01-20 10:19:06] local.DEBUG: Return JSON unauthenticated error.  
firefly_iii_core  | 172.19.0.2 - - [20/Jan/2025:10:19:06 -0500] "POST /api/v1/preferences HTTP/1.1" 401 940 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:134.0) Gecko/20100101 Firefox/134.0"
firefly_iii_core  | 172.19.0.2 - - [20/Jan/2025:10:19:06 -0500] "POST /api/v1/preferences HTTP/1.1" 401 940 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:134.0) Gecko/20100101 Firefox/134.0"
firefly_iii_core  | [2025-01-20 10:19:06] local.DEBUG: Now in Handler::render()  
firefly_iii_core  | [2025-01-20 10:19:06] local.DEBUG: Return JSON unauthenticated error.  
firefly_iii_core  | 172.19.0.2 - - [20/Jan/2025:10:19:06 -0500] "POST /api/v1/preferences HTTP/1.1" 401 940 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:134.0) Gecko/20100101 Firefox/134.0"
firefly_iii_core  | 172.19.0.2 - - [20/Jan/2025:10:19:06 -0500] "GET /favicon.ico HTTP/1.1" 200 15317 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:134.0) Gecko/20100101 Firefox/134.0"
```

docker-compose.yml: 
```
services:
  app:
    image: fireflyiii/core:latest
    hostname: app
    container_name: firefly_iii_core
    restart: unless-stopped
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    networks:
      - firefly_iii
      - reverse-proxy
    depends_on:
      - db
    labels:
      - traefik.enable=true
      - traefik.http.routers.firefly-http.rule=Host(`firefly.fishstall.net`)
      - traefik.http.routers.firefly-http.entrypoints=web
      - traefik.http.routers.firefly-https.tls=true
      - traefik.http.routers.firefly-https.tls.certresolver=cloudflare
      - traefik.http.routers.firefly-https.entrypoints=websecure
      - traefik.http.routers.firefly-https.rule=Host(`firefly.fishstall.net`)
  db:
    image: mariadb:lts
    hostname: db
    container_name: firefly_iii_db
    restart: unless-stopped
    env_file: .db.env
    networks:
      - firefly_iii
    volumes:
      - firefly_iii_db:/var/lib/mysql
  cron:
    image: alpine
    restart: unless-stopped
    container_name: firefly_iii_cron
    command: sh -c "echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/HIDEN" | crontab - && crond -f -L /dev/stdout"
    networks:
      - firefly_iii

volumes:
   firefly_iii_upload:
   firefly_iii_db:

networks:
  firefly_iii:
    driver: bridge
  reverse-proxy:
    external: true
```

.env: 
```
TRUSTED_PROXIES=**
APP_URL=firefly.fishstall.net
```

Thank for the helps in advance.
