### DISCUSSION TITLE
How to upgrade DB version

### DISCUSSION THREAD

**Discussion by optimistic5** [firefly-iii/firefly-iii#9939] [Firefly III]
Hi.
I quite old user of firefly (by the way how to find first transaction?).
I have quite old DB.
Should I update PG version, how? Just latest version or some other way?
Should I migrate to MySQL? If yes - what the best way?
Please suggest.
Thank you.

```yml
--- 
networks:
  default:
    external:
      name: nginx-proxy
      
services:

  firefly_iii_app: 
    image: fireflyiii/core:version-6.2.9 
    restart: unless-stopped
    depends_on:
      - firefly_iii_db
    expose: 
      - 8080
    env_file: .env
    volumes: 
      - ./firefly_iii_export:/var/www/firefly-iii/storage/export
      - ./firefly_iii_upload:/var/www/firefly-iii/storage/upload
        
  firefly_iii_db: 
    image: "postgres:10"
    restart: unless-stopped
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=xx
      - POSTGRES_DB=xx
      - POSTGRES_USER=xx
    volumes: 
      - ./firefly_iii_db:/var/lib/postgresql/data
  
  firefly_iii_cron:
    image: alpine
    command: sh -c "echo \"0 3 * * * wget https://xxx/cron/run/6ec85141f454a2204e3d6cfe9e392658\" | crontab - && crond -f -L /dev/stdout"
version: "3.2"
```
