### DISCUSSION TITLE
There isn't a simple and quick way of backup and restore, so I wrote one.

### DISCUSSION THREAD

**Discussion by ddyykk** [firefly-iii/firefly-iii#9960] [General]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [x] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [x] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

- I have read the docs of this app, I use it for quite a long time, and I like it.
- I run it on my home server, a mini pc with Debian installed.
- I run it in docker containers.
- Sometimes I have power outage or SSD damage concern. (And I have encountered power cut, luckily the SSD wasn't broken)
- The backup methods in the docs is not straight forward enough to me. I think a good app like this should have a easier backup method.

### Solution

https://gist.github.com/ddyykk/84bc588d6de1d346fbf473af49c34cf0

- I wrote this one to backup everything in the docker containers, verify the password of MariaDB and the contents.
- Restore is also easy. Once finished installation using docker-compose in a new environment, run the restore script, providing the path of the backup tar.gz file. And it shall work like your old machine.

**Comment by JC5** [comment]
Hey, thanks for starting this discussion.

This is very cool! I'll link to it from the documentation for sure.

What you could do, is put the scripts up at https://gist.github.com/. This will allow people to reply to them, and you can edit them too.

Cheers,
James

**Reply by ddyykk** [reply]
Good idea, have updated the link in the post to gist.

Cheers.

**Reply by MrCaringi** [reply]
thanks a lot!

**Comment by madindehead** [comment]
I run Firefly III using a postgresql database. How easy would it be to create a postgresql version of this backup script? Or to add the steps into the current script with some conditional checks?

**Comment by ddyykk** [comment]
I don't use postgreSQL, so I can't test it. Anyway I asked ChatGPT to answer your question. Here is what it gives. Let me know it works or not.
[Restore-Firefly-PostgreSQL.sh](https://github.com/user-attachments/files/24688872/Restore-Firefly-PostgreSQL.sh)
[Backup-Firefly-PostgreSQL.sh](https://github.com/user-attachments/files/24688873/Backup-Firefly-PostgreSQL.sh)

**Reply by madindehead** [reply]
> I don't use postgreSQL, so I can't test it. Anyway I asked ChatGPT to answer your question. Here is what it gives. Let me know it works or not. [Restore-Firefly-PostgreSQL.sh](https://github.com/user-attachments/files/24688872/Restore-Firefly-PostgreSQL.sh) [Backup-Firefly-PostgreSQL.sh](https://github.com/user-attachments/files/24688873/Backup-Firefly-PostgreSQL.sh)

Thanks for this. Finally managed to get around to testing it. 

When I run the script, the verification section fails with the following message: `ERROR: Required table 'users' not found in database dump!`

I think it's because PostgresSQL can only run `CREATE TABLE` inside psql. This is likely going to require some changes to verify the backup properly.

pgdump can also be used for the export, so might be a different process overall.

**Comment by fbuetler** [comment]
For postgres, I'd recommend to use [docker-postgres-backup-local](https://github.com/prodrigestivill/docker-postgres-backup-local):

```yaml
  backups:
    image: prodrigestivill/postgres-backup-local:18
    restart: always
    user: postgres:postgres
    depends_on:
      - db 
    env_file: 
      - db.env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_EXTRA_OPTS=-Z1 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_DIR=/backups
      - BACKUP_ON_START=TRUE
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080
    networks:
      - firefly_iii
    volumes:
      - ./backups:/backups
```

For mysql, there is a similar project called [docker-mysql-cron-backup](https://github.com/fradelg/docker-mysql-cron-backup).
