### ISSUE TITLE
Portainer stack, firefly3 core not starting

### ISSUE THREAD

**Issue by EBS-DarkD** [firefly-iii/firefly-iii#10211]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [x] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I've attempted to deploy the portainer stack as per the instructions [here](https://docs.firefly-iii.org/how-to/firefly-iii/installation/portainer/)

### Debug information

Unable to get this far

### Expected behaviour

core container would start and I could proceed with the initial configuration

### Steps to reproduce

I have a complex portainer setup with multipe stacks already running so I tried to fit the various containers into a stack to work with my current (complex) setup and uploaded the edited stack.env. The core logs show the container starting and setting up the database then reaching the state below
```

              ______ _           __ _            _____ _____ _____  
             |  ____(_)         / _| |          |_   _|_   _|_   _| 
             | |__   _ _ __ ___| |_| |_   _       | |   | |   | |   
             |  __| | | '__/ _ \  _| | | | |      | |   | |   | |   
             | |    | | | |  __/ | | | |_| |     _| |_ _| |_ _| |_  
             |_|    |_|_|  \___|_| |_|\__, |    |_____|_____|_____| 
                                       __/ |                        
                                      |___/                         
+------------------------------------------------------------------------------+
|                                                                              |
| Thank you for installing Firefly III, v6.2.12!                               |
| There are no extra installation instructions.                                |
| Firefly III should be ready for use.                                         |
|                                                                              |
| Did you know you can support the development of Firefly III?                 |
| You can donate in many ways, like GitHub Sponsors or Patreon.                |
| For more information, please visit https://bit.ly/donate-to-Firefly-III      |
|                                                                              |
+------------------------------------------------------------------------------+
[26-Apr-2025 21:26:20] NOTICE: fpm is running, pid 391
[26-Apr-2025 21:26:20] NOTICE: ready to handle connections
```
The container is shown as starting and eventually switches to unhealthy. When I try access on the IP and port, I can't and there is nothing showing in any of the logs I can find within the container.

I did a clean stack exactly as per your example apart from the volumes which I set to a path on the host server and I had to change the port numbers

```
services:
  app:
    image: fireflyiii/core:latest
    hostname: app
    container_name: firefly_iii_core
    networks:
      - firefly_iii
    restart: always
    volumes:
      - /opt/docker/appdata/firefly3/data:/var/www/html/storage/upload
    env_file: stack.env
    ports:
      - '8111:8080'
    depends_on:
      - db
  db:
    image: mariadb:lts
    hostname: db
    container_name: firefly_iii_db
    networks:
      - firefly_iii
    restart: always
    env_file: stack.env
    volumes:
      - /opt/docker/appdata/firefly3/db:/var/lib/mysql

  importer:
    image: fireflyiii/data-importer:latest
    hostname: importer
    restart: always
    container_name: firefly_iii_importer
    networks:
      - firefly_iii
    ports:
      - '8112:8080'
    depends_on:
      - app
    env_file: stack.env
```

### Additional info

I'm at a loss as none of the logs are giving me any useful info. Anyone either let me know what I'm doing wrong or guide me on where to look for more info to resolve this?
