### ISSUE TITLE
DISABLE_FRAME_HEADER is ignored

### ISSUE THREAD

**Issue by Leah96xxx** [firefly-iii/firefly-iii#10310]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [x] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem
- [x] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I have set `DISABLE_FRAME_HEADER` to true, yet Firefly is ignoring it and returning the following error in the browser console:
```
The loading of “[my firefly url]” in a frame is denied by “X-Frame-Options“ directive set to “sameorigin“.
```

### Debug information

Debug information generated at 2025-05-17 20:19:22 for Firefly III version **v6.2.12**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.2.12 / <span>#</span>25 (expects <span>#</span>25)</td></tr><tr><td>PHP version</td><td>8.4.6 (64bits) / fpm-fcgi / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>104857600 (100 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/London + Europe/London</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver, session driver</td><td>file, file</td></tr><tr><td>Default language and locale</td><td>en_GB + equal</td></tr><tr><td>Trusted proxies</td><td><code>172.18.0.2</code></td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2025-05-16 23:00:00 (20 hours ago)</td></tr><tr><td>Mailer</td><td>smtp</td></tr><tr><td>Exchange rates</td><td>Disabled, downloads disabled</td></tr><tr><td>RB-column</td><td>Disabled</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has piggy banks">:pig:</span> <span title="Has rules">:wrench:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Native currency</td><td>GBP</td></tr><tr><td>Convert to native currency?</td><td>Disabled</td></tr><tr><td>Session start</td><td>2025-05-01 00:00:00</td></tr><tr><td>Session end</td><td>2025-05-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_GB</td></tr><tr><td>User locale</td><td>en_GB</td></tr><tr><td>Locale(s) supported</td><td>en_GB.utf8: :white_check_mark:<br>en_GB.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0</td></tr></tbody></table>

### Expected behaviour

Firefly loads in iframe without error

### Steps to reproduce

1. Run Firefly in Docker with `DISABLE_FRAME_HEADER` set to true
2. Try to embed Firefly and get that error

### Additional info

This was working previously. Nothing has changed at my end other than updating Firefly's container. Not sure which version has broke this as it's been a while since I used Firefly

**Comment by JC5** [comment]
Hey, thanks for opening an issue.

Nothing in the code has changed either. I can literally see the code doing what it is supposed to do. 

Can you tell me a bit more about your setup? Especially interesting is the fact that Firefly III does not set the header to "sameorigin", which implies some reverse proxy might. 

Cheers,
James

**Comment by Leah96xxx** [comment]
I am running Firefly through Traefik reverse proxy, however Traefik is not configured to set any headers. Below is the relevant sections of my docker-compose.yml for Firefly

``` yaml
services:
  app:
    image: fireflyiii/core:latest
    container_name: fireflyiii
    hostname: app
    networks:
      firefly_iii:
        ipv4_address: 172.25.0.200
      proxies_default:
    restart: always
    volumes:
      - [my upload path]:/var/www/html/storage/upload
    env_file: .env
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.firefly.rule=Host(`[my firefly URL]`)"
      - "traefik.http.routers.firefly.entrypoints=websecure"
      - "traefik.http.routers.firefly.service=firefly"
      - "traefik.http.services.firefly.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxies_default"
 
networks:
  firefly_iii:
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1
  proxies_default:
    external: true

```

The above config has worked for ages and hasn't been touched, so I'm not sure what has changed. All my other docker services work fine in iframes through Traefik and all have a basically identical config to the one above. Note that the only reason it uses 2 networks was to avoid IP conflicts on the external network, since the main container needs a static IP for the importer to work.

I have also ruled out the proxy being the issue by exposing port 8080 on the container and trying to embed that directly via the Docker host's IP. It resulted in the same error as above.
```
The loading of “http://[host IP]:8080/login” in a frame is denied by “X-Frame-Options“ directive set to “sameorigin“.
```

Below is a sanitised version of my .env file, minus comments to save space on here. Most of these are unchanged from default:
``` yaml
APP_ENV=local

APP_DEBUG=false

SITE_OWNER=[private email]

APP_KEY=[key]

DEFAULT_LANGUAGE=en_GB

DEFAULT_LOCALE=equal

TZ=Europe/London

TRUSTED_PROXIES=172.18.0.2
# this is Traefik's Docker IP

LOG_CHANNEL=stack

PAPERTRAIL_HOST=
PAPERTRAIL_PORT=

APP_LOG_LEVEL=notice

AUDIT_LOG_LEVEL=info

DB_CONNECTION=mysql
DB_HOST=db
DB_PORT=3306
DB_DATABASE=firefly
DB_USERNAME=firefly
DB_PASSWORD=[password]
DB_SOCKET=

MYSQL_USE_SSL=false
MYSQL_SSL_VERIFY_SERVER_CERT=true
MYSQL_SSL_CAPATH=/etc/ssl/certs/
MYSQL_SSL_CA=
MYSQL_SSL_CERT=
MYSQL_SSL_KEY=
MYSQL_SSL_CIPHER=

PGSQL_SSL_MODE=prefer
PGSQL_SSL_ROOT_CERT=null
PGSQL_SSL_CERT=null
PGSQL_SSL_KEY=null
PGSQL_SSL_CRL_FILE=null
PGSQL_SCHEMA=public

CACHE_DRIVER=file
SESSION_DRIVER=file

REDIS_SCHEME=tcp
REDIS_PATH=
REDIS_HOST=127.0.0.1
REDIS_PORT=6379
REDIS_USERNAME=
REDIS_PASSWORD=
REDIS_DB="0"
REDIS_CACHE_DB="1"

COOKIE_PATH="/"
COOKIE_DOMAIN=
COOKIE_SECURE=false
COOKIE_SAMESITE=lax

# redacted my mailer details

MAILGUN_DOMAIN=
MAILGUN_SECRET=

MAILGUN_ENDPOINT=api.mailgun.net

MANDRILL_SECRET=
SPARKPOST_SECRET=

SEND_ERROR_MESSAGE=true

SEND_REPORT_JOURNALS=true

ENABLE_EXTERNAL_MAP=false

ENABLE_EXTERNAL_RATES=false

MAP_DEFAULT_LAT=51.983333
MAP_DEFAULT_LONG=5.916667
MAP_DEFAULT_ZOOM=6

AUTHENTICATION_GUARD=web
AUTHENTICATION_GUARD_HEADER=REMOTE_USER
AUTHENTICATION_GUARD_EMAIL=

PASSPORT_PRIVATE_KEY=
PASSPORT_PUBLIC_KEY=

CUSTOM_LOGOUT_URL=

DISABLE_FRAME_HEADER=true

DISABLE_CSP_HEADER=false
# note: I have also tried setting this true but issue persists

TRACKER_SITE_ID=
TRACKER_URL=

ALLOW_WEBHOOKS=false

STATIC_CRON_TOKEN=[token]

DKR_BUILD_LOCALE=false
DKR_CHECK_SQLITE=true
DKR_RUN_MIGRATION=true
DKR_RUN_UPGRADE=true
DKR_RUN_VERIFY=true
DKR_RUN_REPORT=true
DKR_RUN_PASSPORT_INSTALL=true

APP_NAME=FireflyIII
BROADCAST_DRIVER=log
QUEUE_DRIVER=sync
CACHE_PREFIX=firefly
PUSHER_KEY=
IPINFO_TOKEN=
PUSHER_SECRET=
PUSHER_ID=
DEMO_USERNAME=
DEMO_PASSWORD=
IS_HEROKU=false
FIREFLY_III_LAYOUT=v1

APP_URL=http://localhost
# I left this alone because the .env comments asked me to so nicely
```

Also for reference, I'm using Organizr in Firefox on Windows (separate machine from my docker host) and have verified the issue also exists in Chromium.
