### ISSUE TITLE
Still see 4.6.3 after upgrade to 4.7.0

### ISSUE THREAD

**Issue by setevoy2** [firefly-iii/firefly-iii#1168]
After upgrading to 4.7.0 - Firefly III still displays 4.6.3 version used.

#### Description of my issue:

I have Firefly III running in Docker from my Docker Compose file:

```
version: '3.2'

services:
  firefly_iii_app_prod:
    image: jc5x/firefly-iii
    environment:
      - FF_DB_HOST=dbHost
      - FF_DB_NAME=firefly_iii_prod
      - FF_DB_USER=firefly_iii_prod
      - FF_DB_PASSWORD=dbPass
      - FF_APP_KEY=appKey
      - FF_APP_ENV=local
      - FF_APP_URL=http://money.domain.org.ua
      - APP_URL=http://money.domain.org.ua
      - TRUSTED_PROXIES=**
    ports:
      - "9090:80"
    volumes:
      - type: volume
        source: firefly_iii_prod_export
        target: /var/www/firefly-iii/storage/export
      - type: volume
        source: firefly_iii_prod_upload
        target: /var/www/firefly-iii/storage/upload
    restart:
      always

volumes:
  firefly_iii_prod_export:
  firefly_iii_prod_upload:
```

Behind NGINX as reverse proxy with SSL and with MariaDB database on a remote DB server.

#### Steps to reproduce 

1. Stop with `docker-compose stop`
2. Pull latest image with `docker-compose pull`
3. Started FF with `docker-compose start`
4. Executed commands as per [documentation](https://firefly-iii.readthedocs.io/en/latest/installation/upgrading.html#docker-hub-via-run-pull):
- `docker exec -it fireflyiii_firefly_iii_app_prod_1 php artisan migrate`
- `docker exec -it fireflyiii_firefly_iii_app_prod_1 php artisan firefly:upgrade-database`
- `docker exec -it fireflyiii_firefly_iii_app_prod_1 php artisan firefly:verify`

But in the bottom still see version 4.63.

On the Administration page after clicking "_Check for updates_" - I have the _"A new version is available. You are running v4.6.13, the latest version is v4.7.0 which was released on January 31, 2018._" message, but - I see the Russian language in Options, which was added (afaik) in 4.7.0.

> Please click the version number in the right corner of any Firefly III page to get debug information. 

This returns me the error:

> "Unfortunately, this error was not recoverable. Firefly III broke. The error is:
> file_get_contents(/var/www/firefly-iii/storage/logs/ff3-apache2handler-2018-02-08.log): failed to open stream: No such file or directory"

But log files are present in the container:

```
15:15:00 [root@ip-172-31-43-63 /opt/firefly-iii] # docker exec -ti fireflyiii_firefly_iii_app_prod_1 ls -l /var/www/firefly-iii/storage/logs/
total 20
-rw-r--r-- 1 www-data www-data 866 Feb  1 20:24 ff3-apache2handler-2018-02-01.log
-rw-r--r-- 1 www-data www-data  71 Feb  2 15:59 ff3-apache2handler-2018-02-02.log
-rw-r--r-- 1 www-data www-data  71 Feb  4 20:37 ff3-apache2handler-2018-02-04.log
-rw-r--r-- 1 www-data www-data  71 Feb  5 17:33 ff3-apache2handler-2018-02-05.log
-rw-r--r-- 1 www-data www-data 866 Feb  8 15:14 ff3-apache2handler-2018-02-08.log
```
