### ISSUE TITLE
Problems with custom port, maybe path is also ignored?

### ISSUE THREAD

**Issue by pacop** [firefly-iii/firefly-iii#1303]
I am running Firefly III version 4.7.1.4

#### Description of my issue:

Custom port is ignored at APP_URL. It also seems like the path is also ignored. 

#### Steps to reproduce 

My docker-compose.yml:
```
--- 
services: 
  firefly_iii_app: 
    environment: 
      - FF_DB_HOST=172.17.0.1
      - FF_DB_NAME=firefly_db
      - FF_DB_USER=firefly
      - FF_DB_PASSWORD=foobarfoo
      - FF_APP_KEY=random_key
      - FF_APP_ENV=local
      - APP_URL=https://mydomain:8080/firefly/
      - APP_FORCE_SSL=true
      - TRUSTED_PROXIES=**
      - APP_LOG_LEVEL=all
    image: jc5x/firefly-iii
    ports: 
      - "127.0.0.1:8082:80"
    volumes: 
      - /mnt/FIREFLY/export:/var/www/firefly_iii/storage/export
      - /mnt/FIREFLY/upload:/var/www/firefly_iii/storage/upload
version: "3.2"
```
It starts firefly at 127.0.0.1:8082, then my nginx acts as reverse proxy:

```
  location /firefly/ {
    add_header X-Forwarded-Proto "https";
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://localhost:8082/;
}

```

When I try to access to https://mydomain:8080/firefly, it renders the login but without css. Base in the HTML is set as:

```
<base href="https://mydomain/">
```

Thus, It also seems like is ignoring the path provided in APP_URL
