### ISSUE TITLE
Firefly III docker image for Raspberry Pi 3

### ISSUE THREAD

**Issue by SIGISLV** [firefly-iii/firefly-iii#1464]
Hi everyone,
thank you for that app it was axactly what I was seaching for.
I tried to install firefly III on a rapberry pi 3 with docker but my container died before working.
Is there anybody who can help me make it work ?

Also I couldn't be able to docker-compose the architecture.

It might not work on rpi3

**Comment by JC5** [comment]
Hi,

Thanks for the compliments!

The RP3 uses a different processor architecture, so the Docker image will not work by default. In order for Firefly III to work on a RP3 the whole Dockerfile needs to be rewritten. I'll put it on the list :).

**Comment by JC5** [comment]
I'll have to do some digging, I am not an expert either! I noticed the cron job doesn't work well either so plenty of tasks there :D.

**Comment by JC5** [comment]
Thanks for the information btw, I appreciate your digging around. :+1:

**Comment by dicastro** [comment]
Hi!

@JC5  I love FireflyIII!! This is exactly what I've been planning to do during several years. It seems you've read my mind. Its awesome!

Following what @ErikFontanel has said in his comment, I've achieved to have FireflyIII running on a Raspberry Pi 3 b+. This is what I've done:

## Changes in the __Dockerfile__

- I've changed the `FROM` by this `FROM arm32v7/php:7.2.8-apache-stretch`
- I've commented the following part:
```
# Install latest curl
#RUN cd /tmp && \
#    wget https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz && \
#    tar -xvf openssl-${OPENSSL_VERSION}.tar.gz && \
#    cd openssl-${OPENSSL_VERSION} && \
#    ./config && \
#    make && \
#    make install

#RUN cd /tmp && \
#    wget https://curl.haxx.se/download/curl-${CURL_VERSION}.tar.gz && \
#    tar -xvf curl-${CURL_VERSION}.tar.gz && \
#    cd curl-${CURL_VERSION} && \
#    ./configure --with-ssl && \
#    make && \
#    make install
```

This is the final _Dockerfile_:

```
# use PHP 7.1 and Apache as a base.
FROM arm32v7/php:7.2.8-apache-stretch

# set working dir
ENV FIREFLY_PATH /var/www/firefly-iii
ENV CURL_VERSION 7.60.0
ENV OPENSSL_VERSION 1.1.1-pre6
WORKDIR $FIREFLY_PATH
ADD . $FIREFLY_PATH

# install packages
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends libcurl4-openssl-dev \
                                               zlib1g-dev \
                                               libjpeg62-turbo-dev \
                                               wget \
                                               libpng-dev \
                                               libicu-dev \
                                               libedit-dev \
                                               libtidy-dev \
                                               libxml2-dev \
                                               libsqlite3-dev \
                                               libpq-dev \
                                               libbz2-dev \
                                               gettext-base \
                                               cron \
                                               locales && \
                                               apt-get clean && \
                                               rm -rf /var/lib/apt/lists/*

# Setup the Composer installer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install latest curl
#RUN cd /tmp && \
#    wget https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz && \
#    tar -xvf openssl-${OPENSSL_VERSION}.tar.gz && \
#    cd openssl-${OPENSSL_VERSION} && \
#    ./config && \
#    make && \
#    make install

#RUN cd /tmp && \
#    wget https://curl.haxx.se/download/curl-${CURL_VERSION}.tar.gz && \
#    tar -xvf curl-${CURL_VERSION}.tar.gz && \
#    cd curl-${CURL_VERSION} && \
#    ./configure --with-ssl && \
#    make && \
#    make install


# Create the log file to be able to run tail
RUN touch /var/log/cron.log

# Setup cron job
RUN (crontab -l ; echo "* * * * * root $FIREFLY_PATH/artisan schedule:run >> /var/log/cron.log") | crontab

# Install PHP exentions.
RUN docker-php-ext-install -j$(nproc) curl gd intl json readline tidy zip bcmath xml mbstring pdo_sqlite pdo_mysql bz2 pdo_pgsql

# Generate locales supported by Firefly III
RUN echo "en_US.UTF-8 UTF-8\nde_DE.UTF-8 UTF-8\nfr_FR.UTF-8 UTF-8\nit_IT.UTF-8 UTF-8\nnl_NL.UTF-8 UTF-8\npl_PL.UTF-8 UTF-8\npt_BR.UTF-8 UTF-8\nru_RU.UTF-8 UTF-8\ntr_TR.UTF-8 UTF-8\n\n" > /etc/locale.gen && locale-gen

# copy Apache config to correct spot.
COPY ./.deploy/docker/apache2.conf /etc/apache2/apache2.conf

# Enable apache mod rewrite..
RUN a2enmod rewrite

# Enable apache mod ssl..
RUN a2enmod ssl

# Create volumes for several directories:
VOLUME $FIREFLY_PATH/storage/export $FIREFLY_PATH/storage/upload

# Enable default site (Firefly III)
COPY ./.deploy/docker/apache-firefly.conf /etc/apache2/sites-available/000-default.conf

# Make sure we own Firefly III directory
RUN chown -R www-data:www-data /var/www && chmod -R 775 $FIREFLY_PATH/storage

# Run composer
RUN composer install --prefer-dist --no-dev --no-scripts --no-suggest

# Expose port 80
EXPOSE 80

# Run the command on container startup
CMD cron

# Run entrypoint thing
ENTRYPOINT [".deploy/docker/entrypoint.sh"]
```

## Changes in the `docker-compose.yml`

This is my `docker-compose.yml` file:

```
--- 
networks: 
  firefly_iii_net: 
    driver: bridge
services: 
  firefly_iii_app: 
    environment: 
      - FF_DB_HOST=firefly_iii_db
      - FF_DB_NAME=firefly_db
      - FF_DB_USER=firefly_db
      - FF_DB_PASSWORD=firefly_db_secret
      - FF_APP_KEY=S0m3R@nd0mStr1ngOf32Ch@rsEx@ctly
      - FF_APP_ENV=local
      - TZ=Europe/Madrid
    build:
      context: ./firefly_iii_app
    image: qopuir/firefly-iii:4.7.5.3
    links: 
      - firefly_iii_db
    networks: 
      - firefly_iii_net
    ports: 
      - "80:80"
    volumes: 
      - 
        source: firefly_iii_export
        target: /var/www/firefly-iii/storage/export
        type: volume
      - 
        source: firefly_iii_upload
        target: /var/www/firefly-iii/storage/upload
        type: volume
  firefly_iii_db: 
    environment: 
      - MYSQL_DATABASE=firefly_db
      - MYSQL_USER=firefly_db
      - MYSQL_PASSWORD=firefly_db_secret
      - MYSQL_ROOT_PASSWORD=firefly_root_secret
    image: "yobasystems/alpine-mariadb:arm32v7"
    networks: 
      - firefly_iii_net
    volumes: 
      - "firefly_iii_db:/var/lib/mysql"
version: "3.2"
volumes: 
  firefly_iii_db: ~
  firefly_iii_export: ~
  firefly_iii_upload: ~
```

## Multiarch docker images

In [this](https://blog.docker.com/2017/11/multi-arch-all-the-things/) article there is an introduction to multiarchitecture docker images.

It should be great to have FireflyIII in Docker Hub ready to run in RPI!!
