### ISSUE TITLE
docker-compose usage does not work

### ISSUE THREAD

**Issue by psistorm** [firefly-iii/firefly-iii#1500]
Trying to start Firefly via docker-compose results in an exception like the one below:

```
In ServiceProvider.php line 236:
                                                                                                                                                                      
  Cannot instantiate Twig extension 'TwigBridge\Extension\Laravel\Session': The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths.
```

I'm as well not sure if this is important but when starting up the first few lines are:

```
chown: cannot access '/var/www/firefly-iii/storage/cache': No such file or directory
chmod: cannot access '/var/www/firefly-iii/storage/cache': No such file or directory
```

**EDIT:** I can not open Firefly. It only shows a blank screen, but the log shows that I'm trying to access the page.

Debug enabled shows an error message when opening the URL:

![bildschirmfoto 2018-06-22 um 15 22 17](https://user-images.githubusercontent.com/401902/41778802-22da52a2-7630-11e8-9ab5-6d8c84ba44c8.png)

**Comment by JC5** [comment]
Mmmm, this is very strange!

The chown/chmod error is not related to this problem. What command did you use to launch the docker images?

A quick download of the docker-composer file and a launch seems to work just fine on my local machine.

Can you show me how you launch it?

**Comment by chrif** [comment]
I had the same problem, maybe for a different reason than @psistorm. 

I use bind mounts instead of volumes so I can easily manage/backup my data. I use only one bind mount for the `/storage` directory so it overwrites the directory structure in the image, therefore folders assumed to exist like the cache/session one are absent. 

My solution was to copy the directory structure at https://github.com/firefly-iii/firefly-iii/tree/master/storage in my storage folder when I bring up my project. I also had to specify the original export and upload volumes as bind mounts for this solution to work. Here is my final solution:

script to bring up
```
cp -R resources/storage var/
docker-compose -f docker-compose.yml up -d
```
docker-compose
```
version: "3.2"
services:
  firefly_iii_app:
    environment:
      - FF_DB_HOST=firefly_iii_db
      - FF_DB_NAME=firefly_db
      - FF_DB_USER=firefly_db
      - FF_DB_PASSWORD=$MYSQL_PASSWORD
      - FF_APP_KEY=$FF_APP_KEY
      - FF_APP_ENV=local
      - TZ=America/New_York
    image: jc5x/firefly-iii:release-4.7.4
    links:
      - firefly_iii_db
    networks:
      - firefly_iii_net
    ports:
      - "8888:80"
    volumes:
      - "$PWD/var/storage/export:/var/www/firefly-iii/storage/export"
      - "$PWD/var/storage/upload:/var/www/firefly-iii/storage/upload"
      - "$PWD/var/storage:/var/www/firefly-iii/storage"
  firefly_iii_db:
    environment:
      - MYSQL_DATABASE=firefly_db
      - MYSQL_USER=firefly_db
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    image: "mariadb:10.3"
    networks:
      - firefly_iii_net
    volumes:
      - "$PWD/var/mysql:/var/lib/mysql"
    ports:
      - "8889:3306"
networks:
  firefly_iii_net:
    driver: bridge
```

I guess a generic solution would be for the entrypoint to make sure the necessary folders are created in case someone does something like I did.
