### ISSUE TITLE
Can't run behind Traefik reverse proxy

### ISSUE THREAD

**Issue by saponace** [firefly-iii/firefly-iii#1853]
I am running Firefly III version v4.7.8 (latest jc5x/firefly-iii docker image)

**Description**
Hi,
I do not manage to make Firefly-iii work behind Traefik reverse proxy.
I use the latest version of Traefik too (v.1.7.4, latest official image from dockerhub).
I tried all the options I found either on github issues or the official firefly-iii documentation, and the traefik documentation :
* Firefly environment variables:
  * TRUSTED_PROXIES=** (as far as I understood, this one should be enough)
  * APP_FORCE_SSL=true (this one is supposed to be deprecated, but still tried, never know)
  * APP_FORCE_ROOT=https://firefly.mydomain.com (same: deprecated)
* Traefik labels:
  * traefik.frontend.headers.referrerPolicy=same-origin
  * traefik.frontend.auth.forward.trustForwardHeader=true

I tried every combination of these parameters, none works.
I am surprised I could not find any github issue or anything online about making Firefly-iii and Traefik work along. Frefly-iii is a quite big project and Traefik is getting more and more used these days ...

**Steps to reproduce** 
The docker-compose file I use is : 
```
version: "3"
networks:
  vpn_client_net:
  firefly_iii_net:
    driver: bridge
  default:
    driver: bridge
services:
  # Finances management
  firefly_iii_app:
    container_name: firefly_iii_app
    image: jc5x/firefly-iii
    links:
      - firefly_iii_db
    networks:
      - firefly_iii_net
    volumes:
      - /firefly-iii/export:/var/www/firefly-iii/storage/export
      - /firefly-iii/upload:/var/www/firefly-iii/storage/upload
    environment:
      - FF_DB_HOST=firefly_iii_db
      - FF_DB_NAME=firefly_db
      - FF_DB_USER=firefly_db
      - FF_DB_PASSWORD=firefly_db_secret
      - FF_APP_KEY=xxxxx
      - FF_APP_ENV=local
      - TZ="Europe/Paris"
      - APP_URL=https://firefly.mydomain.com
      - TRUSTED_PROXIES=**
      - APP_FORCE_SSL=true
      - APP_FORCE_ROOT=https://firefly.mydomain.com
    labels:
      - traefik.enable=true
      - traefik.backend=firefly
      - traefik.frontend.rule=Host:firefly.mydoiain.com
      - traefik.port=80
      - traefik.frontend.headers.referrerPolicy=strict-origin
      - traefik.frontend.auth.forward.trustForwardHeader=true
  # Firefly iii database
  firefly_iii_db:
    container_name: firefly_iii_db
    image: mariadb:latest
    networks:
      - firefly_iii_net
    volumes:
      - /firefly-iii/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=firefly_db
      - MYSQL_USER=firefly_db
      - MYSQL_PASSWORD=firefly_db_secret
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
  # Reverse proxy
  traefik:
    container_name: traefik
    image: traefik:latest
    restart: always
    networks:
   - default
      - vpn_client_net
    domainname: mydomain.com
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/data/traefik:/etc/traefik
    environment:
      - CLOUDFLARE_EMAIL=xxxx
      - CLOUDFLARE_API_KEY=xxxx
    labels:
      - traefik.enable=true
      - traefik.backend=traefik
      - traefik.frontend.rule=Host:traefik.mydomain.com
      - traefik.port=8080
```
My Traefik config file is as follow:
```
logLevel = "INFO" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC
defaultEntryPoints = ["http", "https"]


# Traefik web UI
[web]
address = ":8080"


[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
    useXForwardedFor = false
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
    useXForwardedFor = false


# Let's encrypt configuration
[acme]
email = "xxxxx"
storage="/etc/traefik/acme/acme.json"
entryPoint = "https"
acmeLogging=true
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
  [acme.dnsChallenge] # In order for this to work, SSL mode on provider DNS should be setto "full (strict)"
  provider = "cloudflare"
  delayBeforeCheck = 0

[[acme.domains]]
   main = "*.mydomain.com"


# Connection to docker host system (docker.sock)
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "mydomain.com"
watch = true
exposedbydefault = false # This will hide all docker containers that don't have explicitly set label to "enable"

```

I then do `docker-compose up -d`, there is no log complaining about anything, but all I get when going to https://firefly.mydomain.com is either a HTTP500, or a timeout (depending on the parameters combination.

The logs I get from Firefly-iii are:
```
firefly_iii_app    | Generating optimized autoload files
firefly_iii_app    | > Illuminate\Foundation\ComposerScripts::postAutoloadDump
firefly_iii_app    | Discovered Package: adldap2/adldap2-laravel
firefly_iii_app    | Discovered Package: danhunsaker/laravel-flysystem-others
firefly_iii_app    | Discovered Package: davejamesmiller/laravel-breadcrumbs
firefly_iii_app    | Discovered Package: fideloper/proxy
firefly_iii_app    | Discovered Package: laravel/passport
firefly_iii_app    | Discovered Package: laravelcollective/html
firefly_iii_app    | Discovered Package: nesbot/carbon
firefly_iii_app    | Discovered Package: pragmarx/google2fa-laravel
firefly_iii_app    | Discovered Package: rcrowe/twigbridge
firefly_iii_app    | Package manifest generated successfully.
firefly_iii_app    | +------------------------------------------------------------------------------+
firefly_iii_app    | |                                                                              |
firefly_iii_app    | | Thank you for installing Firefly III, v4.7.8!                                |
firefly_iii_app    | |                                                                              |
firefly_iii_app    | |                                                                              |
firefly_iii_app    | +------------------------------------------------------------------------------+
firefly_iii_app    | 2018-11-03 19:04:10,809 CRIT Supervisor running as root (no user in config file)
firefly_iii_app    | 2018-11-03 19:04:10,809 INFO Included extra file "/etc/supervisor/conf.d/cronjob.conf" during parsing
firefly_iii_app    | 2018-11-03 19:04:10,809 INFO Included extra file "/etc/supervisor/conf.d/firefly-iii.conf" during parsing
firefly_iii_app    | 2018-11-03 19:04:10,815 INFO RPC interface 'supervisor' initialized
firefly_iii_app    | 2018-11-03 19:04:10,815 CRIT Server 'unix_http_server' running without any HTTP authentication checking
firefly_iii_app    | 2018-11-03 19:04:10,815 INFO supervisord started with pid 1
firefly_iii_app    | 2018-11-03 19:04:11,817 INFO spawned: 'cron' with pid 49
firefly_iii_app    | 2018-11-03 19:04:11,818 INFO spawned: 'apache2' with pid 50
firefly_iii_app    | 2018-11-03 19:04:11,865 DEBG 'apache2' stderr output:
firefly_iii_app    | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using xxx.xxx.xxx.xxx. Set the 'ServerName' directive globally to suppress this message
firefly_iii_app    | 
firefly_iii_app    | 2018-11-03 19:04:11,879 DEBG 'apache2' stderr output:
firefly_iii_app    | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using xxx.xxx.xxx.xxx. Set the 'ServerName' directive globally to suppress this message
firefly_iii_app    | 
firefly_iii_app    | 2018-11-03 19:04:11,886 DEBG 'apache2' stderr output:
firefly_iii_app    | [Sat Nov 03 19:04:11.886672 2018] [mpm_prefork:notice] [pid 50] AH00163: Apache/2.4.25 (Debian) PHP/7.2.11 OpenSSL/1.0.2l configured -- resuming normal operations
firefly_iii_app    | [Sat Nov 03 19:04:11.886694 2018] [core:notice] [pid 50] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
firefly_iii_app    | 
firefly_iii_app    | 2018-11-03 19:04:12,888 INFO success: apache2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
firefly_iii_app    | 2018-11-03 19:04:21,899 INFO success: cron entered RUNNING state, process has stayed up for > than 10 seconds (startsecs)
```
The Traefik logs are : 
```
traefik            | time="2018-11-03T19:04:09Z" level=info msg="Using TOML configuration file /etc/traefik/traefik.toml"
traefik            | time="2018-11-03T19:04:09Z" level=warning msg="web provider configuration is deprecated, you should use these options : api, rest provider, ping and metrics"
traefik            | time="2018-11-03T19:04:09Z" level=info msg="Traefik version v1.7.4 built on 2018-10-30_10:44:30AM"
traefik            | time="2018-11-03T19:04:09Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/basics/#collected-data\n"
traefik            | time="2018-11-03T19:04:09Z" level=info msg="Account URI does not match the current CAServer. The account will be reset"
traefik            | time="2018-11-03T19:04:09Z" level=info msg="Preparing server https &{Address::443 TLS:0xc0002c3200 Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc0003bd720} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
traefik            | time="2018-11-03T19:04:09Z" level=info msg="Preparing server traefik &{Address::8080 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc0003bd740} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
traefik            | time="2018-11-03T19:04:09Z" level=info msg="Starting server on :443"
traefik            | time="2018-11-03T19:04:09Z" level=info msg="Preparing server http &{Address::80 TLS:<nil> Redirect:0xc0002ba580 Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc0003bd700} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
traefik            | time="2018-11-03T19:04:09Z" level=info msg="Starting server on :8080"
traefik            | time="2018-11-03T19:04:09Z" level=info msg="Starting provider configuration.ProviderAggregator {}"
traefik            | time="2018-11-03T19:04:09Z" level=info msg="Starting server on :80"
traefik            | time="2018-11-03T19:04:09Z" level=info msg="Starting provider *docker.Provider {\"Watch\":true,\"Filename\":\"\",\"Constraints\":null,\"Trace\":false,\"TemplateVersion\":2,\"DebugLogGeneratedTemplate\":false,\"Endpoint\":\"unix:///var/run/docker.sock\",\"Domain\":\"mydomain.com\",\"TLS\":null,\"ExposedByDefault\":false,\"UseBindPortIP\":false,\"SwarmMode\":false,\"Network\":\"\"}"
traefik            | time="2018-11-03T19:04:09Z" level=info msg="Starting provider *acme.Provider {\"Email\":\"xxxxx\",\"ACMELogging\":true,\"CAServer\":\"https://acme-staging-v02.api.letsencrypt.org/directory\",\"Storage\":\"/etc/traefik/acme/acme.json\",\"EntryPoint\":\"https\",\"KeyType\":\"\",\"OnHostRule\":false,\"OnDemand\":false,\"DNSChallenge\":{\"Provider\":\"cloudflare\",\"DelayBeforeCheck\":0,\"Resolvers\":null,\"DisablePropagationCheck\":false},\"HTTPChallenge\":null,\"TLSChallenge\":null,\"Domains\":[{\"Main\":\"*.mydomain.com\",\"SANs\":null}],\"Store\":{}}"
traefik            | time="2018-11-03T19:04:09Z" level=info msg="Testing certificate renew..."
traefik            | time="2018-11-03T19:04:09Z" level=info msg="Server configuration reloaded on :80"
traefik            | time="2018-11-03T19:04:09Z" level=info msg="Server configuration reloaded on :443"
traefik            | time="2018-11-03T19:04:09Z" level=info msg="Server configuration reloaded on :8080"
traefik            | time="2018-11-03T19:04:09Z" level=info msg="Server configuration reloaded on :80"
traefik            | time="2018-11-03T19:04:09Z" level=info msg="Server configuration reloaded on :443"
traefik            | time="2018-11-03T19:04:09Z" level=info msg="Server configuration reloaded on :8080"
traefik            | time="2018-11-03T19:04:11Z" level=info msg="Server configuration reloaded on :443"
traefik            | time="2018-11-03T19:04:11Z" level=info msg="Server configuration reloaded on :8080"
traefik            | time="2018-11-03T19:04:11Z" level=info msg="Server configuration reloaded on :80"
```
And nothing appears when I try to reach firefly.mydomain.com

Firefly-iii works as expected when running from this docker-compose.yml, but without reverse proxy.

**Extra info**
Obviously, the /debug page returns a HTTP500

Anyway tank you very much for this software. Basically what I've been loking for for ages.

**Comment by JC5** [comment]
The 500 error is what we should focus on first. It obviously works, it's just erroring out.

Did you run the installation commands after deploying the docker compose thing?

```
docker-compose exec firefly_iii_app php artisan migrate --seed
docker-compose exec firefly_iii_app php artisan firefly:upgrade-database
docker-compose exec firefly_iii_app php artisan firefly:verify
docker-compose exec firefly_iii_app php artisan passport:install
```

**Comment by saponace** [comment]
Yes, I did.
No error came up

**Comment by JC5** [comment]
OK. Then let's focus on the 500. If you can [enable debug mode](https://github.com/firefly-iii/help/wiki/Enable-debug-logging-and-debug-mode) you should get some more info as to where the 500 is coming from.

**Comment by saponace** [comment]
I enabled debug mode, but nothing changes in Firefly-iii logs (docker logs are the same, /var/www/firefly-iii/storage/logs in the container is empty, except .gitignore).
It seems like the HTTP500 comes from Traefik and not Firefly-iii (The HTTP request seems to not even reach Firefly-iii), but I am surprised the error comes from Traefik since the configuration is the same as all my other containers ....

**Comment by JC5** [comment]
Keep me posted. I am curious to hear what is going wrong.

**Comment by pkoziol** [comment]
Both continers (`firefly_iii_app` and `traefik`) should be in the same network to be able to communicate with each other. I'm guessing that this is a problem.

If you have one `docker-compose.yml` file like pasted then just add one of the containers to common network.

If you (want to) have multiple `docker-compose.yml` files, then declare external network like like me:

File `.../traefik/docker-compose.yml` (so all containers, volumes and networks will have `traefik_` prefix):
```
version: '3'

services:
  proxy:
    image: traefik:1.5-alpine
    networks:
      - web
    ...

networks:
  web:
    driver: bridge
```

File `.../firefly/docker-compose.yml`:
```
version: '3.2'

networks:
  web:
    external:
      name: traefik_web # full name of the network - with prefix (directory name) and name from .yml file

services:
  app:
    image: jc5x/firefly-iii:release-4.7.5.3
    networks:
      - web
    ...
```
