### ISSUE TITLE
Is APP_URL enough to address the firefly-iii in a different folder?

### ISSUE THREAD

**Issue by Odyno** [firefly-iii/firefly-iii#1869]
Hello, 
I'm working with the master version firefly-iii but rebuilt on my raspberry (you can see my branch here https://github.com/Odyno/firefly-iii/tree/rpi-docker  and the docker image here https://hub.docker.com/r/odyno/rpi-firefly-iii/ ).

I'm running the docker image in a compose like that (some variable is removed ;)
```
networks:
  firefly_iii_net:
    driver: bridge
services:
  firefly_iii_app:
    environment:
      - APP_DEBUG=false
      - APP_URL=/finance/
      - TRUSTED_PROXIES=**
      - FF_DB_HOST=...
      - FF_DB_NAME=....
      - FF_DB_USER=...
      - FF_DB_PASSWORD=....
      - FF_APP_KEY=.....
      - FF_APP_ENV=local
      - TZ=Europe/Rome
      - SITE_OWNER=.....
      - MAIL_DRIVER=....
      - MAIL_HOST=....
      - MAIL_PORT=...
      - MAIL_FROM=...
      - MAIL_USERNAME=....
      - MAIL_PASSWORD=...
      - MAIL_ENCRYPTION=...
      - MAPBOX_API_KEY=...
      - FIXER_API_KEY=....

    image: odyno/rpi-firefly-iii:0.0.1
    restart: always
    links:
      - firefly_iii_db
    networks:
      - firefly_iii_net
    ports:
      - "9080:80"
    volumes:
      - "/media/srv/firefly_iii_workspace/export:/var/www/firefly-iii/storage/export"
      - "/media/srv/firefly_iii_workspace/upload:/var/www/firefly-iii/storage/upload"
  firefly_iii_db:
    environment:
      - MYSQL_DATABASE=....
      - MYSQL_USER=...
      - MYSQL_PASSWORD=....
      - MYSQL_ROOT_PASSWORD=....
    image: yobasystems/alpine-mariadb:arm32v7
    restart: always
    networks:
      - firefly_iii_net
    volumes:
      - "/media/srv/firefly_iii/db:/var/lib/mysql"
version: "3.2"
```

and finally I'm exposing the service via Nginx proxy_pass behind the /finance/ route:  

```
  location /finance/ {

        proxy_pass              http://127.0.0.1:9080/;
        proxy_redirect          http://127.0.0.1:9080/ /finance/;
        proxy_pass_header       Server;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Scheme $scheme;
        proxy_set_header        Host $http_host;
        proxy_set_header        X-NginX-Proxy true;
        proxy_connect_timeout   5;
        proxy_read_timeout      240;
        proxy_intercept_errors  on;


    }
```

What I'm trying to do is: load firefly on docker ( so http://localhost:9080/ ) and provide this service on public  endpoint https://public.host/finance/

whats happened is that:
-> https://public.host/finance   ---> https://public.host/login

In addition to the variable **APP_URL** do I need to add anything else?
