### ISSUE TITLE
Custom paths?

### ISSUE THREAD

**Issue by dbelz** [firefly-iii/firefly-iii#2111]
Hey, I'm using the official docker compose file and would like to use custom paths for the volumes. But everytime I get volume must be a mapping not a string.

It looks like this:
```
--- 
networks: 
  firefly_iii_net: 
    driver: bridge
services: 
  firefly_iii_app: 
    environment: 
      - FF_DB_HOST=firefly_iii_db
      - FF_DB_NAME=firefly
      - FF_DB_USER=firefly
      - FF_DB_PASSWORD=firefly
      - FF_APP_KEY=eUgeHK7PgH3cGeZE9LEJEa8VRTjdLY9m
      - FF_APP_ENV=local
      - FF_DB_CONNECTION=pgsql
      - TZ=Europe/Amsterdam
      - APP_LOG_LEVEL=debug
    image: jc5x/firefly-iii
    links: 
      - firefly_iii_db
    networks: 
      - firefly_iii_net
    ports: 
      - "80:80"
    volumes: 
      - 
        source: firefly_iii_export
        target: /mnt/sdc1/docker/firefly/storage/export
        type: volume
      - 
        source: firefly_iii_upload
        target: /mnt/sdc1/docker/firefly/storage/upload
        type: volume
  firefly_iii_db: 
    environment: 
      - POSTGRES_PASSWORD=firefly
      - POSTGRES_USER=firefly
    image: "postgres:10"
    networks: 
      - firefly_iii_net
    volumes: 
      - "/mnt/sdc1/docker/firefly/postgressql/data:/var/lib/postgresql/data"
version: "3.2"
volumes: 
  firefly_iii_db: ~
  firefly_iii_export: ~
  firefly_iii_upload: ~
```

**Comment by JC5** [comment]
You're mixing up the volumes inside the docker image, and the location of those volumes on your own drive.

Inside the container you can't change the location of those folders. That's up to the application, you can't change that.

If you want to store the data on your host machine somewhere else you must change your Docker configuration.

**Comment by dbelz** [comment]
Can't I somehow do it like this:
volumes: 
      - "firefly_iii_db:/var/lib/postgresql/data"

I mean if I replace firefly_iii_db with my path this works. Why can't I also specify paths for the other things? Sorry to ask all this questions^^

**Comment by JC5** [comment]
So there are three references to volumes in the docker-compose file: `firefly_iii_export`, `firefly_iii_upload` and `firefly_iii_db`. They point to places **inside** the Docker containers. You cannot change to where they point to. This path for example: `/var/lib/postgresql/data` is fixed and cannot be changed. Even if you change it, your container will either break or refuse to run.

On the side of your host machine (where you run and control all containers) the `firefly_iii_db` paths *also* have a reference. Usually, this is something like `/opt/docker/volumes/firefly_iii_db` or something similar.

Now, if you want to change the `/opt/docker/...` path, you must update your Docker configuration, restart Docker and recreate the Docker containers.

**Comment by dbelz** [comment]
Thanks for your time. Will try to do this. You can close this ticket, I have no further questions :)

**Comment by dbelz** [comment]
This works somehow:

```
--- 
networks: 
  firefly_iii_net: 
    driver: bridge
services: 
  firefly_iii_app: 
    environment: 
      - FF_DB_HOST=firefly_iii_db
      - FF_DB_NAME=firefly
      - FF_DB_USER=firefly
      - FF_DB_PASSWORD=firefly
      - FF_APP_KEY=S0m3R@nd0mStr1ngOf32Ch@rsEx@ctly
      - FF_APP_ENV=local
      - FF_DB_CONNECTION=pgsql
      - TZ=Europe/Amsterdam
      - APP_LOG_LEVEL=debug
    image: jc5x/firefly-iii
    links: 
      - firefly_iii_db
    networks: 
      - firefly_iii_net
    ports: 
      - "80:80"
    volumes: 
      - /mnt/sdc1/docker/firefly/storage/export:/var/www/firefly-iii/storage/export
      - /mnt/sdc1/docker/firefly/storage/upload:/var/www/firefly-iii/storage/upload
  firefly_iii_db: 
    environment: 
      - POSTGRES_PASSWORD=firefly
      - POSTGRES_USER=firefly
    image: "postgres:10"
    networks: 
      - firefly_iii_net
    volumes: 
      - "/mnt/sdc1/docker/firefly/postgres/data:/var/lib/postgresql/data"
version: "3.2"
```
