### ISSUE TITLE
docker-compose: cannot connect to database

### ISSUE THREAD

**Issue by nkay08** [firefly-iii/firefly-iii#2122]
I am trying to build and run a docker container with firefly.
However, I run into problems with the firefly container not being able to connect to the database in the other container.
This is my docker-compose.yml:
```
version: '2'
services:
  
#  db:
#    image: mariadb
#    container_name:firefly-db
#    restart: unless-stopped
#    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
#    volumes:
#      - db:/var/lib/mysql
#      - /etc/localtime:/etc/localtime:ro
#    networks:
#      - ff-net
#    environment:
#      - MYSQL_ROOT_PASSWORD=${DB_PASS}
#      - MYSQL_PASSWORD=${DB_PASS}
#      - MYSQL_DATABASE=${DB_NAME}
#      - MYSQL_USER=${DB_USER}

  db:
    image: "postgres:10"
    container_name: nkay.info-firefly-db
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql
      - /etc/localtime:/etc/localtime:ro
    networks:
      - ff-net
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}

  firefly_app:
    image: jc5x/firefly-iii
    container_name: firefly
    depends_on:
      - db
    networks:
      - ff-net
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - export:/var/www/firefly-iii/storage/export
      - upload:/var/www/firefly-iii/storage/upload
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - FF_DB_HOST=db
      - FF_DB_NAME=${DB_NAME}
      - FF_DB_USER=${DB_USER}
      - FF_DB_PASSWORD=${DB_PASS}
      - FF_DB_CONNECTION=pgsql
#      - FF_DB_PORT=5432
      - TZ=Europe/Berlin
      - FF_APP_KEY=${FF_APP_KEY}
      - APP_URL=${VIRTUAL_HOST}  
      - ServerName=${VIRTUAL_HOST}
      - FF_APP_ENV=local
      - APP_LOG_LEVEL=debug
volumes:
  db:
  export:
  upload:

networks:
  ff-net:
    driver: bridge
  proxy:
    external:
name: <external_network>
```
I run a nginx-proxy container on the external network, which works quite well for my other containers.
When I `docker-compose up`  I see the following notable errors:

```
...
xxxx | Run various artisan commands...
xxxx | [2019-02-24 23:15:42] local.ERROR: SQLSTATE[08006] [7] could not connect to server: Connection refused
xxxx | 	Is the server running on host "db" (172.24.0.2) and accepting
xxxx | 	TCP/IP connections on port 5432? (SQL: select * from information_schema.tables where table_schema = public and table_name = migrations) 
...
#20 /var/www/firefly-iii/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
xxxx | #21 {main}
xxxx  | "} 
xxxx  | 
xxxx  | In Connection.php line 664:
xxxx  |                                                                                
xxxx  |   SQLSTATE[08006] [7] could not connect to server: Connection refused          
xxxx  |   	Is the server running on host "db" (172.24.0.2) and accepting               
xxxx  |   	TCP/IP connections on port 5432? (SQL: select * from information_schema.ta  
xxxx  |   bles where table_schema = public and table_name = migrations)                
xxxx  |                                                                                
xxxx  | 
xxxx  | In PDOConnection.php line 31:
xxxx  |                                                                        
xxxx  |   SQLSTATE[08006] [7] could not connect to server: Connection refused  
xxxx  |   	Is the server running on host "db" (172.24.0.2) and accepting       
xxxx  |   	TCP/IP connections on port 5432?
...
...
xxxx   | In Connection.php line 664:
xxxx   |                                                                                
xxxx   |   SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "oauth_clients" does n  
xxxx   |   ot exist                                                                     
xxxx   |   LINE 1: insert into "oauth_clients" ("user_id", "name", "secret", "r...      
xxxx   |                       ^ (SQL: insert into "oauth_clients" ("user_id", "name",  
xxxx   |    "secret", "redirect", "personal_access_client", "password_client", "revoke  
xxxx   |   d", "updated_at", "created_at") values (, FireflyIII Personal Access Client  
xxxx   |   , asdasdfdsfsdfsdfsdfsdfsdfsdfsds, http://localhost, 1, 0, 0, 2019  
xxxx   |   -02-24 23:15:44, 2019-02-24 23:15:44) returning "id")           
....           
```
And similar repeating errors.
When I shut the containers down and restart them there seem to be no connection problems and some migrations are performed seemingly successfully.
I tried to access the web UI then and it shows me 
```
Firefly III
installation and upgrade
Please wait...
Migration failed! See log files :(
```
I checked `storage/logs`, in the container, but there are no logs. 
I have no idea how to fix these errors.
I tried it with postgres and mariadb.
I even tested the exact sample docker-compose.yml (minus the exposed ports, plus the virtual host) with the same or similar problems.

The containers are running on a VPS with Linux version 4.15.0-45-generic, Ubuntu 18.04.2 LTS

Thanks in advance.
