### ISSUE TITLE
Docker install fails on ASUS TinkerBoard

### ISSUE THREAD

**Issue by Paul-dH** [firefly-iii/firefly-iii#2141]
**Bug description**
I'm trying to install Firefly 4.7.15 (latest tag) trough docker-compose on a Asus TinkerBoard (SSD) and I receive the following error:
```
user@hassio:~/firefly$ docker-compose -f docker-compose.yml up -d
Pulling firefly_iii_app (jc5x/firefly-iii:)...
latest: Pulling from jc5x/firefly-iii
e07de503944f: Pull complete
67d2a0c1d131: Pull complete
271d58948a13: Pull complete
34f3a80a747e: Pull complete
1c221881787f: Pull complete
2df8f21ec4a6: Pull complete
c93a133ff301: Pull complete
b16498caf1d0: Pull complete
805fc306963c: Pull complete
04c8c0e035b9: Pull complete
af8073bdc847: Pull complete
30cbb9113567: Pull complete
4421dcbdee66: Pull complete
5c07605bc556: Pull complete
ccb8e11913df: Pull complete
4073171392bd: Pull complete
bdf71d794c9a: Pull complete
7376b77dd043: Pull complete
df6aadf62f56: Pull complete
c7e92c05a2aa: Pull complete
24020badb2b8: Pull complete
82b9b1266484: Extracting [==================================================>]  54.49MB/54.49MB
ERROR: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: unexpected EOF
```
The Postgress container is build successfully, it looks likt the storage on the TinkerBoard is not really supported I guess? When I searched Google for the error message I found some results saying this (https://github.com/moby/moby/issues/34817)

I've run below composefile on a ASUS TinkerBoard with TinkerOs (debian)
```
networks:
  firefly_iii_net:
    driver: bridge
services:
  firefly_iii_app:
    environment:
      - FF_DB_HOST=firefly_iii_db
      - FF_DB_NAME=firefly
      - FF_DB_USER=REDACTED
      - FF_DB_PASSWORD=REDACTED
      - FF_APP_KEY=REDACTED
      - FF_APP_ENV=local
      - FF_DB_CONNECTION=pgsql
      - TZ=Europe/Amsterdam
      - APP_LOG_LEVEL=debug
    image: jc5x/firefly-iii
    links:
      - firefly_iii_db
    networks:
      - firefly_iii_net
    ports:
      - "8003:80"
    volumes:
      -
        source: firefly_iii_export
        target: /var/www/firefly-iii/storage/export
        type: volume
      -
        source: firefly_iii_upload
        target: /var/www/firefly-iii/storage/upload
        type: volume
  firefly_iii_db:
    environment:
      - POSTGRES_PASSWORD=REDACTED
      - POSTGRES_USER=REDACTED
    image: "postgres:10"
    networks:
      - firefly_iii_net
    volumes:
      - "firefly_iii_db:/var/lib/postgresql/data"
version: "3.2"
volumes:
  firefly_iii_db: ~
  firefly_iii_export: ~
  firefly_iii_upload: ~
```

Thanks in advance for any help! Hope to get this fixed, looks like a great solutionin a container :)
