### ISSUE TITLE
invalid env file

### ISSUE THREAD

**Issue by mplemay** [firefly-iii/firefly-iii#2156]
I am running Firefly III version 4.7.15

**Description**
Pardon my ignorance, but I am new user of firefly. Recently I tried creating a docker container using first a modified .env file and then the example .env file (I used curl to download the file from github so there wouldn't be any issues resulting from copying the file). Each time I try to start the container using docker compose, I get the following error:
```

firefly_iii_app    | Discover packages...
firefly_iii_app    | The environment file is invalid: Dotenv values containing spaces must be surrounded by quotes.Run various artisan commands...

```
Most likely it is an error resulting from my own mistake, but your input on how to go forward would be greatly appreciated. Thanks in advance.

**Extra info**
```
firefly_iii_app    | Now in entrypoint.sh for Firefly III
firefly_iii_app    | Architecture:          x86_64
firefly_iii_app    | CPU op-mode(s):        32-bit, 64-bit
firefly_iii_app    | Byte Order:            Little Endian
firefly_iii_app    | CPU(s):                1
firefly_iii_app    | On-line CPU(s) list:   0
firefly_iii_app    | Thread(s) per core:    1
firefly_iii_app    | Core(s) per socket:    1
firefly_iii_app    | Socket(s):             1
firefly_iii_app    | NUMA node(s):          1
firefly_iii_app    | Vendor ID:             GenuineIntel
firefly_iii_app    | CPU family:            6
firefly_iii_app    | Model:                 85
firefly_iii_app    | Model name:            Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz
firefly_iii_app    | Stepping:              4
firefly_iii_app    | CPU MHz:               2294.608
firefly_iii_app    | BogoMIPS:              4589.21
firefly_iii_app    | Virtualization:        VT-x
firefly_iii_app    | Hypervisor vendor:     KVM
firefly_iii_app    | Virtualization type:   full
firefly_iii_app    | L1d cache:             32K
firefly_iii_app    | L1i cache:             32K
firefly_iii_app    | L2 cache:              1024K
firefly_iii_app    | L3 cache:              25344K
firefly_iii_app    | NUMA node0 CPU(s):     0
firefly_iii_app    | Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl cpuid pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves pku ospke


```

**Bonus points**

**Comment by JC5** [comment]
As per the error you're getting, one of the `-e VALUE=abc` parameters you're using has a space in it. Can you share your full docker run command?

Generally speaking there is no need to edit your .env file yourself.

**Comment by mplemay** [comment]
Hello, @JC5. Here is the docker-compose.yml file I am using. Would you recommend that I simply switch to setting the few environment variables I need in the compose file and omitting the env?

```
version: "3.4"
services:
  nginx:
      links:
        - firefly_iii_app
      networks:
        - firefly_iii_net
      container_name: nginx
      image: nginx:latest
      volumes:
        - '/home/docker_host_user/docker_configs/nginx.conf:/etc/nginx/nginx.conf:ro'
        - '/home/docker_host_user/.certbot/config/live/example.com/fullchain.pem:/https-cert.pem:ro'
        - '/home/docker_host_user/.certbot/config/live/example.com/privkey.pem:/https-key.pem:ro'
      ports:
        - '80:80'
        - '443:443'
      restart: unless-stopped
  firefly_iii_app: 
    container_name: firefly_iii_app
    env_file: .env
    image: jc5x/firefly-iii
    links: 
      - firefly_iii_db
    networks: 
      - firefly_iii_net
    volumes: 
      - 
        source: firefly_iii_export
        target: /var/www/firefly-iii/storage/export
        type: volume
      - 
        source: firefly_iii_upload
        target: /var/www/firefly-iii/storage/upload
        type: volume
  firefly_iii_db: 
    container_name: firefly_iii_db
    environment: 
      - POSTGRES_PASSWORD=homestead
      - POSTGRES_USER=secret
    image: "postgres:10"
    networks: 
      - firefly_iii_net
    volumes: 
      - "firefly_iii_db:/var/lib/postgresql/data"
networks: 
  firefly_iii_net: 
    driver: bridge
volumes: 
  firefly_iii_db: ~
  firefly_iii_export: ~
  firefly_iii_upload: ~

```
