### ISSUE TITLE
Add cron to the docker image for recurring transactions

### ISSUE THREAD

**Issue by WatskeBart** [firefly-iii/firefly-iii#2170]
**Description**
- The addition of cron and a text editor.

**Solution**
- Add packages cron and nano to the apt install part in the dockerfile(s)

**What are alternatives?**
- Web-based GUI implementation for the docker variant of Firefly

**Comment by JC5** [comment]
I removed it on purpose. I’m thinking off another solution. It won’t be added to the container.

**Comment by WatskeBart** [comment]
Thank you for your reply, I will patiently wait for your solution. Right now I installed nano and cron inside my container.

**Comment by JC5** [comment]
Is it working without supervisor? Because you can only run one process.

**Comment by WatskeBart** [comment]
You are absolutely right, it isn't working. I added the cronjob, but didn't check if it worked.
I guess I'll wait for your solution.

**Comment by wangongtsen** [comment]
There is a way to make this kind of work:
* install cron and an editor of your choice
* find php: `which php` (it's in /usr/local/bin/php for the docker container)
* edit your crontab and add `0 3 * * * /usr/local/bin/php /var/www/firefly-iii/artisan firefly:cron`
* start cron daemon: `service cron start`

**But** you have to do this after every update and make sure cron is running after every restart of the container. That's why I changed to using cron on the host with
`0 3 * * * docker exec firefly_iii_app /usr/local/bin/php /var/www/firefly-iii/artisan firefly:cron`

**Comment by skuzzle** [comment]
Also, take a look at #2057 regarding this topic. It also mentionend a way to add another docker container running the cron job. Might be a little bit cleaner than running the cron job directly on the host.

**Comment by WatskeBart** [comment]
> There is a way to make this kind of work:
> 
> * install cron and an editor of your choice
> * find php: `which php` (it's in /usr/local/bin/php for the docker container)
> * edit your crontab and add `0 3 * * * /usr/local/bin/php /var/www/firefly-iii/artisan firefly:cron`
> * start cron daemon: `service cron start`
> 
> **But** you have to do this after every update and make sure cron is running after every restart of the container. That's why I changed to using cron on the host with
> `0 3 * * * docker exec firefly_iii_app /usr/local/bin/php /var/www/firefly-iii/artisan firefly:cron`

I chose this option, because of the quickest implementation.

> Also, take a look at #2057 regarding this topic. It also mentionend a way to add another docker container running the cron job. Might be a little bit cleaner than running the cron job directly on the host.

Thanks for this suggestion btw

**Comment by vitobotta** [comment]
Hi, what is the "official" way of enabling cron? At the moment I am using this command in cron on the host

```
docker exec -it firefly php /var/www/firefly-iii/artisan firefly:cron
```

Is this OK? It seems to work :)

**Comment by JC5** [comment]
That should work just fine. There is no official way yet.

**Comment by marcelbrueckner** [comment]
Although it's closed, I want to share my approach. As I'm using Docker Compose, I've simply added [mcuadros/ofelia](https://github.com/mcuadros/ofelia) (the repository is currently unmaintained, but there are [efforts](https://github.com/mcuadros/ofelia/issues/66) to get a new maintainer) to my `docker-compose.yml`:

```yaml
version: "3.7"
networks: 
  firefly_iii_net: 
    driver: bridge
services:

  # Your Firefly III app and database service definition goes here,
  # see https://github.com/firefly-iii/firefly-iii/blob/master/docker-compose.yml

  ofelia:
    # Ofelia is a modern and low footprint job scheduler for docker environments, built on Go. 
    # https://github.com/mcuadros/ofelia
    image: mcuadros/ofelia:latest
    depends_on:
      - firefly_iii_app
    networks: 
      - firefly_iii_net
    volumes:
      # https://docs.docker.com/compose/compose-file/#long-syntax-3
      # The configuration file for Ofelia
      - source: host/path/to/ofelia-config.ini
        target: /etc/ofelia/config.ini
        type: bind
      # Bind Docker socket to be able to 'docker exec' commands
      - source: /var/run/docker.sock
        target: /var/run/docker.sock
        type: bind
      # Mount log directory
      - source: host/path/to/ofelia-logs
        target: /tmp/logs
        type: bind
```

`host/path/to/ofelia-config.ini` contains the following:

```ini
[global]
save-folder = /tmp/logs
save-only-on-error = false

[job-exec "firefly-iii-cron"]
schedule = @daily
container = firefly_iii_app_1
command = /usr/local/bin/php /var/www/firefly-iii/artisan firefly:cron
```

To get your Firefly III container name, use `docker container list`:
```bash
CONTAINER ID        IMAGE                             NAMES
2f5bbac3380f        jc5x/firefly-iii:release-4.7.17   firefly_iii_app_1
```

Your container name may slightly differ, depending on your what Docker Compose calls the [`COMPOSE_PROJECT_NAME`](https://docs.docker.com/compose/reference/envvars/#compose_project_name) and the service name in your `docker-compose.yml`.

If you used the [`docker-compose.yml`](https://github.com/firefly-iii/firefly-iii/blob/master/docker-compose.yml) from the [docs](https://docs.firefly-iii.org/en/latest/installation/docker.html) and placed your `docker-compose.yml` in a folder called `awesome_personal_finance_app` 😉, your container name will probably turn out to be `awesome_personal_finance_app_firefly_iii_app_1`.

Alternatively, you could use the [`container_name:`](https://docs.docker.com/compose/compose-file/#container_name) attribute in your Firefly III app service definition to set a fix name for the container.

My approach works fine for me. If you don't want to use "unmaintained" software as mentioned at the beginning, you may want to have a look at https://github.com/willfarrell/docker-crontab or https://github.com/aptible/supercronic.
