### ISSUE TITLE
Docker distribution does not work behind a reverse proxy

### ISSUE THREAD

**Issue by elvetemedve** [firefly-iii/firefly-iii#2222]
**Bug description**
I am running Firefly III version 4.7.17, and my problem is:

Apache2 inside the Docker container does not respect the `X-Forwarded-Proto` HTTP header, therefore the application concludes that it's running on the insecure HTTP protocol resulting all absolute URLs being generated with HTTP scheme (while the application is really accessed via HTTPS). As a result of that the browser prevents using the application indicated by errors like: 
> Content Security Policy: The page’s settings blocked the loading of a resource

**Steps to reproduce**
1. Install the app via the [Docker method](https://docs.firefly-iii.org/en/latest/installation/docker.html#docker-hub-with-automatic-updates-via-docker-compose).
1. Export the port 80 on 8011 by adding the following to the **firefly_iii_app** section of `docker-compose.yml`:

    ```
    ports:
      - "8011:80"
    ```
1. Install Nginx and setup the reverse proxy (see [my-firefly.zip](https://github.com/firefly-iii/firefly-iii/files/3075327/my-firefly.zip)).
1. Open the homepage in a web browser and try to login.

**Expected behavior**
The app should show the welcome screen.

**Actual behavior**
The browser does not submit the login form.

**Extra info**
A possible solution is to update the Apache2 configuration inside the Docker container. Add the lines under to the *VirtualHost* section of the file **/etc/apache2/sites-enabled/000-default.conf**:
```
<IfModule mod_setenvif.c>	
	SetEnvIf X-Forwarded-Proto "(?i)^https$" HTTPS=on
</IfModule>
```

**Comment by JC5** [comment]
Do you use the trust proxies environment variable?

**Comment by elvetemedve** [comment]
Hi @JC5!
No, I don't. Adding `TRUSTED_PROXIES=**` to **docker-compose.yml** also makes it work.

Thanks for pointing that out. I missed [the reverse proxy part](https://docs.firefly-iii.org/en/latest/installation/docker.html#docker-and-reverse-proxies) of the documentation.

**Comment by JC5** [comment]
Glad to hear it works! If you feel the docs can be better, feel free to tell me or open a pull request. Cheers! :+1:

**Comment by 0x3333** [comment]
Hi, I added TRUSTED_PROXIES, added X-Forwarded-Proto, but my installation keeps redirecting to localhost.

My docker-compose.yml:
```
---
version: "3.2"
networks:
  firefly-tier:
    driver: bridge
services:
  firefly_app:
    image: jc5x/firefly-iii
    restart: always
    environment:
      - FF_DB_HOST=firefly_db
      - FF_DB_NAME=firefly
      - FF_DB_USER=firefly
      - FF_DB_PASSWORD=firefly
      - FF_APP_KEY=48680365575395197743824589049832
      - FF_APP_ENV=local
      - FF_DB_CONNECTION=pgsql
      - TZ=America/Sao_Paulo
      - APP_LOG_LEVEL=debug
      - APP_URL=https://firefly.example.com
      - TRUSTED_PROXIES=**
    depends_on:
      - firefly_db
    networks:
      - firefly-tier
    ports:
      - "3004:80"
    volumes:
      -
        source: firefly_export
        target: /var/www/firefly-iii/storage/export
        type: volume
      -
        source: firefly_upload
        target: /var/www/firefly-iii/storage/upload
        type: volume
  firefly_db:
    image: "postgres:10"
    environment:
      - POSTGRES_PASSWORD=firefly
      - POSTGRES_USER=firefly
    networks:
      - firefly-tier
    volumes:
      - "firefly_db:/var/lib/postgresql/data"
volumes:
  firefly_db: ~
  firefly_export: ~
  firefly_upload: ~
```

My nginx conf:
```
   server {
       listen 443 ssl http2;
       server_name firefly.example.com;

       include include.d/00-ssl-star.example.com.conf;
       include include.d/05-ssl.conf;

       add_header Strict-Transport-Security max-age=31536000;

       proxy_set_header X-Real-IP  $remote_addr;

       client_max_body_size 100m;

       location / {
           proxy_set_header X-Forwarded-Proto $scheme;
           proxy_pass http://localhost:3004;
       }
   }
```
