### ISSUE TITLE
HTTP 500 when use https with nginx proxy docker

### ISSUE THREAD

**Issue by CodeAndChoke** [firefly-iii/firefly-iii#2334]
I am running Firefly III version 4.7.17

**Description**
I use https://github.com/jwilder/nginx-proxy to proxy my server.  Http works fine but https return a 500. My docker-compose.yml looks like this. Logs will follow:

```
---
networks:
  default:
    external:
      name: webproxy
services:
  firefly_iii_app:
    environment:
      - FF_DB_HOST=firefly_iii_db
      - FF_DB_NAME=firefly
      - FF_DB_USER=firefly
      - FF_DB_PASSWORD=firefly
      - FF_APP_KEY=S0m3R@nd0mStr1ngOf32Ch@rsEx@ctly
      - FF_APP_ENV=local
      - FF_DB_CONNECTION=pgsql
      - TZ=Europe/Amsterdam
      - APP_LOG_LEVEL=debug
      - VIRTUAL_HOST=firefly.long-nguyen.de
      - LETSENCRYPT_HOST=firefly.my-domain.com, www.firefly.my-domain.com
      - LETSENCRYPT_EMAIL=admin@my-domain.com
      - APP_URL=https://firefly.my-domain.com
      - TRUSTED_PROXIES=**
    image: jc5x/firefly-iii
    links:
      - firefly_iii_db
    volumes:
      - 
        source: firefly_iii_export
        target: /var/www/firefly-iii/storage/export
        type: volume
      - 
        source: firefly_iii_upload
        target: /var/www/firefly-iii/storage/upload
        type: volume
  firefly_iii_db:
    environment:
      - POSTGRES_PASSWORD=firefly
      - POSTGRES_USER=firefly
    image: "postgres:10"
    volumes:
      - "firefly_iii_db:/var/lib/postgresql/data"
version: "3.2"
volumes:
  firefly_iii_db: ~
  firefly_iii_export: ~
  firefly_iii_upload: ~
```
