### ISSUE TITLE
Cannot enable debug mode

### ISSUE THREAD

**Issue by tinloaf** [firefly-iii/firefly-iii#2362]
**Bug description**
I am running Firefly III version 4.7.17.3 via docker-compose, and I tried to enable debug mode (I've now figured out that I'm hit by #2321 …)

This is how my debug log looks like:
![debug](https://user-images.githubusercontent.com/442687/62326170-bfb28380-b4ad-11e9-8dab-87e76b8daece.png)

 This is my docker-compose file:

``` 
--- 
networks: 
  firefly_iii_net: 
    driver: bridge
services: 
  firefly_iii_app: 
    environment: 
      - FF_DB_HOST=<REDACTED>
      - FF_DB_NAME=firefly
      - FF_DB_USER=firefly
      - FF_DB_PASSWORD=<REDACTED>
      - FF_APP_KEY=<REDACTED>
      - FF_APP_ENV=local
      - APP_URL=<REDACTED>
      - FF_APP_URL=<REDACTED>
      - FF_DB_CONNECTION=mysql
      - TZ=Europe/Berlin
      - APP_LOG_LEVEL=debug
      - TRUSTED_PROXIES=**
      - FF_TRUSTED_PROXIES=**
      - APP_DEBUG=true
    image: jc5x/firefly-iii
    networks: 
      - firefly_iii_net
    ports: 
      - "1080:80"
    volumes: 
      - /var/www/firefly-iii/storage/export:/mnt/data/firefly/export
      - /var/www/firefly-iii/storage/upload:/mnt/data/firefly/upload
      - /var/www/firefly-iii/storage/logs:/mnt/data/firefly/logs
version: "2"
```

I realize that the last volume is nonstandard, however I also don't get a debug log if I leave that volume out.

**Steps to reproduce**
Start the container.

**Expected behavior**
A debug log when I do stuff.

**Extra info**
Running the docker image. The debug output is:

Debug information generated at 2019-08-01 22:44:35 Europe/Berlin for Firefly III version **4.7.17.3**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.17.3 |
| FF API version | 0.9.2 |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | , stdout |
| PHP version | 7.2.20 |
| Display errors | Off |
| Session start | 2019-08-01 00:00:00 |
| Session end | 2019-08-31 23:59:59 |
| Session first | 2019-07-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | true |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, zip, Zend OPcache |

Thanks a lot!
