### ISSUE TITLE
Latest docker image doesn't recognize app key

### ISSUE THREAD

**Issue by agilob** [firefly-iii/firefly-iii#2380]
**Bug description**
Latest official docker image `sha256:c46639ec93fe91e7c3fc3da64a4a2ed3453cae4bbad1307b18fba2882f64b6ca`

**Steps to reproduce**
Watchtower updated docker image doesn't start correctly - loads blank page.

**Extra info**

> AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.32.2. Set the 'ServerName' directive globally to suppress this message
> AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.32.2. Set the 'ServerName' directive globally to suppress this message
> [Fri Aug 09 20:04:05.632381 2019] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.2.21 OpenSSL/1.1.1c configured -- resuming normal operations
> [Fri Aug 09 20:04:05.632432 2019] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
> [Fri Aug 09 20:04:06.375593 2019] [php7:error] [pid 277] [client 192.168.1.1:1033] PHP Fatal error:  Uncaught RuntimeException: No application encryption key has been specified. in /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:44\nStack trace:\n#0 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Support/helpers.php(1124): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(NULL)\n#1 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(48): tap(NULL, Object(Closure))\n#2 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(24): Illuminate\\Encryption\\EncryptionServiceProvider->key(Array)\n#3 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(787): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(Object(Illuminate\\Foundation\\Application), Array)\n#4 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(667): Illuminate\\Container\\C in /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php on line 44
> [Fri Aug 09 20:04:06.376240 2019] [php7:error] [pid 277] [client 192.168.1.1:1033] PHP Fatal error:  Uncaught RuntimeException: No application encryption key has been specified. in /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:44\nStack trace:\n#0 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Support/helpers.php(1124): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(NULL)\n#1 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(48): tap(NULL, Object(Closure))\n#2 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(24): Illuminate\\Encryption\\EncryptionServiceProvider->key(Array)\n#3 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(787): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(Object(Illuminate\\Foundation\\Application), Array)\n#4 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(667): Illuminate\\Container\\C in /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php on line 44
> 192.168.1.1 - - [09/Aug/2019:20:04:06 +0000] "GET / HTTP/1.1" 500 211 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"

It stopped working today after automated update made by watchtower, but it also doesn't work when I removed container instance and re-created manually from the same docker-compose I created weeks ago:

Simplified docker file is as follows:

```
version: "3.3"

services:

  firefly_iii_app:
    image: jc5x/firefly-iii
    container_name: firefly
    networks:
      postgresql-network:
        aliases:
          - postgresql-network
      traefik-network:
    environment:
      - FF_DB_HOST=postgresql-network
      - FF_DB_NAME=firefly
      - FF_DB_USER=firefly
      - FF_DB_PASSWORD=firefly
      - FF_APP_KEY=S0m3R@nd0mStr1ngOf32Ch@rsEx@ctly
      - FF_APP_ENV=local
      - FF_DB_CONNECTION=pgsql
      - PUID=1000
      - PGID=1000
    ports:
      - 8777:80
    expose:
      - 80
```
