### ISSUE TITLE
Application encryption key after updating Firefly to 4.8.0

### ISSUE THREAD

**Issue by DenBeke** [firefly-iii/firefly-iii#2396]
I'm using the Firefly docker image, and I'm running in a problem when trying to upgrade. Trying to upgrade from the latest 4.7.x version to 4.8.0.
Everything is in a docker-compose file, so I did a `docker-compose pull` and `docker-compose up -d` to perform the upgrade.

Since I did the upgrade I run into:

```
PHP Fatal error:  Uncaught RuntimeException: No application encryption key has been specified
```

How should I tackle this problem?

**Comment by DenBeke** [comment]
The relevant part of my `docker-compose.yml` file:

```
firefly:
  environment:
    - FF_DB_HOST=xxxxxx
    - FF_DB_NAME=xxxxxx
    - FF_DB_USER=xxxxxx
    - FF_DB_PASSWORD=xxxxxx
    - FF_APP_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    - FF_DB_CONNECTION=mysql
    - TZ=Europe/Brussels
    - TRUSTED_PROXIES=**
    - APP_LOG_LEVEL=warning
  image: jc5x/firefly-iii
```
