### ISSUE TITLE
New user docker install

### ISSUE THREAD

**Issue by Sparticuz** [firefly-iii/firefly-iii#2579]
I am running Firefly III version :latest, 4.8.1?

**Description**
I've just put the config into my docker-compose file. DB tables got created correctly, nginx reverse proxy set up. However, I'm getting a 404 when I browse to the instance.

![image](https://user-images.githubusercontent.com/161913/64627620-f5585f80-d3bd-11e9-92e5-a053c2f754a8.png)

![image](https://user-images.githubusercontent.com/161913/64627518-ca6e0b80-d3bd-11e9-9072-9099232423f8.png)

**Extra info**
docker-compose.yml (relevant info)
````
  firefly:
    image: jc5x/firefly-iii:latest
    depends_on:
      - mariadb
    ports:
      - 8101:80
    env_file: firefly.env
    volumes:
      - /var/dock/firefly/export:/var/www/firefly-iii/storage/export
      - /var/dock/firefly/upload:/var/www/firefly-iii/storage/upload
      - /var/dock/firefly/logs:/storage/logs
    restart: unless-stopped
````
firefly.env (things I've changed)
````
SITE_OWNER=..........
APP_KEY=................... (32 chars)
TZ=America/New_York
APP_URL=https://............/firefly
TRUSTED_PROXIES=**
DB_CONNECTION=mysql
DB_HOST=........
DB_PORT=3306
DB_DATABASE=..........
DB_USERNAME=...........
DB_PASSWORD=..............
````
nginx.conf (some of the proxy headers are for other apps, if any conflict let me know)
````
        location /firefly {
                proxy_set_header        Host                    $host;
                proxy_set_header        X-Real-IP               $remote_addr;
                proxy_set_header        X-Forwarded-For         $proxy_add_x_forwarded_for;
                proxy_set_header        X-Forwarded-Host        $server_name;
                proxy_set_header        X-Forwarded-Proto       $scheme;
                proxy_set_header        X-Forwarded-Ssl         on;
                proxy_set_header        Upgrade                 $http_upgrade;
                proxy_set_header        Connection              "upgrade";

                proxy_pass http://127.0.0.1:8101;
        }
````

Thank you for your help!!
