### ISSUE TITLE
Firefly-III fails to work after Container restart

### ISSUE THREAD

**Issue by dirkcjelli** [firefly-iii/firefly-iii#2594]
I am running Firefly III version 4.8.1 (Docker Image 17bca427605c)

**Description**
I just stumbled over Firefly and did a self-hosted docker setup using the docker-compose.yml provided in the docs as well as the env file. I adjusted both for my use case and was able to start Firefly in no time and did some basic testing setup which worked like a charm.

Unfortunately, after stopping and restarting the containers (postgres and firefly), I was no longer able to login and got a blank page. A look inside the logs gave me 

```
PHP Fatal error:  Uncaught Error: Class 'Illuminate\Foundation\Application' not found in /var/www/firefly-iii/bootstrap/app.php:57                                                                                                                           
Stack trace:                                                                                                                                                                                                                                                 
#0 /var/www/firefly-iii/artisan(20): require_once()                                                                                                                                                                                                          
#1 {main}                                                                                                                                                                                                                                                    
  thrown in /var/www/firefly-iii/bootstrap/app.php on line 57
```
in startup and for every access after that. I repeated all the steps and it works every time until a restart is made.

Am I missing something really stupid?

**Comment by JC5** [comment]
What's the use case you adapted them for?

**Comment by dirkcjelli** [comment]
Nothing special, I just
- added labels for traefik
- used host-mounted volumes for `storage/export` and `storage/upload` and for the postgres
- added an `adminer` container and a `memcached` container
- adjusted the `env` file to use memcached 

To make it easier, here's my docker-compose.yml:
```
version: "2.4"

services:
  memcached:
    cpus: 0.2
    mem_limit: 128M
    restart: always
    image: memcached:1.5.17
    networks:
      - memcached
    command: 
      - "-m 100"

  adminer:
    depends_on:
      - db
    cpus: 0.1
    restart: always
    mem_limit: 128M
    image: adminer:4
    networks:
      - web
      - db
    expose:
      - "8080"
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.http.routers.ffadminer.rule=Host(`domain`)"
      - "traefik.http.routers.ffadminer.entrypoints=http-internal"

  db:
    cpus: 0.8
    mem_limit: 1124M
    shm_size: 256M
    image: postgres:11.5
    command: -c 'shared_buffers=256MB' -c 'work_mem=32MB'
    restart: always
    networks:
      - db
    environment:
      - POSTGRES_USER=firefly
      - POSTGRES_PASSWORD=SuperSecretPasswordHere
    volumes:
      - /share/d_firefly/ff_pg11:/var/lib/postgresql/data:rw
      
  app:
    depends_on:
      - db
      - memcached
    cpus: 0.2
    mem_limit: 256M
    restart: always
    env_file: /share/d_firefly/env
    image: jc5x/firefly-iii:latest
    expose:
      - "80"
    networks:
      - web
      - db
    environment:
      - TZ=Europe/Berlin
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.http.routers.ffhttps.rule=Host(`mydomain`)"
      - "traefik.http.routers.ffhttps.entrypoints=https"
      - "traefik.http.routers.ffhttps.tls.certresolver=default"
      - "traefik.http.routers.ffhttps.middlewares=sec@file"

      - "traefik.http.routers.ffhttp.middlewares=redirect"
      - "traefik.http.routers.ffhttp.rule=Host(`mydomain`)"
      - "traefik.http.routers.ffhttp.entrypoints=http"
           
      - "traefik.http.middlewares.redirect.headers.sslredirect=true"

    volumes:
      - /share/d_firefly/storage/export:/var/www/firefly-iii/storage/export:rw
      - /share/d_firefly/storage/upload:/var/www/firefly-iii/storage/upload:rw

networks:
  web:
    external: true
  db:
    name: ff-db
  memcached:
    name: ff-memcached
```

As said, everythin works fine, but there seems to be some (dependency?) problem on restarts
