### ISSUE TITLE
[HOW TO] Setup Firefly III in 10 min with NGINX and auto-renewal SSL

### ISSUE THREAD

**Issue by optimistic5** [firefly-iii/firefly-iii#2600]
I would like to tell how to setup Firefly III with auto-renewal SSL in docker-compose.

We will use [jwilder](https://github.com/jwilder/nginx-proxy/). This is NGINX which will be follow all containers and issue Let's encrypt certificates for them.

0. Prepare server or rent VPS. 
You can ask me and I will suggest VPS I use.
I use Ubuntu 18.04.
You also need the domain name with А DNS record pointed to your server.

1. Install [docker](https://docs.docker.com/install/linux/docker-ce/ubuntu/)

2. Create folder `nginx-proxy` and `docker-compose.yml` inside this folder
```
mkdir nginx-proxy
cd nginx-proxy
vim docker-compose.yml
```
<details>
        <summary>docker-compose.yml</summary>

```
version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./current/public:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
      - ./vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./pass:/etc/nginx/htpasswd:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
      NGINX_DOCKER_GEN_CONTAINER: nginx-proxy
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./vhost:/etc/nginx/vhost.d
      - ./current/public:/usr/share/nginx/html
networks:
  default:
    external:
      name: nginx-proxy
```    
</details>

3. You can start this docker-compose
```
docker-compose up -d
```
4. Return to your home folder and create `firefly-iii` folder. And `docker-compose.yml` in it.
```
cd
mkdir firefly-iii
cd firefly-iii
vim docker-compose.yml
```
<details>
        <summary>docker-compose.yml</summary>

```
--- 
networks:
  default:
    external:
      name: nginx-proxy
      
services:

  firefly_iii_app: 
    image: jc5x/firefly-iii:latest
    restart: unless-stopped
    depends_on:
      - firefly_iii_db
    ports: 
      - 80
    env_file: .env
    volumes: 
      - 
        source: firefly_iii_export
        target: /var/www/firefly-iii/storage/export
        type: volume
      - 
        source: firefly_iii_upload
        target: /var/www/firefly-iii/storage/upload
        type: volume
        
  firefly_iii_db: 
    image: "postgres:10"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=homestead
      - POSTGRES_USER=firefly
    volumes: 
      - firefly_iii_db:/var/lib/postgresql/data
  
  firefly_iii_cron:
    image: alpine
    command: sh -c "echo \"0 3 * * * wget https://your_domain/cron/run/token\" | crontab - && crond -f -L /dev/stdout"
version: "3.2"

volumes: 
  firefly_iii_db: ~
  firefly_iii_export: ~
  firefly_iii_upload: ~
```
</details>

Reference: [official](https://docs.firefly-iii.org/en/latest/installation/docker.html) documentation about Firefly III in docker and [cron](https://docs.firefly-iii.org/en/latest/installation/cronjob.html) in Firefly III.
Please replace `pass` with strong password, `your_domain` with your domain and `token` with your token (see link to docs above).

5. Create .env file and edit it accordingly to your setup.
```
vim .env
```
<details>
        <summary>.env</summary>

```
VIRTUAL_HOST=your_domain
LETSENCRYPT_HOST=your_domain
LETSENCRYPT_EMAIL=info@your_domain

# You can leave this on "local". If you change it to production most console commands will ask for extra confirmation.
# Never set it to "testing".
APP_ENV=local

# Set to true if you want to see debug information in error screens.
APP_DEBUG=false

# This should be your email address
SITE_OWNER=info@your_domain

# The encryption key for your sessions. Keep this very secure.
# If you generate a new one existing data must be considered LOST.
# Change it to a string of exactly 32 chars or use command `php artisan key:generate` to generate it
APP_KEY=some32chars


# Change this value to your preferred time zone.
# Example: Europe/Amsterdam
TZ=Europe/Amsterdam

# This variable must match your installation's external address but keep in mind that
# it's only used on the command line as a fallback value.
APP_URL=your_domain

# TRUSTED_PROXIES is a useful variable when using Docker and/or a reverse proxy.
# Set it to ** and reverse proxies work just fine.
TRUSTED_PROXIES=**

# The log channel defines where your log entries go to.
# 'daily' is the default logging mode giving you 5 daily rotated log files in /storage/logs/.
# Several other options exist. You can use 'single' for one big fat error log (not recommended).
# Also available are 'syslog', 'errorlog' and 'stdout' which will log to the system itself.
LOG_CHANNEL=daily

# Log level. You can set this from least severe to most severe:
# debug, info, notice, warning, error, critical, alert, emergency
# If you set it to debug your logs will grow large, and fast. If you set it to emergency probably
# nothing will get logged, ever.
APP_LOG_LEVEL=notice

# Database credentials. Make sure the database exists. I recommend a dedicated user for Firefly III
# For other database types, please see the FAQ: http://firefly-iii.readthedocs.io/en/latest/support/faq.html
DB_CONNECTION=pgsql
#FF_DB_CONNECTION=pgsql
# If you use DOCKER COMPOSE, change this variable to "firefly_iii_db"
DB_HOST=firefly_iii_db
DB_PORT=5432
DB_DATABASE=homestead
DB_USERNAME=firefly
DB_PASSWORD=pass

# PostgreSQL supports SSL. You can configure it here.
PGSQL_SSL_MODE=prefer
PGSQL_SSL_ROOT_CERT=null
PGSQL_SSL_CERT=null
PGSQL_SSL_KEY=null
PGSQL_SSL_CRL_FILE=null

# If you're looking for performance improvements, you could install memcached.
CACHE_DRIVER=file
SESSION_DRIVER=file

# You can configure another file storage backend if you cannot use the local storage option.
# To set this up, fill in the following variables. The upload path is used to store uploaded
# files and the export path is to store exported data (before download).
SFTP_HOST=
SFTP_PORT=
SFTP_UPLOAD_PATH=
SFTP_EXPORT_PATH=

# SFTP uses either the username/password combination or the private key to authenticate.
SFTP_USERNAME=
SFTP_PASSWORD=
SFTP_PRIV_KEY=

# Cookie settings. Should not be necessary to change these.
COOKIE_PATH="/"
COOKIE_DOMAIN=
COOKIE_SECURE=false

# If you want Firefly III to mail you, update these settings
# For instructions, see: https://firefly-iii.readthedocs.io/en/latest/installation/mail.html
MAIL_DRIVER=log
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_FROM=changeme@example.com
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

# Other mail drivers:
MAILGUN_DOMAIN=
MAILGUN_SECRET=
MANDRILL_SECRET=
SPARKPOST_SECRET=

# Firefly III can send you the following messages
SEND_REGISTRATION_MAIL=true
SEND_ERROR_MESSAGE=true

# These messages contain (sensitive) transaction information:
SEND_REPORT_JOURNALS=true

# Set a Mapbox API key here (see mapbox.com) so there might be a map available at various places.
MAPBOX_API_KEY=

# Firefly III currently supports two provider for live Currency Exchange Rates:
# "fixer", and "ratesapi".
# RatesApi.IO (see https://ratesapi.io) is a FREE and OPEN SOURCE live currency exchange rates,
# built compatible with Fixer.IO, based on data published by European Central Bank, and doesn't require API key.
CER_PROVIDER=ratesapi

# If you have select "fixer" as default currency exchange rates,
# set a Fixer IO API key here (see https://fixer.io) to enable live currency exchange rates.
# Please note that this WILL ONLY WORK FOR PAID fixer.io accounts because they severely limited
# the free API up to the point where you might as well offer nothing.
FIXER_API_KEY=

# If you wish to track your own behavior over Firefly III, set a valid analytics tracker ID here.
ANALYTICS_ID=

# Firefly III has two options for user authentication. "eloquent" is the default,
# and "ldap" for LDAP servers.
# For full instructions on these settings please visit:
# https://firefly-iii.readthedocs.io/en/latest/installation/authentication.html
LOGIN_PROVIDER=eloquent

# LDAP connection configuration
# OpenLDAP, FreeIPA or ActiveDirectory
ADLDAP_CONNECTION_SCHEME=OpenLDAP
ADLDAP_AUTO_CONNECT=true

# LDAP connection settings
ADLDAP_CONTROLLERS=
ADLDAP_PORT=389
ADLDAP_TIMEOUT=5
ADLDAP_BASEDN=""
ADLDAP_FOLLOW_REFFERALS=false
ADLDAP_USE_SSL=false
ADLDAP_USE_TLS=false

ADLDAP_ADMIN_USERNAME=
ADLDAP_ADMIN_PASSWORD=

ADLDAP_ACCOUNT_PREFIX=
ADLDAP_ACCOUNT_SUFFIX=

# LDAP authentication settings.
ADLDAP_PASSWORD_SYNC=false
ADLDAP_LOGIN_FALLBACK=false

ADLDAP_DISCOVER_FIELD=distinguishedname
ADLDAP_AUTH_FIELD=distinguishedname

# Will allow SSO if your server provides an AUTH_USER field.
WINDOWS_SSO_DISCOVER=samaccountname
WINDOWS_SSO_KEY=AUTH_USER

# field to sync as local username.
ADLDAP_SYNC_FIELD=userprincipalname

# You can disable the X-Frame-Options header if it interfears with tools like
# Organizr. This is at your own risk.
DISABLE_FRAME_HEADER=false

# Leave the following configuration vars as is.
# Unless you like to tinker and know what you're doing.
APP_NAME=FireflyIII
ADLDAP_CONNECTION=default
BROADCAST_DRIVER=log
QUEUE_DRIVER=sync
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379
CACHE_PREFIX=firefly
SEARCH_RESULT_LIMIT=50
PUSHER_KEY=
PUSHER_SECRET=
PUSHER_ID=
DEMO_USERNAME=
DEMO_PASSWORD=
IS_DOCKER=false
USE_ENCRYPTION=false
IS_SANDSTORM=false
IS_HEROKU=false
BUNQ_USE_SANDBOX=false
FFIII_LAYOUT=v1
```
</details>

Please note that first three environment variable needs for jwilder.

Because in our firefly-iii docker-compose.yml we specify the same network as jwilder use, now jwilder will monitor every container and will be searching for this envs.

Another envs need for Firefly III itself.

Change `pass` to pass from firefly-iii docker-compose.yml
Change `your_domain` to your domain.
Change `Europe/Amsterdam` to your time zone.
Change `some32chars` to some random 32 chars, don't ask, just do it.

Reference: [official](https://raw.githubusercontent.com/firefly-iii/firefly-iii/master/.env.example) `.env` example

6. You can now start your Firefly III instance
```
docker-compose up -d
```
Just after this command jwilder will proxy Firefly III instance with your domain and auto issue SSL for you. It also will check expiration date of SSL cert and auto-renew it.

**BONUS**
7. Update to the latest version of Firefly III in one command!

This command will connect your VPS via SSH update your Firefly III and delete unused docker images.

```ssh YOU_SERVER_USER@YOUR_SERVER_IP "cd firefly-iii && docker-compose stop firefly_iii_app && docker-compose rm && docker-compose pull firefly_iii_app && docker-compose up -d && docker images | grep "<none>" | awk '{print $3}' | xargs docker rmi"```
