### ISSUE TITLE
Firefly III Docker with Pomerium - Mixed Content - http/https

### ISSUE THREAD

**Issue by fightforlife** [firefly-iii/firefly-iii#2669]
Hey there,

I am running Firefly v4.8.1.1 in the official Docker container.
As a reverse proxy I am using Pomerium v0.3.0 (https://www.pomerium.io/). This is working quite good for all my other services. (Guacamole, Nodered, Filebrowser, Portainer, Wordpress, ....)

**Description**
But Firefly iii seems to have a problem with pomerium as a reverse proxy.

The Login Page gives the following error:
```
Mixed` Content: The page at 'https://money.domain.tld/login' was loaded over a secure connection, but contains a form that targets an insecure endpoint 'http://money.domain.tld/login'. This endpoint should be made available over a secure connection.
```
And in the source code of the login page all links are http:// and not https://, even if I call the Site successfully over https://.

I already tried the following setings in .env but the links are still http://
(in some older Issues other env variables are mentioned, like APP_Force_SSL and so on, but as far as i could find out, these are not used anymore)

```
- APP_URL=https://money.domain.tld/
- TRUSTED_PROXIES=**
```

**Extra info**

Docker compose file:

```
version: '2'
networks: 
  firefly_iii_net: 
    driver: bridge
    
services: 
  firefly_iii_app: 
    image: jc5x/firefly-iii:latest
    depends_on:
      - firefly_iii_db
    networks: 
      - firefly_iii_net
    ports: 
      - "9033:80"
    volumes: 
      - firefly_iii_export:/var/www/firefly-iii/storage/export
      - firefly_iii_upload:/var/www/firefly-iii/storage/upload
    environment:
      - APP_KEY=XXX
      - APP_URL=https://money.domain.tld/
      - TRUSTED_PROXIES=**    
      
      - TZ=Europe/Amsterdam
      - DB_CONNECTION=mysql
      - DB_HOST=firefly_iii_db
      - DB_PORT=3306
      - DB_DATABASE=firefly
      - DB_USERNAME=firefly
      - DB_PASSWORD=XXX


  firefly_iii_db: 
    image: "mariadb:10"
    environment:
      - MYSQL_DATABASE=firefly
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=XXX
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    networks: 
      - firefly_iii_net
    volumes: 
      - firefly_iii_db:/var/lib/mysql
```

pomerium policy:

```
#Firefly iii
  - from: https://money.domain.tld
    to: http://178.155.1.10:9033
    allowed_users:
      - some.user@gmail.com

```

**Comment by klepek** [comment]
I had same issue in past, and I have solved it with using following settings in nginx reverse proxy:
`        location / {
                proxy_pass       http://127.0.0.1:3084;
                proxy_set_header X-Real-IP  $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto https;
                proxy_set_header X-Forwarded-Port 443;
                proxy_set_header Host $host;
        }
`

together with 
`APP_URL=https://firefly.something.darkside
APP_FORCE_SSL=true
TRUSTED_PROXIES=*
`

and it has been working fine after that. I guess your firefly receives incorrect X-Forwarded-Proto

**Comment by fightforlife** [comment]
Hey, thanks for the quick answer.

Here is what I tried:

APP_URL=https://firefly.something.darkside
APP_FORCE_SSL=true
TRUSTED_PROXIES=*

Gives me a redirect to the local IP address.

_______________

APP_URL=https://firefly.something.darkside
APP_FORCE_SSL=true
TRUSTED_PROXIES=**

Gives the same error from the initial post. (Mixed content)


I need to check what I can configure in Pomerium.

**Comment by fightforlife** [comment]
I also found out that Pomerium is using this header configuration as standard.
I am no expert with this, is there something that needs to be changed?

X-Content-Type-Options : nosniff,
X-Frame-Options:SAMEORIGIN,
X-XSS-Protection:1; mode=block,
Strict-Transport-Security:max-age=31536000; includeSubDomains; preload,

**Comment by fightforlife** [comment]
I have no the following configuration and still see the same problem.

Firefly iii .env:
```
APP_URL=https://firefly.something.darkside
APP_FORCE_SSL=true
TRUSTED_PROXIES=**
```

Headers from proxy:
```
x-content-type-options: nosniff
x-forwarded-proto: https
x-frame-options: deny
x-powered-by: PHP/7.3.9
x-xss-protection: 1; mode=block

```

Are there additinal logs, which I an provide?

**Comment by fightforlife** [comment]
I am currently on vacation.
I will try to work on this problem next week.

**Comment by fightforlife** [comment]
Problem is still there :(
My other services (around 20) are successfully proxied by pomerium.
Only Firefly has this mixed content problem.

Is there anythin I can provide to get to the ground of this problem?

Refused to send form data to '<URL>' because it violates the following Content Security Policy directive: "form-action 'self'".

Refused to set the document's base URI to 'http://finance.domain.tld/' because it violates the following Content Security Policy directive: "base-uri 'self'".

Mixed Content: The page at 'https://finance.domain.tld/login#' was loaded over a secure connection, but contains a form that targets an insecure endpoint 'http://finance.domain.tld/login'. This endpoint should be made available over a secure connection.

**Comment by JC5** [comment]
You have to do [this](https://github.com/firefly-iii/firefly-iii/issues/2669#issuecomment-536665159) in Pomerium. If those headers are set and correct, Firefly III will work.

**Comment by fightforlife** [comment]
Thank you very much!

It is working now. For anyone finding this here is the correct pomerium policy:

```
# Firefly III policy 
  - from: https://finance.domain.tld
    to: http://123.456.1.2:8734
    allowed_users:
      - some.mail@mail.com   
    set_request_headers:
        X-Real-IP: $remote_addr
        X-Forwarded-For: $proxy_add_x_forwarded_for
        X-Forwarded-Proto: https
        X-Forwarded-Port: 443
        Host: $host
```

```
      - APP_URL=https://finance.domain.tld
      - TRUSTED_PROXIES=**
```
