### ISSUE TITLE
"Failed to open stream: Permission denied" error after a fresh Docker install

### ISSUE THREAD

**Issue by eorn** [firefly-iii/firefly-iii#2684]
**Bug description**
I am running Firefly III version 4.8.1.1, using docker-compose. After a fresh install, I get the following error (with `APP_DEBUG=true`) :

```
The stream or file "/var/www/firefly-iii/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied
```

**Steps to reproduce**
Have the `docker-compose.yml` below and run `docker-compose up`

**docker-compose.yml**
```
version: '3.2'

services:
        firefly_db:
                image: "postgres:10"
                restart: unless-stopped
                environment:
                        - POSTGRES_USER=firefly
                        - POSTGRES_PASSWORD=yyy
                networks:
                        - myweb
                volumes:
                        - ./db:/var/lib/postgresql/data

        firefly:
                image: jc5x/firefly-iii:release-4.8.1.1
                depends_on:
                        - firefly_db
                networks:
                        - myweb
                volumes:
                        - ./firefly_iii_export:/var/www/firefly-iii/storage/export                                                                                                                                              
                        - ./firefly_iii_upload:/var/www/firefly-iii/storage/upload                                                                                                                                                                                                                                                                                                                                                                           
                environment:                                                                                                                                                                                                                   
                        - APP_ENV=local                                                                                                                                                                                                        
                        - APP_DEBUG=true                                                                                                                                                                                                       
                        - SITE_OWNER=email@domain
                        - APP_KEY=xxx                                                                                                                                                                             
                        - TZ=Europe/Paris                                                                                                                                                                                                      
                        - APP_URL=http://domain                                                                                                                                                                            
                        - LOG_CHANNEL=daily                                                                                                                                                                                                    
                        - APP_LOG_LEVEL=NOTICE                                                                                                                                                                                                 
                        - DB_CONNECTION=pgsql                                                                                                                                                                                                  
                        - DB_HOST=firefly_db                                                                                                                                                                                                   
                        - DB_PORT=5432                                                                                                                                                                                                         
                        - DB_DATABASE=firefly                                                                                                                                                                                                  
                        - DB_USERNAME=firefly                                                                                                                                                                                                  
                        - DB_PASSWORD=yyy                                                                                                                                                                                                                                                                                                                                                                                                        
                labels:                                                                                                                                                                                                                        
                        - "traefik.enable=true"                                                                                                                                                                                                
                        - "traefik.http.routers.thunes.rule=Host(`domain`)"                                                                                                                                                           
                        - "traefik.http.routers.thunes.entrypoints=web"                                                                                                                                                                        
                        - "traefik.http.routers.thunestls.rule=Host(`domain`)"                                                                                                                                                        
                        - "traefik.http.routers.thunestls.entrypoints=websecure"                                                                                                                                                               
                        - "traefik.http.routers.thunestls.tls=true"                                                                                                                                                                            
                        - "traefik.http.routers.thunestls.tls.certresolver=sample"                                                                                                                                                             
                                                                                                                                                                                                                                               
networks:                                                                                                                                                                                                                                      
        myweb:                                                                                                                                                                                                                                 
                external: true                                                                                                                                                                                                                 
```



**Extra info**
Many issues have been opened and closed related to the permission of the file `/var/www/firefly-iii/storage/logs/laravel.log`, for example: https://github.com/firefly-iii/firefly-iii/issues/926, https://github.com/firefly-iii/firefly-iii/issues/1320

It looks really similar, because when I `chmod -R og+rw storage/logs/`. But the bug reappeared somehow?
However, running `docker exec -it <container> php artisan cache:clear` does not work.

**EDIT**
My bad, I had a typo in my environment variables: the `APP_LOG_LEVEL` value was in capital letters… Not it works perfectly.
