### ISSUE TITLE
Dockerized Firefly III fails to start

### ISSUE THREAD

**Issue by blaineventurine** [firefly-iii/firefly-iii#2779]
I am running Firefly III version 4.8.1.8

**Description**
When starting the container, I get this error:

```
    In ServiceProvider.php line 236:
    Cannot instantiate Twig extension 'TwigBridge\Extension\Laravel\Session': The only supported
    ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths.
```

**Extra info**
Relevant section of docker-compose file:

```
    firefly_iii:  
      container_name: firefly_iii  
    image: jc5x/firefly-iii:latest  
    depends_on:
      - mariadb
    links:
      - mariadb
    networks: 
      - default
    ports: 
      - "8675:80"
    volumes: 
      - ${USERDIR}/fireflyiii/storage/export:/var/www/firefly-iii/storage/export
      - ${USERDIR}/fireflyiii/storage/upload:/var/www/firefly-iii/storage/upload
      - ${USERDIR}/fireflyiii/storage:/var/www/firefly-iii/storage/
    environment:
      - TZ=${TZ}
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=firefly
      - DB_USERNAME=firefly
      - DB_PASSWORD=${FIREFLY_DB_PASSWORD}
      - APP_KEY={$FIREFLY_APP_KEY}
      - APP_LOG_LEVEL=debug
      - APP_ENV=local
```

I have seen issues posted before with improperly named environment variables causing this error, but I think all of mine are correct. I have verified my APP_KEY is 32 characters exactly, and the DB password is as well for good measure. Any thoughts?
