### ISSUE TITLE
redirected to login page without port number

### ISSUE THREAD

**Issue by xinstein** [firefly-iii/firefly-iii#3007]
I use jwilder/nginx-proxy as a reverse proxy, with because of network provider restriction, I've changed listening ports (80/443) to 7080:7443. Below is the part of docker-compose of nginx-proxy

```

services:
  nginx_proxy:
    image: jwilder/nginx-proxy:latest
    restart: unless-stopped
    ports:
      # - "80:80"
      # - "7080:80"
      - "7443:443"
      # - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy
      
networks:
  proxy: ~

volumes:
  conf: ~
  vhost: ~
  html: ~
  dhparam: ~
  certs: ~
```

Notice that I change listening port not by modifying settings of jwilder/nginx-proxy, but by port mapping of docker container.

Firefly iii is the first web app that failed to work with this configuration.

The first thing I encounter after hitting https://my.domain.name:7443 is being redirected to https://my.domain.name/login with no port number specification, which I think is the reason it doesn't work.

I tried changing the listening port back to 443 and editing hosts file to map my.domain.name to 127.0.0.1, which makes everything work like normal. But this is useless since it only works locally.

I've been digging around for quite some time and can't find a modification or configuration that could eventually make things right.

Please help me resolve this issue, Thank you for your great work!
