### ISSUE TITLE
Curl error (code 3): <url> malformed

### ISSUE THREAD

**Issue by mrz** [firefly-iii/firefly-iii#3138]
Hello, I am getting this stacktrace when deploying firefly-iii to my VPS using the instructions for **[docker-compose](https://docs.firefly-iii.org/installation/docker#docker-hub-with-automatic-updates-via-docker-compose)**:

```
 (1/1) RuntimeException

Curl error (code 3): <url> malformed
in Util.php line 45
at Util::execute('Resource id #448')in SlackWebhookHandler.php line 102
at SlackWebhookHandler->write(array('message' => 'Curl error (code 3): <url> malformed', 'context' => array('exception' => object(RuntimeException)), 'level' => 400, 'level_name' => 'ERROR', 'channel' => 'local', 'datetime' => object(DateTime), 'extra' => array(), 'formatted' => '[2020-02-21 08:52:41] local.ERROR: Curl error (code 3): <url> malformed {"exception":"[object] (RuntimeException(code: 0): Curl error (code 3): <url> malformed at /var/www/firefly-iii/vendor/monolog/monolog/src/Monolog/Handler/Curl/Util.php:45)[stacktrace]#0 /var/www/firefly-iii/vendor/monolog/monolog/src/Monolog/Handler/SlackWebhookHandler.php(102): Monolog\\\\Handler\\\\Curl\\\\Util::execute(Resource id #447)#1 /var/www/firefly-iii/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\\\\Handler\\\\SlackWebhookHandler->write(Array)#2 /var/www/firefly-iii/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\\\\Handler\\\\AbstractProcessingHandler->handle(Array)#3 /var/www/firefly-iii/vendor/monolog/monolog/src/Monolog/Logger.php(707): Monolog\\\\Logger->addRecord(400, \'Curl error (cod...\', Array)#4 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Log/Logger.php(176): Monolog\\\\Logger->error(\'Curl error (cod...\', Array)#5 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Log/Logger.php(87): Illuminate\\\\Log\\\\Logger->writeLog(\'error\', \'Curl error (cod...\', Array)#6 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(493): Illuminate\\\\Log\\\\Logger->error(\'Curl error (cod...\', Array)#7 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(114): Illuminate\\\\Log\\\\LogManager->error(\'Curl error (cod...\', Array)#8 /var/www/firefly-iii/app/Exceptions/Handler.php(153): Illuminate\\\\Foundation\\\\Exceptions\\\\Handler->report(Object(RuntimeException))#9 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): FireflyIII\\\\Exceptions\\\\Handler->report(Object(RuntimeException))#10 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\\\Foundation\\\\Http\\\\Kernel->reportException(Object(RuntimeException))#11 /var/www/firefly-iii/public/index.php(76): Illuminate\\\\Foundation\\\\Http\\\\Kernel->handle(Object(Illuminate\\\\Http\\\\Request))#12 {main}"} '))in AbstractProcessingHandler.php line 39
at AbstractProcessingHandler->handle(array('message' => 'Curl error (code 3): <url> malformed', 'context' => array('exception' => object(RuntimeException)), 'level' => 400, 'level_name' => 'ERROR', 'channel' => 'local', 'datetime' => object(DateTime), 'extra' => array(), 'formatted' => '[2020-02-21 08:52:41] local.ERROR: Curl error (code 3): <url> malformed {"exception":"[object] (RuntimeException(code: 0): Curl error (code 3): <url> malformed at /var/www/firefly-iii/vendor/monolog/monolog/src/Monolog/Handler/Curl/Util.php:45)[stacktrace]#0 /var/www/firefly-iii/vendor/monolog/monolog/src/Monolog/Handler/SlackWebhookHandler.php(102): Monolog\\\\Handler\\\\Curl\\\\Util::execute(Resource id #447)#1 /var/www/firefly-iii/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\\\\Handler\\\\SlackWebhookHandler->write(Array)#2 /var/www/firefly-iii/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\\\\Handler\\\\AbstractProcessingHandler->handle(Array)#3 /var/www/firefly-iii/vendor/monolog/monolog/src/Monolog/Logger.php(707): Monolog\\\\Logger->addRecord(400, \'Curl error (cod...\', Array)#4 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Log/Logger.php(176): Monolog\\\\Logger->error(\'Curl error (cod...\', Array)#5 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Log/Logger.php(87): Illuminate\\\\Log\\\\Logger->writeLog(\'error\', \'Curl error (cod...\', Array)#6 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(493): Illuminate\\\\Log\\\\Logger->error(\'Curl error (cod...\', Array)#7 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(114): Illuminate\\\\Log\\\\LogManager->error(\'Curl error (cod...\', Array)#8 /var/www/firefly-iii/app/Exceptions/Handler.php(153): Illuminate\\\\Foundation\\\\Exceptions\\\\Handler->report(Object(RuntimeException))#9 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): FireflyIII\\\\Exceptions\\\\Handler->report(Object(RuntimeException))#10 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\\\Foundation\\\\Http\\\\Kernel->reportException(Object(RuntimeException))#11 /var/www/firefly-iii/public/index.php(76): Illuminate\\\\Foundation\\\\Http\\\\Kernel->handle(Object(Illuminate\\\\Http\\\\Request))#12 {main}"} '))in Logger.php line 344
at Logger->addRecord(400, 'Curl error (code 3): <url> malformed', array('exception' => object(RuntimeException)))in Logger.php line 707
at Logger->error('Curl error (code 3): <url> malformed', array('exception' => object(RuntimeException)))in Logger.php line 176
at Logger->writeLog('error', 'Curl error (code 3): <url> malformed', array('exception' => object(RuntimeException)))in Logger.php line 87
at Logger->error('Curl error (code 3): <url> malformed', array('exception' => object(RuntimeException)))in LogManager.php line 493
at LogManager->error('Curl error (code 3): <url> malformed', array('exception' => object(RuntimeException)))in Handler.php line 114
at Handler->report(object(RuntimeException))in Handler.php line 153
at Handler->report(object(RuntimeException))in HandleExceptions.php line 81
at HandleExceptions->handleException(object(RuntimeException))
```

Let me know if there is additional information I can provide that might help in isolating this issue.

**Comment by JC5** [comment]
Which version are you trying to deploy?

**Comment by JC5** [comment]
What should work regardless, is changin `LOG_CHANNEL=stack` to `LOG_CHANNEL=daily`.

**Comment by mrz** [comment]
Here's the docker-compose that I've been using:

```
networks: 
  firefly_iii_net: 
    driver: bridge
services: 
  firefly_iii_app: 
    image: jc5x/firefly-iii:latest
    depends_on:
      - firefly_iii_db
    networks: 
      - firefly_iii_net
    ports: 
      - "5080:80"
    env_file: .env
    volumes: 
      - 
        source: firefly_iii_export
        target: /var/www/firefly-iii/storage/export
        type: volume
      - 
        source: firefly_iii_upload
        target: /var/www/firefly-iii/storage/upload
        type: volume
  firefly_iii_db: 
    image: "postgres:10"
    environment:
      - POSTGRES_PASSWORD=[redacted]
      - POSTGRES_USER=firefly
    networks: 
      - firefly_iii_net
    volumes: 
      - firefly_iii_db:/var/lib/postgresql/data
version: "3.2"
volumes: 
  firefly_iii_db: ~
  firefly_iii_export: ~
  firefly_iii_upload: ~
```

so pretty much the same as [this](https://raw.githubusercontent.com/firefly-iii/docker/master/docker-compose.yml) except with the port changed.
