### ISSUE TITLE
Scripts "app.js" and "guest.js" always requested from localhost

### ISSUE THREAD

**Issue by werdck** [firefly-iii/firefly-iii#3168]
I have firefly-iii set up in a docker container via docker-compose.
The HTTP traffic is redirected via an nginx reverse-proxy.

Every time I try to use/register firefly-iii, everything except `app.js` and `guest.js` load, because every resource uses the right URL/path, except those two.
I tried firefox and chromium, so it's not a browser issue.

I have `APP_URL`, `APP_FORCE_SSL`, `APP_FORCE_ROOT` and `TRUSTED_PROXIES` set in my .env file. those vars are also set inside the container.

**Comment by JC5** [comment]
What’s your nginx configuration? See also #3167

**Comment by werdck** [comment]
I already read that issue, the solutions there didn't work.
nginx.conf:
```
server {
	listen 443 ssl;
	server_name firefly.server.domain;
  	
	ssl_certificate /etc/nginx/conf.d/server.crt;
  	ssl_certificate_key /etc/nginx/conf.d/server.key;
	
	location / {
		proxy_pass http://127.0.0.1:2001/;
		proxy_hide_header Vary;
		proxy_buffering off;
        }
}
```
firefly docker-compose.yml:
```
---
networks: 
  net1: 
    driver: bridge

services:

  firefly_iii_app: 
    image: jc5x/firefly-iii:latest
    depends_on:
      - postgres
    networks: 
      - net1
    ports:
            - "127.0.0.1:2001:80"      
    env_file: .env
    volumes: 
      - /opt/docker/data/firefly_iii_export:/var/www/firefly-iii/storage/export
      - /opt/docker/data/firefly_iii_upload:/var/www/firefly-iii/storage/upload

  postgres: 
    image: "postgres"
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=firefly
    networks: 
      - net1
    volumes: 
      - /opt/docker/data/postgres:/var/lib/postgresql/data

version: "3.2"
```
.env:
```
APP_URL=https://firefly.server.domain
APP_FORCE_SSL=true
APP_FORCE_ROOT=https://firefly.server.domain

TRUSTED_PROXIES=**
```
