### ISSUE TITLE
Error connecting to database (i think)

### ISSUE THREAD

**Issue by revilo951** [firefly-iii/firefly-iii#3476]
I am running Firefly III version v5.2.8

**Description**
using docker-compose v3, fresh install of fireflyiii and postgres10. webpage error is:

```
Whoops! An error occurred.
Unfortunately, this error was not recoverable :(. Firefly III broke. The error is:

Trying to get property 'data' of non-object
```

**Extra info**
/debug page shows the same as the homepage, see above

I installed ping in the ffiii container, and i can ping the postgres container by hostname

logs attached below. LMK if there's something else you need. hopefully it's something I've fat-fingered, but if it is, i haven't caught it yet.

[ffiii-log.txt](https://github.com/firefly-iii/firefly-iii/files/4809080/ffiii-log.txt)

**Comment by leander091** [comment]
Could you share the docker compose file used to install firefly-iii? 

It look like something is wrong with the authentication between your app and the database

**Comment by JC5** [comment]
I see a “connection refused” in the logs.

**Comment by revilo951** [comment]
my docker-compose.yml:

```
  fireflyiii:
    image: jc5x/firefly-iii:latest
    volumes:
      - /home/me/docker/firefly/export:/var/www/firefly-iii/storage/export
      - /home/me/docker/firefly/upload:/var/www/firefly-iii/storage/upload
    env_file: /home/me/docker/firefly/env/.env
    ports:
      - 85:80
    depends_on:
      - fireflyiiidb
    container_name: fireflyiii
    networks: 
      - firefly
  
  fireflyiiidb:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=firefly
      - POSTGRES_PASSWORD=secret_firefly_password
    volumes: 
      - /home/me/docker/firefly/db:/var/lib/postgresql/data
    container_name: fireflyiiidb
    networks: 
      - firefly
    ports: 
      - 3306:3306
```


the .env db creds section:
```
# Database credentials. Make sure the database exists. I recommend a dedicated user for Firefly III
# For other database types, please see the FAQ: https://docs.firefly-iii.org/support/faq
# If you use Docker or similar, you can set these variables from a file by appending them with _FILE
# Use "mysql" for MySQL and MariaDB. Use "sqlite" for SQLite.
DB_CONNECTION=mysql
DB_HOST=fireflyiiidb
DB_PORT=3306
DB_DATABASE=firefly
DB_USERNAME=firefly
DB_PASSWORD=secret_firefly_password
```
