### ISSUE TITLE
PSA: If you are using Traefik and get 'Bad Gateway' after updating to Firefly 5.3.0 here's how to fix it

### ISSUE THREAD

**Issue by Kwbmm** [firefly-iii/firefly-iii#3527]
Got the above issue, and spent some time looking into how to fix it.

Release 5.3.0 changes the port on which the service is being provided from 80 to 8080. You should inform traefik about it.

Your **firefly container** should have the following label as well:
```
traefik.http.services.firefly.loadbalancer.server.port=8080
```

Hope this can help someone.

@JC5 consider deleting this if you don't find it useful! :)

**Comment by niklas2810** [comment]
While setting up a Firefly III instance on my server with Traefik, I ran into the same issue. However, I could not use your fix to work around this issue.

Here is my config:

```yml
version: '3.3'

services:
  fireflyiii:
    image: jc5x/firefly-iii:latest
    container_name: firefly
    volumes:
      - ./data/export:/var/www/firefly-iii/storage/export
      - ./data/upload:/var/www/firefly-iii/storage/upload
    env_file: .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.firefly.rule=Host(`firefly.domain.com`)
      - traefik.http.routers.firefly.tls=true
      - traefik.http.services.firefly.loadbalancer.server.port=8080
    depends_on:
      - fireflyiiidb
    networks:
      - web
    links:
      - fireflyiiidb

  fireflyiiidb:
    image: postgres:10-alpine
    container_name: fireflyiiidb
    environment:
      - POSTGRES_USER=<removed>
      - POSTGRES_PASSWORD=<removed>
    volumes:
      - ./data/sql:/var/lib/postgresql/data

networks:
  web:
    external: true
```

`web` is the name of my Traefik network. Other services within the same instance work just fine.

This is the error message I could find in the logs:
`time="2020-08-10T20:38:25Z" level=debug msg="'502 Bad Gateway' caused by: dial tcp 172.20.0.5:8080: connect: connection refused"`

Based on the message text I guess that there's an issue with the exposed port. I'll be more than happy to provide further details on request and share more of my config with you. I've already tried upgrading the docker image + restarted the server as well as the docker images.
