### ISSUE TITLE
Unable to start release-5.3.3 (current latest)

### ISSUE THREAD

**Issue by goliath888** [firefly-iii/firefly-iii#3581]
I am trying to run Firefly III version 5.3.3 in a docker container, and my problem is:

Docker does not start. I will attach full log at the end. I started to go to previous versions and with release-5.2.0 it goes with no problem

Running in OpenMediaVault 5.5.3 (debian based OS).

Reading the logs:
```
  The stream or file "/var/www/firefly-iii/storage/logs/ff3-cli-2020-07-20.lo
  g" could not be opened: failed to open stream: Permission denied
```
 it seems permission folder related, but it is in docker, so it should not have that type of issue I think.

I cannot try this solution:
`docker exec -it <container> chown -R www-data:www-data /var/www/firefly-iii/storage`
because container does not really start, so I cannot access inside it. If I try it when is starting, it says the container is restarting. 
I have no persistent data mounted.

This is how my docker-compose looks like (with 5.2.0 port is 80 and with latest port is 8080 if I am not wrong, but anyway this should not be related with my problem). I have another container for mariadb

```
version: '3'
services: 
 firefly:
  container_name: firefly
  restart: always
  depends_on:
   - firefly-mariadb
  ports:
   - 8051:8080
  environment:
   - APP_KEY=XXXXXX
   - DB_HOST=XXXXXX
   - DB_CONNECTION=mysql
   - DB_PORT=XXXXXX

   - DB_DATABASE=XXXXXX
   - DB_USERNAME=XXXXXX
   - DB_PASSWORD=XXXXXX
  network_mode: bridge 
  image: jc5x/firefly-iii
```

[firefly.log](https://github.com/firefly-iii/firefly-iii/files/4949833/firefly.log)
