### ISSUE TITLE
Nginx and Firefly with docker

### ISSUE THREAD

**Issue by jbwittner** [firefly-iii/firefly-iii#3582]
Hey !

I am running Firefly III version v5.3.2 (docker)

**Description**
On my server i have multiple docker container. I want to use nginx (docker) to proxify my services.
But i have a problems with the nginx configuration. But i don't know what.

My docker firefly configuration :

```
version: '3.3'

services:
  fireflyiii:
    image: jc5x/firefly-iii:release-5.3.2
    volumes:
      - firefly_iii_export:/var/www/firefly-iii/storage/export
      - firefly_iii_upload:/var/www/firefly-iii/storage/upload
      - firefly_iii_html:/var/www/firefly-iii
    env_file: firefly.env
    networks:
        - firefly_iii_db
        - firefly_iii_service
        - reverse-proxy-ldap
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.20
    env_file: mysql.env
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
        - firefly_iii_db

volumes:
   firefly_iii_export:
   firefly_iii_upload:
   firefly_iii_html:
   mysql_db:

networks:
  firefly_iii_db:
  firefly_iii_service:
  reverse-proxy-ldap:
    external:
      name: authentication_ldap_service
```

My docker nginx configuration :

```
version: '3.7'

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./volumes/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./volumes/etc/nginx/certs:/etc/nginx/certs
      - firefly_iii_html:/var/www/html/firefly_iii
    ports:
      - "80:80"
      - "443:443"
    env_file: nginx.env
    networks:
      reverse-proxy-firefly_iii_service:
        aliases:
            - nginx-fireflyiii
    restart: unless-stopped

networks:
  reverse-proxy-firefly_iii_service:
    external:
      name: webapps_firefly_iii_service
volumes:
  firefly_iii_html:
    external:
      name: webapps_firefly_iii_html

```

app.conf of nginx :

```
###############
## HTTP SERVERS
###############
server {
    listen nginx-fireflyiii:80;
    server_name firefly.lan.opendoha.fr;

    return 301 https://$host$request_uri;
}

###############
## HTTPS SERVERS
###############

server {
    listen nginx-fireflyiii:443 http2;
        ssl on;
		ssl_certificate /etc/nginx/certs/server_firefly.lan.opendoha.fr.crt;
		ssl_certificate_key /etc/nginx/certs/server_firefly.lan.opendoha.fr.key;
        server_name firefly.lan.opendoha.fr;
        ssl_session_timeout 5m;
        ssl_session_cache shared:SSL:5m;

        # secure settings (A+ at SSL Labs ssltest at time of writing)
        # see https://wiki.mozilla.org/Security/Server_Side_TLS#Nginx
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers on;

        proxy_set_header X-Forwarded-For $remote_addr;

        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        server_tokens off;

        root /var/www/html/firefly_iii/public;

    # Add index.php to the list if you are using PHP
        client_max_body_size 300M;
        index index.html index.htm index.php;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;
        location ~ \.php$ {
              try_files $uri =404;
              fastcgi_pass  fireflyiii:8080;
              fastcgi_index index.php;
              fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              include fastcgi_params;

        }

        index index.php index.htm index.html;

        location / {
          try_files $uri $uri/ /index.php?$query_string;
          autoindex on;
          sendfile off;
        }
    }
```

I have define, on my host file : `127.0.0.1		firefly.lan.opendoha.fr`

After, when i try to connect to firefly on my browser i have a 502 error.

```
nginx_1  | 10.0.2.2 - - [21/Jul/2020:07:23:14 +0000] "GET / HTTP/2.0" 502 552 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36 Edg/84.0.522.40" "-"
nginx_1  | 2020/07/21 07:23:14 [error] 19#19: *10 upstream sent unsupported FastCGI protocol version: 72 while reading response header from upstream, client: 10.0.2.2, server: firefly.lan.opendoha.fr, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.2:8080", host: "firefly.lan.opendoha.fr"
```

I thinks that the problems come from the fastcgi_pass but i'm not sure.

Thanks you :)
