### ISSUE TITLE
Serious permission issues

### ISSUE THREAD

**Issue by subhamagr** [firefly-iii/firefly-iii#3747]
**Bug description**
I have my docker volumes owned by user "app" of my host machine, but the contents of "/var/www/firefly-iii" is still owned by "www-data". The containers start but all checks fails with "permission denied". But the website is unreachable.

Version: 5.3.3

**Steps to reproduce**
My Dockerfile is as follows:
```
version: "3.3"

services:
  firefly_app:
    container_name: firefly_app
    image: jc5x/firefly-iii:latest
    user: "1001:1001"
    restart: always
    depends_on:
      - firefly_postgres
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /deploy/data/firefly/storage_export:/var/www/firefly-iii/storage/export
      - /deploy/data/firefly/storage_upload:/var/www/firefly-iii/storage/upload
    env_file: .env
    ports:
      - 8401:8080
    networks:
      - dbnet

  firefly_cron:
    container_name: firefly_cron
    image: jc5x/firefly-iii:latest
    user: "1001:1001"
    restart: always
    command: sh -c "echo \"0 3 * * * /usr/local/bin/php /var/www/firefly-iii/artisan firefly-iii:cron\" | crontab - && crond -f -L /dev/stdout"
    depends_on:
      - firefly_postgres
      - firefly_app
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /deploy/data/firefly/storage_export:/var/www/firefly-iii/storage/export
      - /deploy/data/firefly/storage_upload:/var/www/firefly-iii/storage/upload
    env_file: .env
    networks:
      - dbnet

  firefly_postgres:
    container_name: firefly_postgres
    image: postgres:latest
    restart: always
    user: "1001:1001"
    environment:
      POSTGRES_USER: firefly
      POSTGRES_PASSWORD: password
      POSTGRES_DB: firefly
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /deploy/data/firefly/postgres:/var/lib/postgresql/data
    networks:
      - dbnet

networks:
  dbnet:
    driver: bridge

```

**Extra info**
logs: https://pastebin.com/jMgyEWpQ

Output from `ls -al`:
```
app@73c619a13905:/var/www/firefly-iii/storage$ ls -al
total 40
drwxrwxr-x 10 www-data www-data 4096 Jul 17 17:16 .
drwxr-xr-x  1 www-data www-data 4096 Jul 17 17:19 ..
drwxrwxr-x  3 www-data www-data 4096 Jul 17 17:16 app
drwxrwxr-x  2 www-data www-data 4096 Jul 17 17:16 build
drwxrwxr-x  2 www-data www-data 4096 Jul 17 17:16 database
drwxrwxr-x  2 www-data www-data 4096 Jul 17 17:16 debugbar
drwxr-xr-x  2 app          1001 4096 Aug 29 10:54 export
drwxrwxr-x  6 www-data www-data 4096 Jul 17 17:16 framework
drwxrwxr-x  2 www-data www-data 4096 Jul 17 17:16 logs
drwxr-xr-x  2 app          1001 4096 Aug 29 10:53 upload
```

Output of `whoami`:
```
app@73c619a13905:/var/www/firefly-iii/storage$ whoami
app
```

How do I fix the permissions? Am I doing something wrong?
