### ISSUE TITLE
CVS impoter can't use a valid token

### ISSUE THREAD

**Issue by azzamsa** [firefly-iii/firefly-iii#3750]
I am running Firefly III version **5.3.3**.

**Description**
I always got this error, even with *a valid token*:

![image](https://user-images.githubusercontent.com/17734314/91684914-01b36a80-eb83-11ea-9ee4-eeeefca4c0c7.png)

**Extra info**

```log

$ ./run-hosted.sh
Now in entrypoint.sh (v1.2) for Firefly III CSV importer.
Please wait for the container to start...
Firefly III CSV importer v2.0.5
PHP: cli 7.4.8 Linux
Will now run Apache web server:
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
[Mon Aug 31 05:04:17.579373 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.4.8 OpenSSL/1.1.1d configured -- resuming normal operations
[Mon Aug 31 05:04:17.579402 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[2020-08-31 07:05:27] production.DEBUG: Now at App\Http\Controllers\IndexController::index
172.17.0.1 - - [31/Aug/2020:05:05:26 +0000] "GET / HTTP/1.1" 200 2338 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0"
172.17.0.1 - - [31/Aug/2020:05:05:27 +0000] "GET /fa/css/all.min.css HTTP/1.1" 200 13013 "http://127.0.0.1:8082/" "Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0"
172.17.0.1 - - [31/Aug/2020:05:05:27 +0000] "GET /js/popper.min.js?version=2.0.5 HTTP/1.1" 200 7847 "http://127.0.0.1:8082/" "Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0"
172.17.0.1 - - [31/Aug/2020:05:05:27 +0000] "GET /css/bootstrap.min.css?version=2.0.5 HTTP/1.1" 200 23577 "http://127.0.0.1:8082/" "Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0"
172.17.0.1 - - [31/Aug/2020:05:05:27 +0000] "GET /js/bootstrap.min.js?version=2.0.5 HTTP/1.1" 200 15790 "http://127.0.0.1:8082/" "Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0"
172.17.0.1 - - [31/Aug/2020:05:05:27 +0000] "GET /js/jquery-3.4.1.min.js?version=2.0.5 HTTP/1.1" 200 31031 "http://127.0.0.1:8082/" "Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0"
172.17.0.1 - - [31/Aug/2020:05:05:27 +0000] "GET /fa/webfonts/fa-solid-900.woff2 HTTP/1.1" 304 182 "http://127.0.0.1:8082/fa/css/all.min.css" "Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0"
127.0.0.1 - - [31/Aug/2020:05:05:32 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.38 (Debian) PHP/7.4.8 OpenSSL/1.1.1d (internal dummy connection)"
[2020-08-31 07:05:58] production.ERROR: Return value of App\Http\Controllers\TokenController::doValidate() must be an instance of Illuminate\Http\JsonResponse, array returned {"exception":"[object] (TypeError(code: 0): Return value of App\\Http\\Controllers\\TokenController::doValidate() must be an instance of Illuminate\\Http\\JsonResponse, array returned at /var/www/html/app/Http/Controllers/TokenController.php:58)
[stacktrace]
#0 [internal function]: App\\Http\\Controllers\\TokenController->doValidate()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\\Routing\\Route->runController()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Route->run()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#35 /var/www/html/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#37 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#42 /var/www/html/public/index.php(99): Illuminate\\Foundation\\Http\\Kernel->handle()
#43 {main}
"}
172.17.0.1 - - [31/Aug/2020:05:05:27 +0000] "GET /token/validate HTTP/1.1" 500 1145 "http://127.0.0.1:8082/" "Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0"
127.0.0.1 - - [31/Aug/2020:05:05:58 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.38 (Debian) PHP/7.4.8 OpenSSL/1.1.1d (internal dummy connection)"
172.17.0.1 - - [31/Aug/2020:05:05:58 +0000] "GET /token HTTP/1.1" 200 2201 "http://127.0.0.1:8082/" "Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0"
^C[Mon Aug 31 05:10:55.453428 2020] [mpm_prefork:notice] [pid 1] AH00169: caught SIGTERM, shutting down
^C
```

```bash
PERSONAL_ACCESS_TOKEN=eyJ0...

FIREFLY_III_URI=http://172.19.0.3:80

docker run \
--rm \
-e FIREFLY_III_ACCESS_TOKEN=$PERSONAL_ACCESS_TOKEN \
-e FIREFLY_III_URI=$FIREFLY_III_URI \
-p 8082:80 \
fireflyiii/csv-importer:latest
```

**Bonus points**

- I have read the FAQ at https://bit.ly/FF3-FAQ
- I added a screenshot
- I added log files

**Comment by JC5** [comment]
It’s a timeout. The token isn’t tried.

**Comment by azzamsa** [comment]
any suggestions? I've tried to run it multiple times.

**Comment by JC5** [comment]
Firefly III Docker container runs on port 8080. Are they in the same network? Can they reach each other?

**Comment by azzamsa** [comment]
I tried using:

- FIREFLY_III_URI=http://172.19.0.3
- FIREFLY_III_URI=http://172.19.0.3:8080
- FIREFLY_III_URI=http://172.19.0.3:80

But none of them works.

Is [this one forward-slash](https://github.com/firefly-iii/csv-importer-docker/blob/main/run-hosted.sh#L13) intended?

---

I tried to telnet from csv-importer container, it doesn't connect:

```bash
root@be33b1f04ad7:/var/www/html# telnet 172.19.0.3 80
Trying 172.19.0.3...
^C
root@be33b1f04ad7:/var/www/html# telnet 172.19.0.3 8080
Trying 172.19.0.3...
^C
```

```bash
$ docker ps
CONTAINER ID        IMAGE                               COMMAND             CREATED             STATUS              PORTS                          NAMES
be33b1f04ad7        fireflyiii/csv-importer:latest      "/entrypoint.sh"    10 minutes ago      Up 10 minutes       0.0.0.0:8082->80/tcp           determined_mclaren
bb1dbaead729        jc5x/firefly-iii:latest             "/entrypoint.sh"    8 hours ago         Up About an hour    80/tcp, 0.0.0.0:80->8080/tcp   firefly_fireflyiii_1
a8a42cbb5d08        yobasystems/alpine-mariadb:latest   "/scripts/run.sh"   8 hours ago         Up About an hour    3306/tcp                       firefly_fireflyiiidb_1

```

Then I make sure that **yes, they are on different networks**

```bash
$ docker inspect bb1dbaead729  -f "{{json .NetworkSettings.Networks }}"
{"firefly_default":{"IPAMConfig":null,"Links":null,"Aliases":["fireflyiii","bb1dbaead729"],"NetworkID":"525ac8f472e7789ab9a0b1f9201833e2c44428f3798b04e92c29bd262087fe0b","EndpointID":"1480d3b862808bf8b2edc11cc27245a854c06f89c7588b90ca75704e8bd1a6e7","Gateway":"172.19.0.1","IPAddress":"172.19.0.3","IPPrefixLen":16,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"02:42:ac:13:00:03","DriverOpts":null}}

$ docker inspect be33b1f04ad7   -f "{{json .NetworkSettings.Networks }}"
{"bridge":{"IPAMConfig":null,"Links":null,"Aliases":null,"NetworkID":"a918f112e8c609b6730067728ece4c44298407d9286e99c83e111800a0247aa5","EndpointID":"0685a3e41207de8d75fed836258fd27be92c57ad15568302b705b64d0e1cb301","Gateway":"172.17.0.1","IPAddress":"172.17.0.2","IPPrefixLen":16,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"02:42:ac:11:00:02","DriverOpts":null}}

$ docker inspect a8a42cbb5d08     -f "{{json .NetworkSettings.Networks }}"
{"firefly_default":{"IPAMConfig":null,"Links":null,"Aliases":["a8a42cbb5d08","fireflyiiidb"],"NetworkID":"525ac8f472e7789ab9a0b1f9201833e2c44428f3798b04e92c29bd262087fe0b","EndpointID":"9ac5ce0a292a470ba730125c87d132234f458a857d0b3c43f0e8e7cf9c473484","Gateway":"172.19.0.1","IPAddress":"172.19.0.2","IPPrefixLen":16,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"02:42:ac:13:00:02","DriverOpts":null}}
```

Now I want to run them together with other, so that it use same network:


```yaml
version: '3.3'

services:
  fireflyiii:
    image: jc5x/firefly-iii:latest
    volumes:
      - firefly_iii_export:/var/www/firefly-iii/storage/export
      - firefly_iii_upload:/var/www/firefly-iii/storage/upload
    env_file: .env
    ports:
      - 80:8080
    depends_on:
      - fireflyiiidb
  fireflyiiidb:
    image: yobasystems/alpine-mariadb:latest
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly
    volumes:
      - firefly_iii_db:/var/lib/mysql
  fireflyiii-csv-importer:
    image: fireflyiii/csv-importer:latest
    ports:
      - 80:8081
    environment:
      - FIREFLY_III_URI=fireflyiii
      - PERSONAL_ACCESS_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI1IiwianRpIjoiZWFiNWIxM2ZhMDUxOWYxMGFkNTM0YjdlY2VhZjVmZTc1YjA5YjNmMDQ0MmQxNWVkODEyMzdkNTFiODMxM2ZlMWY4NDZlM2EzMjlmOWNmMDQiLCJpYXQiOjE1OTg4NDk3MDUsIm5iZiI6MTU5ODg0OTcwNSwiZXhwIjoxNjMwMzg1NzA1LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.gazc69BEpqgIylERe38_ln0rt42oJJqw0G8W_oBq8b2RfuliayOLr3eNdSetUsFSSu46RMryg-UF_vqlpRRfnxU4zM8CH7LKJxJfTZXoayRfeoxXInI82pIRVzlLV4qcPC6Ms3hAnXuN0mCC9xZEzp6yIVAVWOi5jU6Xar4l_zhfLlBEl5gflvD6InSUwYjhrBreKVXaYyduYyZ0I2RZz4bSfK89kYtnp3wNyvo-qlzVqtTUzDPhsGPXyfme2LbZ0F1BxeCJE9_2EVvkLjqkweDZBtxJVUEsWdPTXN8-Xhk1Hee-aourjKYHXiVqHZoOyp6Yh1RNe9cq6VlzgAKPNEdReReW3SiKJmHkAFrSQPkrWutruN7QIlBv6hBO5D-nY9QdnvDqLF5FaHHBRTiRiyYIvBWbbIpcHUaPAEuQtE986LkKSBt6kdXZdEiTK63-ye_04KQ378ukSKjTcQ6WMNGtQZ-MwClvsiBHnndfMxoWWJui5G3TrBW2cLomwhIk13HhJh9UawMhTkoNfxUJAWET4Sl5KdHmxJNTN4Nwd7LwRgAkqkXMTCBDtiCabpzp5E1CCnYSf5O9EHzCXweNCtSqgTAVpAeWJF8rl84_qmRQEP00H0L-NpewRm6g3oPzQbDuKtkBWQ14Q9lV3_NLiCHWZzVlEsJ2aOeevfLCqoU


volumes:
   firefly_iii_export:
   firefly_iii_upload:
   firefly_iii_db:
```

Sadly, port `80` is already used by firefly, any ideas?

**Comment by psychowood** [comment]
My conf is quite similar to yours (same docker-compose.yml), this is my importer section:

```yaml
  fireflyiiiimporter:
    image: fireflyiii/csv-importer:develop
    environment:
      - FIREFLY_III_ACCESS_TOKEN=$IMPORTER_PERSONAL_ACCESS_TOKEN
      - FIREFLY_III_URI=http://fireflyiii:8080
      - JSON_CONFIGURATION_DIR=/configurations
    volumes:
      - ./importer/configurations:/configurations
    restart: unless-stopped
    ports:
      - 8082:80
    depends_on:
      - fireflyiii
```

- Change the mapped port to something unused
- Add a depends_on if you want (should not be needed)
- Check the uri
- Don't publish your token online ;)

**Comment by konwin** [comment]
> Sadly, port `80` is already used by firefly, any ideas?

it must be
```  fireflyiii-csv-importer:
    image: fireflyiii/csv-importer:latest
    ports:
      - 8081:80
```
Then you should access the csv importer via http://yourfireflydomain:8081

**Comment by azzamsa** [comment]
Great, thanks @psychowood and @konwin.

I will put my complete config here so people can copy-paste.

```yaml
version: '3.3'

services:
  fireflyiii:
    image: jc5x/firefly-iii:latest
    volumes:
      - firefly_iii_export:/var/www/firefly-iii/storage/export
      - firefly_iii_upload:/var/www/firefly-iii/storage/upload
    env_file: .env
    ports:
      - 80:8080
    depends_on:
      - fireflyiiidb
  fireflyiiidb:
    image: yobasystems/alpine-mariadb:latest
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly
    volumes:
      - firefly_iii_db:/var/lib/mysql
  fireflyiiicsvimporter:
    image: fireflyiii/csv-importer:latest
    ports:
      - 8082:80
    environment:
      - FIREFLY_III_URI=http://fireflyiii:8080
      - FIREFLY_III_ACCESS_TOKEN=eyJ0...

volumes:
   firefly_iii_export:
   firefly_iii_upload:
   firefly_iii_db:

```

to see the ports used by the container, use `docker-compose ps`.

```

$ docker-compose ps
             Name                     Command       State              Ports
----------------------------------------------------------------------------------------
firefly_fireflyiii_1              /entrypoint.sh    Up      80/tcp, 0.0.0.0:80->8080/tcp
firefly_fireflyiiicsvimporter_1   /entrypoint.sh    Up      0.0.0.0:8082->80/tcp
firefly_fireflyiiidb_1            /scripts/run.sh   Up      3306/tcp
```

Now you can access firefly csv importer in ` 0.0.0.0:8082`
