### ISSUE TITLE
arm7: raspberry pi 4: firefly iii - docker doesn't run anymore

### ISSUE THREAD

**Issue by josefbachmann** [firefly-iii/firefly-iii#3848]
**Bug description**
I am running Firefly III docker version jc5x/firefly-iii stable, container id: 9c2e8dee646a, downloaded 2 days ago (2020-09-21) (627MB) for arm7 and my problem is that the container won't run anymore:

`docker logs firefly`:

**`standard_init_linux.go:211: exec user process caused "exec format error"`**

**Steps to reproduce**

Installed on raspberry PI 4 B, 4 GB:

From docker-compose file:
```
# Firefly
  firefly-db:
    image: postgres
    container_name: firefly-db
    logging:
      driver: "json-file"
      options:
        max-size: "900k"
        max-file: "5"
    restart: unless-stopped
    volumes:
      - ./firefly/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=firefly
      - POSTGRES_USER=firefly
      - POSTGRES_PASSWORD=xyz

  firefly:
    depends_on:
      - firefly-db
    image: jc5x/firefly-iii:latest
    container_name: firefly
    environment:
      - APP_KEY=appkey
      - DB_HOST=firefly-db
      - DB_PORT=5432
      - DB_DATABASE=firefly
      - DB_USERNAME=firefly
      - DB_PASSWORD=xyz
      - APP_URL=https://money.mydomain.xyz
      - TRUSTED_PROXIES=**
    volumes:
        - ./firefly/export:/var/www/firefly-iii/storage/export
        - ./firefly/upload:/var/www/firefly-iii/storage/upload
    logging:
      driver: "json-file"
      options:
        max-size: "900k"
        max-file: "5"
    restart: unless-stopped
    healthcheck:
      test: curl --fail -s http://firefly:8080/ || exit 1
      interval: 2m
      timeout: 10s
      retries: 3
```

**Extra info**

Linux server 5.4.51-v7l+  SMP **armv7l** GNU/Linux
