### ISSUE TITLE
"The connection was reset" in CVS impoter for self-hosted firefly

### ISSUE THREAD

**Issue by azzamsa** [firefly-iii/firefly-iii#3890]
I am running Firefly III version 5.4.2

**Description**
I use this config do CSV import on my local machine. it works, not problem at all:

``` yml
version: '3.3'

services:
  fireflyiii:
    image: jc5x/firefly-iii:latest
    volumes:
      - firefly_iii_export:/var/www/firefly-iii/storage/export
      - firefly_iii_upload:/var/www/firefly-iii/storage/upload
    env_file: .env
    ports:
      - 80:8080
    depends_on:
      - fireflyiiidb
  fireflyiiidb:
    image: yobasystems/alpine-mariadb:latest
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly
    volumes:
      - firefly_iii_db:/var/lib/mysql
  fireflyiiicsvimporter:
    image: fireflyiii/csv-importer:latest
    ports:
      - 8082:80
    environment:
      - FIREFLY_III_URI=http://fireflyiii:8080
      - FIREFLY_III_ACCESS_TOKEN=eyJ0...

volumes:
   firefly_iii_export:
   firefly_iii_upload:
   firefly_iii_db:
```

Then, I decide to use the same config in self-hosted machine, with slightly modification *(only changing the ports)*.

``` yml
services:
  fireflyiii:
    image: jc5x/firefly-iii:version-5.4.2
    volumes:
      - firefly_iii_upload:/var/www/firefly-iii/storage/upload
    env_file: .env
    ports:
      - 8081:8080 # ⚠  I change 80 to 8081
    depends_on:
      - fireflyiiidb
  fireflyiiidb:
    image: yobasystems/alpine-mariadb:10.4.13
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=firefly
    volumes:
      - firefly_iii_db:/var/lib/mysql
  fireflyiiicsvimporter:
    image: fireflyiii/csv-importer:latest
    ports:
      - 8082:80
    environment:
      - FIREFLY_III_URI=http://fireflyiii:8080
      - FIREFLY_III_ACCESS_TOKEN=ey...

```

I have no probem accessing firefly from `http://MYIP:8081/`. But **I can't open the importer in `http://MYIP:8082/`**. I always get `The connection was reset`.

I've tried to use:

- `FIREFLY_III_URI=http://fireflyiii:8080`
- `FIREFLY_III_URI=http://firflyiii-docker-ip:8081` [from importer doc](https://firefly-iii.gitbook.io/firefly-iii-csv-importer/installing-and-running/configure#url-or-ip)
- `FIREFLY_III_URI=http://MYIP:8081`

But nothing works.

**Extra info**
Take a note that in local machine, I use 5.3.3, and I try to use 5.4.2 in self-hosted machine.

I am able to interact with firefly and its database in `http://MYIP:8081/` with no problem.

**Bonus points**

- [X] I have read the FAQ at https://bit.ly/FF3-FAQ
- I added a screenshot
- I added log files 
- I was able to replicate the issue on the demo site.
