### ISSUE TITLE
Firefly III CSV Import Tool - Failed to connect to 172.18.0.3 port 443: Connection refused 

### ISSUE THREAD

**Issue by rolfbe** [firefly-iii/firefly-iii#3912]
I am running Firefly III version 5.4.3 which is deployed using docker compose and it is running on the standard port 80.

**Description**
When installing the CSV Import Tool, everything goes ok, but when accessing the the website it shows an error; 

`cURL error 7: Failed to connect to 172.18.0.3 port 443: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)`

![afbeelding](https://user-images.githubusercontent.com/49622053/95189662-70ad6000-07ce-11eb-8fb8-c83baae9f955.png)

and i dont know what i'm doing wrong.

I used the following command to deploy the CSV import Tool

```
docker run \
--rm \
-e FIREFLY_III_ACCESS_TOKEN=ey......
-e FIREFLY_III_URI=http://172.18.0.3 \
-p 8081:8080 \
fireflyiii/csv-importer:latest
```

After that i used portainer to join them in the same network (fireflyiii_default).  And then the error show up..

Can someone point me in the right direction?

**Comment by Refferic** [comment]
I've got a similar problem; 

`Tried "http://xxx.xxx.x.xxx:8080/api/v1/about" 5 times but failed: cURL error 28: Connection timed out after 31415 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)`

Console error;
`DevTools failed to load SourceMap: Could not load content for http://xxx.xxx.x.xxx:8081/js/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

Initiated by;
`http://xxx.xxx.x.xxx:8081/js/jquery-3.4.1.min.js?version=2.2.1`

**Comment by JC5** [comment]
* Connection refused means that the server exists and sees the connection but actively blocks it. It could be the wrong port, a firewall or another misconfiguration. But the server is present. I'm surprised that the connection is refused on port 443, while your configuration seems to connect to port 80. Do you have a TLS connection in place? Is nginx forwarding to port 443 for example?
* Timeouts mean that the IP isn't reachable from the CSV importer at all. Either the network doesn't exist, the IP is blocked or something else is blocking the connection.

Assuming you're both using Docker both VM's must be in the same network / subnet or must reach each other through the outside.

The DevTools error isn't relevant.

**Comment by Refferic** [comment]
In my case, what's causing the timeout is that my Firefly instance is located at; 192.168.1. In the config of the CSV importer, the correct IP is present at the FIREFLY_III_URL (192.168.1) but the error message states Tried "http://192.168.0... That's the problem at my end.

**Comment by Refferic** [comment]
After clearing my cookies & temp. browser data, and using the "reauth" button, it now works.

**Comment by rolfbe** [comment]
I have changed the ip adres from the donker ip. To the real ip adres and now it works.

**Comment by rster2002** [comment]
Will ask here to not create another issue. I've been trying to get Firefly and the CSV importer to play nice with eachother but haven't been successful after two hours of head scratching. Here's what I've done so far:

* From the [documentation](https://firefly-iii.gitbook.io/firefly-iii-csv-importer/installing-and-running/docker)
  * **Web server with personal access token**: Causes a cURL error 7 could not connect to localhost port 8090 connection refused
  * **Web server with a client ID**: Shows the auth dialog from my Firefly instance, then shows authentication confirmation and then shows a page with 500 server error. The docker container shows the following: [full-log.txt](https://github.com/firefly-iii/firefly-iii/files/5392010/full-log.txt)
    * When manually navigating to `http://localhost:8090/oauth/token` there's an error: `405 method not allowed`. Don't know if this is expected behavior when pasting the url into the browser, but thought I'd mention it.
  * **Web server with no configuration**: The same as Web server with personal access token
* Tried setting different ip addresses retrieved from using the [command](https://firefly-iii.gitbook.io/firefly-iii-csv-importer/installing-and-running/docker#docker-and-ip-addresses) from the docs. Resulted in a timeout.
* Tried adding it to the docker compose file that starts the Firefly instance and DB, but no different results.

To be honest, there is probably something *I'm* not doing correctly, but I really can't figure out what I'm doing wrong.

If you need more information to help, just ask.

**Comment by rster2002** [comment]
Tried doing this using the following steps:
**Show the running containers**
```
docker ps
```
```
CONTAINER ID        IMAGE                               COMMAND                  CREATED              STATUS              PORTS                    NAMES
e3e5b7231be3        fireflyiii/csv-importer:latest      "/usr/local/bin/entr…"   About a minute ago   Up 59 seconds       0.0.0.0:8081->8080/tcp   compassionate_keller
1022b5590012        jc5x/firefly-iii:latest             "/usr/local/bin/entr…"   3 hours ago          Up 2 hours          0.0.0.0:8090->8080/tcp   fireflyiii
4ac5956ff2b7        yobasystems/alpine-mariadb:latest   "/scripts/run.sh"        4 days ago           Up 2 hours          3306/tcp                 firefly3_fireflyiiidb_1
```

**Get the internal IP address**
```
docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' 1022b5590012
```
```
'172.18.0.4'
```

**Run the container**
```
docker run --rm -e FIREFLY_III_ACCESS_TOKEN=<token> -e FIREFLY_III_URI=http://172.18.0.4:8080 -p 8081:8080 fireflyiii/csv-importer:latest
```

CSV importer shows a timeout when trying to authenticate.

**Comment by JC5** [comment]
Are the docker containers in the same network?

**Comment by rster2002** [comment]
I've added the configuration for the importer to the docker-composer.yml as show below so I think they are:

```yml
version: '3.3'

services:
  fireflyiii:
    container_name: fireflyiii
    image: jc5x/firefly-iii:latest
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - 8090:8080
    depends_on:
      - fireflyiiidb
  fireflyiiidb:
    image: yobasystems/alpine-mariadb:latest
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly
    volumes:
      - firefly_iii_db:/var/lib/mysql
  fireflyimport:
    image: fireflyiii/csv-importer:latest
    environment:
      - FIREFLY_III_ACCESS_TOKEN=<token>
      - FIREFLY_III_URI=http://172.18.0.4:8080
      - FIREFLY_III_CLIENT_ID=16
    ports:
      - 8091:8080
volumes:
   firefly_iii_upload:
   firefly_iii_db:
```

**Comment by rster2002** [comment]
I got it working using the above config. I think it might have had something to do with that the Firefly container was started using docker-compose, and the CSV Importer was started using the `docker run` command.

Thanks for spending time on my stupid issue 🥇  appreciate it!

**Comment by lhindir** [comment]
I'm using docker-compose and getting `cURL error 7: Failed to connect to firefly-iii port 80: Connection refused` despite specifying `FIREFLY_III_URI=http://firefly-iii:8080` in the environment section. I opened a shell in the csv container and verified that `curl http://firefly-iii` fails and `curl http://firefly-iii:8080` works. Does the CSV importer parse the port in the environment variable? If you're confused by the `firefly-iii` hostname, note that docker-compose allows containers on the same network to access each other by name via DNS it sets up.

**Comment by hamun8** [comment]
> I've added the configuration for the importer to the docker-composer.yml as show below so I think they are in the same network:
> 
> ```yaml
> version: '3.3'
> 
> services:
>   fireflyiii:
>     container_name: fireflyiii
>     image: jc5x/firefly-iii:latest
>     volumes:
>       - firefly_iii_upload:/var/www/html/storage/upload
>     env_file: .env
>     ports:
>       - 8090:8080
>     depends_on:
>       - fireflyiiidb
>   fireflyiiidb:
>     image: yobasystems/alpine-mariadb:latest
>     environment:
>       - MYSQL_RANDOM_ROOT_PASSWORD=yes
>       - MYSQL_USER=firefly
>       - MYSQL_PASSWORD=secret_firefly_password
>       - MYSQL_DATABASE=firefly
>     volumes:
>       - firefly_iii_db:/var/lib/mysql
>   fireflyimport:
>     image: fireflyiii/csv-importer:latest
>     environment:
>       - FIREFLY_III_ACCESS_TOKEN=<token>
>       - FIREFLY_III_URI=http://172.18.0.4:8080
>     ports:
>       - 8091:8080
> volumes:
>    firefly_iii_upload:
>    firefly_iii_db:
> ```

I tried your docker-composer.yml but get the following errror 
![image](https://user-images.githubusercontent.com/30229385/100478232-ce816880-30ea-11eb-9e97-8e11fddca8f2.png)

What do you have in you .env file?

**Comment by rster2002** [comment]
So I'll just show my whole installation process from start to finish to make it as clear as possible. This is my method to get a complete installation of firefly iii

### Step 1
Create a folder somewhere on your pc and create a file called `docker-compose.yml`. Paste the following into that file:

```yml
version: '3.3'

services:
  fireflyiii:
    container_name: fireflyiii
    image: jc5x/firefly-iii:latest
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - 8090:8080
    depends_on:
      - fireflyiiidb
  fireflyiiidb:
    image: yobasystems/alpine-mariadb:latest
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly
    volumes:
      - firefly_iii_db:/var/lib/mysql
  fireflyimport:
    image: fireflyiii/csv-importer:latest
    environment:
      - FIREFLY_III_ACCESS_TOKEN=<token>
      - FIREFLY_III_URI=<host>:8080
    ports:
      - 8091:8080
volumes:
   firefly_iii_upload:
   firefly_iii_db:
```

### Step 2
Next we need to add the .env file from the website to the folder which you can download from [here](https://raw.githubusercontent.com/firefly-iii/firefly-iii/main/.env.example). Place it in the same folder as your `docker-compose.yml` file.

### Step 3
Open a terminal in the folder where your `docker-compose.yml` file is located and run `docker-compose up`. Wait for it to start and then head to your filefly iii instance (if you didn't modify the `docker-compose.yml` file it should be located at [http://localhost:8090](http://localhost:8090)) create an account or log in as usual.

### Step 4
Go to your profile's OAuth settings (located under Options > Profile). Scroll down to 'personal access tokens' and create a new token. Copy the generated token to your clipboard. Go back to your `docker-compose.yml` file and replace `<token>` in the environment variables of the importer (line 26)

### Step 5
Open a terminal window and run `docker ps`. Locate the container of the fireflyiii and copy the container id (do not copy the container id of the db or the importer). Then run `docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' 1022b5590012` and copy the given ip address. Replace `<host>` in your `docker-compose.yml` file with this ip address.

### Step 6
Shut down the containers and restart them again. Now if you navigate to [http://localhost:8091](http://localhost:8091) you should be able to use the importer (you might need to click 'Reauthenticate')

I hope this clears up and confusion on how to get it working. But if you are still stuck, please don't hesitate to leave a comment.
