### ISSUE TITLE
Empty HTTP reply from Firefly upon upgrading docker image to 5.4.3

### ISSUE THREAD

**Issue by randomshinichi** [firefly-iii/firefly-iii#3979]
**Bug description**
I am running Firefly III version 5.4.3, and my problem is:

I seem to be receiving no HTTP response from the docker container (using the docker-compose method).

```
root@vps635048:~/firefly# curl -v localhost:2001
* Rebuilt URL to: localhost:2001/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 2001 (#0)
> GET / HTTP/1.1
> Host: localhost:2001
> User-Agent: curl/7.58.0
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```

Could it have something to do with this error?
```
firefly_iii_app_1  | Report on empty objects finished in 0.05 seconds
firefly_iii_app_1  | Amount integrity OK for user #1
firefly_iii_app_1  | Report on total sum finished in 0.02 seconds
firefly_iii_app_1  | [2020-10-22 17:34:08] local.DEBUG: Going to restoreOAuthKeys()  
firefly_iii_app_1  | [2020-10-22 17:34:08] local.DEBUG: Keys are in DB and keys are not on the drive. Restore.  
firefly_iii_app_1  | [2020-10-22 17:34:08] local.ERROR: The MAC is invalid. {"exception":"[object] (Illuminate\\Contracts\\Encryption\\DecryptException(code: 0): The MAC is invalid. at /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:199)
firefly_iii_app_1  | [stacktrace]
firefly_iii_app_1  | #0 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php(136): Illuminate\\Encryption\\Encrypter->getJsonPayload()
firefly_iii_app_1  | #1 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Encryption\\Encrypter->decrypt()
firefly_iii_app_1  | #2 /var/www/html/app/Support/System/OAuthKeys.php(72): Illuminate\\Support\\Facades\\Facade::__callStatic()
firefly_iii_app_1  | #3 /var/www/html/app/Console/Commands/Integrity/RestoreOAuthKeys.php(91): FireflyIII\\Support\\System\\OAuthKeys::restoreKeysFromDB()
firefly_iii_app_1  | #4 /var/www/html/app/Console/Commands/Integrity/RestoreOAuthKeys.php(110): FireflyIII\\Console\\Commands\\Integrity\\RestoreOAuthKeys->restoreKeysFromDB()
firefly_iii_app_1  | #5 /var/www/html/app/Console/Commands/Integrity/RestoreOAuthKeys.php(57): FireflyIII\\Console\\Commands\\Integrity\\RestoreOAuthKeys->restoreOAuthKeys()
firefly_iii_app_1  | #6 [internal function]: FireflyIII\\Console\\Commands\\Integrity\\RestoreOAuthKeys->handle()
firefly_iii_app_1  | #7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): call_user_func_array()
firefly_iii_app_1  | #8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
firefly_iii_app_1  | #9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure()
firefly_iii_app_1  | #10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(39): Illuminate\\Container\\BoundMethod::callBoundMethod()
firefly_iii_app_1  | #11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\\Container\\BoundMethod::call()
firefly_iii_app_1  | #12 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call()
firefly_iii_app_1  | #13 /var/www/html/vendor/symfony/console/Command/Command.php(258): Illuminate\\Console\\Command->execute()
firefly_iii_app_1  | #14 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
firefly_iii_app_1  | #15 /var/www/html/vendor/symfony/console/Application.php(920): Illuminate\\Console\\Command->run()
firefly_iii_app_1  | #16 /var/www/html/vendor/symfony/console/Application.php(266): Symfony\\Component\\Console\\Application->doRunCommand()
firefly_iii_app_1  | #17 /var/www/html/vendor/symfony/console/Application.php(142): Symfony\\Component\\Console\\Application->doRun()
firefly_iii_app_1  | #18 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
firefly_iii_app_1  | #19 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
firefly_iii_app_1  | #20 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
firefly_iii_app_1  | #21 {main}
firefly_iii_app_1  | "} 
firefly_iii_app_1  | 
firefly_iii_app_1  | In Encrypter.php line 199:
firefly_iii_app_1  |                        
firefly_iii_app_1  |   The MAC is invalid.  
firefly_iii_app_1  |                        
firefly_iii_app_1  | 
firefly_iii_app_1  | Generating new OAuth keys...
firefly_iii_app_1  | Encryption keys generated successfully.
firefly_iii_app_1  | [2020-10-22 17:34:09] local.INFO: OAuth client generated but no user associated.  
firefly_iii_app_1  | Personal access client created successfully.
firefly_iii_app_1  | Client ID: 33
firefly_iii_app_1  | Client secret: yC4cDKjPApnuiUqn8g78wa8Yxu5RvRi9RTZCbXpY
firefly_iii_app_1  | [2020-10-22 17:34:09] local.INFO: OAuth client generated but no user associated.  
firefly_iii_app_1  | Password grant client created successfully.
firefly_iii_app_1  | Client ID: 34
firefly_iii_app_1  | Client secret: WSzz112vd2Wd1bWdIFaCJmOr3OH6ycKZuyRerPrV
firefly_iii_app_1  | Updated version.
firefly_iii_app_1  | +------------------------------------------------------------------------------+
firefly_iii_app_1  | |                                                                              |
firefly_iii_app_1  | | Thank you for installing Firefly III, v5.4.3!                                |
firefly_iii_app_1  | |                                                                              |
firefly_iii_app_1  | |                                                                              |
firefly_iii_app_1  | +------------------------------------------------------------------------------+
```

docker-compose.yml
```
networks: 
  firefly_iii_net: 
    driver: bridge
services: 
  firefly_iii_app: 
    image: jc5x/firefly-iii:latest
    depends_on:
      - firefly_iii_db
    networks: 
      - firefly_iii_net
    ports: 
      - "127.0.0.1:2001:80"
    env_file: .env
    volumes: 
      - 
        source: firefly_iii_export
        target: /var/www/firefly-iii/storage/export
        type: volume
      - 
        source: firefly_iii_upload
        target: /var/www/firefly-iii/storage/upload
        type: volume
  firefly_iii_db: 
    image: "postgres:10"
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=firefly
    networks: 
      - firefly_iii_net
    volumes: 
      - firefly_iii_db:/var/lib/postgresql/data
version: "3.2"
volumes: 
  firefly_iii_db: ~
  firefly_iii_export: ~
  firefly_iii_upload: ~
```

**Steps to reproduce**
1. Have existing data (several years' worth) in docker container of older Firefly version.
2. Somehow it stopped.
3. Run  `docker pull jc5x/firefly-iii:latest`
4. rerun docker-compose up on latest (5.4.3) docker image.

**Extra info**
Host: Ubuntu 18 LTS

```
root@vps635048:~/firefly# curl -v localhost:2001/debug
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 2001 (#0)
> GET /debug HTTP/1.1
> Host: localhost:2001
> User-Agent: curl/7.58.0
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```

**Bonus points**

TRUE - I searched and nobody reported this bug before
TRUE - I have added a stack trace from my log files 
FALSE - I have added a screenshot.
FALSE - I was able to replicate it on the demo site https://demo.firefly-iii.org/
