### ISSUE TITLE
[CSV Importer] Invalid Response after authenticated to firefly III

### ISSUE THREAD

**Issue by stroskler** [firefly-iii/firefly-iii#4036]
I am running Firefly III version 5.4.5 and CSV-import version 2.2.2

**Description**
I am using Firefly III in a docker setup. I have:
- Nginx Proxy Manager with DB
- Firefly III
- Firefly CSV Importer

**Extra info**
Ubuntu 20.04
Docker: version 19.03.8, build afacb8b7f0
docker-compose: version 1.25.0, build unknown

docker-compose.yml
```
version: '3.3'

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '8081:80'
      - '8181:81'
      - '8843:443'
    volumes:
      - ./prxmgr/config.json:/app/config/production.json
      - ./prxmgr/data:/data
      - ./prxmgr/letsencrypt:/etc/letsencrypt
    networks:
      - finance
  db:
    image: 'jc21/mariadb-aria:10.4'
    environment:
      MYSQL_ROOT_PASSWORD: 'user_prx'
      MYSQL_DATABASE: 'user_prx'
      MYSQL_USER: 'user_prx'
      MYSQL_PASSWORD: 'somepassword'
    volumes:
      - ./prxmgr/data/mysql:/var/lib/mysql
    networks:
      - finance

  fireflyiii:
    image: jc5x/firefly-iii:latest
    volumes:
      - ./upload/:/var/www/html/storage/upload
    env_file: .env
    depends_on:
      - fireflyiiidb
    networks:
      - finance
  
  fireflyiiidb:
    image: yobasystems/alpine-mariadb:latest
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=somepassword
      - MYSQL_DATABASE=firefly
    volumes:
      - ./db/:/var/lib/mysql
    networks:
      - finance
  
  firefly-csv:
    image: fireflyiii/csv-importer:latest
    env_file: .csv.env
    volumes:
      - ./import/:/import
    depends_on:
      - fireflyiii
    networks:
      - finance

networks:
  finance:
```
Logs:
```
# after allow the csv importer in firefly
throw_unless()
in /var/www/html/app/Http/Controllers/TokenController.php (line 183)
        $baseURL      = (string) $request->session()->pull('form_base_url');        $code         = $request->get('code');        throw_unless(            strlen($state) > 0 && $state === $request->state,            InvalidArgumentException::class        );        $finalURL = sprintf('%s/oauth/token', $baseURL);        $params   = [            'form_params' => [                'grant_type'    => 'authorization_code',
```
Docker Logs
```
firefly-csv_1   | [2020-11-04 19:23:35] local.DEBUG: Now at App\Http\Controllers\TokenController::callback  
firefly-csv_1   | [2020-11-04 19:23:35] local.ERROR:  {"exception":"[object] (InvalidArgumentException(code: 0):  at /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php:304)
firefly-csv_1   | [stacktrace]
firefly-csv_1   | #0 /var/www/html/app/Http/Controllers/TokenController.php(183): throw_unless()
firefly-csv_1   | #1 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\TokenController->callback()
firefly-csv_1   | #2 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
firefly-csv_1   | #3 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(255): Illuminate\\Routing\\ControllerDispatcher->dispatch()
firefly-csv_1   | #4 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\\Routing\\Route->runController()
firefly-csv_1   | #5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(691): Illuminate\\Routing\\Route->run()
firefly-csv_1   | #6 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
firefly-csv_1   | #7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
firefly-csv_1   | #8 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
firefly-csv_1   | #9 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
firefly-csv_1   | #10 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
firefly-csv_1   | #11 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
firefly-csv_1   | #12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
firefly-csv_1   | #13 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
firefly-csv_1   | #14 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
firefly-csv_1   | #15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
firefly-csv_1   | #16 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
firefly-csv_1   | #17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
firefly-csv_1   | #18 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
firefly-csv_1   | #19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
firefly-csv_1   | #20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
firefly-csv_1   | #21 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(693): Illuminate\\Pipeline\\Pipeline->then()
firefly-csv_1   | #22 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(668): Illuminate\\Routing\\Router->runRouteWithinStack()
firefly-csv_1   | #23 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(634): Illuminate\\Routing\\Router->runRoute()
firefly-csv_1   | #24 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->dispatchToRoute()
firefly-csv_1   | #25 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch()
firefly-csv_1   | #26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
firefly-csv_1   | #27 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
firefly-csv_1   | #28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
firefly-csv_1   | #29 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
firefly-csv_1   | #30 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
firefly-csv_1   | #31 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
firefly-csv_1   | #32 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
firefly-csv_1   | #33 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(87): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
firefly-csv_1   | #34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
firefly-csv_1   | #35 /var/www/html/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
firefly-csv_1   | #36 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
firefly-csv_1   | #37 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
firefly-csv_1   | #38 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
firefly-csv_1   | #39 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
firefly-csv_1   | #40 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then()
firefly-csv_1   | #41 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
firefly-csv_1   | #42 /var/www/html/public/index.php(99): Illuminate\\Foundation\\Http\\Kernel->handle()
firefly-csv_1   | #43 {main}
firefly-csv_1   | "} 
firefly-csv_1   | 192.168.240.4 - - [04/Nov/2020:19:23:35 +0100] "GET /callback?code=def5020077a4da92487a391ee1b3d811a81e78596355502d222ba9b9a52e0b96bd6c6e04c568eaf111018394d393f6bcd16c21e41e2a3ee223d2e7c6412106ef055cf7b0c226df9454dbd358cf34793f05385d4daa86a4b70a59d44b72ad5a694f5367d7dc52821adc8994d94b44233b5f7ceac2f504035c3774aa0e5413b723b7c47726a4e49ca17e04f2e6b0841b48700e6e0e6a7e0c1f85cf591f42703871ce05e7c87ecfebc1b7264d98e6b89853d0f970f8a32b611db3f9ad5eae8d0840d721c7442b84f3da0bfc997f006db405bb58d59fa3ebaf27493de2ef38de03c73a2786cc5c42c69e5a65358a5c03296457a4bd2649987567ec51b77017de3d4fb30422187fb85f03d581fb45c378c098bef7fb56779862a043e1d9376ee152252750fb988986de8013237bd1874e07035777bc3c1b32ddca694bb327d8cd080b2cb40b0ec8b31087726aa0b62678c903fd44292649c472234d65f9e37d8307f80d32695b95b6c460beddc9e924692dca011940c92aecac03bbc7d8188d7485628d8fe2226408278dbf0a2b845cbb40656a8e6ef93242&state=kKQzJUkbVrac9qgPBO3evePs5gVCBUMssrF0xkub HTTP/1.1" 500 304351 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36"
firefly-csv_1   | [2020-11-04 19:41:24] local.DEBUG: Now at App\Http\Controllers\IndexController::index  
firefly-csv_1   | [2020-11-04 19:41:24] local.DEBUG: Base URL: ""  
firefly-csv_1   | [2020-11-04 19:41:24] local.DEBUG: No access token cookie, redirect to token.index  
firefly-csv_1   | 192.168.240.4 - - [04/Nov/2020:19:41:24 +0100] "GET / HTTP/1.1" 302 1521 "http://csv.priv.strosklerlab.dev" 
```
