### ISSUE TITLE
Upgrade from 4.7 to 5.4 via docker-compose

### ISSUE THREAD

**Issue by LesnyRumcajs** [firefly-iii/firefly-iii#4054]
I am running Firefly III version  4.7.17 via Docker Compose on a QNAP NAS

**Description**
I would like to perform an upgrade to version 5.4.6.

**Extra info**

Debug information generated at 2020-11-10 23:04:13 Europe/Warsaw for Firefly III version **4.7.17**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.17 |
| FF API version | 0.9.2 |
| App environment | local |
| App debug mode | '' |
| App cache driver | file |
| App logging | , stdout |
| PHP version | 7.2.16 |
| Display errors | Off |
| Session start | 2020-11-01 00:00:00 |
| Session end | 2020-11-30 23:59:59 |
| Session first | 2020-03-29 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 2 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | true |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, bcmath, gd, intl, ldap, memcached, pdo_mysql, pdo_pgsql, sodium, zip, Zend OPcache |

I noticed from the new docker compose file, that the underlying DB changed - tried to dumbly update psql to 11, but got quite a lot of errors. My current docker-compose file looks like so:
```
version: '3'

networks: 
  firefly_iii_net: 
    driver: bridge
services: 
  firefly_iii_app: 
    environment: 
      - FF_DB_HOST=firefly_iii_db
      - FF_DB_NAME=firefly
      - FF_DB_USER=firefly
      - FF_DB_PASSWORD=blabla
      - FF_APP_KEY=blabla
      - FF_APP_ENV=local
      - FF_DB_CONNECTION=pgsql
      - TZ=Europe/Warsaw
      - APP_LOG_LEVEL=debug
    image: jc5x/firefly-iii:latest
    links: 
      - firefly_iii_db
    networks: 
      - firefly_iii_net
    ports: 
      - "8082:80"
    volumes: 
      - 
        source: firefly_iii_export
        target: /var/www/firefly-iii/storage/export
        type: volume
      - 
        source: firefly_iii_upload
        target: /var/www/firefly-iii/storage/upload
        type: volume
  firefly_iii_db: 
    environment: 
      - POSTGRES_PASSWORD=blabla
      - POSTGRES_USER=firefly
    image: "postgres:10"
    networks: 
      - firefly_iii_net
    volumes: 
      - "firefly_iii_db:/var/lib/postgresql/data"
version: "3.2"
volumes: 
  firefly_iii_export:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /share/dockdata/firefly_firefly_iii_export
  firefly_iii_upload:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /share/dockdata/firefly_firefly_iii_upload
  firefly_iii_db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /share/dockdata/firefly_firefly_iii_db
```

How would I need to modify this for an upgrade to a recent version?

**Comment by JC5** [comment]
First and foremost. Do you have a backup of all of your Docker volumes? And can you restore them if necessary? Try this docker compose file. Notice how I don't upgrade postgres itself. Wont be necessary for now.

```
version: '3'

networks: 
  firefly_iii_net: 
    driver: bridge
services: 
  firefly_iii_app: 
    environment: 
      - DB_HOST=firefly_iii_db
      - DB_DATABASE=firefly
      - DB_USER=firefly
      - DB_PASSWORD=blabla
      - APP_KEY=blabla
      - APP_ENV=local
      - DB_CONNECTION=pgsql
      - TZ=Europe/Warsaw
      - APP_LOG_LEVEL=debug
    image: jc5x/firefly-iii:latest
    links: 
      - firefly_iii_db
    networks: 
      - firefly_iii_net
    ports: 
      - "8082:80"
    volumes: 
      - 
        source: firefly_iii_upload
        target: /var/www/html/storage/upload
        type: volume
  firefly_iii_db: 
    environment: 
      - POSTGRES_PASSWORD=blabla
      - POSTGRES_USER=firefly
    image: "postgres:10"
    networks: 
      - firefly_iii_net
    volumes: 
      - "firefly_iii_db:/var/lib/postgresql/data"
version: "3.2"
volumes: 
  firefly_iii_upload:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /share/dockdata/firefly_firefly_iii_upload
  firefly_iii_db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /share/dockdata/firefly_firefly_iii_db
```
