### ISSUE TITLE
Transactions disappeared

### ISSUE THREAD

**Issue by MateEke** [firefly-iii/firefly-iii#4104]
**Bug description**
I am running Firefly III version 5.4.6, and my problem is:
I have recently started using Firefly and I have noticed that two of my transaction disappeared.
Yesterday I have created two transactions, each of them created new categories and expense accounts.
Yesterday they were listed under the transactions tab and on the dashboard (I'm sure about that, and my wife remembers too), but today when I wanted to create new transactions I have noticed that the two transactions from yesterday are missing.
The categories and accounts that were created by these transactions are still there.
Unfortunately after I have discovered the issue I have recreated the docker container (tried to reproduce), so I dont have the logs, but before that I couldn't find anything relevant in the logs.

Category 5 and 6 were created by this transactions:
```
mysql> select id, created_at, deleted_at, name from categories;
+----+---------------------+------------+--------------------+
| id | created_at          | deleted_at | name               |
+----+---------------------+------------+--------------------+
|  1 | 2020-11-28 19:20:01 | NULL       | XXXX   |
|  2 | 2020-11-28 19:49:43 | NULL       | XXXX               |
|  3 | 2020-11-28 20:54:05 | NULL       | XXXX                |
|  4 | 2020-11-28 20:56:09 | NULL       | XXXX      |
|  5 | 2020-11-29 12:28:06 | NULL       | Bevásárlás         |
|  6 | 2020-11-29 12:28:39 | NULL       | Cigi               |
|  7 | 2020-11-30 14:30:07 | NULL       | XXXX            |
+----+---------------------+------------+--------------------+
7 rows in set (0.04 sec)
```

Account 35 and 36:
```
mysql> select id, created_at, deleted_at, account_type_id, name from accounts where created_at > '2020-11-28 19:00:00';
+----+---------------------+------------+-----------------+-------------------------------------------------------+
| id | created_at          | deleted_at | account_type_id | name                                                  |
+----+---------------------+------------+-----------------+-------------------------------------------------------+
| 15 | 2020-11-28 19:00:33 | NULL       |               3 | XXXX                                           |
| 16 | 2020-11-28 19:00:33 | NULL       |               6 | XXXX                       |
| 17 | 2020-11-28 19:03:22 | NULL       |               3 | XXXX                                          |
| 18 | 2020-11-28 19:03:22 | NULL       |               6 | XXXX                      |
| 19 | 2020-11-28 19:04:11 | NULL       |               3 | XXXX                                                   |
| 20 | 2020-11-28 19:04:11 | NULL       |               6 | XXXX                               |
| 21 | 2020-11-28 19:07:08 | NULL       |               3 | XXXX                                              |
| 22 | 2020-11-28 19:07:08 | NULL       |               6 | XXXX                          |
| 23 | 2020-11-28 19:07:40 | NULL       |               3 | XXXX                                              |
| 24 | 2020-11-28 19:07:40 | NULL       |               6 | XXXX                          |
| 25 | 2020-11-28 19:10:22 | NULL       |               3 | XXXX                                         |
| 26 | 2020-11-28 19:10:22 | NULL       |               6 | XXXX                     |
| 27 | 2020-11-28 19:12:05 | NULL       |               9 | XXXX                                              |
| 28 | 2020-11-28 19:12:05 | NULL       |               6 | XXXX                          |
| 29 | 2020-11-28 19:17:29 | NULL       |               2 | XXXX                                          |
| 30 | 2020-11-28 19:36:17 | NULL       |               3 | XXXX                         |
| 31 | 2020-11-28 19:36:17 | NULL       |               6 | XXXX     |
| 32 | 2020-11-28 19:53:41 | NULL       |               4 | XXXX                                                   |
| 33 | 2020-11-28 20:51:43 | NULL       |               4 | XXXX                                              |
| 34 | 2020-11-28 21:45:54 | NULL       |               4 | XXXX                                            |
| 35 | 2020-11-29 12:28:06 | NULL       |               4 | CBA                                                   |
| 36 | 2020-11-29 12:28:39 | NULL       |               4 | Dohánybolt                                            |
| 37 | 2020-11-30 14:30:07 | NULL       |               4 | XXXX                                            |
| 38 | 2020-11-30 18:04:54 | NULL       |               5 | XXXX                                            |
+----+---------------------+------------+-----------------+-------------------------------------------------------+
24 rows in set (0.00 sec)
```

No transactions at 2020-11-29:
```
mysql> select id, created_at, deleted_at, account_id from transactions where created_at > '2020-11-28 19:00:00';
+----+---------------------+---------------------+------------+
| id | created_at          | deleted_at          | account_id |
+----+---------------------+---------------------+------------+
| 15 | 2020-11-28 19:00:33 | NULL                |         16 |
| 16 | 2020-11-28 19:00:33 | NULL                |         15 |
| 17 | 2020-11-28 19:03:22 | NULL                |         18 |
| 18 | 2020-11-28 19:03:22 | NULL                |         17 |
| 19 | 2020-11-28 19:04:11 | NULL                |         20 |
| 20 | 2020-11-28 19:04:11 | NULL                |         19 |
| 21 | 2020-11-28 19:07:09 | NULL                |         22 |
| 22 | 2020-11-28 19:07:09 | NULL                |         21 |
| 23 | 2020-11-28 19:07:40 | NULL                |         24 |
| 24 | 2020-11-28 19:07:40 | NULL                |         23 |
| 25 | 2020-11-28 19:10:22 | NULL                |         26 |
| 26 | 2020-11-28 19:10:22 | NULL                |         25 |
| 27 | 2020-11-28 19:12:05 | NULL                |         28 |
| 28 | 2020-11-28 19:12:05 | NULL                |         27 |
| 29 | 2020-11-28 19:20:01 | 2020-11-28 21:30:12 |          1 |
| 30 | 2020-11-28 19:20:01 | 2020-11-28 21:30:12 |         27 |
| 31 | 2020-11-28 19:36:17 | NULL                |         31 |
| 32 | 2020-11-28 19:36:17 | NULL                |         30 |
| 33 | 2020-11-28 19:49:43 | NULL                |          7 |
| 34 | 2020-11-28 19:49:43 | NULL                |         32 |
| 35 | 2020-11-28 21:45:54 | NULL                |          1 |
| 36 | 2020-11-28 21:45:54 | NULL                |         34 |
| 37 | 2020-11-28 21:47:46 | NULL                |          1 |
| 38 | 2020-11-28 21:47:46 | NULL                |         27 |
| 39 | 2020-11-28 22:49:43 | 2020-11-28 22:51:27 |         27 |
| 40 | 2020-11-28 22:49:43 | 2020-11-28 22:51:27 |          1 |
| 41 | 2020-11-30 14:30:07 | NULL                |          9 |
| 42 | 2020-11-30 14:30:07 | NULL                |         37 |
| 43 | 2020-11-30 17:57:12 | NULL                |          7 |
| 44 | 2020-11-30 17:57:12 | NULL                |         35 |
| 45 | 2020-11-30 17:58:39 | NULL                |          7 |
| 46 | 2020-11-30 17:58:39 | NULL                |         36 |
| 47 | 2020-11-30 18:02:09 | NULL                |          7 |
| 48 | 2020-11-30 18:02:09 | NULL                |         35 |
| 49 | 2020-11-30 18:02:36 | NULL                |          7 |
| 50 | 2020-11-30 18:02:36 | NULL                |         36 |
| 51 | 2020-11-30 18:04:54 | NULL                |         38 |
| 52 | 2020-11-30 18:04:54 | NULL                |          7 |
+----+---------------------+---------------------+------------+
38 rows in set (0.00 sec)
```

**Steps to reproduce**
Unfortunately I couldn't reproduce.

**Extra info**
My docker compose config:

```
version: '3.3'

services:
  fireflyiii:
    image: jc5x/firefly-iii:latest
    container_name: fireflyiii
    restart: unless-stopped
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - 9567:8080
    depends_on:
      - db
      - memcached
    networks:
      - fireflyiii-net
  memcached:
    image: memcached:1.6-alpine
    container_name: fireflyiii-memcached
    entrypoint: memcached -m 128
    restart: unless-stopped
    networks:
      - fireflyiii-net
    labels:
      - com.centurylinklabs.watchtower.enable=true
  db:
    image: mariadb:10
    container_name: fireflyiii-db
    restart: unless-stopped
    environment:
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=XXXX
      - MYSQL_DATABASE=firefly
    volumes:
      - firefly_iii_db:/var/lib/mysql
    networks:
      - fireflyiii-net
    labels:
      - com.centurylinklabs.watchtower.enable=true
volumes:
   firefly_iii_upload:
   firefly_iii_db:
networks:
   fireflyiii-net:
```

mariadb version: `10.5.8-MariaDB-1:10.5.8+maria~focal`
