### ISSUE TITLE
401 Error - No graphs on fresh installation.

### ISSUE THREAD

**Issue by peperunas** [firefly-iii/firefly-iii#4114]
**Bug description**
I am running Firefly III version 5.4.6 installed through the official docker image, and my problem is:

I cannot see the graph in the overview page and the 4 main blocks (Balance, Bills to Pay, etc.) are empty.
I have checked the debugging console and it seems there are a bunch of `401` errors for endpoints:
- `endpoints`
- `revenue`
- `piggybanks`

and more.

**Steps to reproduce**

Install the docker official docker image along with MariaDB and register the first account.

**Extra info**

Docker-compose:
```
  firefly:
    image: jc5x/firefly-iii
    container_name: firefly
    depends_on:
      - firefly_db
      - traefik
    environment:
      APP_KEY: ${FIREFLY_APP_KEY}
      DB_HOST: ${FIREFLY_DB_HOST}
      DB_PORT: 3306
      DB_CONNECTION: mysql
      DB_DATABASE: ${FIREFLY_DB_NAME}
      DB_USERNAME: ${FIREFLY_DB_USER}
      DB_PASSWORD: ${FIREFLY_DB_PASSWORD}
    volumes:
      - ${VOLUMES_DIRECTORY}/firefly:/var/www/html/storage/upload

  firefly_db:
    image: mariadb:10
    container_name: firefly_db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${FIREFLY_DB_ROOT_PASSWORD}
      MYSQL_USER: ${FIREFLY_DB_USER}
      MYSQL_PASSWORD: ${FIREFLY_DB_PASSWORD}
      MYSQL_DATABASE: ${FIREFLY_DB_NAME}
    volumes:
      - ${VOLUMES_DIRECTORY}/firefly/db:/var/lib/mysql
    restart: unless-stopped
    command: --max-connections=1000
```

**Bonus points**
