### ISSUE TITLE
Registration page not working - Request are not sent from client-side

### ISSUE THREAD

**Issue by peperunas** [firefly-iii/firefly-iii#4115]
**Bug description**
I am running Firefly III version 5.4.6 using the official docker image and my problem is:

The registration page does not send any request to the server when filling out the form. I have checked if the server received any connection and subsequently, if the client's browser sent any requests. It seems that the register button does not trigger the POST request.

**Steps to reproduce**

Enable user registration in the admin panel -> Try to register a new user.

**Extra info**

Docker-compose.yml:

```
  firefly:
    image: jc5x/firefly-iii
    container_name: firefly
    depends_on:
      - firefly_db
      - traefik
    environment:
      APP_KEY: ${FIREFLY_APP_KEY}
      DB_HOST: ${FIREFLY_DB_HOST}
      DB_PORT: 3306
      DB_CONNECTION: mysql
      DB_DATABASE: ${FIREFLY_DB_NAME}
      DB_USERNAME: ${FIREFLY_DB_USER}
      DB_PASSWORD: ${FIREFLY_DB_PASSWORD}
    volumes:
      - ${VOLUMES_DIRECTORY}/firefly:/var/www/html/storage/upload

  firefly_db:
    image: mariadb:10
    container_name: firefly_db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${FIREFLY_DB_ROOT_PASSWORD}
      MYSQL_USER: ${FIREFLY_DB_USER}
      MYSQL_PASSWORD: ${FIREFLY_DB_PASSWORD}
      MYSQL_DATABASE: ${FIREFLY_DB_NAME}
    volumes:
      - ${VOLUMES_DIRECTORY}/firefly/db:/var/lib/mysql
    restart: unless-stopped
    command: --max-connections=1000
```
