### ISSUE TITLE
Firefly 3 does not accept files for password

### ISSUE THREAD

**Issue by Chaoschaot232** [firefly-iii/firefly-iii#4216]
Hey,

I try to install it but I get the error that https://github.com/firefly-iii/docker/blob/main/entrypoint.sh#L25 tells me, that the file does not exists.

Te problem is, that the docker image seems not to try to access /run/secrets/ and I don't know why. For the MariaDB setup it works just fine but for the application it seems to miss smth. to access this specific folder even given read/write to the files in there.

Could you look into this because for know I must store the passwords in the .env file.

Also the .env file is not copied by automatic deploy over gitlab and must be named which shouldn't happen. Is this a gitlab issue or not?

**Comment by JC5** [comment]
What's the command you use to start the image?

**Comment by Chaoschaot232** [comment]
Well, it is started over my gitlab using the gitlab runners for deploy and startup.

**Comment by JC5** [comment]
That's not helpful I'm afraid.

**Comment by Chaoschaot232** [comment]
Maybe this could help you a bit more:

```
---
variables:
  CUSTOMER_NAME: ${CI_PROJECT_NAMESPACE}
  PROJECT_NAME: ${CI_PROJECT_NAME}

before_script:
  - |
    # Setting environment vars
    if [ -z "$QUALIFIED_NAME" ]; then export QUALIFIED_NAME="${CUSTOMER_NAME}-${PROJECT_NAME}"; fi
    if [ -z "$DATA_PATH" ]; then export DATA_PATH="/home/data/${QUALIFIED_NAME}"; fi
    if [ -z "$CONFIG_PATH" ]; then export CONFIG_PATH="/home/server/${QUALIFIED_NAME}"; fi
    if [ -z "$SECRETS_PATH" ]; then export SECRETS_PATH="/home/secrets/${QUALIFIED_NAME}"; fi

stages:
  - verify
  - deploy
  - build
  - start

verify_files:
  stage: verify
  tags:
    - local
  script:
    - |
      # Present environment vars:
      echo "Customer: ${CUSTOMER_NAME}"
      echo "Project: ${PROJECT_NAME}"
      echo "Qualified Name: ${QUALIFIED_NAME}"
      echo "Data Path: ${DATA_PATH}"
      echo "Config Path: ${CONFIG_PATH}"
      echo "Secrets Path: ${SECRETS_PATH}"
    
lint_dockerfile:
  stage: verify
  image: hadolint/hadolint:latest-alpine
  allow_failure: true
  tags:
    - docker
  script:
    - for f in `find . -type f -name 'Dockerfile'`; do hadolint $f; done
  rules:
    - if: "$DISABLE_LINTER == 'true'"
      when: never

lint_yaml:
  stage: verify
  image: vpgrp/linter:yaml-lint
  allow_failure: true
  tags:
    - docker
  script:
    - for f in `find . -type f -name '*.yml'`; do yaml-lint $f; done
    - for f in `find . -type f -name '*.yaml'`; do yaml-lint $f; done
  rules:
    - if: "$DISABLE_LINTER == 'true'"
      when: never

lint_python:
  stage: verify
  image: vpgrp/linter:py-lint
  allow_failure: true
  tags:
    - docker
  script:
    - for f in `find . -type f -name '*.py'`; do pylint $f; done
  rules:
    - if: "$DISABLE_LINTER == 'true'"
      when: never

lint_json:
  stage: verify
  image: vpgrp/linter:json-lint
  allow_failure: true
  tags:
    - docker
  script:
    - for f in `find . -type f -name '*.json'`; do jsonlint $f; done
  rules:
    - if: "$DISABLE_LINTER == 'true'"
      when: never

lint_md:
  stage: verify
  image: vpgrp/linter:mdl
  allow_failure: true
  tags:
    - docker
  script:
    - mdl .
  rules:
    - if: "$DISABLE_LINTER == 'true'"
      when: never

deploy_files:
  stage: deploy
  tags:
    - local
  script:
    - rm -rf /home/server/${QUALIFIED_NAME}/ || true
    - mkdir /home/server/${QUALIFIED_NAME}/
    - cp -R ${CI_PROJECT_DIR}/* /home/server/${QUALIFIED_NAME}/

build_docker_images:
  stage: build
  tags:
    - local
  script:
    - docker-compose build

docker_compose_up:
  stage: start
  tags:
    - local
  script:
    - cd /home/server/${QUALIFIED_NAME}/
    - docker-compose -p "${QUALIFIED_NAME}" up -d --build --quiet-pull
```

**Comment by JC5** [comment]
I see no references to _FILE variables in ff.env, is that correct?

**Comment by Chaoschaot232** [comment]
Yes, I changed it for both, DB and Mail as it notifies me, about no file in /run/secrets/ but they are there, otherwiese no DB would have been created.

Also I ended up in a HTTP 500 but this got resolved and is now the HTTP 404 like stated in #4156

**Comment by JC5** [comment]
The secrets may only work when you're deploying in Swarm mode. Is that the case?

**Comment by Chaoschaot232** [comment]
No, it is a single server where all is deployed in docker containers.
Also the secrets are working just fine for the mariadb container as you can see in the service "fireflydb"

**Comment by JC5** [comment]
I’ve managed to break both of them. Or neither. I can’t get Firefly III to stop working while MariaDB works fine. But I haven’t mapped the secrets directory manually as GitLab seems to do. 

I’ll tinker some more.

**Comment by Chaoschaot232** [comment]
That's great 👍 
Maybe you can help me too with my 404 problem which I linked? Hopefully it isn't related to a missconfiguration with traefik 🤔

**Comment by JC5** [comment]
Open a new ticket please if it's still an issue.

**Comment by JC5** [comment]
So after some tinkering, I can't reproduce the problem. Keep in mind that the DB will be generated regardless of the secret's presence.

Docker compose:

```
version: '3.3'

services:
  fireflyiii:
    image: jc5x/firefly-iii:latest
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - 80:8080
    depends_on:
      - fireflyiiidb
    secrets:
     - firefly_iii_mysql_password
  fireflyiiidb:
    image: mariadb:latest
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD_FILE=/run/secrets/firefly_iii_mysql_password
      - MYSQL_DATABASE=firefly
    volumes:
      - firefly_iii_db:/var/lib/mysql
    secrets:
     - firefly_iii_mysql_password
volumes:
   firefly_iii_upload:
   firefly_iii_db:


secrets:
  firefly_iii_mysql_password:
    external: true
```

And the only change in my `env` file:

```
DB_PASSWORD_FILE=/run/secrets/firefly_iii_mysql_password
```

I notice in your configs that you don't seem to use secrets per se, but choose to mount the secrets directory by hand.

```
      - ${SECRETS_PATH}:/run/secrets:ro
```

I tried this as well, and it works fine:

```
version: '3.3'

services:
  fireflyiii:
    image: jc5x/firefly-iii:latest
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
      - /Users/james/Sites/temp/issue-4216/secrets:/run/secrets:ro
    env_file: .env
    ports:
      - 80:8080
    depends_on:
      - fireflyiiidb
  fireflyiiidb:
    image: mariadb:latest
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD_FILE=/run/secrets/firefly_iii_mysql_password
      - MYSQL_DATABASE=firefly
    volumes:
      - firefly_iii_db:/var/lib/mysql
      - /Users/james/Sites/temp/issue-4216/secrets:/run/secrets:ro
volumes:
   firefly_iii_upload:
   firefly_iii_db:
```

With of course a "secret" in the correct directory:

<img width="316" alt="Screenshot 2021-01-07 at 07 31 05" src="https://user-images.githubusercontent.com/5889984/103859438-f1237b80-50b1-11eb-9927-a2d729a87173.png">

```
Now in entrypoint.sh for Firefly III
Entrypoint script version is 1.0.12 (2020-12-16)
Running as 'root' in group 'root'.
Current working dir is '/var/www/html'
Now parsing _FILE variables.
done!
Touch DB file (if SQLite)...
Dump auto load...
Discover packages...
Current working dir is '/var/www/html'
Wait for the database.
wait-for-it.sh: waiting 60 seconds for fireflyiiidb:3306
wait-for-it.sh: fireflyiiidb:3306 is available after 7 seconds
DB is up. Time to execute artisan commands.
```
