### ISSUE TITLE
Adding a tutorial/guide for periodic backups

### ISSUE THREAD

**Issue by ClementNerma** [firefly-iii/firefly-iii#4270]
As Firefly III stores very important informations that most of us can't afford to lose, I think it'd be great to add a little guide or tutorial to indicate how to backup the whole data.

Something that comes to my mind, which is my actual backup process, it to complete the reference `docker-compose.yml` with a backup container, like [https://github.com/fradelg/docker-mysql-cron-backup](this one) for instance.

Here is my personal Docker Compose file for reference:

```yaml
version: "3.3"

services:
  fireflyiii:
    container_name: software_fireflyiii
    image: jc5x/firefly-iii:latest
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - 7000:8080
    depends_on:
      - fireflyiiidb

  fireflyiiidb:
    container_name: software_fireflyiii_db
    image: yobasystems/alpine-mariadb:latest
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=XXXXXXXXXX
      - MYSQL_PASSWORD=XXXXXXXXXX
      - MYSQL_DATABASE=XXXXXXXXXX
    volumes:
      - firefly_iii_db:/var/lib/mysql

  mysql-cron-backup:
    container_name: software_fireflyiii_db_backuper
    image: fradelg/mysql-cron-backup
    depends_on:
      - fireflyiiidb
    volumes:
      - ./mysql_backup:/backup
    environment:
      - MYSQL_HOST=software_fireflyiii_db
      - MYSQL_USER=XXXXXXXXXX
      - MYSQL_PASS=XXXXXXXXXX
      - MAX_BACKUPS=15
      - INIT_BACKUP=1
      - CRON_TIME=0 * * * * # Every hour at minute 0
      - GZIP_LEVEL=9 # High compression level

volumes:
  firefly_iii_upload:
  firefly_iii_db:
```

Of course the period can be changed, but here the database is completely backed up every hour. With the current database I have (not so many transactions) it takes around 25 KB compressed. The backup consists in a simple SQL file that can be run to restore the database to the state it was at when the backup was performed.

What do you think of it?
