### ISSUE TITLE
http cronjob in a multi-account setup able to execute recurring actions with wrong command line token

### ISSUE THREAD

**Issue by BoudewijnSwen** [firefly-iii/firefly-iii#4484]
**Bug description**
I am running Firefly III version 5.4.6 in Kubernetes. I have two accounts setup, one for my personal finance and one for my partner. I have been testing with setting up a k8s cronjob for running the FF cron to execute the recurring transactions etc. 

**Steps to reproduce**
The yaml for the cronjob is as follows:
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: firefly-cron-job
  namespace: firefly-iii
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: radial/busyboxplus:curl
            name: firefly-cron
            args:
            - curl
            - http://10.13.37.98/cron/run/<command line token account 2>
```

Not sure if this is relevant, but one is admin, the other is not:
_**'Account 1'** = Is admin
**'Account 2'** = Is not admin_
I added the Command Line token from **account 2** (not admin) to the url for the cronjob.
I also created a recurring transaction, first under **account 2**, then another under account 1. Both the same, both running everyday.

The morning after I checked if the recurring transfer was created. I found that only the recurring transfer for **account 1** was created! 
- I ran curl http://10.13.37.98/cron/run/<command line token **account 2**> manually again, now the recurring transfer for **account 2** was created as well.
- I slightly editted the test recurring transfer under **account 2**.

The morning after only the recurring transfer from **account 2** was created.
- I ran curl http://10.13.37.98/cron/run/<command line token **account 1**>, output:
```
The recurring transaction cron job fired successfully.
The auto budget cron job fired successfully.
The telemetry cron job did not fire.
```
- Now the recurring transfer for **account 1** was created as well.

**Extra**
- On both days ran the curl command manually a 2nd time:
```
The recurring transaction cron job did not fire.
The auto budget cron job did not fire.
The telemetry cron job did not fire.
```
But this output is expected I guess, both accounts had their cronjobs ran. 

**Conclusion**
It seems only for one of the accounts the cronjobs get executed per trigger over http. No mater which command line token you use, only the recurring transactions that were editted last, get executed. 

**Solution/work around**
I will try and just schedule a 2nd cronjob to run the curl command with the command line token for the other account, so if and when this gets fixed, it wont break my setup :)

**Final thoughts**
This is nothing major I guess, but I though to report this behavior anyway, cause in my mind this does not feels like expected behavior that I am able to run cronjobs for account 2 from a account 1 token, and also that it only triggers the last one edited.
However, I have to say: I love firefly, I have been having a great learning experience setting it up in Kubernetes. Hopefully I might be able to contribute one day! Keep up the good work!
