### ISSUE TITLE
Support running containers with recommended security settings in Kubernetes

### ISSUE THREAD

**Issue by justsomebody42** [firefly-iii/firefly-iii#4919]
Hi,
I'm running core and importer in my Kubernetes cluster and tried to apply some of the recommended security settings.
Unfortunately, it seems that the images rely on root privileges and quite a bit of setup when starting.

Would it be possible to create updated images that allow running with a read-only container filesystem and a non-root user?

Snipped of the security settings I'm trying to use:
```yaml
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: firefly-importer
          image: fireflyiii/csv-importer:version-2.5.3
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 1032
            runAsGroup: 65537
```
