### ISSUE TITLE
ARM64 Docker Error - "exec format error"

### ISSUE THREAD

**Issue by ajaskiewiczpl** [firefly-iii/firefly-iii#4977]
Yesterday I pulled the latest docker image on Ubuntu Server 20.04 ARM64, this is how my docker-compose look like:
```
version: '3.3'

services:
  fireflyiii:
    external_links:
      - mariadb
    image: jc5x/firefly-iii:latest
    container_name: firefly
    volumes:
      - /mnt/storage/firefly/export:/var/www/firefly-iii/storage/export
      - /mnt/storage/firefly/upload:/var/www/firefly-iii/storage/upload
    env_file: .env
    ports:
      - 8099:8080
    networks:
      - mariadb_shared
    restart: unless-stopped
networks:
  mariadb_shared:
    external: true
```

When I run the container I receive this error:
`standard_init_linux.go:228: exec user process caused: exec format error`
This is the only output from `docker-compose up` and the container immediately stops.
