### ISSUE TITLE
Add cronjob to kubernetes repo

### ISSUE THREAD

**Issue by sushi30** [firefly-iii/firefly-iii#5278]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

- I would like to suggest a k8s cronjob template for firing the FireFly III cron job.

### Solution

I have template that looks like this. It is very customized for my own personal cloud so it will need some adjusting.

```yaml
{{ if .Values.fireflyiii.cron.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ .Release.Name }}-cron"
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            component: "cron"
      activeDeadlineSeconds: 120
      backoffLimit: 5
      template:
        spec:
          containers:
            - name: cron
              image: busybox
              imagePullPolicy: IfNotPresent
              command:
                - wget
              args:
                - "{{.Release.Name}}.{{.Release.Namespace}}:8080/api/v1/cron/$(STATIC_CRON_TOKEN)"
              envFrom:
                - secretRef:
                    name: {{ .Release.Name }}-secrets
          restartPolicy: Never
{{ end }}
```
