### ISSUE TITLE
protocol mismatch when data importer is behind proxy, but working with csv importer

### ISSUE THREAD

**Issue by sotornien** [firefly-iii/firefly-iii#5344]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Hi all,

I started working with firefly these days and got the csv importer to work. Now it seems that the csv importer is now part of the data importer and the csv docs redirects to the dataimporter docs.
My working setup is:

- Dockerhost with nginx reverse proxy 
- pointing banking.mhome.local to firefly
- pointing csvimport.mhome.local to the csv importer. 

Now I deployed the dataimporter exactly the same as the csv importer (just changed the hostname and image from fireflyiii/csv-importer:version-2.6.1 to fireflyiii/data-importer:version-0.1.0.

The Issue:

- opening https://csvimport.mhome.local works
- opening https://dataimport.mhome.local I got CSP / XSS problems as the dataimporter thinks it uses HTTP

Conclusion:
I don't think this is a proxy related issue as Firefly and CSVImporter is still working behind the proxy with HTTPS

Please have a look on the screenshots below. The dataimporter is also displaying the callback URL with HTTP

### Expected behaviour

Content gets loaded via HTTPS

### Debug information

I'm automating my deployments via Ansible:

```
- name: "Setup Container Volume"
  docker_volume:
    volume_name: "firefly-uploads-volume"

- name: "Deploy Firefly"
  docker_container:
    hostname: "firefly"
    image: "fireflyiii/core:version-5.6.5"
    name: "firefly"
    pull: yes
    restart_policy: always
    state: started
    volumes:
      - "firefly-uploads-volume:/data"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "8080"
    networks:
      - name: "mhome-net"
    env:
      VIRTUAL_HOST: "banking.mhome.local"
      VIRTUAL_PORT: "8080"
      APP_URL: "banking.mhome.local"
      DEFAULT_LANGUAGE: "de_DE"
      TZ: "Europe/Berlin"
      DB_HOST: "mariadb-live"
      DB_PORT: "3306"
      DB_CONNECTION: "mysql"
      DB_DATABASE: "firefly"
      DB_USERNAME: "root"
      DB_PASSWORD: "{{ defaultpw }}"
      APP_KEY: "..."
      TRUSTED_PROXIES: "**"

- name: "Deploy Firefly CSV Importer"
  docker_container:
    hostname: "firefly-csvimporter"
    image: "fireflyiii/csv-importer:version-2.6.1"
    name: "firefly-csvimporter"
    pull: yes
    restart_policy: always
    state: started
    networks:
      - name: "mhome-net"
    ports:
      - "8080"
    env:
      FIREFLY_III_URL: "http://firefly:8080"
      VANITY_URL: "https://banking.mhome.local"
      VIRTUAL_HOST: "csvimport.banking.mhome.local"
      VIRTUAL_PORT: "8080"
      TRUSTED_PROXIES: "**"

- name: "Deploy Firefly Data Importer"
  docker_container:
    hostname: "firefly-dataimporter"
    image: "fireflyiii/data-importer:version-0.1.0"
    name: "firefly-dataimporter"
    pull: yes
    restart_policy: always
    state: started
    networks:
      - name: "mhome-net"
    ports:
      - "8080"
    env:
      FIREFLY_III_URL: "http://firefly:8080"
      VANITY_URL: "https://banking.mhome.local"
      TRUSTED_PROXIES: "**"
      VIRTUAL_HOST: "dataimport.banking.mhome.local"
      VIRTUAL_PORT: "8080"
```

Nginx Dump:
Nginx Proxy header is applied based on https://docs.firefly-iii.org/data-importer/errors/freq_errors/

```
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
# configuration file /etc/nginx/nginx.conf:

user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  10240;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}
daemon off;

# configuration file /etc/nginx/conf.d/default.conf:
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive X-Forwarded-Port, pass it through; otherwise, pass along the
# server port the client connected to
map $http_x_forwarded_port $proxy_x_forwarded_port {
  default $http_x_forwarded_port;
  ''      $server_port;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
# Apply fix for very long server names
server_names_hash_bucket_size 128;
# Default dhparam
ssl_dhparam /etc/nginx/dhparam/dhparam.pem;
# Set appropriate X-Forwarded-Ssl header based on $proxy_x_forwarded_proto
map $proxy_x_forwarded_proto $proxy_x_forwarded_ssl {
  default off;
  https on;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent" '
                 '"$upstream_addr"';
access_log off;
		ssl_protocols TLSv1.2 TLSv1.3;
		ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384';
		ssl_prefer_server_ciphers off;
resolver 127.0.0.11;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	server_tokens off;
	listen 80;
	access_log /var/log/nginx/access.log vhost;
	return 503;
}
# banking.mhome.local
upstream banking.mhome.local {
	## Can be connected with "bridge" network
	# firefly
	server 172.17.0.5:8080;
	## Can be connected with "mhome-net" network
	# firefly
	server 172.18.0.5:8080;
}
server {
	server_name banking.mhome.local;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	# Do not HTTPS redirect Let'sEncrypt ACME challenge
	location ^~ /.well-known/acme-challenge/ {
		auth_basic off;
		auth_request off;
		allow all;
		root /usr/share/nginx/html;
		try_files $uri =404;
		break;
	}
	location / {
		return 301 https://$host$request_uri;
	}
}
server {
	server_name banking.mhome.local;
	listen 443 ssl http2 ;
	access_log /var/log/nginx/access.log vhost;
	ssl_session_timeout 5m;
	ssl_session_cache shared:SSL:50m;
	ssl_session_tickets off;
	ssl_certificate /etc/nginx/certs/mhome.local.crt;
	ssl_certificate_key /etc/nginx/certs/mhome.local.key;
	add_header Strict-Transport-Security "max-age=31536000" always;
	location / {
		proxy_pass http://banking.mhome.local;
	}
}
# csvimport.banking.mhome.local
upstream csvimport.banking.mhome.local {
	## Can be connected with "bridge" network
	# firefly-csvimporter
	server 172.17.0.7:8080;
	## Can be connected with "mhome-net" network
	# firefly-csvimporter
	server 172.18.0.7:8080;
}
server {
	server_name csvimport.banking.mhome.local;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	# Do not HTTPS redirect Let'sEncrypt ACME challenge
	location ^~ /.well-known/acme-challenge/ {
		auth_basic off;
		auth_request off;
		allow all;
		root /usr/share/nginx/html;
		try_files $uri =404;
		break;
	}
	location / {
		return 301 https://$host$request_uri;
	}
}
server {
	server_name csvimport.banking.mhome.local;
	listen 443 ssl http2 ;
	access_log /var/log/nginx/access.log vhost;
	ssl_session_timeout 5m;
	ssl_session_cache shared:SSL:50m;
	ssl_session_tickets off;
	ssl_certificate /etc/nginx/certs/mhome.local.crt;
	ssl_certificate_key /etc/nginx/certs/mhome.local.key;
	add_header Strict-Transport-Security "max-age=31536000" always;
	location / {
		proxy_pass http://csvimport.banking.mhome.local;
	}
}
# dataimport.banking.mhome.local
upstream dataimport.banking.mhome.local {
	## Can be connected with "bridge" network
	# firefly-dataimporter
	server 172.17.0.6:8080;
	## Can be connected with "mhome-net" network
	# firefly-dataimporter
	server 172.18.0.6:8080;
}
server {
	server_name dataimport.banking.mhome.local;
	listen 443 ssl http2 ;
	access_log /var/log/nginx/access.log vhost;
	ssl_session_timeout 5m;
	ssl_session_cache shared:SSL:50m;
	ssl_session_tickets off;
	ssl_certificate /etc/nginx/certs/mhome.local.crt;
	ssl_certificate_key /etc/nginx/certs/mhome.local.key;
	location / {
		proxy_pass http://dataimport.banking.mhome.local;
                include /etc/nginx/vhost.d/dataimport.banking.mhome.local_location;		
	}
}
server {
	server_name dataimport.banking.mhome.local;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	# Do not HTTPS redirect Let'sEncrypt ACME challenge
	location ^~ /.well-known/acme-challenge/ {
		auth_basic off;
		auth_request off;
		allow all;
		root /usr/share/nginx/html;
		try_files $uri =404;
		break;
	}
	location / {
		return 301 https://$host$request_uri;
                include /etc/nginx/vhost.d/dataimport.banking.mhome.local_location;		
	}
}

# configuration file /etc/nginx/vhost.d/dataimport.banking.mhome.local_location:
proxy_buffering on;
proxy_busy_buffers_size   512k;
proxy_buffers   4 512k;
proxy_buffer_size   256k;
proxy_connect_timeout       600;
proxy_send_timeout          600;
proxy_read_timeout          600;
send_timeout                600;
proxy_set_header X-Forwarded-Host $host;

# configuration file /etc/nginx/conf.d/nginx-proxy-global.conf:
client_max_body_size 100m;

```

### Steps to reproduce

1. Setup VM
2. Install Docker
3. Deploy Nginx reverse Proxy (https://hub.docker.com/r/jwilder/nginx-proxy)
4. Deploy csv and data importer based on Documentation (https://docs.firefly-iii.org/data-importer/install/docker/)

### Additional info

What I've tried:

- /flush
- php artisan cache:clear
- php artisan config:clear
- php artisan route:clear
- php artisan twig:clean
- php artisan view:clear
- Adding TRUSTED_PROXIES to env fixed the issue on the csvimporter but not with dataimporter

I think this screenshot shows it at best:

- Left: working CSV Importer
- Right: Dataimporter 

![2021-12-02 15_58_01-](https://user-images.githubusercontent.com/51051200/144449026-85afb578-6ca0-44a3-bb40-be9d63a0d36b.png)
