### ISSUE TITLE
Kubernetes - indentation error in metadata of ingress-firefly-iii-cron.yaml

### ISSUE THREAD

**Issue by yohancourbe** [firefly-iii/firefly-iii#5398]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

`kubectl apply -k ./` triggers error because of indentation error in file ingress-firefly-iii-cron.yaml

File should be 

```
      template:
        metadata:
          labels:
            app: firefly-iii
            tier: cron
```

### Expected behaviour

kubectl apply succeeds

### Debug information

`error validating "ingress-firefly-iii-cron.yaml": error validating data: ValidationError(CronJob.spec.jobTemplate.spec.template): unknown field "labels" in io.k8s.api.core.v1.PodTemplateSpec; if you choose to ignore these errors, turn validation off with --validate=false`
