### ISSUE TITLE
Transaction API ID inconsistency

### ISSUE THREAD

**Issue by GeorgeHahn** [firefly-iii/firefly-iii#5608]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The API schema defines the transaction models with a string ID. However, the transaction API methods define transaction IDs as integers. Both point to the same objects.

Model schema:
```yaml
TransactionRead:
  type: object
  required:
    - type
    - id
    - attributes
    - links
  properties:
# ...
    id:
      type: string
      format: string
      example: "2"
```

API method:
```yaml
/api/v1/transactions/{id}:
  get:
    summary: Get a single transaction.
    description: Get a single transaction.
    operationId: getTransaction
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
          example: 1
        description: The ID of the transaction.
```

Relevant models: `TransactionRead`, `TransactionSplit`, `TransactionLinkRead`, `TransactionLink`, `TransactionLinkStore`, `TransactionLinkUpdate`, `Bill`, `PiggyBankEvent`, 
Relevant methods: `getTransaction`, `updateTransaction`, `deleteTransaction`, `listAttachmentByTransaction`, `listEventByTransaction`, `listLinksByJournal`, `getTransactionByJournal`, `deleteTransactionJournal`

I included transaction journal IDs in these lists. I'm not sure if that's correct.

### Expected behaviour

Expected the same type for IDs of the same object across the board.

### Debug information

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.10 |
| Firefly III API | 1.5.5 |
| Build | 75, 09-01-2022 08:36:35 CET |
