### ISSUE TITLE
[Bug] API: CurrencyUpdate type default is bool, type is enum

### ISSUE THREAD

**Issue by jafin** [firefly-iii/firefly-iii#5630]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Referencing the firefly-iii-1.5.4.yaml,

When I attempt to create a client wrapper for the API it produces an error on `CurrencyUpdate` using the OpenAPIGenerators for dotnet

```yaml
  CurrencyUpdate:
      type: object
      properties:
        ...
        default:
          type: boolean
          format: boolean
          example: true
          description: "If the currency must be the default for the user. You can only submit TRUE."
          enum:
            - true
```

Having type `boolean` and `enum` appears to be causing the issue.
Can the `enum: - true` be removed so the type is just `boolean` ?

**NOTE UPDATE**:  Reading OpenAPI spec, what is in the schema appears valid, this could just be a case of the client generator not working correctly. So this may be actually not be an issue, but more so the generator I used.

### Expected behaviour

Creating a API wrapper should work.

### Debug information

N/A
