### ISSUE TITLE
Add probes to kubernetes deployment

### ISSUE THREAD

**Issue by cmillani** [firefly-iii/firefly-iii#5797]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Hello everyone! First of all thanks for the amazing tool that is Firefly!

Firefly takes a while to be ready to receive requests (for example running migrations, from what I can see on the logs), but the current deployment yaml causes the _Pod_ to be marked as ready as soon as the container is running, what causes the _Service_ to send requests to the instance before it can accept connections.

By adding probes to the deployment it will continuously check the `/health` route and only mark the container as `ready` once we receive a 200 response.

### Solution

By adding the three probes bellow kubernetes will:
* Use StartupProbe to wait up to 3 minutes until container is serving requests
* After StartupProbe succeeds, use ReadinessProbe to mark container as Ready
* If ever `/health` returns anything but 2xx or 3xx, LivenessProbe will cause a reset

```yaml
startupProbe:
  httpGet:
    path: /health
    port: 8080
  failureThreshold: 18
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /health
    port: 8080
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 5
livenessProbe:
  httpGet:
    path: /health
    port: 8080
  periodSeconds: 15
  successThreshold: 1
  failureThreshold: 5
```

### Additional context

I'm currently using the configuration above on my setup.

I wanted to open this issue to discuss it, and will be happy to open a PR if it makes sense!
