### ISSUE TITLE
Unauthenticated! when behind traefik proxy + external-auth-server + using remote_user auth

### ISSUE THREAD

**Issue by andrewzah** [firefly-iii/firefly-iii#5850]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When I try to do anything that interacts with the API (like submit a transaction), it just says `Unauthenticated!`.

### Expected behaviour

After logging in via remote_user, I should be able to enter transactions or do things that interact with the API.

### Debug information

Debug information generated at 2022-03-04 15:11:07 America/New_York for Firefly III version **5.6.16**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.16 |
| Firefly III API | 1.5.5 |
| Build | 113, 02-03-2022 19:39:22 CET |
| PHP | 8.0.16 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 4f00da3c-30a6-41b1-8612-c5bb8b08ad92 |
| Using docker? | true |
| Layout |  |
| System TZ | America/New_York |
| Browser TZ | UTC |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, stdout |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2022-03-01 00:00:00 |
| Session end | 2022-03-31 23:59:59 |
| Session first | 2022-02-28 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0 |

### Steps to reproduce

```yaml
services:
  firefly:
    # 03-02-2022
    image: fireflyiii/core:version-5.6.16@sha256:c07b41c0508877d5f8f6443e7b77369fc06ded5c702cbd81961e9d9452268d06
    env_file:
      - "secret.env"
    environment:
      APP_URL: 'https://firefly.foo.bar'
      APP_LOG_LEVEL: 'debug'
      AUDIT_LOG_LEVEL: 'debug'
      LOG_CHANNEL: 'stdout'
      AUTHENTICATION_GUARD: 'remote_user_guard'
      AUTHENTICATION_GUARD_HEADER: 'X-Auth-Email'
      AUTHENTICATION_GUARD_EMAIL: 'X-Auth-Email'
      TZ: 'America/New_York'
      TRUSTED_PROXIES: '**'
      DB_HOST: 'postgres'
      DB_PORT: 5432
      DB_CONNECTION: 'pgsql'
      DB_DATABASE: 'firefly'
      DB_USERNAME: 'firefly'
      SITE_OWNER: 'email@foo.bar'
      depends_on:
      - eas
      - postgres
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.firefly.rule=Host(`firefly.foo.bar`)"
      - "traefik.http.routers.firefly.entrypoints=websecure"
      - 'traefik.http.routers.firefly.middlewares=eas-default'
      - "traefik.http.routers.firefly.tls.certresolver=myresolver
      
  eas:
    image: travisghansen/external-auth-server:latest
    env_file:
      - "secret.env"
    environment:
      EAS_PORT: 8080
    restart: unless-stopped
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.eas.rule=Host(`eas.foo.bar`)"
      - "traefik.http.routers.eas.entrypoints=websecure"
      - "traefik.http.routers.eas.tls.certresolver=myresolver"
      - "traefik.http.middlewares.eas-default.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.eas-default.forwardauth.authResponseHeaders=X-Auth-Email,X-Auth-Username"
      - "traefik.http.middlewares.eas-default.forwardauth.address=https://eas.foo.bar/verify?config_token=%<trunc>"
      
 keycloak:
    image: jboss/keycloak:12.0.3
    env_file: 
      - "secret.env"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`idp.foo.bar`)"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.tls.certresolver=myresolver"
    restart: unless-stopped
      
  traefik:
    # 03-03-2022
    image: traefik:v2.6.1@sha256:79b4af2f1a73345d9cbfc3ae9fca0bde3aaa88787d890456f312c461bc8dcdf8
    container_name: "traefik"
    restart: unless-stopped
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entryPoints.web.forwardedHeaders.insecure"
      - "--entryPoints.websecure.forwardedHeaders.insecure"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=admin@foo.bar"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https@docker"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redir.redirectScheme.scheme=https"
```

### Additional info

Instead of Authelia, I'm running [external-auth-server](https://github.com/travisghansen/external-auth-server) + [keycloak (for OIDC)](https://github.com/keycloak/keycloak).

So for services behind eas+traefik, when I visit `firefly.foo.bar` I get redirected to `idp.foo.bar`, *via* `eas.foo.bar`. If the conditions pass, then I'm redirected back to `firefly.foo.bar`.

For firefly, I've set `X-Auth-Email` and `X-Auth-Username` to be passed along in the response headers, which allows me to log into firefly just fine. But I've no idea why I don't auth for the api endpoints- is there another header that I need to be passing? Even if I whitelist `/api/*` paths to automatically return from eas, it still just says `Unauthenticated` when I try to submit a transaction. I understand that this problem isn't really firefly's fault, but I'm not sure where to begin debugging this.
