### ISSUE TITLE
404 | Not Found on self-hosted docker installation over Nginx reverse proxy

### ISSUE THREAD

**Issue by ispmarin** [firefly-iii/firefly-iii#5947]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

After configuring both Firefly and Firefly importer over SWAG reverse-proxy, I can use Firefly normally, but the only thing that I get is 404 from firefly data importer after either adding the token directly or configuring it using the Client ID.

### Expected behaviour

Install Firefly and Firefly data importer using docker compose and they can talk with each other.

### Debug information

data importer:
```
[2022-03-29 18:51:07] production.INFO: Client ID            : "0"  
[2022-03-29 18:51:07] production.INFO: Base URL             : "https://firefly.tunguska.cc"  
[2022-03-29 18:51:07] production.INFO: Vanity URL           : "https://firefly.tunguska.cc"  
[2022-03-29 18:51:07] production.DEBUG: Found personal access token + URL "https://firefly.tunguska.cc" in config, set cookie and return to index.  
172.72.1.4 - - [29/Mar/2022:18:51:07 -0300] "GET /token HTTP/1.1" 302 4662 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"
172.72.1.4 - - [29/Mar/2022:18:51:07 -0300] "GET /502.html HTTP/1.1" 404 6803 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"
```

Firefly
```
172.72.1.4 - - [29/Mar/2022:18:47:33 -0300] "GET /oauth/authorize?client_id=10&redirect_uri=http%3A%2F%2Fosaka%3A8081%2Fcallback&response_type=code&scope=&state=oxnPZAZKzMLiC2vygEn1T5s3lfEXEEHlS1q54JfW&code_challenge=CMvybmethoIQMGR6dYasCt2JlTmF4IBEHczX1OQynaQ&code_challenge_method=S256 HTTP/1.1" 401 2617 "http://osaka:8081/" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"
172.72.1.4 - - [29/Mar/2022:18:47:34 -0300] "GET /serviceworker.js?v=5.6.16 HTTP/1.1" 304 159 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"
172.72.1.4 - - [29/Mar/2022:18:47:37 -0300] "GET /oauth/authorize?client_id=7&redirect_uri=http%3A%2F%2Fosaka%3A8081%2Fcallback&response_type=code&scope=&state=nERPX0wQKIicdKGDRLNMcLhMlIalhi0XsjLl6ZcU&code_challenge=HFa7oV-RlHv6do3YNmkRsNrYfTFD86tigIjxrFz3OBQ&code_challenge_method=S256 HTTP/1.1" 401 2617 "http://osaka:8081/" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"
172.72.1.4 - - [29/Mar/2022:18:47:38 -0300] "GET /serviceworker.js?v=5.6.16 HTTP/1.1" 304 159 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"
172.72.1.4 - - [29/Mar/2022:18:47:57 -0300] "GET /oauth/authorize?client_id=7&redirect_uri=http%3A%2F%2Fosaka%3A8081%2Fcallback&response_type=code&scope=&state=BPqaLpnER14T9QTwgAVkXDqs6ViCh7L4IeQYbBjq&code_challenge=ly94LEmlp_VwKHaZYhCbWNnXa7BI71DVa1LzvWHRCTc&code_challenge_method=S256 HTTP/1.1" 401 2617 "http://osaka:8081/" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"
172.72.1.4 - - [29/Mar/2022:18:47:58 -0300] "GET /serviceworker.js?v=5.6.16 HTTP/1.1" 304 159 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"
172.72.1.4 - - [29/Mar/2022:18:48:32 -0300] "DELETE /oauth/tokens/f2c3525a390eb7f37aa748441592478618406c179b8c3446d5b3bf23a954c752126c07c3e35176d3 HTTP/1.1" 204 1753 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"
172.72.1.4 - - [29/Mar/2022:18:48:32 -0300] "GET /oauth/tokens HTTP/1.1" 200 3609 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"
172.72.1.4 - - [29/Mar/2022:18:48:33 -0300] "DELETE /oauth/tokens/74ab3ffc84965bee07313d39d134a3408741cb9f76b2abca9c57447678b75fb6b63b582d02839cf9 HTTP/1.1" 204 1753 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"
172.72.1.4 - - [29/Mar/2022:18:48:33 -0300] "GET /oauth/tokens HTTP/1.1" 200 3059 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"
172.72.1.4 - - [29/Mar/2022:18:48:34 -0300] "DELETE /oauth/tokens/2bbcedc2c8cb9fbaa83ec6c35213bd375184da58f45e7b4a727a984f4c47f0239207df2401fffc5b HTTP/1.1" 204 1753 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"
172.72.1.4 - - [29/Mar/2022:18:48:34 -0300] "GET /oauth/tokens HTTP/1.1" 200 2509 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"
[2022-03-29T18:48:41.695230-03:00] local.INFO: AUDIT: User visits homepage. (192.168.1.2 (ivan@tunguska.cc) -> GET:https://firefly.tunguska.cc) [] []
172.72.1.4 - - [29/Mar/2022:18:48:41 -0300] "GET / HTTP/1.1" 200 9714 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"
172.72.1.4 - - [29/Mar/2022:18:48:42 -0300] "GET /v1/js/ff/help.js?v=5.6.16 HTTP/1.1" 200 1203 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"
172.72.1.4 - - [29/Mar/2022:18:48:42 -0300] "GET /v1/js/ff/charts.js?v=5.6.16 HTTP/1.1" 200 3075 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"
172.72.1.4 - - [29/Mar/2022:18:48:42 -0300] "GET /v1/js/lib/chartjs-plugin-annotation.min.js?v=5.6.16 HTTP/1.1" 200 4863 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"
172.72.1.4 - - [29/Mar/2022:18:48:42 -0300] "GET /v1/js/ff/firefly.js?v=5.6.16 HTTP/1.1" 200 2460 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"
172.72.1.4 - - [29/Mar/2022:18:48:42 -0300] "GET /v1/js/ff/index.js?v=5.6.16 HTTP/1.1" 200 2106 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"
172.72.1.4 - - [29/Mar/2022:18:48:42 -0300] "GET /v1/js/ff/charts.defaults.js?v=5.6.16 HTTP/1.1" 200 1730 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"
172.72.1.4 - - [29/Mar/2022:18:48:42 -0300] "GET /v1/js/lib/Chart.bundle.min.js?v=5.6.16 HTTP/1.1" 200 8451 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"
172.72.1.4 - - [29/Mar/2022:18:48:42 -0300] "GET /v1/jscript/variables?ext=.js&v=5.6.16 HTTP/1.1" 200 5608 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"
172.72.1.4 - - [29/Mar/2022:18:48:42 -0300] "GET /chart/category/frontpage HTTP/1.1" 200 2887 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"
172.72.1.4 - - [29/Mar/2022:18:48:42 -0300] "GET /chart/account/revenue HTTP/1.1" 200 2887 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"
172.72.1.4 - - [29/Mar/2022:18:48:42 -0300] "GET /json/frontpage/piggy-banks HTTP/1.1" 200 2897 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"
172.72.1.4 - - [29/Mar/2022:18:48:42 -0300] "GET /json/box/available HTTP/1.1" 200 3037 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"
172.72.1.4 - - [29/Mar/2022:18:48:42 -0300] "GET /chart/budget/frontpage HTTP/1.1" 200 3088 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"
172.72.1.4 - - [29/Mar/2022:18:48:42 -0300] "GET /chart/account/expense HTTP/1.1" 200 2887 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"
172.72.1.4 - - [29/Mar/2022:18:48:42 -0300] "GET /json/box/balance HTTP/1.1" 200 3002 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"
172.72.1.4 - - [29/Mar/2022:18:48:42 -0300] "GET /api/v1/summary/basic?start=2022-03-01&end=2022-03-31 HTTP/1.1" 200 1173 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"
172.72.1.4 - - [29/Mar/2022:18:48:42 -0300] "GET /json/box/net-worth HTTP/1.1" 200 2923 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"
172.72.1.4 - - [29/Mar/2022:18:48:42 -0300] "GET /chart/account/frontpage HTTP/1.1" 200 17576 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"
172.72.1.4 - - [29/Mar/2022:18:48:42 -0300] "GET /serviceworker.js?v=5.6.16 HTTP/1.1" 200 1239 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"
172.72.1.4 - - [29/Mar/2022:18:48:57 -0300] "POST /oauth/personal-access-tokens HTTP/1.1" 200 3078 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"

```

### Steps to reproduce

docker-compose up -d
```
  firefly:
    image: fireflyiii/core:latest
    container_name: firefly
    restart: always
    environment:
      - PUID=1000
      - PGID=200
      - TZ=America/Sao_Paulo
      - DB_HOST=mariadb
      - DB_DATABASE=firefly
      - DB_USERNAME=firefly
      - DB_PORT=3306
      - DB_CONNECTION=mysql
      - DB_PASSWORD=<passwrod>
      - APP_KEY=<hereitis>
      - APP_URL=https://firefly.example.cc
      - TRUSTED_PROXIES=**
      - MAPBOX_API_KEY=<cut>
      - MAIL_MAILER=log
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=465
      - MAIL_FROM=myuser@example.cc
      - MAIL_USERNAME=myuser@gmail.com
      - MAIL_PASSWORD=<passwd>
      - MAIL_ENCRYPTION=SSL
    volumes:
      - /data/services/fireflyiii/storage/export:/var/www/html/storage/export
      - /data/services/fireflyiii/storage/upload:/var/www/html/storage/upload
    networks:
      - homelab
    ports:
      - 8080:8080

  firefly-importer:
    image: fireflyiii/data-importer:latest
    container_name: firefly-importer
    restart: always
    environment:
      - PUID=1000
      - PGID=200
      - TZ=America/Sao_Paulo
      - FIREFLY_III_URL=https://firefly.example.cc
      - VANITY_URL=https://firefly.example.cc
      - FIREFLY_III_ACCESS_TOKEN=<removed>
      - TRUSTED_PROXIES=**
      - JSON_CONFIGURATION_DIR=/configurations
      - VERIFY_TLS_SECURITY=false
      - CLIENT_ID=7
    networks:
      - homelab
    ports:
      - 8081:8080
    volumes:
      - /data/services/firefly-importer/config:/configurations
    depends_on:
      - firefly

```

firefly nginx:
```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name firefly.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    # enable for Authelia
    #include /config/nginx/authelia-server.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /ldaplogin;

        # enable for Authelia
        #include /config/nginx/authelia-location.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app firefly;
        set $upstream_port 8080;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    }

}
```

firefly data importer:
```server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name firefly-importer.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    # enable for Authelia
    #include /config/nginx/authelia-server.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /ldaplogin;

        # enable for Authelia
        #include /config/nginx/authelia-location.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app firefly-importer;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        set $upstream_port 8080;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    }

}

```
