### ISSUE TITLE
Cannot send email using self signed certificates 

### ISSUE THREAD

**Issue by DenBeke** [firefly-iii/firefly-iii#5996]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

After updating to Firefly 5.7.1 (official Docker image), I'm having troubles sending emails.

I get the following error:

```
Possible email error: Unable to connect with STARTTLS: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
```

I use a self-hosted SMTP server with self-signed certificates. It worked before with Firefly, and it still works with other services. I checked for the expiry date of my self signed certificates and they expire in 2030.

I have the following email config:

```
      - MAIL_DRIVER=smtp
      - MAIL_HOST=smtp
      - MAIL_PORT=25
      - MAIL_FROM=xxxxxxx
      - MAIL_USERNAME=xxxxxxx
      - MAIL_PASSWORD=xxxxxxx
      - MAIL_ENCRYPTION=null
```

### Expected behaviour

Is there an env variable I can use to disable certificate validation?

### Debug information

Debug information generated at 2022-04-12 17:59:57 Europe/Brussels for Firefly III version **5.7.1**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.1 |
| Firefly III API | 1.5.6 |
| Build | 153, 04-04-2022 05:56:25 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.0.17` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Brussels |
| Browser TZ | Europe/Brussels |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | warning, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-04-01 00:00:00 |
| Session end | 2022-04-30 23:59:59 |
| Session first | 2018-08-06 00:00:00 |
| User ID | 1 |
| User language | nl_NL |
| User locale | nl_NL |
| Attempt at "nl_NL.utf8" | 'nl_NL.utf8' |
| Attempt at "nl_NL.UTF-8" | 'nl_NL.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15 |

### Additional info

I use the following local SMTP relay config in my docker compose env:

```
smtp:
    container_name: smtp
    image: alterrebe/postfix-relay
    environment:
      - ACCEPTED_NETWORKS=xxxxxx
      - RELAY_HOST_NAME=xxxxxxxx
      - EXT_RELAY_HOST= xxxxxxxx
      - EXT_RELAY_PORT= xxxxxxxx
      - SMTP_LOGIN= xxxxxxxx
      - SMTP_PASSWORD= xxxxxxxx
      - SERVER_HOSTNAME= xxxxxxxx
    ports:
      - "25:25"
    expose:
      - "25"
    volumes:
      - ./conf/smtp/ssl:/etc/ssl:ro
```
