### ISSUE TITLE
firefly-iii Helm chart cannot inject extra env variables

### ISSUE THREAD

**Issue by mmalyska** [firefly-iii/firefly-iii#6066]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

In [firefly-iii chart](https://github.com/firefly-iii/kubernetes/tree/main/charts/firefly-iii) I cannot override `env` in deployment.
My usecase is that I'm using postgres operator that generates secret object that contains all DB related config.
I cannot use this secret as it has different keys than expected by firefly-iii.
So, I would like to use existing secret and map it to corresponding keys like this:
```
env:
  - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: fireflydb-pguser-fireflydb
          key: user
```

### Solution

allow to add `config.extraEnv` in chart values that will add up to deployment
