### ISSUE TITLE
[Helm] Deploying new version of application - `FailedAttachVolume`

### ISSUE THREAD

**Issue by mmalyska** [firefly-iii/firefly-iii#6078]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When updating deployment of application in K8S it fails with `FailedAttachVolume`. 
It happens only when `.persistance.enabled: true` and the pod is deployed on different node. The cause is `accessMode` set to: `ReadWriteOnce` as it says in documentation it cannot be used by pods in different nodes. I suppose changing it to `ReadWriteMany` would help, or changing chart to allow us to specify this parameter.

For now the fix is to create `pvc` by myself and use `.persistence.existingClaim`.

### Expected behaviour

The new deployment should start without issues.

### Debug information

![obraz](https://user-images.githubusercontent.com/999598/168592845-18f76c97-1d90-4937-bdf6-970ad3a183d5.png)
it is stuck with error
![obraz](https://user-images.githubusercontent.com/999598/168592896-7f57c9ed-b207-426d-8940-76f82254bc22.png)
Generated PVC manifest
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: firefly
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: firefly-iii
    helm.sh/chart: firefly-iii-1.3.0
  name: firefly-firefly-iii
  namespace: firefly
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
```

### Steps to reproduce

1. Set `.persistance.enabled: true`,
2. Deploy chart,
3. Change setting in deployment, ex. `env variable`,
4. Apply changes(this error only shows when pod is scheduled on different node).
