### ISSUE TITLE
multiple IMPORT_DIR_WHITELIST

### ISSUE THREAD

**Issue by TWART016** [firefly-iii/firefly-iii#6149]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I want to import a csv file with the data-importer v0.9.9.

`sudo docker exec -t fireflyiii_import_data php artisan importer:import /import/configurations/diba.json /data/file.csv`

```
docker-compose of the the data-importer
  import:
    image: fireflyiii/data-importer:latest
    container_name: fireflyiii_import_data
    restart: unless-stopped
    volumes:
      - /volume1/Skripte/fireflyIII/import:/import
      - /volume1/docker/fireflyIII/import/temp:/data
    ports:
      - 10001:8080
    environment:
      - FIREFLY_III_ACCESS_TOKEN=MYTOKEN
      - FIREFLY_III_URL=http://192.168.178.36:10000
      - JSON_CONFIGURATION_DIR=/import/configurations 
      - IMPORT_DIR_WHITELIST=/import/configurations
    depends_on:
      - app
      - db
```

I get the error:
`Path "/data" is not in the list of allowed paths (IMPORT_DIR_WHITELIST).
`

If I add the line 
`      - IMPORT_DIR_WHITELIST=/data`
I get the error:
`Path "/import/configurations" is not in the list of allowed paths (IMPORT_DIR_WHITELIST).
`

It seems that multiple paths are not allowed.

### Expected behaviour

add multiple IMPORT_DIR_WHITELIST is possible.

### Debug information

How can I get the information?
