### ISSUE TITLE
swagger json api v2 render issue

### ISSUE THREAD

**Issue by timhae** [firefly-iii/firefly-iii#7137]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

First of all, thanks for your great work! The [swagger api docu for v2](https://api-docs.firefly-iii.org/?urls.primaryName=2.0.0%20(v2)) does not render the v2 endpoints due to:
```
Parser error on line 715
duplicated mapping key
```
because there is on line 715:
```
  /v2/budgets/{id}/spent:
    get:
      tags:
        - budgets
      operationId: getSpentForBudgets
```
and also on line 545:
```
  /v2/budgets/{id}/spent:
    get:
      tags:
        - budgets
      operationId: getSpentForBudget
```
notice the missing `s` in the `operationId` in the second part. I don't know if this intentional or not possible to avoid.

### Expected behaviour

the api docu renders for v2 endpoints

### Debug information

not applicable
