### ISSUE TITLE
Forward Auth with Authentik

### ISSUE THREAD

**Issue by VPaulV** [firefly-iii/firefly-iii#7460]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I would really appreciate if one could add Authentic forward auth headers to firefly. The problem that it is using it's own custom headers not REMOTE_USER, but X-Authentik-Email, X-Authentik-Username, etc

Thank you for considering my request!

### Solution

Add support for custom forward auth headers

**Comment by VPaulV** [comment]
Nvm, I am just idiot. It is possible to customize header with AUTHENTICATION_GUARD_HEADER. Had to read wiki better. I am sorry for the confusion

**Comment by JC5** [comment]
Not a problem! 👍

**Comment by KubaDavid** [comment]
> Nvm, I am just an idiot. It is possible to customize header with AUTHENTICATION_GUARD_HEADER. Had to read wiki better. I am sorry for the confusion

Sorry for necroposting but how did you setup your Firefly and Authentik? I'm using it with Traefik and it still shows that "The guard header was unexpectedly empty".

**Comment by VPaulV** [comment]
Just add to your .env 
```
AUTHENTICATION_GUARD_HEADER=HTTP_X_AUTHENTIK_EMAIL
```
I use traefik as forward proxy here is my firefly setup for firefly:
```
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.firefly-app-secure.entrypoints=websecure"
      - "traefik.http.routers.firefly-app-secure.rule=Host(`domain.ltd`)"
      - "traefik.http.routers.firefly-app-secure.tls=true"
      - "traefik.http.routers.firefly-app-secure.tls.certresolver=myresolver"
      - "traefik.http.routers.firefly-app-secure.middlewares=chain-authentik@file"
      - "traefik.http.services.firefly-app-secure.loadbalancer.server.port=8080"
      - "traefik.docker.network=webproxy"
```
And here is how chain-authentik defined:
```
http:
  middlewares:
    chain-authentik:
      chain:
        middlewares:
          #- middlewares-traefik-bouncer # leave this out if you are not using CrowdSec
          - middlewares-rate-limit
          - middlewares-secure-headers
          - middlewares-authentik
          - middlewares-compress
```
I will not show all middlewares, just the ones you need to get it work
```
    middlewares-authentik:
      forwardAuth:
        address: "http://myLocalAuthentikDockerName:9000/outpost.goauthentik.io/auth/traefik"
        trustForwardHeader: true
        authResponseHeaders:
          - X-authentik-username
          - X-authentik-groups
          - X-authentik-email
          - X-authentik-name
          - X-authentik-uid
          - X-authentik-jwt
          - X-authentik-meta-jwks
          - X-authentik-meta-outpost
          - X-authentik-meta-provider
          - X-authentik-meta-app
          - X-authentik-meta-version
```
```
    middlewares-secure-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        accessControlMaxAge: 100
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        customFrameOptionsValue: "allow-from https:domain.ltd" 
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "same-origin"
        permissionsPolicy: "camera=(), microphone=(), geolocation=(), payment=(), usb=(), vr=()"
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex,"
          server: ""
```
Last step you need to setup a forward proxy in authentik, for this please have a look here:
https://github.com/brokenscripts/authentik_traefik#provider-creation-domain-wide

Hope this helps!

**Comment by VPaulV** [comment]
Just add to your .env 
```
AUTHENTICATION_GUARD_HEADER=HTTP_X_AUTHENTIK_EMAIL
```
I use traefik as forward proxy here is my firefly setup for firefly:
```
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.firefly-app-secure.entrypoints=websecure"
      - "traefik.http.routers.firefly-app-secure.rule=Host(`domain.ltd`)"
      - "traefik.http.routers.firefly-app-secure.tls=true"
      - "traefik.http.routers.firefly-app-secure.tls.certresolver=myresolver"
      - "traefik.http.routers.firefly-app-secure.middlewares=chain-authentik@file"
      - "traefik.http.services.firefly-app-secure.loadbalancer.server.port=8080"
      - "traefik.docker.network=yourNetwork"
```
And here is how chain-authentik defined:
```
http:
  middlewares:
    chain-authentik:
      chain:
        middlewares:
          #- middlewares-traefik-bouncer # leave this out if you are not using CrowdSec
          - middlewares-rate-limit
          - middlewares-secure-headers
          - middlewares-authentik
          - middlewares-compress
```
I will not show all middlewares, just the ones you need to get it work
```
    middlewares-authentik:
      forwardAuth:
        address: "http://myLocalAuthentikDockerName:9000/outpost.goauthentik.io/auth/traefik"
        trustForwardHeader: true
        authResponseHeaders:
          - X-authentik-username
          - X-authentik-groups
          - X-authentik-email
          - X-authentik-name
          - X-authentik-uid
          - X-authentik-jwt
          - X-authentik-meta-jwks
          - X-authentik-meta-outpost
          - X-authentik-meta-provider
          - X-authentik-meta-app
          - X-authentik-meta-version
```
```
    middlewares-secure-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        accessControlMaxAge: 100
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        customFrameOptionsValue: "allow-from https:domain.ltd" 
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "same-origin"
        permissionsPolicy: "camera=(), microphone=(), geolocation=(), payment=(), usb=(), vr=()"
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex,"
          server: ""
```
Last step you need to setup a forward proxy in authentik, for this please have a look here:
https://github.com/brokenscripts/authentik_traefik#provider-creation-domain-wide

Hope this helps!
