### ISSUE TITLE
Exit login error: 405 Method Not Allowed

### ISSUE THREAD

**Issue by s4w4j4** [firefly-iii/firefly-iii#7680]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Accessing `http://10.0.0.2:22301/v3/` Afterwards, visit again `http://10.0.0.2:22301`. Next, click on the "Exit Login" button and the following error page will appear. Unable to log out.

```
Oops! An Error Occurred

The server returned a "405 Method Not Allowed".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
```

### Debug information

Debug information generated at 2023-06-23 23:56:37 Asia/Shanghai for Firefly III version **6.0.15**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.15 |
| Firefly III API | 2.0.4 |
| Build | 506, 22-06-2023 03:58:31 UTC |
| Base Build | 10, 21-06-2023 21:55:03 CEST |
| DB version | 19 (exp. 19) |
| PHP | `8.2.7` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Asia/Shanghai |
| Browser TZ | Asia/Shanghai |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-06-01 00:00:00 |
| Session end | 2023-06-30 23:59:59 |
| Session first | 2023-06-12 00:00:00 |
| User ID | 72 |
| User language | zh_CN |
| User locale | zh_CN |
| Attempt at "zh_CN.utf8" | 'zh_CN.utf8' |
| Attempt at "zh_CN.UTF-8" | 'zh_CN.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.1 Safari/605.1.15 |

### Expected behaviour

I hope the logout button can work properly

### Steps to reproduce

1. Accessing `http://10.0.0.2:22301/v3/`
2. Accessing `http://10.0.0.2:22301`
3. click on the "Exit Login" button
4. Return to error page: '405 Method Not Allowed', unable to log out

**Comment by JC5** [comment]
Welp, that's what you get for testing the experimental new layout. Thanks for letting me know 👍

**Comment by s4w4j4** [comment]
> Welp, that's what you get for testing the experimental new layout. Thanks for letting me know 👍

This error, even if a new layout is not used, will occur randomly, so the steps to reproduce the problem cannot be determined.
After using the new layout, using the old layout will reproduce the problem 100%.

When a problem occurs, in addition to the "log out" exception, the dashboard page will also experience an exception

- Normal state instrument cluster
    <img width="1178" alt="截屏2023-06-24 13 21 42" src="https://github.com/firefly-iii/firefly-iii/assets/90949008/69cce9a1-331e-4c83-9d6b-f43b21b8f70e">

- Abnormal instrument cluster
    <img width="1178" alt="截屏2023-06-24 13 25 54" src="https://github.com/firefly-iii/firefly-iii/assets/90949008/2f796ab9-c41b-41df-ab9b-e2480d08625a">

**Comment by JC5** [comment]
Could you share some logs with me please?

**Comment by s4w4j4** [comment]
> Could you share some logs with me please?

Hello, is there a link to how to obtain the log?

**Comment by JC5** [comment]
https://docs.firefly-iii.org/firefly-iii/faq/other/#how-do-i-enable-debug-mode

**Comment by s4w4j4** [comment]
> Could you share some logs with me please?

Please check, thank you

[download_2023-06-24_20-31-58.zip](https://github.com/firefly-iii/firefly-iii/files/11856955/download_2023-06-24_20-31-58.zip)

**Comment by JC5** [comment]
Sorry, I see nothing that could indicate a problem. Does your browser report issues?

**Comment by s4w4j4** [comment]
> Sorry, I see nothing that could indicate a problem. Does your browser report issues?

Can you use Safari browser to test it? I tested using Safari and Chrome, and only Safari reproduced the problem.

**Comment by JC5** [comment]
No, sorry, I don't have Safari available right now.

**Comment by JC5** [comment]
I should be able to check this out in about 12 days.

**Comment by s4w4j4** [comment]
> I should be able to check this out in about 12 days.

Great, for the convenience of finding the problem, I recorded a video and hope it will be helpful.


https://github.com/firefly-iii/firefly-iii/assets/90949008/70da3775-2997-4ef3-8386-ebb5c364b230

**Comment by JC5** [comment]
Thank you. What platform are you using to host Firefly III?

**Comment by s4w4j4** [comment]
> Thank you. What platform are you using to host Firefly III?

The machine is QNAP NAS (TS-453Bmini, Intel x86), managed using Docker.

```
version: '3'

services:
    db:
        container_name: db-postgres-1
        image: postgres:14.7
        volumes:
            - /share/Container/data/fireflyiii/db:/var/lib/postgresql/data
#        ports:
#            - "5432:5432"
        restart: unless-stopped
        environment:
            - POSTGRES_DB=fireflyiii
            - POSTGRES_USER=fireflyiii
            - POSTGRES_PASSWORD=fireflyiii
    app-fireflyiii:
        container_name: app-fireflyiii
        image: fireflyiii/core:version-6.0.15
        volumes:
            - /share/Container/data/fireflyiii/upload:/var/www/html/storage/upload
        restart: unless-stopped
        ports:
            - 22301:8080
        depends_on:
            - db
        environment:
            - TZ=Asia/Shanghai
            - APP_KEY=xxxxx
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=fireflyiii
            - DB_USERNAME=fireflyiii
            - DB_PASSWORD=fireflyiii
```
