### ISSUE TITLE
Crontab Container should restart

### ISSUE THREAD

**Issue by vspaziani** [firefly-iii/firefly-iii#7705]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The docker-compose file that is sourced within the documentation currently includes the option for running a separate container that will preform the crontab tasks. In the current configuration it does not specify the restart parameter which means that it does not restart when the machine is restarted or the container otherwise stops.

### Debug information

`Debug information not applicable`

### Expected behaviour

On system startup, I expect the 'cron' container to start automatically as the other containers do.

### Steps to reproduce

1. Use current docker-compose.yml available at [docker-compose.yml](https://raw.githubusercontent.com/firefly-iii/docker/main/docker-compose.yml)
2. Verify that all three containers are currently running by executing: `sudo docker container ls`
3. Restart machine: `sudo reboot`
4. Verify that only two of three containers are currently running by executing: `sudo docker container ls`

### Additional info

I am suggesting that you add `restart: always` to Contab container as shown (I did not bump the version number despite a modification, I would update the version number according to your own method)

```
version: '3.3'

services:
  app:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    networks:
      - firefly_iii
    ports:
      - 80:8080
    depends_on:
      - db
  db:
    image: mariadb    
    hostname: fireflyiiidb
    restart: always
    env_file: .db.env
    networks:
      - firefly_iii
    volumes:
      - firefly_iii_db:/var/lib/mysql
  cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable and replace REPLACEME below
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    image: alpine
    restart: always
    command: sh -c "echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/REPLACEME\" | crontab - && crond -f -L /dev/stdout"
    networks:
      - firefly_iii

volumes:
   firefly_iii_upload:
   firefly_iii_db:

networks:
  firefly_iii:
    driver: bridge
```
