### ISSUE TITLE
mysqldump not available in db container

### ISSUE THREAD

**Issue by not1q84-1** [firefly-iii/firefly-iii#7922]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Just recognized that my backup procedure does not work anymore - and found out that the firefly_db_1 when executing a mysqldump command responds with a file not found. I also downloaded the firefly-iii-backuper.sh and tried this - with a rather simililar result. I installed version 6.0.22 earlier today, but from what I see from my backup history this error was also visible in 6.0.19 already. 

### Debug information

Debug information generated at 2023-09-02 05:56:49 Europe/Amsterdam for Firefly III version **6.0.22**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.22 |
| Firefly III API | 2.0.7 |
| Build | 630, 01-09-2023 17:55:37 UTC |
| Base Build | 37, 22-08-2023 14:10:40 UTC |
| DB version | 20 (exp. 20) |
| PHP | `8.2.9` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Amsterdam |
| Browser TZ | Asia/Singapore |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-09-01 00:00:00 |
| Session end | 2023-09-30 23:59:59 |
| Session first | 2013-06-07 00:00:00 |
| User ID | 1 |
| User language | de_DE |
| User locale | de_DE |
| Attempt at "de_DE.utf8" | 'de_DE.utf8' |
| Attempt at "de_DE.UTF-8" | 'de_DE.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.62 |

### Expected behaviour

mysqldump is available in firefly_db container or alternative method to backup the database

### Steps to reproduce

1. docker exec firefly_db_1 sh -c 'exec mysqldump --all-databases -uXXXX -p"XXXXXXX"' > /...../firefly.sql
2. responds with mysqldump not found

**Comment by JC5** [comment]
```
james@highgarden:~$ docker exec -it firefly-iii-db-1 mysqldump
Usage: mysqldump [OPTIONS] database [tables]
OR     mysqldump [OPTIONS] --databases DB1 [DB2 DB3...]
OR     mysqldump [OPTIONS] --all-databases
OR     mysqldump [OPTIONS] --system=[SYSTEMOPTIONS]]
For more options, use mysqldump --help
```

What image do you use for the database?

**Comment by not1q84-1** [comment]
Sorry should have checked that; but  I am simply running your docker-compose file example from the installation instructions. 

```
version: '3.3'

services:
  app:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - 8084:8080
    depends_on:
      - db

  db:
    image: mariadb
    hostname: fireflyiiidb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=xxxx
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=xxxx
      - MYSQL_DATABASE=firefly
      - MYSQLD_OPTS="--skip-grant-tables --skip-networking"
    ports:
      - 3306:3306
    volumes:
      - firefly_iii_db:/var/lib/mysql

volumes:
  firefly_iii_upload:
  firefly_iii_db:
```

which uses the _:latest_ container of mariadb. I am doing a monthly maintenance routine and as part of this update all containers to the latest version (like today). Hence, I am using mariadb image version 11.1.2.
