### ISSUE TITLE
Data Importer stops Autoimport of multiple Nordigen/GoCardless files if one has zero transactions

### ISSUE THREAD

**Issue by rerobade** [firefly-iii/firefly-iii#8389]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hi,

today I've upgraded my firefly instance to fireflyiii/data-importer:version-1.4.1 where issue #8386 should have been resolved. After the upgrade the autoimport of a directory (it contains multiple Nordigen/GoCardless configurations) still failes after importing a Nordigen/GoCardless file with 0 transactions and error

> 2024-01-14 13:08:12: Conversion index (error) 0: Zero transactions found at GoCardless
2024-01-14 13:08:12: Too many errors in the data conversion (1), exit.

### Debug information

Debug information generated at 2024-01-14 13:12:53 Europe/Berlin for Firefly III Data Importer version **1.4.1**.

<table><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr><tr><td>Version</td><td>1.4.1</td></tr><tr><td>Build</td><td><span>#</span>, base <span>#</span>78</td></tr><tr><td>System</td><td>PHP 8.3.1, Linux, apache2handler</td></tr></table><table><tr><th colspan="2">App information</th></tr><tr><th>Item</th><th>Value</th></tr><tr><td>Timezone</td><td>Europe/Berlin, Europe/Berlin</td></tr><tr><td>Environment</td><td>production</td></tr><tr><td>Debug mode</td><td>false, cache 'file'</td></tr><tr><td>Log level</td><td>debug, stack</td></tr><tr><td>Display errors</td><td>Off, ALL errors</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Trusted proxies</td><td></td></tr></table><table><tr><th colspan="2">User information</th></tr><tr><th>Item</th><th>Value</th></tr><tr><td>User agent</td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36</td></tr></table>

### Expected behaviour

Even if one Nordigen/GoCardless Configuration returns an empty set of transactions the autoimport should continue to import the other files as well.

### Steps to reproduce

1. Setup data-importer and config directory with at least one Nordigen/GoCardless file and other files for autoimport
2. Ensure that the "zero transaction" Nordigen/GoCardless config is not process as last file
3. Start the autoimport via curl --location --request POST 'http://fidi:8080/autoimport?directory=/configurations&secret=****'
4. check the output and see the some similar error like
```html
2024-01-14 13:08:12: Conversion index (error) 0: Zero transactions found at GoCardless
2024-01-14 13:08:12: Too many errors in the data conversion (1), exit.
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="color-scheme" content="light dark">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="http://docker-prod-01:32780/css/bootstrap-dark.min.css?version=1.4.1">
    <link href="http://docker-prod-01:32780/fa/css/all.min.css" rel="stylesheet">

    <meta name="theme-color" content="#111111" media="(prefers-color-scheme: light)">
    <meta name="theme-color" content="#eeeeee" media="(prefers-color-scheme: dark)">

    <title>500 error :(</title>
</head>
<body>
<div class="container">
    <div class="row mt-3">
        <div class="col-lg-10 offset-lg-1">
            <h1>Whoops! 500 :(</h1>
            <p>
                Sorry, the Firefly III Data Importer broke down.
            </p>
            <h2>Error message</h2>
            <p class="text-danger">
                Import exception (see the logs): Too many errors in the data conversion.
            </p>
            <h2>More information</h2>
            <p>
                The error occurred in <code>/var/www/html/app/Http/Controllers/AutoImportController.php:86</code>.
            </p>
            <p>
                Please collect more information in the <code>storage/logs</code> directory, where you will find log files.
                If you're running Docker, use <code>docker logs -f [container]</code>.
                You can read more about collecting error information <a href="https://docs.firefly-iii.org/how-to/general/debug/"
                                                                        target="_blank">in the FAQ</a>.
            </p>
            <h2>Get help on GitHub</h2>
            <p>
                You're more than welcome to open a new issue <strong><a href="https://github.com/firefly-iii/firefly-iii/issues">on GitHub</a></strong>.
            </p>
            <ol>
                <li>Use the search!</li>
                <li>Include the information <a href="http://******/debug">from this debug page</a>.</li>
                <li>Tell us more than &quot;it says100  4288    0  4288    0     0    201      0 --:--:--  0:00:21 --:--:--   997
 Whoops!&quot;</li>
                <li>Include error logs (see above).</li>
                <li>Tell us what you were doing.</li>
            </ol>

        </div>
    </div>
</body>
</html>
```

### Additional info

Before the upgrade I used data-importer 1.3.12 which worked like expected and did not have this issue. So I was going through your releasenotes and found https://github.com/firefly-iii/firefly-iii/issues/8000 and after a closer look also this commit [482d093](https://github.com/firefly-iii/data-importer/commit/482d093e5d0236ca2ecb44f119896ab0936dadab) in which you added an error if zero transactions are returned.
I'm not sure why you see it as an error to get no transactions back. For me it is only an info or a warning because it is expected to get sometimes 0 transactions for some accounts as not all have daily transactions. E.g. we have our saving accounts at another bank which normally are only having transactions once or twice per month.
So currently version 1.4.0 & 1.4.1 makes data-importer not usable for me without creating some workaround to process each file separately. So I would be happy if you can fix this, please :-)

Thanks and Regards
René

**Comment by JC5** [comment]
> I'm not sure why you see it as an error to get no transactions back

That's not entirely what's happening in the code, but I understand the confusion. I'll pick it up!

**Comment by rerobade** [comment]
> > I'm not sure why you see it as an error to get no transactions back
> 
> That's not entirely what's happening in the code, but I understand the confusion. I'll pick it up!

Thank you :-D

**Comment by thomase1234** [comment]
Hi @JC5 ,
I have an issue which is triggered under the same conditions.
My first json import file will fetch multiple transactions. The 2nd json fetches zero. Still the "Import Report Mail" of the 2nd will show all transactions ( obviously as duplicates ) of the 1st.

First report:
![image](https://github.com/firefly-iii/firefly-iii/assets/74363906/2601c1fa-4b33-4659-bb7c-3f1a671d4ad7)

2nd report:
![image](https://github.com/firefly-iii/firefly-iii/assets/74363906/5afe1dd9-3eab-4643-82ab-93ef9e4b1536)
The fact that transaction 5155 is twice listed as duplicate is normal. But it's not possible that the bank in the 2nd json has an identical list of transaction as the first json.

I have a 3rd and 4th json but those are never processed, because the process stopped with the same error as the original poster. "Too many errors in the data conversion"

Could it be that the transactions list is not cleared when switching from 1 json configuration file to another ?

If this issue is completely unrelated, I can open a new issue.

Thanks,
Thomas

**Comment by JC5** [comment]
Thanks all. This will be fixed in the next release. You can test if this works by running `:develop`.

**Comment by rerobade** [comment]
Hi @JC5 ,

thanks for the quick fix, the import works again with the latest :develop version. But the defect reported by @thomase1234 above still persists. The first Mail with an error like 

> Line #1: Could not download from GoCardless: GuzzleHttp\Exception\ServerException: Server error: GET https://ob.nordigen.com/api/v2/accounts/4aa8ddb5-aaa8-4f9e-bdeb-abc845bf729e/transactions/ resulted in a 503 Service Unavailable response: {"summary":"Couldn't update account transactions","detail":"Institution service unavailable","status_code":503,"type":"S (truncated...)

also contains the successful messages from the previous import. So it looks like some list or array is not reseted after an import. It's up to you of this is a separate issue or something you wanted also to fix with this defect.
And I'm also not so sure if an exception in a Mail will make some users nervous and causes unwanted bug-reports in your inbox :-)

Thanks and regards
René

**Comment by JC5** [comment]
Thanks René. Tell me, how did you fire the import routine that resulted in this error? Was it a cron job, the UI, something else? Please share the command as detailed as you are able, it helps me narrow down the search.

**Comment by rerobade** [comment]
Hi @JC5,

I've a simple daily cron-job which just calls
`curl --location --request POST 'http://fidi:8080/autoimport?directory=/configurations&secret=<my secret>'`
And this is the configuration of my importer container within my docker-compose.yml

```yml
...
fidi:
    container_name: fireflyiii_fidi
    image: fireflyiii/data-importer:develop
    restart: unless-stopped
    networks:
      - fireflyiii
    environment:
      - FIREFLY_III_URL=http://fireflyiii_app:8080
      - VANITY_URL=https://${DNS_NAME}
      - FIREFLY_III_ACCESS_TOKEN_FILE=/run/secrets/fireflyiii_access_token
      - NORDIGEN_ID_FILE=/run/secrets/fireflyiii_nordigen_id
      - NORDIGEN_KEY_FILE=/run/secrets/fireflyiii_nordigen_key
      - TZ=${TZ}
      - JSON_CONFIGURATION_DIR=/configurations
      - AUTO_IMPORT_SECRET_FILE=/run/secrets/fireflyiii_auto_import_secret
      - CAN_POST_AUTOIMPORT=true
      - CAN_POST_FILES=true
      - IMPORT_DIR_ALLOWLIST=/configurations
      - ENABLE_MAIL_REPORT=true
      - MAIL_DESTINATION=xxxxx@xxxxx.com
      - MAIL_MAILER=smtp
      - MAIL_HOST_FILE=/run/secrets/smtp_host
      - MAIL_PORT_FILE=/run/secrets/smtp_port
      - MAIL_FROM_ADDRESS_FILE=/run/secrets/smtp_mail_from
      - MAIL_USERNAME_FILE=/run/secrets/smtp_name
      - MAIL_PASSWORD_FILE=/run/secrets/smtp_password
      - MAIL_ENCRYPTION_FILE=/run/secrets/smtp_secure
      - STATIC_CRON_TOKEN_FILE=/run/secrets/fireflyiii_static_cron_token
    volumes:
      - ./fidi-config:/configurations:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - xxxxxx:8080
    depends_on:
      - app
    secrets:
      - fireflyiii_access_token
      - fireflyiii_nordigen_id
      - fireflyiii_nordigen_key
      - fireflyiii_auto_import_secret
      - fireflyiii_static_cron_token
      - smtp_host
      - smtp_port
      - smtp_mail_from
      - smtp_name
      - smtp_password
      - smtp_secure
...    
```

Regards René
