### ISSUE TITLE
Add OCI Labels to Docker Images

### ISSUE THREAD

**Issue by mytlogos** [firefly-iii/firefly-iii#8391]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

I would like to have at least the docker image for firefly-iii itself, labels set in the image.
For example the image for docker-mailserver has these labels set:

```yaml
        "org.opencontainers.image.authors": "The Docker Mailserver Organization on GitHub",
        "org.opencontainers.image.description": "A fullstack but simple mail server (SMTP, IMAP, LDAP, Antispam, Ant>
        "org.opencontainers.image.documentation": "https://github.com/docker-mailserver/docker-mailserver/blob/maste>
        "org.opencontainers.image.licenses": "MIT",
        "org.opencontainers.image.revision": "652bbd831f6d25bf79b619094610011891ecddb7",
        "org.opencontainers.image.source": "https://github.com/docker-mailserver/docker-mailserver",
        "org.opencontainers.image.title": "docker-mailserver",
        "org.opencontainers.image.url": "https://github.com/docker-mailserver",
        "org.opencontainers.image.vendor": "The Docker Mailserver Organization",
        "org.opencontainers.image.version": "12.1.0"
```

This e.g. allows people to immediately spot the software/project version that is running in the container in an *standardized* way.

### Solution

Add Labels in the Build step where the "maintainer" label is already set.

### What are alternatives?

Currently the version can be gleamed from the env variables set or from the variable in the config/firefly.php file.

```[tasklist]
### Tasks
```
