### ISSUE TITLE
419 Page expired using redis

### ISSUE THREAD

**Issue by rizlas** [firefly-iii/firefly-iii#8492]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Using redis and a fresh (empty) istance I'm hitting randomly the error page "419 Page expired".
Without redis, everything is working fine.

### Debug information

No errors in logs.

https://stackoverflow.com/questions/52583886/post-request-in-laravel-error-419-sorry-your-session-419-your-page-has-exp

### Steps to reproduce

I've no secure step to reproduce but after login, refresh the page once or more than once and the error will appear. Or it'll just pop up randomly.

### Additional info

My redis setup. Everything else is default.

```
  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    container_name: firefly_iii_redis
    env_file:
      - env/redis.env
    command: /bin/sh -c 'redis-server --appendonly yes --requirepass $${REDIS_PASSWORD}'
    networks:
      - network
    volumes:
      - firefly_iii_redis_cache_data:/data
```
