### ISSUE TITLE
Expose basic transaction counts through API

### ISSUE THREAD

**Issue by GensHaze** [firefly-iii/firefly-iii#8629]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/explanation/more-information/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

Hello,

I love Firefly. I have integrated it into my daily life. I was hoping to implement it into my Homepage, using a custom API widget. I've looked through the v1 and v2 endpoints, though I don't think I've spotted any existing feature similar to this.

### Solution

I'd love it if Firefly could expose just basic counts of what you've transacted during any given period of time. One single API endpoint that would give you (perhaps based on any given parameters) - current week's transactions, current month transactions, year to date, any specified year... total amount of transactions recorded. Perhaps just something like... `v2/transactions/counts`?

My hope is to set my homepage widget like
FireFlyIII
[Transactions Recorded This Week] [Transactions Recorded This Month] [Transactions Recorded All Time]

Similar to how I have set it up with Maloja:
![image](https://github.com/firefly-iii/firefly-iii/assets/56946907/63a0c7b6-9f12-45b2-abf6-ce2d0f28a900)

### Additional context

I am hoping this is a simple addition, that would actually have tangible benefit. Whenever I see a '0' any given day, I think it would be a good reminder that I need to start recording any transactions I may have in mybacklog.

Thank you!

**Comment by JC5** [comment]
In the mean time, every API endpoint exposes a "total" that you can use.

**Comment by GensHaze** [comment]
Thank you;  using this total value, I was able to come up with a, although relatively jank, working solution. I created a bash script to poll the API's (returning a single transaction to reduce load), setting the needed date range parameters through the script itself, and save these values to a JSON that I expose through a bare nginx Docker container (that I use for other things too). I'll be running a cronjob for checking every few minutes, and that's that. It won't be real time, but good enough for now!

Thanks again for your hard work.

![image](https://github.com/firefly-iii/firefly-iii/assets/56946907/0ee0d04c-eb49-4d0f-bc7b-f8d713eedf13)

**Comment by luzpaz** [comment]
@GensHaze would you be willing to share the code ?

**Comment by GensHaze** [comment]
Nothing super fancy, really, and I know this could be improved in a million ways. Far from being the expert resource at this all!
Worth noting also, since I had created this thread, Homepage did add an official Firefly widget. I think I prefer seeing the counts rather than my massive debt though, I mean my net worth 🥲 

The script, set to run constantly in cron, goes like this:


```
#!/bin/bash

current_week=$(date +"%V")
current_month=$(date +"%m")
current_year=$(date +"%Y")

start_of_week=$(date -d "$(date +%Y-%m-%d) -$(date +%u) days" +"%Y-%m-%d")
start_of_month=$(date -d "$current_year-$current_month-01" +"%Y-%m-%d")
start_of_year=$(date -d "$current_year-01-01" +"%Y-%m-%d")

authheader="Authorization: Bearer <token>"
contentheader="Content-Type: application/json; Charset=UTF-8"

totalweek=$(curl -s -H "$authheader" "https://<url>/api/v1/transactions?limit=1&start=$start_of_week" | jq '.meta.pagination.total')
totalmonth=$(curl -s -H "$authheader" "https://<url>/api/v1/transactions?limit=1&start=$start_of_month" | jq '.meta.pagination.total')
totalyear=$(curl -s -H "$authheader" "https://<url>/api/v1/transactions?limit=1&start=$start_of_year" | jq '.meta.pagination.total')
total=$(curl -s -H "$authheader" "https://<url>/api/v1/transactions?limit=1" | jq '.meta.pagination.total')

echo "Start of week: $start_of_week"
echo "Start of month: $start_of_month"
echo "Start of year: $start_of_year"

echo "Total current week: $totalweek"
echo "Total current month: $totalmonth"
echo "Total current year: $totalyear"
echo "Total: $total"

printf '{"totalweek": "%s", "totalmonth": "%s", "totalyear": "%s", "total": "%s"}' "$totalweek" "$totalmonth" "$totalyear" "$total" > <pathToServer>.json
```

To make this work and expose the json, you'd need to also stand up at the very least an nginx instance:

```
services:
    nginx:
        container_name: nginx
        image: nginx
        volumes:
            - ./static:/app/static
        networks:
          proxy:
            ipv4_address: <dockerIP>
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "<port>:8080"
```

Dockerfile:

```
FROM nginx:alpine

WORKDIR /app

COPY . .

COPY ./nginx.conf /etc/nginx/nginx.conf
```

And finally, to have the counts actually show in your homepage widget, you'd need to add:

```
    - FireflyIII:
        icon: firefly.png
        href: https://<url>/
        description: Finance expense tracker
        siteMonitor: https://<url>/
        widget:
          type: customapi
          url: http://<nginxUrl>/<serverPath>.json
          refreshInterval: 300000
          method: GET
          mappings:
            - field: totalweek
              label: This Week
              fomat: number
            - field: totalmonth
              label: This Month
              format: number
            - field: totalyear
              label: This Year
```

You might need to reference the internal docker IP depending on how you have it set up, and additionally, the Total count stopped working at some point and I removed it, I figured it didn't add much value to me anyway, at this time. Hopefully that helps.
