### ISSUE TITLE
Wrong base URL when using Docker

### ISSUE THREAD

**Issue by skobkin** [firefly-iii/firefly-iii#8785]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

# Summary

When running Firefly III using Docker Compose based on official Compose configuration files (but slightly simplified), I'm getting strange behavior from Firefly III.

### Debug information

Debug information generated at 2024-04-15 02:41:30 for Firefly III version **v6.1.13**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.13 / v2.0.13 / 23 (exp. 23)</td></tr><tr><td>PHP version</td><td>8.3.4 (64bits) / apache2handler / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>1052, base <span>#</span>82</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Moscow + Europe/Moscow</td></tr><tr><td>App environment</td><td>production, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>never (never)</td></tr><tr><td>Mailer</td><td>smtp</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td></td></tr><tr><td>Session start</td><td></td></tr><tr><td>Session end</td><td></td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36</td></tr></tbody></table>

### Expected behaviour

Site is working properly, every resource and form works fine.

For some reason most URL's point at `http://127.0.0.1:8392/`

![image](https://github.com/firefly-iii/firefly-iii/assets/967576/4fbde43d-69a8-4f21-819e-99f498ec24bd)

Because 8392 is my port on host where internal container port is being mapped to. Firefly III should't know about it at all.

### Steps to reproduce

Nginx config is like this:

```
server {
  listen 443 ssl http2;                                                                                                                                                                                             
  server_name *redacted*;                                                                                                                                                                                          

  access_log /var/log/nginx/*redacted*.access;                                                                                                                                                                   
  error_log /var/log/nginx/*redacted*.error;                                                                                                                                                                       

  charset utf-8;

  location / {
    proxy_pass http://127.0.0.1:8392;                                                                                                                                                                               
  }

  #include config/gzip.conf;

  # Wildcard certificate config                                                                                                                                                                                     
  include ssl/*redacted*.conf;
}
```

Docker Compose config:

```yaml
version: '3.8'

services:
  app:
    image: 'fireflyiii/core:${IMAGE_TAG:-latest}'
    hostname: app
    container_name: firefly_iii_core
    restart: always
    volumes:
      - '${UPLOAD_DIR:-./upload}:/var/www/html/storage/upload'
    env_file: .env
    networks:
      - firefly_iii
    ports:
      - '${WEB_BIND_ADDR:-127.0.0.1}:${WEB_BIND_PORT:-8392}:8080/tcp'
    depends_on:
      - db

  db:
    image: mariadb:lts
    hostname: db
    container_name: firefly_iii_db
    restart: always
    env_file: .env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: '${DB_USERNAME:-firefly}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE:-firefly}'
    networks:
      - firefly_iii
    volumes:
      - '${DB_DIR:-./db}:/var/lib/mysql'

  cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable and replace REPLACEME below
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    image: alpine
    restart: always
    container_name: firefly_iii_cron
    env_file: .env
    command: sh -c "echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/${STATIC_CRON_TOKEN}\" | crontab - && crond -f -L /dev/stdout"
    networks:
      - firefly_iii

networks:
  firefly_iii:
    driver: bridge
```

### What did I try to fix this?

1. Set `APP_URL`, of course.
2. Tried to set `APP_FORCE_ROOT` as was suggested in some ticket.
3. Checked with `docker compose config` that both are really being read from the `.env` file I use.
4. Some other tinkering like renaming env vars I suspected to conflict with Laravel, but it didn't help.
5. Setting `TRUSTED_PROXIES` from `**` to host IP on the Firefly III stack bridge interface and back.

### Configuration

Here I have my stack publicly accessible. It may be more convenient to view it in Forgejo web interface:

https://git.skobk.in/skobkin/docker-stacks/src/branch/master/firefly-iii

### P.S.

I'm not entirely sure that it's not my fault, but I
