### ISSUE TITLE
Authorization tokens become invalid ufter pull new docker version

### ISSUE THREAD

**Issue by JcMinarro** [firefly-iii/firefly-iii#9076]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I have a docker compose with my configuration.
Then, I does `docker compose pull && docker compose up -d`
After that, the 3 Personal Access Token I have configured on my profile become invalid and receive 401 error.
I have 3 PAT, one for the Firefly Importer and 2 for two different apps, both of them become invalid after upgrade my containers.
Am I doing anything wrong when upgrading my containers?

### Debug information

Debug information generated at 2024-07-22 17:28:27 for Firefly III version **v6.1.19**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.19 / v2.1.0 / 24 (exp. 24)</td></tr><tr><td>PHP version</td><td>8.3.9 (64bits) / apache2handler / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>1113, base <span>#</span>86</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Madrid + Europe/Madrid</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>es_ES + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-07-21 22:00:00 (17 hours ago)</td></tr><tr><td>Mailer</td><td>smtp</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has liabilities">:credit_card:</span> <span title="Has rules">:wrench:</span> <span title="Has object groups">:bookmark_tabs:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-07-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-07-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>es_ES</td></tr><tr><td>User locale</td><td>es_ES</td></tr><tr><td>Locale(s) supported</td><td>es_ES.utf8: :white_check_mark:<br>es_ES.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36</td></tr></tbody></table>

### Expected behaviour

The PAT remain valid after upgrading my container

### Steps to reproduce

I am using `latest` version, pull last version and start contianers

**Comment by JC5** [comment]
Mmm, this was the first thing I fixed, years ago already. Upgrades should not invalidate tokens and the latest upgrade didn't invalidate my own tokens. 

I'm curious to see this reproduced. Do you have any logs from a time this happened?

**Comment by JcMinarro** [comment]
I have it installed on a proxmox container using docker.
I can rollback to a previous snapshot and do the test you need.
Which logs do you need?

BTW, I can see that whatever change that "recreate the container", the tokens becomes invalid.
Could it be tokens are not properly stored a volume?

It is the docker-compsoe.yml I use:
```
version: '3.3'

services:
  firefly-app:
    image: fireflyiii/core:latest
    hostname: firefly-app
    container_name: firefly_iii_core
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    networks:
      - firefly_iii
    ports:
      - 80:8080
    depends_on:
      - firefly-db

  firefly-importer:
    image: fireflyiii/data-importer:latest
    hostname: firefly-importer
    restart: always
    container_name: firefly_iii_importer
    volumes:
      - firefly_iii_import:/import
      - firefly_iii_configs:/storage/configurations
    networks:
      - firefly_iii
    ports:
      - '81:8080'
    depends_on:
      - firefly-app
    env_file: .importer.env

  firefly-db:
    image: mariadb
    hostname: firefly-db
    container_name: firefly_iii_db
    restart: always
    env_file: .db.env
    networks:
      - firefly_iii
    volumes:
      - firefly_iii_db:/var/lib/mysql
  firefly-cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable and replace REPLACEME below
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    image: alpine
    restart: always
    container_name: firefly_iii_cron
    command: sh -c "echo \"0 3 * * * wget -qO- http://firefly-app:8080/api/v1/cron/[***REMOVED SENSITIVE VALUE***]\" > /tmp/crontab && echo \"0 0 * * * wget -qO- --post-data '' 'http://firefly-importer:8080/autoimport?directory=/import&secret=[***REMOVED SENSITIVE VALUE***]'\" >> /tmp/crontab && crontab /tmp/crontab && rm /tmp/crontab && crond -f -L /dev/stdout"
    depends_on:
      - firefly-importer
      - firefly-app
    networks:
      - firefly_iii

  my-telegram-importer:
    image: ***REMOVED SENSITIVE VALUE***:main
    hostname: my-telegram-importer
    container_name: my-telegram-importer
    env_file: .telegram.importer.env
    volumes:
      - telegram_firefly_data:/data
    networks:
      - firefly_iii
    restart: always
    depends_on:
      - firefly-importer

volumes:
   firefly_iii_upload:
   firefly_iii_db:
   firefly_iii_import:
   firefly_iii_configs:
   telegram_firefly_data:

networks:
  firefly_iii:
```
