### ISSUE TITLE
500 Server Error after importing data with Cadburn (cron)

### ISSUE THREAD

**Issue by Gsyltc** [firefly-iii/firefly-iii#9095]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hi, 
I'm having a problem using the command ```php artisan importer:import /import/account.json``` via chadburn (Cron for swarm).

When I try to open the Web ui, I get the message (500 | Server Error).
However, commands via bash (php artisant importer:import) still work.

Import realized with GoCardless

![Sans titre](https://github.com/user-attachments/assets/adce16b2-e46e-4039-807b-5bcfb9a9ab06)

Thanks

### Debug information

No logs in stdout :(

### Expected behaviour

After the cron job, I wish to access the web UI without restarting the importer container

### Steps to reproduce

Launch importer with this configuration :
```
services:
 importer:
    image: fireflyiii/data-importer:latest
    labels:
      - chadburn.enabled=true
      - chadburn.job-exec.fiii_revolut.schedule=30 7 * * *
      - chadburn.job-exec.fiii_revolut.command=php artisan importer:import /config/account.json
  ...
  ```
  
  For the chadburn stack 
```
services:
  chadburn:
    image: premoweb/chadburn:latest
    command: daemon
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      chadburn.job-local.my-test-job.schedule: "@every 1h"
      chadburn.job-local.my-test-job.command: "date"
    deploy:
      mode: global
```

### Additional info

Data Importer Version 1.5.3
Chadburn Version : latest
