### ISSUE TITLE
After latest update (6.1.20), FIrefly III is not starting

### ISSUE THREAD

**Issue by Adandu** [firefly-iii/firefly-iii#9277]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When starting the docker container the logs look like this and firfly core is not starting.

Portainer Logs Logs:
Now in entrypoint.sh for Firefly III
Script:            1.4.1 (2024-05-18)
User:              root
Group:             root
Working dir:       /var/www/html
Base build number: 90
Base build date:   31-08-2024 19:17:00 CEST
Build number:      1123
Build date:        28-09-2024 08:29:11 CEST
APACHE_RUN_GROUP:  
APACHE_RUN_USER:   
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
Generated optimized autoload files containing 7392 classes
   INFO  Discovering packages.  
  diglactic/laravel-breadcrumbs ......................................... DONE
  genealabs/laravel-model-caching ....................................... DONE
  jc5/google2fa-laravel ................................................. DONE
  laravel-json-api/encoder-neomerx ...................................... DONE
  laravel-json-api/laravel .............................................. DONE
  laravel-json-api/spec ................................................. DONE
  laravel-json-api/validation ........................................... DONE
  laravel/passport ...................................................... DONE
  laravel/sanctum ....................................................... DONE
  laravel/slack-notification-channel .................................... DONE
  laravel/ui ............................................................ DONE
  nesbot/carbon ......................................................... DONE
  nunomaduro/collision .................................................. DONE
  nunomaduro/termwind ................................................... DONE
  rcrowe/twigbridge ..................................................... DONE
  spatie/laravel-html ................................................... DONE
  spatie/laravel-ignition ............................................... DONE
  [i] Wait for the database. You may see an error about an 'aborted connection', this is normal.
wait-for-it.sh: waiting 60 seconds for 192.168.200.249:3306
wait-for-it.sh: 192.168.200.249:3306 is available after 0 seconds
  [✓] DB is up.
  [i] Wait another 10 seconds in case the DB needs to boot.
  [✓] Done waiting for the DB to boot.
  [i] Will run database commands.
      DSN is mysql:host=192.168.200.249;port=3306;charset=utf8mb4
  [i] Database "firefly" exists.
  [i] Will run upgrade commands.
   INFO  Nothing to migrate.  
   INFO  Seeding database.  
  Database\Seeders\AccountTypeSeeder ................................. RUNNING  
  Database\Seeders\AccountTypeSeeder .............................. 12 ms DONE  
  Database\Seeders\TransactionCurrencySeeder ......................... RUNNING  
  Database\Seeders\TransactionCurrencySeeder ...................... 65 ms DONE  
  Database\Seeders\TransactionTypeSeeder ............................. RUNNING  
  Database\Seeders\TransactionTypeSeeder .......................... 10 ms DONE  
  Database\Seeders\PermissionSeeder .................................. RUNNING  
  Database\Seeders\PermissionSeeder ................................ 3 ms DONE  
  Database\Seeders\LinkTypeSeeder .................................... RUNNING  
  Database\Seeders\LinkTypeSeeder .................................. 7 ms DONE  
  Database\Seeders\ConfigSeeder ...................................... RUNNING  
  Database\Seeders\ConfigSeeder .................................... 2 ms DONE  
  Database\Seeders\UserRoleSeeder .................................... RUNNING  
  Database\Seeders\UserRoleSeeder ................................. 15 ms DONE  
  Database\Seeders\ExchangeRateSeeder ................................ RUNNING  
  Database\Seeders\ExchangeRateSeeder ............................. 56 ms DONE  
  [i] No decryption required for table "accounts".
  [i] No decryption required for table "attachments".
  [i] No decryption required for table "bills".
  [i] No decryption required for table "budgets".
  [i] No decryption required for table "categories".
  [i] No decryption required for table "piggy_banks".
  [i] No decryption required for table "preferences".
  [i] No decryption required for table "tags".
  [i] No decryption required for table "transaction_journals".
  [i] No decryption required for table "transactions".
  [i] No decryption required for table "journal_links".
      Now executing firefly-iii:transaction-identifiers
  [i] This command has already been executed.
      Now executing firefly-iii:migrate-to-groups
  [i] Database is already migrated.
      Now executing firefly-iii:account-currencies
  [i] This command has already been executed.
      Now executing firefly-iii:transfer-currencies
  [i] This command has already been executed.
      Now executing firefly-iii:other-currencies
  [i] This command has already been executed.
      Now executing firefly-iii:migrate-notes
  [i] This command has already been executed.
      Now executing firefly-iii:migrate-attachments
  [i] This command has already been executed.
      Now executing firefly-iii:bills-to-rules
  [i] This command has already been executed.
      Now executing firefly-iii:bl-currency
  [i] This command has already been executed.
      Now executing firefly-iii:cc-liabilities
  [i] This command has already been executed.
      Now executing firefly-iii:back-to-journals
  [i] This command has already been executed.
      Now executing firefly-iii:rename-account-meta
  [i] This command has already been executed.
      Now executing firefly-iii:migrate-recurrence-meta
  [i] This command has already been executed.
      Now executing firefly-iii:migrate-tag-locations
  [i] This command has already been executed.
      Now executing firefly-iii:migrate-recurrence-type
  [i] This command has already been executed.
      Now executing firefly-iii:upgrade-liabilities
  [i] This command has already been executed.
      Now executing firefly-iii:liabilities-600
  [i] This command has already been executed.
      Now executing firefly-iii:budget-limit-periods
  [i] This command has already been executed.
      Now executing firefly-iii:migrate-rule-actions
  [i] All rule actions are up to date.
      Now executing firefly-iii:restore-oauth-keys
  [i] Restored OAuth keys from database.
      Now executing firefly-iii:correct-account-balance
  [i] This command has already been executed.
      Now executing firefly-iii:create-group-memberships
  [✓] Validated group memberships
      Now executing firefly-iii:upgrade-group-information
      Now executing firefly-iii:upgrade-currency-preferences
  [i] This command has already been executed.
      Now executing firefly-iii:correct-database
      Now executing command "firefly-iii:fix-piggies"
  [✓] All piggy bank events are OK.
      Now executing command "firefly-iii:create-link-types"
  [✓] All link types are OK
      Now executing command "firefly-iii:create-access-tokens"
  [✓] Verified access tokens.
      Now executing command "firefly-iii:remove-bills"
  [✓] All bills and journals are OK
      Now executing command "firefly-iii:fix-amount-pos-neg"
  [✓] All auto budget amounts are positive.
  [✓] All available budget amounts are positive.
  [✓] All bill amounts are positive.
  [✓] All budget limit amounts are positive.
  [✓] All currency exchange rates are positive.
  [✓] All piggy bank repetition amounts are positive.
  [✓] All piggy bank amounts are positive.
  [✓] All recurring transaction amounts are positive.
  [✓] All rule trigger amounts are positive.
      Now executing command "firefly-iii:enable-currencies"
      Now executing command "firefly-iii:fix-transfer-budgets"
  [✓] No invalid budget/journal entries.
      Now executing command "firefly-iii:fix-uneven-amount"
  [✓] No "old style" foreign currency transfers.
  [✓] Database amount integrity is OK
  [✓] Journal currency integrity is OK

Portainer says that the container is unhealthy.
![image](https://github.com/user-attachments/assets/bb20802f-375b-4786-8fea-6f9f5895c48b)

### Debug information

Docker Compose:
```
  firefly:
    <<: *common-keys-core
    image: fireflyiii/core:latest
    container_name: Firefly_Core
    networks:
      masterchief:
        ipv4_address: <IP_ADDRESS>
    ports:
      - 8084:8080
    environment:
      - SITE_OWNER=<SITE_OWNE>
      - APP_KEY=<API_KEY>
      - DEFAULT_LANGUAGE=en_US
      - TZ=Europe/Bucharest
      - ALLOW_WEBHOOKS=true
      - DB_CONNECTION=mysql
      - DB_HOST=<DB_HOST>
      - DB_PORT=3306
      - DB_DATABASE=<DB_NAME>
      - DB_USERNAME=<DB_USERNAME>
      - DB_PASSWORD=<DB_PASS>
      - MAIL_MAILER=smtp
      - MAIL_HOST=<SMTP_HOSTNAME>
      - MAIL_PORT=465
      - MAIL_FROM=<EMAIL>
      - MAIL_USERNAME=<MAIL_USERNAME>
      - MAIL_PASSWORD=<MAIL_PASS>
      - MAIL_ENCRYPTION=ssl
      - TRUSTED_PROXIES=**
      - LOG_CHANNEL=stack
      - APP_URL=https://firefly.adandu.ro
      - AUTHENTICATION_GUARD=remote_user_guard
      - AUTHENTICATION_GUARD_HEADER=Remote-Email
    volumes:
      - $DOCKERDIR/firefly/upload:/var/www/html/storage/upload
      - $DOCKERDIR/firefly/logs:/var/www/html/storage/logs
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.firefly-rtr.entrypoints=https"
      - "traefik.http.routers.firefly-rtr.rule=Host(`firefly.$DOMAINNAME_CLOUD_SERVER`)"
      - "traefik.http.routers.firefly-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.firefly-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.firefly-rtr.service=firefly-svc"
      - "traefik.http.services.firefly-svc.loadbalancer.server.port=8080"

  firefly_cron:
    <<: *common-keys-core
    image: alpine
    container_name: Firefly_III_Cron
    networks:
      masterchief:
        ipv4_address: <IP_ADDRESS>
    environment:
      - STATIC_CRON_TOKEN=AUlQg09ggdVOAz58zO4OUbsWFRlr2wYL
    command: sh -c "echo \"0 3 * * * wget -qO- http://firefly:8080/api/v1/cron/AUlQg09ggdVOAz58zO4OUbsWFRlr2wYL\" | crontab - && crond -f -L /dev/stdout"

```
Portainer says that the container is unhealthy.
![image](https://github.com/user-attachments/assets/bb20802f-375b-4786-8fea-6f9f5895c48b)

ff3-cli*.log file

[ff3-cli-2024-09-28.log](https://github.com/user-attachments/files/17173971/ff3-cli-2024-09-28.log)

### Expected behaviour

Firefly Core should start correctly.
